### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by sarimmehdi** [facebookresearch/detectron2#1000]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:
2. what exact command you run:
`python demo/demo.py --config-file configs/Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml --video-input testing_left_0010.avi --output testing_left_0010_seg_dets.avi --opts MODEL.WEIGHTS detectron2://Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv/18131413/model_0039999_e76410.pk`l
3. what you observed (including the full logs):
```
Traceback (most recent call last):
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/demo/demo.py", line 142, in <module>
    for vis_frame, boxes, labels, scores, masks, sem_seg in demo.run_on_video(video):
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/demo/predictor.py", line 131, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/engine/defaults.py", line 192, in __call__
    predictions = self.model([inputs])[0]
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/meta_arch/rcnn.py", line 107, in forward
    return self.inference(batched_inputs)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/meta_arch/rcnn.py", line 169, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/roi_heads/cascade_rcnn.py", line 98, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/roi_heads/roi_heads.py", line 600, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/roi_heads/roi_heads.py", line 666, in _forward_mask
    mask_logits = self.mask_head(mask_features)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/modeling/roi_heads/mask_head.py", line 196, in forward
    x = layer(x)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarim/PycharmProjects/trajectory_pred/detectron2-master/detectron2/layers/wrappers.py", line 69, in forward
    x = self.norm(x)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 226, in forward
    input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/sarim/PycharmProjects/trajectory_pred/venv3.7/lib/python3.7/site-packages/torch/nn/functional.py", line 1706, in group_norm
    torch.backends.cudnn.enabled)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```
I ran detectron2 on kitti testing video (object tracking) from folder 0010. I think your code doesn't handle the case in which there are no bounding or segmentations detected. Please tell me how to fix this issue. Thanks

**Comment by ppwwyyxx** [comment]
This is fixed in https://github.com/pytorch/pytorch/pull/32401 which will be in pytorch 1.5
In 1.4 group norm does not support empty inputs. You may have to use nightly pytorch or build pytorch from source.

**Comment by ppwwyyxx** [comment]
BTW, we can backport the fix in detectron2 like we did for convolution & batchnorm, but it's extra temporary effort for a relatively less frequently used layer.
If anyone would like to contribute such a temporary fix we can accept that.
