### ISSUE TITLE
Arguments pooler must be list error

### ISSUE THREAD

**Issue by darwinharianto** [facebookresearch/detectron2#1019]
```
Traceback (most recent call last):
  File "../../KeypointPose/KeypointPose/test/box_hsr/detectron2_image_infer.py", line 70, in <module>
    img, successBBox, successKey = inferer.infer_image(img=img, draw_hm_collage=True)
  File "/home/doors/nddsTest/darwin/KeypointPose/KeypointPose/test/box_hsr/src/util/detectron2/inferer.py", line 124, in infer_image
    score_list, bbox_list, kpt_confidences_list, vis_keypoints_list, heatmap_arr_list = self.predict(img=result)
  File "/home/doors/nddsTest/darwin/KeypointPose/KeypointPose/test/box_hsr/src/util/detectron2/inferer.py", line 46, in predict
    outputs = self.predictor(img)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/engine/defaults.py", line 196, in __call__
    predictions = self.model([inputs])[0]
  File "/home/doors/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 170, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/doors/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 593, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 620, in forward_with_given_boxes
    instances = self._forward_keypoint(features, instances)
  File "/home/doors/nddsTest/darwin/KeypointPose/KeypointPose/test/box_hsr/src/util/detectron2/roi_heads.py", line 77, in _forward_keypoint
    keypoint_features = self.keypoint_pooler(features, pred_boxes)
  File "/home/doors/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/doors/nddsTest/darwin/data/detectron2/detectron2/modeling/poolers.py", line 199, in forward
    ), "Arguments to pooler must be lists"
AssertionError: Arguments to pooler must be lists
```

I found a same problem https://github.com/facebookresearch/meshrcnn/issues/12 . I tried to change Serialize to false at https://github.com/facebookresearch/detectron2/blob/c14fcaee32b253e9b76b78a56053f159e5e5ada0/detectron2/data/common.py#L65, but it doesn't seem to work.
I am using keypoint_rcnn_R_50_FPN_1x zoo model. I think there is some problem upon update. My Mac version does well (version from February) , but on ubuntu it fails (built today).
Is there any thing I could do?

**Comment by ppwwyyxx** [comment]
You need
https://github.com/facebookresearch/detectron2/blob/a4450defe7651bb04a252198f594bc289e2e9543/detectron2/modeling/roi_heads/roi_heads.py#L721
in `_forward_keypoint`.

**Comment by darwinharianto** [comment]
I do have that
<img width="731" alt="Screen Shot 2020-03-10 at 14 17 50" src="https://user-images.githubusercontent.com/44696192/76282124-26b4d800-62da-11ea-86e0-3751d7e8942d.png">

**Comment by ppwwyyxx** [comment]
I meant in "KeypointPose/test/box_hsr/src/util/detectron2/roi_heads.py", line 77, in _forward_keypoint"
