### ISSUE TITLE
How to completely UNINSTALL detectron2

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1029]
## ❓ How to use Detectron2

I install detectron2 successfully via 
`python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`
But now I want to purge it and install it again from source.
So I run: 
```
$pip uninstall detectron2
$rm -rf build/ **/*.so

```
And then I run 
```
git clone https://github.com/facebookresearch/detectron2.git
cd detectron2 && python -m pip install -e .
```
but it raise errors: 
```
Obtaining file:///home/minhkv/tienpv/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.1.0)
Requirement already satisfied: Pillow in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (6.2.2)
Requirement already satisfied: yacs>=0.1.6 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.1.6)
Requirement already satisfied: tabulate in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.8.6)
Requirement already satisfied: cloudpickle in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.2.2)
Requirement already satisfied: matplotlib in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (3.1.2)
Requirement already satisfied: tqdm>4.29.0 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (4.41.0)
Requirement already satisfied: tensorboard in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (2.1.0)
Requirement already satisfied: fvcore in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.1)
Requirement already satisfied: future in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.18.2)
Requirement already satisfied: pydot in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.4.1)
Requirement already satisfied: PyYAML in /home/minhkv/.local/lib/python3.6/site-packages (from yacs>=0.1.6->detectron2==0.1.1) (5.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (2.4.6)
Requirement already satisfied: numpy>=1.11 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (1.18.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (2.8.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.10.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.16.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.33.6)
Requirement already satisfied: setuptools>=41.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (42.0.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.4.1)
Requirement already satisfied: protobuf>=3.6.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (3.11.2)
Requirement already satisfied: markdown>=2.6.8 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (3.1.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (2.22.0)
Requirement already satisfied: six>=1.10.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.13.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.26.0)
Requirement already satisfied: absl-py>=0.4 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.9.0)
Requirement already satisfied: portalocker in /home/minhkv/.local/lib/python3.6/site-packages (from fvcore->detectron2==0.1.1) (1.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.2.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (1.3.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2019.11.28)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/minhkv/.local/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (3.1.0)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.1.1
ERROR: Exception:
Traceback (most recent call last):
  File "/home/minhkv/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/minhkv/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/home/minhkv/.local/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 64, in install_given_reqs
    auto_confirm=True
  File "/home/minhkv/.local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/home/minhkv/.local/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 544, in from_dist
    '(at %s)' % (link_pointer, dist.project_name, dist.location)
AssertionError: Egg-link /home/minhkv/tienpv_DO_NOT_REMOVE/detectron2 does not match installed location of detectron2 (at /home/minhkv/tienpv/detectron2)

```
What should I do?
By the way, is there anything different between these 2 ways of intallation:
```
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
# (add --user if you don't have permission)

# Or, to install it from a local clone:
git clone https://github.com/facebookresearch/detectron2.git
cd detectron2 && python -m pip install -e .
```
Thanks for reading.

**Comment by ppwwyyxx** [comment]
This is a python packaging question and unrelated to detectron2. I suggest you read http://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/. My guess is that your`python -m pip` is different from `pip` so you need `python -m pip uninstall`.

>  is there anything different between these 2 ways of intallation:

The second one will put the installed files in the directory you cloned.
