### ISSUE TITLE
[Custom Data] TypeError while training.

### ISSUE THREAD

**Issue by lalit-mohan** [facebookresearch/detectron2#103]
Using the colab tutorial, I'm training on some custom dataset. I ran into this error. From the look of it, I think, there is something wrong with my data, annotations or json file structure. Here's the error:
```
`TypeError                                 Traceback (most recent call last)
<ipython-input-31-03a749af0ba5> in <module>()
     14 
     15 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
---> 16 trainer = DefaultTrainer(cfg)
     17 trainer.resume_or_load(resume=False)
     18 trainer.train()

5 frames
/content/detectron2_repo/detectron2/engine/defaults.py in __init__(self, cfg)
    215         model = self.build_model(cfg)
    216         optimizer = self.build_optimizer(cfg, model)
--> 217         data_loader = self.build_train_loader(cfg)
    218 
    219         # For training, wrap with DDP. But don't need this for inference.

/content/detectron2_repo/detectron2/engine/defaults.py in build_train_loader(cls, cfg)
    361             iterable
    362         """
--> 363         return build_detection_train_loader(cfg)
    364 
    365     @classmethod

/content/detectron2_repo/detectron2/data/build.py in build_detection_train_loader(cfg, mapper)
    323         if cfg.MODEL.KEYPOINT_ON
    324         else 0,
--> 325         proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
    326     )
    327     dataset = DatasetFromList(dataset_dicts, copy=False)

/content/detectron2_repo/detectron2/data/build.py in get_detection_dataset_dicts(dataset_names, filter_empty, min_keypoints, proposal_files)
    254     """
    255     assert len(dataset_names)
--> 256     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
    257 
    258     if proposal_files is not None:

/content/detectron2_repo/detectron2/data/build.py in <listcomp>(.0)
    254     """
    255     assert len(dataset_names)
--> 256     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
    257 
    258     if proposal_files is not None:

/content/detectron2_repo/detectron2/data/catalog.py in get(name)
     56                 )
     57             )
---> 58         return f()
     59 
     60     @staticmethod

TypeError: 'list' object is not callable
````
Here's how I registered my dataset:
```
def get_hand_dicts(img_dir):
  json_file = os.path.join(img_dir,'parsed.json')
  with open(json_file) as f:
    imgs_anns = json.load(f)
  print(imgs_anns[0])
  dataset_dicts = []
  for v in imgs_anns:
    record={}
    filename = os.path.join(img_dir,v['filename'])

    record['file_name'] = filename
    record['height'] = v['height']
    record['width'] = v['width']
    objs =[]
    px1 = int(v['xmin'])
    px2 = int(v['xmax'])
    py1 = int(v['ymin'])
    py2 = int(v['ymax'])
    px = [px1,px2]
    py = [py1,py2]
    poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
    poly = list(itertools.chain.from_iterable(poly))
    obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": 0,
                "iscrowd": 0
           }
    objs.append(obj)
    record['annotations'] = objs
    dataset_dicts.append(record)
  return dataset_dicts
```
json file is structured as a list of dicts:
```
{"filename": "PUZZLE_OFFICE_T_S_frame_2697.jpg", "width": "1280", "height": "720", "class": "hand", "xmin": "338", "ymin": "213", "xmax": "545", "ymax": "348"}
```

**Comment by kinalmehta** [comment]
@lalit-mohan 
You are making a list of list here
```"segmentation": [poly],```
as poly is already a list 
```poly = list(itertools.chain.from_iterable(poly))``` 
so you should be using
```"segmentation": poly,```

**Comment by ppwwyyxx** [comment]
You need to register a function that returns a list of data, as mentioned in https://detectron2.readthedocs.io/modules/data.html#detectron2.data.DatasetCatalog.register and shown in the colab tutorial. However you seem to register a list of data directly.

`"segmentation": [poly]` is correct.

**Comment by lalit-mohan** [comment]
Thanks, I'm now at another error:
```
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/detectron2_repo/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/detectron2_repo/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/detectron2_repo/detectron2/data/dataset_mapper.py", line 129, in __call__
    annos, image_shape, mask_format=self.mask_format
  File "/content/detectron2_repo/detectron2/data/detection_utils.py", line 223, in annotations_to_instances
    masks = PolygonMasks(polygons)
  File "/content/detectron2_repo/detectron2/structures/masks.py", line 235, in __init__
    process_polygons(polygons_per_instance) for polygons_per_instance in polygons
  File "/content/detectron2_repo/detectron2/structures/masks.py", line 235, in <listcomp>
    process_polygons(polygons_per_instance) for polygons_per_instance in polygons
  File "/content/detectron2_repo/detectron2/structures/masks.py", line 231, in process_polygons
    assert len(polygon) % 2 == 0 and len(polygon) >= 6
AssertionError

```
I guess I'm still doing something wrong hence continuing this usage issue thread.

**Comment by ppwwyyxx** [comment]
A polygon by definition consists of at least 3 points, however it seems like yours only have two.

Also, if your dataset only has box annotations, but not polygon segmentations, it does not make much sense to train a segmentation model on it. But that's up to you.

**Comment by lalit-mohan** [comment]
Thanks a lot. I overlooked absence of regions in the .json file. Yes it doesn't make sense to train a segmentation model without polygon segmentations. Can you tell me more why is that the case?

**Comment by thanoscs** [comment]
Excuse me have you found a solution in th second problem?

**Comment by venkatesh-kulkarni** [comment]
@lalit-mohan can you please tell how you resolved this issue?
