### ISSUE TITLE
COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml not available in Model Zoo

### ISSUE THREAD

**Issue by kavyabhadran2020** [facebookresearch/detectron2#1037]
I am facing the below error while running detectron 2 code. The entire code was working successfully previously.

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
<img width="637" alt="ModelZoo" src="https://user-images.githubusercontent.com/59048984/76483782-f38b5980-643d-11ea-85ca-33e1ef678c75.PNG">

RuntimeError: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml not available in Model Zoo!

**Comment by ppwwyyxx** [comment]
Please show full colab otherwise I don't know what you did before the line that causes the error.

**Comment by raffihsieh** [comment]
I'm getting the same error.
I was following this collab notebook: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=uM1thbN-ntjI

**Comment by Flock1** [comment]
I am following [this](https://gilberttanner.com/blog/detectron-2-object-detection-with-pytorch) and I wrote the code for instance segmentation:

```
cfg = get_cfg()
cfg.merge_from_file("/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(img)

v = Visualizer(img[:,:,::-1])
v = v.draw_instance_predictions(outputs['instance'].to("cpu"))
cv2.imshow(v.get_image()[:,:,::-1])
```
I got the following error:
```
Traceback (most recent call last):
  File "segment.py", line 11, in <module>
    cfg.merge_from_file("/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/config/config.py", line 23, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file '/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' does not exist!
```
Then, when I added the line `cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))`, I got the above mentioned error.

**Comment by ppwwyyxx** [comment]
You can go and verify that the colab tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=uM1thbN-ntjI does work with the same code. So detailed information with instructions to reproduce the issue would be needed for us to make a helpful comment.

Also, if you attempted to use a pre-built detectron2, don't run code while you're in detectron2's source code directory. This rule applies to python packages in general.

**Comment by Flock1** [comment]
@ppwwyyxx, what all details would you need? 

I am not running the code in detectron2's source code directory. I am in a different folder, just mentioning the path to `yaml` file.

**Comment by ppwwyyxx** [comment]
There is an [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Flock1** [comment]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
1) Using my own image for inference

2) cfg.merge_from_file("/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
```
2. what exact command you run: python segment.py
3. what you observed (including __full logs__):
```
Traceback (most recent call last):
  File "segment.py", line 11, in <module>
    cfg.merge_from_file("/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/config/config.py", line 23, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file '/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' does not exist!
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

Display segmented image

## Environment:

Provide your environment information using the following command:
```
sys.platform              linux
Python                    3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  not available
detectron2 arch flags     /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080
CUDA_HOME                 None
Pillow                    7.0.0
torchvision               0.5.0 @/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torchvision
torchvision arch flags    /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torchvision/_C.so
cv2                       4.2.0
------------------------  -----------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
I'm not sure why you're expecting that the path `/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/model_zoo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"` should work. It's incorrect and not instructed by the tutorial.

**Comment by Flock1** [comment]
That's the location of the `yaml` file. I am not running it on Colab. I am running it on my local machine.

**Comment by ppwwyyxx** [comment]
That's not the location of the yaml file - it does not exist as the error says, and I do not expect it to exist

**Comment by Flock1** [comment]
So how should I run it on my local machine? I get the error when I run [this](https://gilberttanner.com/blog/detectron-2-object-detection-with-pytorch) code as well

**Comment by ppwwyyxx** [comment]
I don't know what code exactly - but it's best to follow our tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=uM1thbN-ntjI . If it does not work, please post the details of that again

**Comment by Flock1** [comment]
I ran the code under 
`
Other models – Instance Segmentation, Person Keypoint Detection and Panoptic Segmentation
`
this is the code:
`
cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imshow(v.get_image()[:, :, ::-1])
`

**Comment by ppwwyyxx** [comment]
Do not use "./detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml" either. It's causing the issue and please follow the official tutorial.

**Comment by Flock1** [comment]
@ppwwyyxx, I changed the code according to the tutorial and I got this error:
```
Traceback (most recent call last):
  File "segment.py", line 15, in <module>
    outputs = predictor(img)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 196, in __call__
    predictions = self.model([inputs])[0]
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 170, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 590, in forward
    pred_instances = self._forward_box(features, proposals)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 643, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/modeling/poolers.py", line 233, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: Not compiled with GPU support (ROIAlign_forward at /tmp/pip-req-build-feg5w7qs/detectron2/layers/csrc/ROIAlign/ROIAlign.h:73)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f0f8899e627 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: detectron2::ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0x171 (0x7f0f5ef05f61 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1faea (0x7f0f5ef15aea in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1aba0 (0x7f0f5ef10ba0 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: THPFunction_apply(_object*, _object*) + 0xa1f (0x7f0fbaa9ae3f in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
```

**Comment by ppwwyyxx** [comment]
The error says your detectron2 does not have GPU support.

If you want to run it with CPUs you need to set `MODEL.DEVICE` to `'cpu'`.

**Comment by Flock1** [comment]
@ppwwyyxx, you are the Boss!! Really amazing help. Just one more question.

I have CUDA 10.1 installed on my machine and I ran the code as mentioned. My system says that the requirements already satisfied:
```
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
Requirement already satisfied: detectron2 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (0.1.1)
Requirement already satisfied: fvcore in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (0.1.dev200307)
Requirement already satisfied: cloudpickle in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (1.3.0)
Requirement already satisfied: pydot in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (1.4.1)
Requirement already satisfied: matplotlib in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (3.1.2)
Requirement already satisfied: tqdm>4.29.0 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (4.42.1)
Requirement already satisfied: yacs>=0.1.6 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (0.1.6)
Requirement already satisfied: tensorboard in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (1.14.0)
Requirement already satisfied: termcolor>=1.1 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (1.1.0)
Requirement already satisfied: tabulate in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (0.8.6)
Requirement already satisfied: future in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (0.18.2)
Requirement already satisfied: Pillow in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from detectron2) (7.0.0)
Requirement already satisfied: numpy in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from fvcore->detectron2) (1.18.1)
Requirement already satisfied: pyyaml>=5.1 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from fvcore->detectron2) (5.2)
Requirement already satisfied: portalocker in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from fvcore->detectron2) (1.5.2)
Requirement already satisfied: pyparsing>=2.1.4 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from pydot->detectron2) (2.4.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from matplotlib->detectron2) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from matplotlib->detectron2) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from matplotlib->detectron2) (2.8.1)
Requirement already satisfied: protobuf>=3.6.0 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (3.11.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (44.0.0.post20200106)
Requirement already satisfied: grpcio>=1.6.3 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (1.16.1)
Requirement already satisfied: markdown>=2.6.8 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (3.1.1)
Requirement already satisfied: six>=1.10.0 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (1.13.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (0.16.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (0.33.6)
Requirement already satisfied: absl-py>=0.4 in /home/sarvagya/miniconda3/envs/gr/lib/python3.6/site-packages (from tensorboard->detectron2) (0.8.1)
```

**Comment by Flock1** [comment]
@ppwwyyxx, I wanted to know if you can help me understand a few things about the working of TensorMasks, mainly around aligned and natural representation.
