### ISSUE TITLE
module 'detectron2._C' has no attribute 'get_cuda_version'

### ISSUE THREAD

**Issue by Chi-Zaozao** [facebookresearch/detectron2#104]
I install detectron2 via the dockerfile. My docker version is 19.03.3。
when I run "python3 tools/train_net.py     --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml     SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025" in the bash as GETTING_STARTED.md mentioned, I got this bug:
Failed to load OpenCL runtime
Command Line Args: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', dist_url='tcp://127.0.0.1:49152', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['SOLVER.IMS_PER_BATCH', '2', 'SOLVER.BASE_LR', '0.0025'], resume=False)
Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[10/17 09:19:32 detectron2]: Rank of current process: 0. World size: 1
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/detectron2_repo/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 125, in main
    cfg = setup(args)
  File "tools/train_net.py", line 120, in setup
    default_setup(cfg, args)
  File "/detectron2_repo/detectron2/engine/defaults.py", line 104, in default_setup
    logger.info("Environment info:\n" + collect_env_info())
  File "/detectron2_repo/detectron2/utils/collect_env.py", line 43, in collect_env_info
    data.append(("Detectron2 CUDA Compiler", _C.get_cuda_version()))
AttributeError: module 'detectron2._C' has no attribute 'get_cuda_version'

## Environment

when I run `python -m detectron2.utils.collect_env` as well as  `python detectron2/utils/collect_env.py`, I got this:
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "detectron2/utils/collect_env.py", line 92, in <module>
    print(collect_env_info())
  File "detectron2/utils/collect_env.py", line 43, in collect_env_info
    data.append(("Detectron2 CUDA Compiler", _C.get_cuda_version()))
AttributeError: module 'detectron2._C' has no attribute 'get_cuda_version'

How can I solve this problem?

**Comment by ppwwyyxx** [comment]
You pulled latest detectron2 code but did not compile it.

**Comment by Chi-Zaozao** [comment]
Ok, thank u very much!
