### ISSUE TITLE
Error in Panoptic Evaluation 

### ISSUE THREAD

**Issue by kHarshit** [facebookresearch/detectron2#105]
## To Reproduce

1. what changes you made / what code you wrote: Nothing
2. what command you run: `python tools/train_net.py --eval-only --config-file configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml  SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025`
3. what you observed (full logs are preferred)

```
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 132, in main
    res = Trainer.test(cfg, model)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/defaults.py", line 404, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/defaults.py", line 371, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 387, in build_detection_test_loader
    else None,
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 256, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 256, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/datasets/register_coco.py", line 81, in <lambda>
    load_coco_json(instances_json, image_root, panoptic_name),
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/datasets/coco.py", line 50, in load_coco_json
    coco_api = COCO(json_file)
  File "/nfs/interns/kharshit/miniconda3/envs/py13/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_val2017.json'
```

## Expected behavior

[2017 Panoptic Train/Val annotations](http://images.cocodataset.org/annotations/panoptic_annotations_trainval2017.zip) provides only `panoptic_val2017.json` not `instances_val2017.json`. Is it also required for panoptic evaluation?

If I rename the file `panoptic_val2017.json` to `instances_val2017.json`, I get another error:

```
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 132, in main
    res = Trainer.test(cfg, model)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/defaults.py", line 404, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/engine/defaults.py", line 371, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 387, in build_detection_test_loader
    else None,
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 256, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/build.py", line 256, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/datasets/register_coco.py", line 81, in <lambda>
    load_coco_json(instances_json, image_root, panoptic_name),
  File "/nfs/interns/kharshit/panoptic/detectron2/detectron2/data/datasets/coco.py", line 50, in load_coco_json
    coco_api = COCO(json_file)
  File "/nfs/interns/kharshit/miniconda3/envs/py13/lib/python3.7/site-packages/pycocotools/coco.py", line 88, in __init__
    self.createIndex()
  File "/nfs/interns/kharshit/miniconda3/envs/py13/lib/python3.7/site-packages/pycocotools/coco.py", line 98, in createIndex
    anns[ann['id']] = ann
KeyError: 'id'
```

*There is a [similar issuer here](https://github.com/cocodataset/cocoapi/issues/191).*

## Environment

```
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                     1.17.2
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1
CUDA available            True
GPU 0                     GeForce RTX 2080
GPU 1                     GeForce GTX 1060 6GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.0
cv2                       4.1.1
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
`instances_val2017.json` is also required for evaluation for now, although that seems unnecessary.
Please follow https://github.com/facebookresearch/detectron2/tree/master/datasets to setup them. The data can be downloaded at http://images.cocodataset.org/annotations/annotations_trainval2017.zip

**Comment by lxtGH** [comment]
@ppwwyyxx  Hi!! Thanks for such great repo. Have you consider adding Cityscapes panopic results or models into this repo?
