### ISSUE TITLE
Unable to find address for: eth0

### ISSUE THREAD

**Issue by ternaus** [facebookresearch/detectron2#1052]
```
------------------------  -----------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                     1.17.2
detectron2                0.1.1 @/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.2
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/root/anaconda3/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3,4,5,6,7       GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.2, V10.2.89
Pillow                    6.2.0
torchvision               0.5.0 @/root/anaconda3/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  -----------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

Trying to train model.

On the machine, with 2x2080Ti the code works well. 

But in the machine with 8x1080Ti training fails with an error:

```
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/root/workspace/kaggle_deepfake/kaggle_deepfake/detector_utils/train_detector.py", line 98, in main
    trainer = Trainer(cfg)
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/engine/defaults.py", line 253, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/engine/defaults.py", line 430, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/data/build.py", line 309, in build_detection_train_loader
    sampler = samplers.TrainingSampler(len(dataset))
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/data/samplers/distributed_sampler.py", line 37, in __init__
    seed = comm.shared_random_seed()
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/utils/comm.py", line 230, in shared_random_seed
    all_ints = all_gather(ints)
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/utils/comm.py", line 154, in all_gather
    group = _get_global_gloo_group()
  File "/root/anaconda3/lib/python3.7/site-packages/detectron2-0.1.1-py3.7-linux-x86_64.egg/detectron2/utils/comm.py", line 89, in _get_global_gloo_group
    return dist.new_group(backend="gloo")
  File "/root/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1565, in new_group
    timeout=timeout)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 475, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0

```

**Comment by chenwydj** [comment]
@ternaus may I ask how did you solve this problem?

Thank you very much!

**Comment by qqlu** [comment]
@ternaus I meet the same error. How could you solve it? Thanks very much.

**Comment by hongdayu** [comment]
use gloo for multi-node training?
