### ISSUE TITLE
train pointrend using background images with no instances

### ISSUE THREAD

**Issue by jhj7905** [facebookresearch/detectron2#1057]
1. i registered the custom dataset(person class) with person images and no person images(background)
2. train the pointrend, config like below
```
cfg = get_cfg()
add_pointrend_config(cfg)
cfg.merge_from_file("/home/hyunjo/Segmentation/detectron2/projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco_person.yaml")
cfg.DATASETS.TRAIN = ("other_train",)
cfg.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False
cfg.DATASETS.TEST = ("other_val",)
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "/home/hyunjo/Segmentation/detectron2/models/model_final_3c3198.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 2500000 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 
```

3. error occured like below
```
[03/17 19:33:57 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[03/17 19:33:57 d2.data.build]: Using training sampler TrainingSampler
'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (2, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (2,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (4, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (4,) in the model! Skipped.
'roi_heads.mask_coarse_head.prediction.weight' has shape (3920, 1024) in the checkpoint but (49, 1024) in the model! Skipped.
'roi_heads.mask_coarse_head.prediction.bias' has shape (3920,) in the checkpoint but (49,) in the model! Skipped.
'roi_heads.mask_point_head.fc1.weight' has shape (256, 336, 1) in the checkpoint but (256, 257, 1) in the model! Skipped.
'roi_heads.mask_point_head.fc2.weight' has shape (256, 336, 1) in the checkpoint but (256, 257, 1) in the model! Skipped.
'roi_heads.mask_point_head.fc3.weight' has shape (256, 336, 1) in the checkpoint but (256, 257, 1) in the model! Skipped.
'roi_heads.mask_point_head.predictor.weight' has shape (80, 336, 1) in the checkpoint but (1, 257, 1) in the model! Skipped.
'roi_heads.mask_point_head.predictor.bias' has shape (80,) in the checkpoint but (1,) in the model! Skipped.
[03/17 19:33:57 d2.engine.train_loop]: Starting training from iteration 0
ERROR [03/17 19:33:57 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/hyunjo/Segmentation/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/hyunjo/Segmentation/detectron2/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/hyunjo/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyunjo/Segmentation/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/hyunjo/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyunjo/Segmentation/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 589, in forward
    losses.update(self._forward_mask(features_list, proposals))
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/roi_heads.py", line 124, in _forward_mask
    losses.update(self._forward_mask_point(features, mask_coarse_logits, proposals))
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/roi_heads.py", line 183, in _forward_mask_point
    point_logits, instances, point_coords_wrt_image
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/point_head.py", line 43, in roi_mask_point_loss
    instances[0].gt_masks, BitMasks
  File "/home/hyunjo/Segmentation/detectron2/detectron2/structures/instances.py", line 62, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!
[03/17 19:33:57 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/train_net_other_person.py", line 28, in <module>
    trainer.train()
  File "/home/hyunjo/Segmentation/detectron2/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/hyunjo/Segmentation/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/hyunjo/Segmentation/detectron2/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/hyunjo/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyunjo/Segmentation/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/hyunjo/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyunjo/Segmentation/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 589, in forward
    losses.update(self._forward_mask(features_list, proposals))
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/roi_heads.py", line 124, in _forward_mask
    losses.update(self._forward_mask_point(features, mask_coarse_logits, proposals))
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/roi_heads.py", line 183, in _forward_mask_point
    point_logits, instances, point_coords_wrt_image
  File "/home/hyunjo/Segmentation/detectron2/projects/PointRend/point_rend/point_head.py", line 43, in roi_mask_point_loss
    instances[0].gt_masks, BitMasks
  File "/home/hyunjo/Segmentation/detectron2/detectron2/structures/instances.py", line 62, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!
```
i think it is related to empty list of annotation which is background image
can you tell me how to modify it?
one more question, then pointrend can not train with background image and empty annotation
("Point head works with GT in 'bitmask' format only. Set INPUT.MASK_FORMAT to 'bitmask'.")
thank you in advance

**Comment by ppwwyyxx** [comment]
fixed in 426d239b9c09932f1caa5023f4477b3fa9e85c32
