### ISSUE TITLE
Error running demo.py

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/detectron2#1060]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
No changes, following INSTALL.MD


```
2. what exact command you run:

Install Detectron2 with anaconda
Gcc --version	gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
Nvcc --version	Cuda compilation tools, release 10.2, V10.2.89

Install Pytorch
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

Install cython
conda install -c anaconda cython

Install pyyaml
conda install -c anaconda pyyaml

Install coco dataset
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

Install openCV
conda install -c conda-forge opencv

Install detetron2
Cd detectron2
python -m pip install -e .

Run demo
Cd demo
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
--input input1.jpg input2.jpg \
--opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

3. what you observed (including __full logs__):
```

python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
> --input input1.jpg input2.jpg \
> --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/18 19:24:56 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['input1.jpg', 'input2.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
[03/18 19:25:06 fvcore.common.checkpoint]: Loading checkpoint from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/18 19:25:06 fvcore.common.file_io]: Downloading https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl ...
[03/18 19:25:06 fvcore.common.download]: Downloading from https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl ...
model_final_f10217.pkl: 178MB [22:51, 130kB/s]                                                                          
[03/18 19:47:58 fvcore.common.download]: Successfully downloaded /home/jamal/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl. 177841981 bytes.
[03/18 19:47:58 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached in /home/jamal/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[03/18 19:47:58 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
Traceback (most recent call last):
  File "demo.py", line 87, in <module>
    img = read_image(path, format="BGR")
  File "/home/jamal/projects/detectron2/detectron2/detectron2/data/detection_utils.py", line 48, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/jamal/anaconda3/envs/detect2_v02/lib/python3.8/site-packages/fvcore/common/file_io.py", line 574, in open
    return PathManager.__get_path_handler(path)._open(  # type: ignore
  File "/home/jamal/anaconda3/envs/detect2_v02/lib/python3.8/site-packages/fvcore/common/file_io.py", line 389, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'input1.jpg'

```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py

------------------------  -------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.8.1 (default, Jan  8 2020, 22:29:32) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/jamal/projects/detectron2/detectron2/detectron2
detectron2 compiler       GCC 6.5
detectron2 CUDA compiler  10.2
detectron2 arch flags     sm_52
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/jamal/anaconda3/envs/detect2_v02/lib/python3.8/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Quadro M5000
CUDA_HOME                 /usr/local/cuda-10.2
NVCC                      Cuda compilation tools, release 10.2, V10.2.89
Pillow                    7.0.0
torchvision               0.5.0 @/home/jamal/anaconda3/envs/detect2_v02/lib/python3.8/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  -------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 




```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
The command you use runs the demo on input images specified in the command. Those images do not exist.
