### ISSUE TITLE
run train_net.py have a FileNotFoundError

### ISSUE THREAD

**Issue by WJ1214** [facebookresearch/detectron2#1069]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
nothing 
```
2. what exact command you run:
./train_net.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
3. what you observed (including __full logs__):
```
Traceback (most recent call last):
  File "./train_net.py", line 163, in <module>
    args=(args,),
  File "/home/wj/REPO/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "./train_net.py", line 145, in main
    trainer = Trainer(cfg)
  File "/home/wj/REPO/detectron2/detectron2/engine/defaults.py", line 253, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/wj/REPO/detectron2/detectron2/engine/defaults.py", line 430, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/home/wj/REPO/detectron2/detectron2/data/build.py", line 297, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/home/wj/REPO/detectron2/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/wj/REPO/detectron2/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/wj/REPO/detectron2/detectron2/data/catalog.py", line 62, in get
    return f()
  File "/home/wj/REPO/detectron2/detectron2/data/datasets/register_coco.py", line 33, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/wj/REPO/detectron2/detectron2/data/datasets/coco.py", line 58, in load_coco_json
    coco_api = COCO(json_file)
  File "/opt/anaconda3/envs/rcnn/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2017.json'
```
hello, after i do every step of install.md, i try to run train_net.py to train the model, and i have already put coco datasets in ./datasets directory. Howerer it still raise a  FileNotFoundError above.
My datasets directory structure is :
```
--datasets
   --coco
      --annotations
      --train2017
      --val2017
```
And in my annotations it has "instances_train2017.json":
```
(rcnn) wj@hzlab:~/REPO/detectron2$ cd datasets
(rcnn) wj@hzlab:~/REPO/detectron2/datasets$ ls -a
.  ..  coco  prepare_cocofied_lvis.py  prepare_for_tests.sh  prepare_panoptic_fpn.py  README.md
(rcnn) wj@hzlab:~/REPO/detectron2/datasets$ cd coco
(rcnn) wj@hzlab:~/REPO/detectron2/datasets/coco$ ls -a
.  ..  annotations  train2017  val2017
(rcnn) wj@hzlab:~/REPO/detectron2/datasets/coco$ cd anno*
(rcnn) wj@hzlab:~/REPO/detectron2/datasets/coco/annotations$ ls -a
.   instances_train2017.json  json_bak                         person_keypoints_val2017.json
..  instances_val2017.json    person_keypoints_train2017.json
```

**Comment by ppwwyyxx** [comment]
`datasets/coco/annotations/instances_train2017.json` is a path relative to your current directory, as said in https://github.com/facebookresearch/detectron2/tree/master/datasets.

You run the code in inside `tools/`, so the datasets should be in `tools/`.

**Comment by WJ1214** [comment]
> `datasets/coco/annotations/instances_train2017.json` is a path relative to your current directory, as said in https://github.com/facebookresearch/detectron2/tree/master/datasets.
> 
> You run the code in inside `tools/`, so the datasets should be in `tools/`.

thank you!  it worked

**Comment by Alan-D-Chen** [comment]
Is there any solution that puts all kinds of datasets into one independent file , not` tool/`??
