### ISSUE TITLE
Training error on custom data set - The size of tensor a (6768) must match the size of tensor b (6960) at non-singleton dimension 0 

### ISSUE THREAD

**Issue by PeterZainzinger** [facebookresearch/detectron2#1075]
Hi,

I"m trying to train on a custom data set. My code works on other datasets but crashes everytime  at some point on a this specific one.  I tried to find out the difference for a few days now (thank you corona) but I'm unable to spot it.

## Instructions To Reproduce the Issue:

As I'm unable to share the dataset I'm not be able to give full instructions. But here is some information:

* The dataset consists of about 3000 Images resized to 512x512px. 
* The is a single catogory with id 1.
* My config are this:

```
_BASE_: "./Base-RCNN-FPN.yaml"
VERSION: 2
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50

TEST:
  DETECTIONS_PER_IMAGE: 1000
  EVAL_PERIOD: 0
SOLVER:
  CHECKPOINT_PERIOD: 2000
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
  GAMMA: 0.20
  STEPS:   (15000,30000,45000)
  MAX_ITER: 60000
TEST:
  EVAL_PERIOD: 0
  AUG:
    ENABLED: False

INPUT:
    MIN_SIZE_TEST: 512
    MAX_SIZE_TEST: 512
    MIN_SIZE_TRAIN: (512,)
    MAX_SIZE_TRAIN: 512
```
This is the error I'm retrieving
```
Traceback (most recent call last):
  File "/home/appuser/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/appuser/detectron2_repo/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 124, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2_repo/detectron2/modeling/proposal_generator/rpn.py", line 182, in forward
    self.training,
  File "/home/appuser/detectron2_repo/detectron2/modeling/proposal_generator/rpn_outputs.py", line 142, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/home/appuser/detectron2_repo/detectron2/layers/nms.py", line 17, in batched_nms
    return box_ops.batched_nms(boxes, scores, idxs, iou_threshold)
  File "/home/appuser/.local/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 75, in batched_nms
    boxes_for_nms = boxes + offsets[:, None]
RuntimeError: The size of tensor a (6768) must match the size of tensor b (6960) at non-singleton dimension 0
[03/19 08:49:02 d2.engine.hooks]: Overall training speed: 544 iterations in 0:01:07 (0.1238 s / it)
[03/19 08:49:02 d2.engine.hooks]: Total training time: 0:01:07 (0:00:00 on hooks)
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    trainer.train()
  File "/home/appuser/detectron2_repo/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/appuser/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/appuser/detectron2_repo/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 124, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/appuser/detectron2_repo/detectron2/modeling/proposal_generator/rpn.py", line 182, in forward
    self.training,
  File "/home/appuser/detectron2_repo/detectron2/modeling/proposal_generator/rpn_outputs.py", line 142, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/home/appuser/detectron2_repo/detectron2/layers/nms.py", line 17, in batched_nms
    return box_ops.batched_nms(boxes, scores, idxs, iou_threshold)
  File "/home/appuser/.local/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 75, in batched_nms
    boxes_for_nms = boxes + offsets[:, None]
RuntimeError: The size of tensor a (6768) must match the size of tensor b (6960) at non-singleton dimension 0
```
The dimensions of the tensors `a` and `b` varies from testrun to testrun but the difference stays constant. Maybe that helps.

 
## Expected behavior:

Should not crash while training

## Environment:

Executed in docker container built with an image built according to the Dockerfile in the repo. 

I would be helpful for any input!

Peter

**Comment by PeterZainzinger** [comment]
Ok, this was a tricky one...

Out of sheer desperation I downgraded detectron2 to `v0.1`. This changed the crash to basically the error reported in #838 . This gave me the hint the the learning rate of `0.02` was to high, so I lowered that to `0.01`.  In combination with removing tiny instances from the annotations the error is now gone.

The crux of issue was to find out the link between the initial error and that the divergence of the model.

**Comment by mtroym** [comment]
@PeterZainzinger Could you please give the details of how to remove the tiny instances by modifications in detectron2 codes or something? but not change the whole dataset.

**Comment by ppwwyyxx** [comment]
The root cause is already fixed in master - when divergence happens at the same place, detectron2 will now throw a clear error.

**Comment by mtroym** [comment]
@ppwwyyxx Yes, but we need to make the model works fine. The model should not diverge.

**Comment by ppwwyyxx** [comment]
The model inevitably diverges when wrong parameters are used. 
As the [issue template](https://github.com/facebookresearch/detectron2/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems-bugs.md) mentions:

> If you expect the model to converge / work better, note that we do not give suggestions on how to train a new model. Only in one of the two conditions we will help with it: (1) You're unable to reproduce the results in detectron2 model zoo. (2) It indicates a detectron2 bug.

We provide configs & models with standard academic settings and expect users to have the knowledge to choose or design appropriate models & parameters for their own tasks.

**Comment by mtroym** [comment]
yes, I used the exact same config of "Keypoint RCNN R 101 FPN 3x" except for num key points, but not on coco. The training process is crashed when the 1st iteration. I think I should make some modifications when load the data.

**Comment by mtroym** [comment]
@ppwwyyxx Do we have the warmup method of "Exponential" instead of linear?

**Comment by ppwwyyxx** [comment]
The warmup is linear

**Comment by mtroym** [comment]
maybe it will satisfied. adding these to solver/lr_scheduler.py:117
```py
# solver/lr_scheduler.py:117
elif method == "exponential":
    alpha = 1.0 / (math.exp(- iter / warmup_iters) + 1.0)
    return warmup_factor * (1 - alpha) + alpha
```

**Comment by mtroym** [comment]
To avoid a higher LR when start iteration. we can use sigmoid-like functions to replace the linear warmup, for example 
![image](https://user-images.githubusercontent.com/30402475/77832852-e081c480-7173-11ea-8537-c86a18f453e0.png)
