### ISSUE TITLE
Attribute 'thing_classes' does not exist in the metadata of 'egohands_val'. Available keys are dict_keys(['name', 'things_classes', 'json_file']).

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1139]
I'm applying the colab tutorial for EgoHands datasets with 4 classes. I wrote get_dicts function, then I verified that this functions works well by Visualizer, then I trained model, everything worked well. But when I try to evaluate the model as the COCO format (same way as in the colab tutorial), I get errors.
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
import argparse
import os
import cv2

#for verify_load_data
import numpy as np 
import random
from detectron2.utils.visualizer import Visualizer

import detectron2
from detectron2 import model_zoo
from detectron2.config import get_cfg
from detectron2.utils.logger import setup_logger
from detectron2.engine import DefaultTrainer
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.structures import BoxMode

import scipy.io as sio 

#for evaluation
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

def setup_cfg(args):
    #load config from file and command-line arguments
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml") #initialize a pretrained weights
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.00025
    cfg.merge_from_list(args.opts)
    #cfg.freeze()
    return cfg

def get_parser():
    parser = argparse.ArgumentParser(description="Egohands datasets for Detectron2")
    parser.add_argument(
        "--config-file",
        default="../../configs/Base-RCNN-FPN.yaml",
        metavar="FILE",
        help="path to config file",
        )
    parser.add_argument(
        "--egohands-dir",
        default="./",
        help="path to egohands dataset"
        )
    parser.add_argument(
        "--opts",
        help="Modify config options using the command-line 'KEY VALUE' pairs",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser

def get_hand_dicts(egohands_dir):
    #this worked well
    return dataset_dicts

def train_net(cfg):
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
    return trainer

def verify_load_data(args, num_samples, egohands_metadata):
    dataset_dicts = get_hand_dicts(args.egohands_dir + "train")
    for d in random.sample(dataset_dicts, num_samples):
        img = cv2.imread(d["file_name"])
        visualizer = Visualizer(img[:, :, ::-1], metadata=egohands_metadata, scale=0.5)
        vis = visualizer.draw_dataset_dict(d)
        cv2.imshow(d["file_name"], vis.get_image()[:, :, ::-1])
        cv2.waitKey(0)
    cv2.destroyAllWindows()
    return

def evaluate(cfg, trainer):
    evaluator = COCOEvaluator("egohands_val", cfg, False, output_dir="./output/")
    val_loader = build_detection_test_loader(cfg, "egohands_val")
    results = inference_on_dataset(trainer.model, val_loader, evaluator)
    return results

def main():
    args = get_parser().parse_args()
    setup_logger(name="fvcore")
    logger = setup_logger()
    logger.info("Arguments: " + str(args))

    cfg = setup_cfg(args)
    for d in ["train", "val"]:
        DatasetCatalog.register("egohands_" + d, lambda d=d: get_hand_dicts(args.egohands_dir + d))
        MetadataCatalog.get("egohands_" + d).set(things_classes=["myleft", "myright", "yourleft", "yourright"])
    egohands_metadata = MetadataCatalog.get("egohands_train")
    #print(egohands_metadata.things_classes)
    #verify_load_data(args, num_samples=3, egohands_metadata=egohands_metadata)

    cfg.DATASETS.TRAIN = ("egohands_train", )
    cfg.DATASETS.TEST = ("egohands_val", )
    trainer = train_net(cfg)
#########################################################################
#########ERRORS HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    #evaluate
    results = evaluate(cfg, trainer) #ONLY THIS LINE MAKE ERROR!
    return 0

if __name__ == "__main__":
    main()

```
2. what exact command you run:
python3 train_net.py --egohands-dir ./ --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --opts SOLVER.BASE_LR 0.00025 SOLVER.MAX_ITER 100 MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE 128

3. what you observed (including __full logs__):
```
[04/02 11:57:07 detectron2]: Arguments: Namespace(config_file='../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', egohands_dir='./', opts=['SOLVER.BASE_LR',0025', 'SOLVER.MAX_ITER', '100', 'MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE', '128'])
[04/02 11:57:12 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelMaxPool()
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (proposal_generator): RPN(
    (anchor_generator): DefaultAnchorGenerator(
      (cell_anchors): BufferList()
    )
    (rpn_head): StandardRPNHead(
      (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (objectness_logits): Conv2d(256, 3, kernel_size=(1, 1), stride=(1, 1))
      (anchor_deltas): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (roi_heads): StandardROIHeads(
    (box_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(7, 7), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(7, 7), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(7, 7), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (box_head): FastRCNNConvFCHead(
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=5, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=16, bias=True)
    )
    (mask_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(14, 14), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(14, 14), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(14, 14), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(14, 14), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (mask_head): MaskRCNNConvUpsampleHead(
      (mask_fcn1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (deconv): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
      (predictor): Conv2d(256, 4, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
./train/CARDS_COURTYARD_B_T/polygons.mat
[04/02 11:57:13 d2.data.build]: Removed 0 images with no usable annotations. 100 images left.
[04/02 11:57:13 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[04/02 11:57:13 d2.data.common]: Serialized dataset takes 1.14 MiB
[04/02 11:57:13 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='c'), RandomFlip()]
[04/02 11:57:13 d2.data.build]: Using training sampler TrainingSampler
2020-04-02 11:57:14.918867: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:
2020-04-02 11:57:14.919032: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugi6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:
2020-04-02 11:57:14.919051: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, e make sure the missing libraries mentioned above are installed properly.
[04/02 11:57:15 fvcore.common.checkpoint]: Loading checkpoint from https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_ff10217.pkl
[04/02 11:57:15 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached ome/minhkv/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[04/02 11:57:16 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (5, 1024) in the model! Skipped.
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (5,) in the model! Skipped.
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (16, 1024) in the model! Skipped.
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (16,) in the model! Skipped.
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (4, 256, 1, 1) in the model! Skipped
WARNING [04/02 11:57:16 fvcore.common.checkpoint]: 'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (4,) in the model! Skipped.
[04/02 11:57:16 fvcore.common.checkpoint]: Some model parameters are not in the checkpoint:
  roi_heads.box_predictor.cls_score.{weight, bias}
  roi_heads.box_predictor.bbox_pred.{weight, bias}
  roi_heads.mask_head.predictor.{weight, bias}
[04/02 11:57:16 d2.engine.train_loop]: Starting training from iteration 0
[04/02 11:57:23 d2.utils.events]:  eta: 0:00:27  iter: 19  total_loss: 2.692  loss_cls: 1.726  loss_box_reg: 0.194  loss_mask: 0.693  loss_rpn_cls: 0.090  loss_rpn_loc: 0.020e: 0.3408  data_time: 0.0212  lr: 0.000005  max_mem: 2675M
[04/02 11:57:30 d2.utils.events]:  eta: 0:00:20  iter: 39  total_loss: 2.743  loss_cls: 1.599  loss_box_reg: 0.323  loss_mask: 0.692  loss_rpn_cls: 0.092  loss_rpn_loc: 0.021e: 0.3419  data_time: 0.0051  lr: 0.000010  max_mem: 2675M
[04/02 11:57:37 d2.utils.events]:  eta: 0:00:14  iter: 59  total_loss: 2.584  loss_cls: 1.389  loss_box_reg: 0.431  loss_mask: 0.689  loss_rpn_cls: 0.075  loss_rpn_loc: 0.022e: 0.3445  data_time: 0.0049  lr: 0.000015  max_mem: 2675M
[04/02 11:57:44 d2.utils.events]:  eta: 0:00:07  iter: 79  total_loss: 2.559  loss_cls: 1.147  loss_box_reg: 0.592  loss_mask: 0.686  loss_rpn_cls: 0.058  loss_rpn_loc: 0.017e: 0.3459  data_time: 0.0050  lr: 0.000020  max_mem: 2675M
[04/02 11:57:51 fvcore.common.checkpoint]: Saving checkpoint to ./output/model_final.pth
./val/CARDS_COURTYARD_H_S/polygons.mat
[04/02 11:57:55 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[04/02 11:57:56 d2.data.common]: Serialized dataset takes 4.74 MiB
WARNING [04/02 11:57:56 d2.engine.defaults]: No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.
[04/02 11:57:56 d2.utils.events]:  eta: 0:00:00  iter: 99  total_loss: 2.159  loss_cls: 0.931  loss_box_reg: 0.463  loss_mask: 0.684  loss_rpn_cls: 0.046  loss_rpn_loc: 0.017e: 0.3456  data_time: 0.0049  lr: 0.000025  max_mem: 2675M
[04/02 11:57:56 d2.engine.hooks]: Overall training speed: 97 iterations in 0:00:33 (0.3492 s / it)
[04/02 11:57:56 d2.engine.hooks]: Total training time: 0:00:39 (0:00:05 on hooks)
WARNING [04/02 11:57:56 d2.evaluation.coco_evaluation]: json_file was not found in MetaDataCatalog for 'egohands_val'. Trying to convert it to COCO format ...
[04/02 11:57:56 d2.data.datasets.coco]: Converting annotations of dataset 'egohands_val' to COCO format ...)
./val/CARDS_COURTYARD_H_S/polygons.mat
Traceback (most recent call last):
  File "train_net.py", line 183, in <module>
    main()
  File "train_net.py", line 176, in main
    evaluator = COCOEvaluator("egohands_val", cfg, False, output_dir="./output/")
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/evaluation/coco_evaluation.py", line 72, in __init__
    convert_to_coco_json(dataset_name, cache_path)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/data/datasets/coco.py", line 425, in convert_to_coco_json
    coco_dict = convert_to_coco_dict(dataset_name)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/data/datasets/coco.py", line 304, in convert_to_coco_dict
    for id, name in enumerate(metadata.thing_classes)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/data/catalog.py", line 119, in __getattr__
    key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'thing_classes' does not exist in the metadata of 'egohands_val'. Available keys are dict_keys(['name', 'things_classes', 'json_file']).
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
I think this is simple enough.
## Expected behavior:
Evaluation as in the tutorial.
## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
------------------------  ------------------------------------------------------------------
sys.platform              linux
Python                    3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
numpy                     1.18.2
detectron2                0.1.1 @/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/minhkv/.local/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-10.0
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    7.0.0
torchvision               0.5.0 @/home/minhkv/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```
@ppwwyyxx Please have a look, many thanks!

**Comment by pvtien96** [comment]
As I understand, the errors say that: Attribute 'thing_classes' does not exist in the metadata of 'egohands_val'. But when I write these lines:
```
egohands_metadata = MetadataCatalog.get("egohands_val")
print(egohands_metadata.things_classes)
```
It successfully print my 4 classes:
`['myleft', 'myright', 'yourleft', 'yourright']`
So what is the problem here?
Why can't it evaluate model as in the colab tutorial?

**Comment by ppwwyyxx** [comment]
> AttributeError: Attribute 'thing_classes' does not exist in the metadata of 'egohands_val'. Available keys are dict_keys(['name', 'things_classes', 'json_file']).

things -> thing

**Comment by Randheerkumar** [comment]
I have similar situation. I have also visualized data and it  correctly converted into standard list [According to this](https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts)
It works for training, But in testing phase it showing following error:

  **key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'evaluator_type' does not exist in the metadata of 'v5_test'. Available keys are dict_keys(['name']).**

**I have registered dataset as:**
    DatasetCatalog.register("v5_train", my_dataset_function)
    DatasetCatalog.register("v5_test", my_dataset_function)
   

@ppwwyyxx Please help.
