### ISSUE TITLE
Problem with META_ARCH registry

### ISSUE THREAD

**Issue by SeanCho1996** [facebookresearch/detectron2#1167]
Hi there, I'm currently trying to use TensorMask module to train with my own dataset. After dealing with the images, I registered my dataset with a simple script:
```python
from detectron2.data.datasets import register_coco_instances
register_coco_instances("fruits_nuts", {}, "./data/trainval.json", "./data/images")
```

Then I tried to train the model with this dataset using this python script:
```python
import sys
tensormask_path = "../detectron2/"
sys.path.append(tensormask_path)

import random
from detectron2.utils.visualizer import Visualizer
from detectron2.data.catalog import MetadataCatalog, DatasetCatalog
import data_register
import cv2
from detectron2.engine import DefaultTrainer, default_argument_parser, default_setup, launch
from detectron2.config import get_cfg
from detectron2.utils.logger import setup_logger
import detectron2.utils.comm as comm
from detectron2.checkpoint import DetectionCheckpointer
from projects.TensorMask.tensormask import add_tensormask_config
import os
setup_logger()


if __name__ == "__main__":
    cfg = get_cfg()
    add_tensormask_config(cfg)
    cfg.merge_from_file("../detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml")
    cfg.DATASETS.TRAIN = ("fruit_nuts",)
    cfg.DATASETS.TEST = ()
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.MODELS.WEIGHTS = "./output/model_final.pth"
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.0025
    cfg.SOLVER.MAX_ITER = (2500)
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (128)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3
    os.makedirs(cfg.OUTPUT_DIR, exis_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
```
Yet, I have encountered this error:
```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from projects.TensorMask.tensormask import add_tensormask_config
  File "../detectron2/projects/TensorMask/tensormask/__init__.py", line 3, in <module>
    from .arch import TensorMask
  File "../detectron2/projects/TensorMask/tensormask/arch.py", line 285, in <module>
    class TensorMask(nn.Module):
  File "/home/zhaozixiao/miniconda3/envs/dl_env/lib/python3.6/site-packages/fvcore/common/registry.py", line 58, in deco
    self._do_register(name, func_or_class)
  File "/home/zhaozixiao/miniconda3/envs/dl_env/lib/python3.6/site-packages/fvcore/common/registry.py", line 45, in _do_register
    name, self._name
AssertionError: An object named 'TensorMask' was already registered in 'META_ARCH' registry!
```
But when I try to run the original `train_net.py` in TensorMask project, there isn't this problem. Do you have any idea how this problem can be solved?

Thx in advance

**Comment by ppwwyyxx** [comment]
You need to import tensormask in the same way its `train_net.py` did.
