### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#1188]
I'm not sure what happened. I coded many things on detectron2, everything works well. But this afternoon, I uninstall tensorflow and then I reinstall tensorflow via pip. Then now I can not `from detectron2 import model_zoo`
## Instructions To Reproduce the Issue:
2. what exact command you run:
To solve this, I tried to uninstall detectron2 by `rm -rf build/ **/*.so`  and reinstall detectron2. The logs is:
```
minhkv@server1:~/tienpv_DO_NOT_REMOVE/detectron2$ python3 -m pip install --user -e .
Obtaining file:///home/minhkv/tienpv_DO_NOT_REMOVE/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.1.0)
Requirement already satisfied: Pillow in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (7.0.0)
Requirement already satisfied: yacs>=0.1.6 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.1.6)
Requirement already satisfied: tabulate in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.8.6)
Requirement already satisfied: cloudpickle in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.3.0)
Requirement already satisfied: matplotlib in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (3.2.1)
Requirement already satisfied: tqdm>4.29.0 in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (4.43.0)
Requirement already satisfied: tensorboard in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (2.1.1)
Requirement already satisfied: fvcore in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.1)
Requirement already satisfied: future in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (0.18.2)
Requirement already satisfied: pydot in /home/minhkv/.local/lib/python3.6/site-packages (from detectron2==0.1.1) (1.4.1)
Requirement already satisfied: PyYAML in /home/minhkv/.local/lib/python3.6/site-packages (from yacs>=0.1.6->detectron2==0.1.1) (5.3.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (2.4.6)
Requirement already satisfied: python-dateutil>=2.1 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (0.10.0)
Requirement already satisfied: numpy>=1.11 in /home/minhkv/.local/lib/python3.6/site-packages (from matplotlib->detectron2==0.1.1) (1.16.2)
Requirement already satisfied: absl-py>=0.4 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.9.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.34.2)
Requirement already satisfied: markdown>=2.6.8 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (3.2.1)
Requirement already satisfied: setuptools>=41.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (42.0.0)
Requirement already satisfied: six>=1.10.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.14.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (0.4.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.11.3)
Requirement already satisfied: protobuf>=3.6.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (3.11.3)
Requirement already satisfied: werkzeug>=0.11.15 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.0.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (2.23.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/minhkv/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.1.1) (1.27.2)
Requirement already satisfied: portalocker in /home/minhkv/.local/lib/python3.6/site-packages (from fvcore->detectron2==0.1.1) (1.5.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (1.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.2.8)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (4.0.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/minhkv/.local/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.1.1) (2019.11.28)
Requirement already satisfied: oauthlib>=3.0.0 in /home/minhkv/.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.1.1) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/minhkv/.local/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.1.1) (0.4.8)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.1.1
    Can't uninstall 'detectron2'. No files were found to uninstall.
  Running setup.py develop for detectron2
Successfully installed detectron2
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
```
3. what you observed (including __full logs__):
```
minhkv@server1:~/tienpv_DO_NOT_REMOVE$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from detectron2 import model_zoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/model_zoo/__init__.py", line 7, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/model_zoo/model_zoo.py", line 8, in <module>
    from detectron2.modeling import build_model
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/modeling/__init__.py", line 6, in <module>
    from .anchor_generator import build_anchor_generator, ANCHOR_GENERATOR_REGISTRY
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/modeling/anchor_generator.py", line 9, in <module>
    from detectron2.structures import Boxes, RotatedBoxes
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, rasterize_polygons_within_box, polygons_to_bitmask
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2/structures/masks.py", line 6, in <module>
    import pycocotools.mask as mask_utils
  File "/home/minhkv/.local/lib/python3.6/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 918, in init pycocotools._mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python3 collect_env.py
------------------------  ------------------------------------------------------------------
sys.platform              linux
Python                    3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
numpy                     1.14.5
detectron2                0.1.1 @/home/minhkv/tienpv_DO_NOT_REMOVE/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/minhkv/.local/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-10.0
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    7.0.0
torchvision               0.5.0 @/home/minhkv/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  ------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```
If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues
Yes. I've read these instructions hundred times since I've worked with detectron2 for 4 months!
THANK YOU FOR YOUR HELP!

**Comment by pvtien96** [comment]
Problem relates to numpy, you need numpy>=1.16.1
You can upgrade all python packages by: 
`pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`
This worked for me.
