### ISSUE TITLE
Exporting GPU compatible Mask RCNN fails with pytorch master

### ISSUE THREAD

**Issue by ashnair1** [facebookresearch/detectron2#1189]
Following the instructions provided [here](https://detectron2.readthedocs.io/tutorials/deployment.html) I tried to export a Mask RCNN model that is GPU compatible via the exporter but it failed. Error details below.

If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
No change
```
2. what exact command you run:
```
tools/deploy/caffe2_converter.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml     --output ./caffe2_model_test  MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
3. what you observed (including __full logs__):
```
[04/09 17:40:12 detectron2]: Command line arguments: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output='./caffe2_model_test', run_eval=False)
[04/09 17:40:15 d2.data.datasets.coco]: Loaded 5000 images in COCO format from datasets/coco/annotations/instances_val2017.json
[04/09 17:40:16 d2.data.build]: Distribution of instances among all 80 categories:
|   category    | #instances   |   category   | #instances   |   category    | #instances   |
|:-------------:|:-------------|:------------:|:-------------|:-------------:|:-------------|
|    person     | 10777        |   bicycle    | 314          |      car      | 1918         |
|  motorcycle   | 367          |   airplane   | 143          |      bus      | 283          |
|     train     | 190          |    truck     | 414          |     boat      | 424          |
| traffic light | 634          | fire hydrant | 101          |   stop sign   | 75           |
| parking meter | 60           |    bench     | 411          |     bird      | 427          |
|      cat      | 202          |     dog      | 218          |     horse     | 272          |
|     sheep     | 354          |     cow      | 372          |   elephant    | 252          |
|     bear      | 71           |    zebra     | 266          |    giraffe    | 232          |
|   backpack    | 371          |   umbrella   | 407          |    handbag    | 540          |
|      tie      | 252          |   suitcase   | 299          |    frisbee    | 115          |
|     skis      | 241          |  snowboard   | 69           |  sports ball  | 260          |
|     kite      | 327          | baseball bat | 145          | baseball gl.. | 148          |
|  skateboard   | 179          |  surfboard   | 267          | tennis racket | 225          |
|    bottle     | 1013         |  wine glass  | 341          |      cup      | 895          |
|     fork      | 215          |    knife     | 325          |     spoon     | 253          |
|     bowl      | 623          |    banana    | 370          |     apple     | 236          |
|   sandwich    | 177          |    orange    | 285          |   broccoli    | 312          |
|    carrot     | 365          |   hot dog    | 125          |     pizza     | 284          |
|     donut     | 328          |     cake     | 310          |     chair     | 1771         |
|     couch     | 261          | potted plant | 342          |      bed      | 163          |
| dining table  | 695          |    toilet    | 179          |      tv       | 288          |
|    laptop     | 231          |    mouse     | 106          |    remote     | 283          |
|   keyboard    | 153          |  cell phone  | 262          |   microwave   | 55           |
|     oven      | 143          |   toaster    | 9            |     sink      | 225          |
| refrigerator  | 126          |     book     | 1129         |     clock     | 267          |
|     vase      | 274          |   scissors   | 36           |  teddy bear   | 190          |
|  hair drier   | 11           |  toothbrush  | 57           |               |              |
|     total     | 36335        |              |              |               |              |
[04/09 17:40:16 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
[04/09 17:40:16 d2.data.common]: Serialized dataset takes 19.39 MiB
[04/09 17:40:16 d2.export.caffe2_export]: Exporting a Caffe2GeneralizedRCNN model via ONNX ...
/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py:231: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py:231: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
Traceback (most recent call last):
  File "tools/deploy/caffe2_converter.py", line 52, in <module>
    caffe2_model = export_caffe2_model(cfg, torch_model, first_batch)
  File "/home/ashwin/Desktop/Projects/detectron2/detectron2/export/api.py", line 57, in export_caffe2_model
    predict_net, init_net = export_caffe2_detection_model(c2_compatible_model, c2_format_input)
  File "/home/ashwin/Desktop/Projects/detectron2/detectron2/export/caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "/home/ashwin/Desktop/Projects/detectron2/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/__init__.py", line 172, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 510, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 350, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/onnx/utils.py", line 307, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 558, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 556, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 542, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ashwin/Desktop/Projects/detectron2/detectron2/export/caffe2_modeling.py", line 268, in forward
    proposals, _ = self._wrapped_model.proposal_generator(images, features)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 556, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 542, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ashwin/Desktop/Projects/detectron2/detectron2/export/c10.py", line 205, in forward
    legacy_plus_one=False,
RuntimeError: Could not run '_caffe2::GenerateProposals' with arguments from the 'CUDATensorId' backend. '_caffe2::GenerateProposals' is only available for these backends: [CPUTensorId].

```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

My Environment

```
------------------------  --------------------------------------------------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/ashwin/Desktop/Projects/detectron2/detectron2
detectron2 compiler       GCC 5.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.6.0a0+7487b2a @/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2070 with Max-Q Design
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.168
Pillow                    6.2.2
torchvision               0.6.0a0+dec8628 @/home/ashwin/anaconda3/envs/test/lib/python3.7/site-packages/torchvision-0.6.0a0+dec8628-py3.7-linux-x86_64.egg/torchvision
torchvision arch flags    sm_75
------------------------  --------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 5.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.2.0 (Git Hash 70f8b879ea7a0c38caedb3320b7c85e8497ff50d)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.2
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
fixed in pytorch by https://github.com/pytorch/pytorch/commit/9a4bc67f662b3ab900327956e6e3c91aa85ef828
and also requires latest detectron2 commit to work.
