### ISSUE TITLE
Problems while running caffe2_converter.py to convert APIS

### ISSUE THREAD

**Issue by Kevinstiff** [facebookresearch/detectron2#1194]
## Instructions To Reproduce the Issue:
1.Using the official model conversion tool, convert. PKL model to caffe ONNX model

2. what exact command you run:
```
<(PyTorch) D:\ProJect\detectron2>python tools/caffe2_converter.py --config-file ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml  --output caffe2_medels --run-eval  MODEL.WEIGHTS model_final_f10217.pkl MODEL.DEVICE cpu>
```
3. full logs:
```
[04/10 15:06:48 detectron2]: Command line arguments: Namespace(config_file='./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', opts=['MODEL.WEIGHTS', 'model_final_f10217.pkl', 'MODEL.DEVICE', 'cpu'], output='caffe2_medels', run_eval=True)
[04/10 15:06:49 d2.data.datasets.coco]: Loaded 5000 images in COCO format from datasets\coco/annotations/instances_val2017.json
[04/10 15:06:49 d2.data.build]: Distribution of instances among all 80 categories:
|   category    | #instances   |   category   | #instances   |   category    | #instances   |
|:-------------:|:-------------|:------------:|:-------------|:-------------:|:-------------|
|    person     | 10777        |   bicycle    | 314          |      car      | 1918         |
|  motorcycle   | 367          |   airplane   | 143          |      bus      | 283          |
|     train     | 190          |    truck     | 414          |     boat      | 424          |
| traffic light | 634          | fire hydrant | 101          |   stop sign   | 75           |
| parking meter | 60           |    bench     | 411          |     bird      | 427          |
|      cat      | 202          |     dog      | 218          |     horse     | 272          |
|     sheep     | 354          |     cow      | 372          |   elephant    | 252          |
|     bear      | 71           |    zebra     | 266          |    giraffe    | 232          |
|   backpack    | 371          |   umbrella   | 407          |    handbag    | 540          |
|      tie      | 252          |   suitcase   | 299          |    frisbee    | 115          |
|     skis      | 241          |  snowboard   | 69           |  sports ball  | 260          |
|     kite      | 327          | baseball bat | 145          | baseball gl.. | 148          |
|  skateboard   | 179          |  surfboard   | 267          | tennis racket | 225          |
|    bottle     | 1013         |  wine glass  | 341          |      cup      | 895          |
|     fork      | 215          |    knife     | 325          |     spoon     | 253          |
|     bowl      | 623          |    banana    | 370          |     apple     | 236          |
|   sandwich    | 177          |    orange    | 285          |   broccoli    | 312          |
|    carrot     | 365          |   hot dog    | 125          |     pizza     | 284          |
|     donut     | 328          |     cake     | 310          |     chair     | 1771         |
|     couch     | 261          | potted plant | 342          |      bed      | 163          |
| dining table  | 695          |    toilet    | 179          |      tv       | 288          |
|    laptop     | 231          |    mouse     | 106          |    remote     | 283          |
|   keyboard    | 153          |  cell phone  | 262          |   microwave   | 55           |
|     oven      | 143          |   toaster    | 9            |     sink      | 225          |
| refrigerator  | 126          |     book     | 1129         |     clock     | 267          |
|     vase      | 274          |   scissors   | 36           |  teddy bear   | 190          |
|  hair drier   | 11           |  toothbrush  | 57           |               |              |
|     total     | 36335        |              |              |               |              |
[04/10 15:06:49 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
[04/10 15:06:50 d2.data.common]: Serialized dataset takes 19.39 MiB
[04/10 15:06:50 d2.export.caffe2_export]: Exporting a Caffe2GeneralizedRCNN model via ONNX ...
Traceback (most recent call last):
  File "tools/caffe2_converter.py", line 52, in <module>
    caffe2_model = export_caffe2_model(cfg, torch_model, first_batch)
  File "d:\project\detectron2\detectron2\export\api.py", line 57, in export_caffe2_model
    predict_net, init_net = export_caffe2_detection_model(c2_compatible_model, c2_format_input)
  File "d:\project\detectron2\detectron2\export\caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "d:\project\detectron2\detectron2\export\caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\onnx\__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\onnx\utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\onnx\utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\onnx\utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\onnx\utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\jit\__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\jit\__init__.py", line 360, in forward
    self._force_outplace,
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\jit\__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\PyTorch\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "d:\project\detectron2\detectron2\export\caffe2_modeling.py", line 266, in forward
    images = self._caffe2_preprocess_image(inputs)
  File "d:\project\detectron2\detectron2\export\caffe2_modeling.py", line 208, in _caffe2_preprocess_image
    data = alias(data, "data")
  File "d:\project\detectron2\detectron2\export\shared.py", line 593, in alias
    return torch.ops._caffe2.AliasWithName(x, name, is_backward=is_backward)
  File "D:\Anaconda3\envs\PyTorch\lib\site-packages\torch\_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator _caffe2::AliasWithName
```

## Expected behavior:

(1)Caffe2 Deployment

## Environment:

Provide your environment information using the following command:
```
(PyTorch) D:\ProJect\detectron2>python -m detectron2.utils.collect_env
------------------------  -------------------------------------------------------------------------------------
sys.platform              win32
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
numpy                     1.14.2
detectron2                0.1.1 @D:\ProJect\detectron2\detectron2
detectron2 compiler       MSVC 192428319
detectron2 CUDA compiler  10.2
detectron2 arch flags     D:\ProJect\detectron2\detectron2\_C.cp36-win_amd64.pyd; cannot find cuobjdump
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @D:\Anaconda3\envs\PyTorch\lib\site-packages\torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2060
CUDA_HOME                 D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\V10.2
NVCC                      Not Available
Pillow                    7.0.0
torchvision               0.5.0 @D:\Anaconda3\envs\PyTorch\lib\site-packages\torchvision
torchvision arch flags    D:\Anaconda3\envs\PyTorch\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
cv2                       3.4.2
------------------------  -------------------------------------------------------------------------------------
PyTorch built with:
  - MSVC 191125547
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - OpenMP 200203
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.5.1
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS  /GR  /w /EHa /MP /bigobj -openmp, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
The official windows version of pytorch does not contain caffe2 support by default. So it's expected. A custom build of pytorch would be needed
