### ISSUE TITLE
Deploy to Caffe2 Example Error

### ISSUE THREAD

**Issue by crocodoyle** [facebookresearch/detectron2#1196]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
None
```
2. what exact command you run:
```
cd tools/deploy/ && ./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --output ./caffe2_model --run-eval \
    MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \
    MODEL.DEVICE cpu
```
Model is converted without error. However, when trying to run the C++ example (`tools/deploy/caffe2_mask_rcnn.cpp`), I get an error.

3. what you observed (including __full logs__):
```
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at conv_pool_op_base.h:240] inner_size > 0. 0 vs 0
Error from operator: 
input: "normalized_data" input: "596" input: "598" output: "322" name: "" type: "Conv" arg { name: "pads" ints: 3 ints: 3 ints: 3 ints: 3 } arg { name: "kernels" ints: 7 ints: 7 } arg { name: "dilations" ints: 1 ints: 1 } arg { name: "strides" ints: 2 ints: 2 } arg { name: "group" i: 1 } device_option { device_type: 0 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7ffff7bb95a6 in /usr/local/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0x568ba7b (0x7fffb151ea7b in /usr/local/libtorch/lib/libtorch.so)
frame #2: <unknown function> + 0x568e91c (0x7fffb152191c in /usr/local/libtorch/lib/libtorch.so)
frame #3: <unknown function> + 0x54d61b5 (0x7fffb13691b5 in /usr/local/libtorch/lib/libtorch.so)
frame #4: <unknown function> + 0x53b85e5 (0x7fffb124b5e5 in /usr/local/libtorch/lib/libtorch.so)
frame #5: caffe2::SimpleNet::Run() + 0x196 (0x7fffb0fac936 in /usr/local/libtorch/lib/libtorch.so)
frame #6: caffe2::Workspace::RunNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x120 (0x7fffb0ff87d0 in /usr/local/libtorch/lib/libtorch.so)
frame #7: <unknown function> + 0xc0e5 (0x5555555600e5 in /home/adoyle/Desktop/opencvTest/caffe2_mask_rcnn)
frame #8: __libc_start_main + 0xe7 (0x7fffa95ceb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0xb1ca (0x55555555f1ca in /home/adoyle/Desktop/opencvTest/caffe2_mask_rcnn)
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

Model is traced/converted so that inference can be run in C++ successfully.

## Environment:
```
------------------------  --------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/adoyle/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/adoyle/anaconda3/envs/runes/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.0.0
torchvision               0.5.0 @/home/adoyle/anaconda3/envs/runes/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       3.4.2
------------------------  --------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```
Thanks to anyone who can help out with this, I have been trying for weeks to convert a custom model to Caffe2. It works flawlessly with the Detectron2 APIs, but I get similar caffe2_enforce errors when trying to use either the Python Caffe2 API or the C++ API.

**Comment by ppwwyyxx** [comment]
Could you reproduce this issue in detectron2's docker (https://github.com/facebookresearch/detectron2/tree/master/docker) ?
If yes, could you provide the input image so others can reproduce the issue as well?

**Comment by crocodoyle** [comment]
I could not get the detectron2 docker container to work properly. Here is the error I got:
```
appuser@fb831fb5afb8:~/detectron2_repo$ python3 tools/deploy/caffe2_converter.py 
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "tools/deploy/caffe2_converter.py", line 10, in <module>
    from detectron2.export import add_export_config, export_caffe2_model
  File "/home/appuser/detectron2_repo/detectron2/export/__init__.py", line 3, in <module>
    from .api import *
  File "/home/appuser/detectron2_repo/detectron2/export/api.py", line 10, in <module>
    from .caffe2_export import export_caffe2_detection_model
  File "/home/appuser/detectron2_repo/detectron2/export/caffe2_export.py", line 8, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

**Comment by ppwwyyxx** [comment]
You can use an existing converted model and the C++ code inside the docker file using instructions in https://detectron2.readthedocs.io/tutorials/deployment.html#use-the-model-in-c-python
Running conversion inside the docker requires some extra dependencies that we haven't added

**Comment by crocodoyle** [comment]
If you haven't added the dependencies required to resolve the bug then why
was the issue closed?

**Comment by ppwwyyxx** [comment]
Because

> You can use an existing converted model and the C++ code inside the docker

Feel free to reopen if the issue exists inside docker
