### ISSUE TITLE
Problems while running caffe2_converter.py to convert APIS

### ISSUE THREAD

**Issue by Kevinstiff** [facebookresearch/detectron2#1204]
## Instructions To Reproduce the Issue:
1.Using the official model conversion tool, convert. PKL model to caffe ONNX model

2. exact run command:
```
(detectron2) kevin@ubuntu:~/project/detectron2$ python tools/caffe2_converter.py --config-file ./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml  --output caffe2_medels --run-eval  MODEL.WEIGHTS model_final_f10217.pkl MODEL.DEVICE cpu
```
3. full logs:
```
Traceback (most recent call last):
  File "tools/caffe2_converter.py", line 8, in <module>
    from detectron2.data import build_detection_test_loader
  File "/home/kevin/project/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/kevin/project/detectron2/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/kevin/project/detectron2/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/kevin/project/detectron2/detectron2/structures/boxes.py", line 8, in <module>
    from detectron2.layers import cat
  File "/home/kevin/project/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/kevin/project/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/kevin/project/detectron2/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

## Expected behavior:

(1)Caffe2 Deployment

## Environment:

my environment information:
```
(detectron2) kevin@ubuntu:~/project/detectron2$ python -m detectron2.utils.collect_env
----------------------  ----------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
numpy                   1.17.4
detectron2              0.1.1 @/home/kevin/project/detectron2/detectron2
detectron2._C           failed to import
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/kevin/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0,1                 Tesla T4
CUDA_HOME               :/usr/local/cuda-10.1/usr/local/cuda-10.1/bin/
Pillow                  6.2.1
torchvision             0.5.0 @/home/kevin/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision
torchvision arch flags  /home/kevin/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision/_C.so; cannot find cuobjdump
cv2                     3.4.2
----------------------  ----------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.5
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/pytorch_1584542718079/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584542718079/work=/usr/local/src/conda/pytorch-1.4.0 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584542718079/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

>  Undefined torch/aten/caffe2 symbols, or segmentation fault immediately when running the library.
This can happen if detectron2 or torchvision is not compiled with the version of PyTorch you’re running.
If you use a pre-built torchvision, uninstall torchvision & pytorch, and reinstall them following pytorch.org. If you manually build detectron2 or torchvision, remove the files you built (build/, **/*.so) and rebuild them.
