### ISSUE TITLE
Program stuck at the final tensorboard writing step

### ISSUE THREAD

**Issue by Shaunlipy** [facebookresearch/detectron2#121]
Hi, I am using the colab tutorial code (training the balloon). The training stuck at the final step:  it prints "Total training time: 0:01:38 (0:00:03 on hooks)" then hangs there forever. 

I tried debug mode. it alerts:

```python
Exception ignored in: <function TensorboardXWriter.__del__ at 0x7fdcc30de6a8>
Traceback (most recent call last):
  File "/home/ubuntu/detectron2_repo/detectron2/utils/events.py", line 118, in __del__
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 965, in close
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 139, in close
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 113, in close
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 164, in close
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 191, in stop
  File "/home/ubuntu/anaconda3/lib/python3.7/queue.py", line 151, in put
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable
```

I am using 
Python 3.7.3
tensorboard 2.0.0
pytorch 1.3.0

Any ideas?

Thanks

**Comment by ppwwyyxx** [comment]
The exception should now disappear with 6f13759941eab453483e5b9f18415440a48a2629. But it's unknown whether it is related to the hang you observed. If you still experience similar issues, please provide detailed instructions to reproduce it.

**Comment by Shaunlipy** [comment]
I don't see where the the function __del__() being called. 

Maybe it should also implement in the train_loop.py file? Somewhere in the 
```python
# on line 134 of train_loop.py
finally:
    self.after_train()

```

I used the same code from the Colab tutorial, but run on my local server in a python file (instead of the Jupiter notebook).

```python
# save in main.py
from detectron2.data.datasets import register_coco_instances
from detectron2.data import MetadataCatalog, DatasetCatalog
import cv2
from detectron2.utils.logger import setup_logger
setup_logger()

register_coco_instances("containers", {}, "/home/ubuntu/Data/Container/output.json", "/home/ubuntu/Data/Container/JPEGImages")

container_metadata = MetadataCatalog.get("containers")

print (container_metadata)

dataset_dicts = DatasetCatalog.get('containers')

from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file(
    "/home/ubuntu/detectron2_repo/configs/COCO-Detection/retinanet_R_50_FPN_3x.yaml"
)
cfg.DATASETS.TRAIN = ("containers",)
cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 0
cfg.MODEL.WEIGHTS = "detectron2://COCO-Detection/retinanet_R_50_FPN_3x/137849486/model_final_4cafe0.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = (
    300
)  # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (
    128
)  # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # 3 classes (data, fig, hazelnut)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```

**Comment by ppwwyyxx** [comment]
The behavior of `__del__` is not quite reliably. 20bef23a65fa3c4b03af419c8772956e46c4df0a should now address the issue.

**Comment by Shaunlipy** [comment]
Yep, that solves the issue.

Thanks!!
