### ISSUE TITLE
ImportError: cannot import name '_C', but able to run yesterday

### ISSUE THREAD

**Issue by Study-is-happy** [facebookresearch/detectron2#125]
Trying to run demo, but **cannot import name '_C'**
The strangest thing is that **I was able to run everything yesterday**, after I pulled the repository again and install today, it crashed.

`$ python demo/demo.py  \
> --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
> --input input.jpg \
> --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/data/build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/structures/boxes.py", line 7, in <module>
    from detectron2.layers import cat
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/zhiyongzhang/venv/AutomatedFishDetection/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: cannot import name '_C'`

**Comment by ppwwyyxx** [comment]
You did not compile detectron2. Please follow [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) to install it.

**Comment by Study-is-happy** [comment]
I am so sorry that I did not cd into the directory and run setup.py. Thanks for your help!!! @ppwwyyxx
