### ISSUE TITLE
RuntimeError: No such operator _caffe2 :: AliasWithName

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1256]
Hello, when I run caffe2_converter.py, my command is:
./caffe2_converter.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2: // COCO-InstanceSegmentation / mask_rcnn_R_50_FPN_10x / 137849600 / final pkl MODEL.DEVICE cpu

RuntimeError: No such operator _caffe2 :: AliasWithName is thrown, specific Traceback:

Traceback (most recent call last):
  File "./caffe2_converter.py", line 52, in <module>
    caffe2_model = export_caffe2_model (cfg, torch_model, first_batch)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/api.py", line 57, in export_caffe2_model
    predict_net, init_net = export_caffe2_detection_model (c2_compatible_model, c2_format_input)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model (model, (tensor_inputs,))
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type = OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes = dynamic_axes, keep_initializers_as_inputs = keep_initializers_as_inputs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, ​​in _export
    fixed_batch_size = fixed_batch_size)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model (model, args, training)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph (model, args, _force_outplace = True, _return_inputs_states = True)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule (f, _force_outplace, return_inputs, _return_inputs_states) (* args, ** kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward (* input, ** kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/jit/__init__.py", line 352, in forward
    out = self.inner (* trace_inputs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward (* input, ** kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward (* input, ** kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/contextlib.py", line 74, in inner
    return func (* args, ** kwds)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_modeling.py", line 266, in forward
    images = self._caffe2_preprocess_image (inputs)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_modeling.py", line 208, in _caffe2_preprocess_image
    data = alias (data, "data")
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/shared.py", line 593, in alias
    return torch.ops._caffe2.AliasWithName (x, name, is_backward = is_backward)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation (qualified_op_name)
RuntimeError: No such operator _caffe2 :: AliasWithName

How to solve this problem, thank you

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Kevinstiff** [comment]
If you are using the environment on Windows，the official windows version of pytorch does not contain caffe2 support by default. So it's expected. A custom build of pytorch would be needed.

**Comment by lg12170226** [comment]
@limengfei3675 @Kevinstiff i get the same err,is sloved?
