### ISSUE TITLE
The match_quality_matrix is less than 0 in the roi_heads section

### ISSUE THREAD

**Issue by sunshuofeng** [facebookresearch/detectron2#1266]
An assertion error occurs in the roi_heads section: 
`assert torch.all(match_quality_matrix >= 0)`
##Error Message
```
Traceback (most recent call last):
  File "test_main.py", line 131, in <module>
    loss_dict = model(data)
  File "/root/anaconda3/envs/python367/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/root/anaconda3/envs/python367/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 551, in forward
    proposals = self.label_and_sample_proposals(proposals, targets)
  File "/root/anaconda3/envs/python367/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/root/yaogan/custom/kaggle_roi.py", line 43, in label_and_sample_proposals
    matched_idxs, matched_labels = self.proposal_matcher(match_quality_matrix)
  File "/root/detectron2/detectron2/modeling/matcher.py", line 85, in __call__
    assert torch.all(match_quality_matrix >= 0)
AssertionError

```
I output both the error-reporting proposal and the gt_instance information：

```
[Instances(num_instances=22, image_height=1000, image_width=1000, fields=[gt_boxes: RotatedBoxes(tensor([[621.0820, 941.3327,  75.0000,  15.0000, -19.2752],
        [537.6692, 399.8650,  58.0000,  47.0000,  80.7248],
        [114.6510, 207.5121,  46.0000,  46.0000, -88.2752],
        [370.4406, 306.7274,  89.0000,  88.0000,  42.7248],
        [125.1932, 245.7465,  34.0000,  31.0000,  -5.2752],
        [265.1678, 204.5627,  83.0000,  34.0000,  61.7248],
        [192.5995, 944.1084,  41.0000,  24.0000,  28.7248],
        [343.7673, 607.5355,  89.0000,  63.0000, -68.2752],
        [325.9977, 926.0277,  47.0000,  31.0000,   4.7248],
        [276.9391, 797.1430,  39.0000,  10.0000,  58.7248],
        [273.6799, 762.3669,  37.0000,  25.0000, -58.2752],
        [282.1378, 733.5665,  46.0000,  37.0000, -59.2752],
        [745.8838, 448.6162,  70.0000,  44.0000, -26.2752],
        [478.2423, 748.8312,  74.0000,  48.0000,  77.7248],
        [774.8605, 520.3195,  83.0000,  51.0000,  29.7248],
        [568.7340, 653.3940,  91.0000,  82.0000, -51.2752],
        [120.2137, 614.7996,  40.0000,  27.0000,  51.7248],
        [443.5682, 675.2466,  58.0000,  56.0000,  50.7248],
        [492.0311, 703.8883,  84.0000,  76.0000, -17.2752],
        [-70.7023, 759.2160,  92.0000,  50.0000,   3.7248],
        [336.2666, 866.2318,  90.0000,  51.0000, -78.2752],
        [  6.4238, 860.5105,  75.0000,  31.0000, -89.2752]], device='cuda:0')), gt_classes: tensor([7, 2, 7, 0, 2, 3, 0, 1, 6, 2, 7, 3, 4, 1, 1, 6, 0, 6, 0, 5, 0, 0],
       device='cuda:0')]), Instances(num_instances=12, image_height=1000, image_width=1000, fields=[gt_boxes: RotatedBoxes(tensor([[ 175.5772, 1014.4172,   62.0000,   30.0000,    4.6554],
        [ -17.2292,  636.6519,   80.0000,   75.0000,  -77.3446],
        [ 666.6331,  825.8856,   62.0000,   61.0000,    8.6554],
        [ 766.5089,  625.1797,   73.0000,   18.0000,  -43.3446],
        [ 853.0723,  578.2035,   58.0000,   39.0000,  -40.3446],
        [ -16.8365,  606.1257,   72.0000,   55.0000,  -38.3446],
        [ -44.3725,  709.4202,   95.0000,   62.0000,  -83.3446],
        [ 393.5010,  784.3058,   49.0000,   26.0000,   73.6554],
        [ 184.0228,  393.6156,   66.0000,   37.0000,   34.6554],
        [ 370.8124,  964.0563,   92.0000,   18.0000,   51.6554],
        [ 165.0993,  402.9377,   68.0000,   63.0000,   45.6554],
        [ 292.8438,  561.9545,   86.0000,   28.0000,  -23.3446]],
       device='cuda:0')), gt_classes: tensor([7, 3, 7, 7, 5, 2, 6, 1, 3, 2, 1, 2], device='cuda:0')])]
[Instances(num_instances=1022, image_height=1000, image_width=1000, fields=[proposal_boxes: RotatedBoxes(tensor([[ 7.6427e+02,  1.6448e+02,  5.6782e+01,  1.5827e-01, -1.3679e+02],
        [ 7.4865e+02,  1.6945e+02,  5.0407e+01,  1.3036e-01, -1.4421e+02],
        [ 7.4379e+02,  1.8136e+02,  4.6112e+01,  1.4892e-01, -1.5670e+02],
        ...,
        [-7.0702e+01,  7.5922e+02,  9.2000e+01,  5.0000e+01,  3.7248e+00],
        [ 3.3627e+02,  8.6623e+02,  9.0000e+01,  5.1000e+01, -7.8275e+01],
        [ 6.4238e+00,  8.6051e+02,  7.5000e+01,  3.1000e+01, -8.9275e+01]],
       device='cuda:0')), objectness_logits: tensor([ 8.3246,  8.2933,  8.1144,  ..., 23.0259, 23.0259, 23.0259],
       device='cuda:0')]), Instances(num_instances=1012, image_height=1000, image_width=1000, fields=[proposal_boxes: RotatedBoxes(tensor([[ 7.6237e+02,  1.6576e+02,  5.5843e+01,  1.5779e-01, -1.3833e+02],
        [ 7.4740e+02,  1.7082e+02,  4.9704e+01,  1.2925e-01, -1.4503e+02],
        [ 7.4136e+02,  1.8420e+02,  4.5204e+01,  1.4620e-01, -1.5787e+02],
        ...,
        [ 3.7081e+02,  9.6406e+02,  9.2000e+01,  1.8000e+01,  5.1655e+01],
        [ 1.6510e+02,  4.0294e+02,  6.8000e+01,  6.3000e+01,  4.5655e+01],
        [ 2.9284e+02,  5.6195e+02,  8.6000e+01,  2.8000e+01, -2.3345e+01]],
       device='cuda:0')), objectness_logits: tensor([ 8.3148,  8.2864,  8.1091,  ..., 23.0259, 23.0259, 23.0259],
       device='cuda:0')])]
```

## My Code:
I provide a simple example
```
# make image_list
def get_image_list(args):
    image_list=[]
    with tqdm(total=1000) as pbar:
        for i in range(1000):
            image_dict={}
            image_dict['image_id']=i
            image_dict['file_name']='image'
            image_dict['height']=1000
            image_dict['width']=1000
            nums=np.random.randint(5,30,1)[0]
            annotations=[]
            for i in range(nums):
                anno={}
                height=np.random.randint(10,100,1)[0]
                width=np.random.randint(10,100,1)[0]
                angle=np.random.randint(-90,90,1)[0]
                label=np.random.randint(0,8,1)[0]
                centerx=np.random.randint(100,900,1)[0]
                centery=np.random.randint(100,900,1)[0]
                if height>width:
                    a=width
                    width=height
                    height=a
                box=[centerx,centery,width,height,angle]
                anno['bbox']=box
                anno['category_id']=label
                annotations.append(anno)
            image_dict['annotations']=annotations
            image_list.append(image_dict)
            pbar.update(1)
    return image_list

#rotation transform

class Rotate_Rotation:
    def __init__(self):
        self.tfms_gen = RandomRotation([-45., 45.])

    def __call__(self, datadict):
        image = datadict['image']
        tfms, angle = self.tfms_gen.get_transform(image)
        image = tfms.apply_image(image)
        datadict['image'] = image
        for anno in datadict['annotations']:
            box = (anno['bbox'])
            centeryx = np.array([(box[0], box[1])])
            new_centeryx = tfms.apply_coords(centeryx)
            new_angle = self.get_new_angle(box[-1], angle)
            box[0] = new_centeryx[0][0]
            box[1] = new_centeryx[0][1]
            box[-1] = new_angle
            anno['bbox'] = box

    def get_new_angle(self, angle, rotate_angle):
        new_angle = angle + rotate_angle
        if new_angle > 90:
            new_angle = -(180 - new_angle)
        elif new_angle < -90:
            new_angle = -90 - (new_angle)

        return new_angle

#Hlip rotation
import albumentations as A
class Hlip_Rotation:
    def __init__(self):
        pass

    def __call__(self, datadict):
        image = datadict['image']
        w = datadict['width']
        new_image = A.HorizontalFlip(p=1)(image=image)['image']
        datadict['image'] = new_image
        for anno in datadict['annotations']:
            box = anno['bbox']
            new_box = self.hlip_box(w, box)
            anno['bbox'] = new_box



def get_transform_list():
    transorm_list = []
    rotate = Rotate_Rotation()
    hlip = Hlip_Rotation()
    transorm_list.append(rotate)
    transorm_list.append(hlip)
    return transorm_list




class test_mapper:
     def __init__(self,cfg,is_train=True):
         self.is_train = is_train
         self.tfms = get_transform_list()

     def __call__(self, dataset_dict):
         image=np.random.random((1000,1000,3)).astype(np.float64)
         image=image*255
         dataset_dict['image']=image
         image_shape=image.shape[:2]
         if not self.is_train:
             dataset_dict.pop('annotations', None)
         for tfm in self.tfms:
             tfm(dataset_dict)
         dataset_dict['image']=torch.as_tensor(np.ascontiguousarray(image.transpose(2, 0, 1))).type(torch.uint8)
         anno = dataset_dict['annotations']
         dataset_dict.pop('annotations')
         instance = detection_utils.annotations_to_instances_rotated(anno, image_shape)
         dataset_dict['instances'] = detection_utils.filter_empty_instances(instance)
         return dataset_dict

```
Above is the custom data handling section

Here is the code for the configuration file：

```
Train_Class_Name = ['helicopter', 'plane', 'ground-track-field', 'roundabout', 'baseball-diamond', 'tennis-court',
                    'harbor', 'soccer-ball-field', 'basketball-court']
for d in ['train']:
    DatasetCatalog.register('test',lambda d=d:get_image_list(d))
    MetadataCatalog.get('test').set(thing_classes=Train_Class_Name)

cfg=get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS=model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.PROPOSAL_GENERATOR.NAME='myRRPN'
cfg.MODEL.ANCHOR_GENERATOR.NAME='RotatedAnchorGenerator'
cfg.MODEL.ANCHOR_GENERATOR.ANGLES=[(-90,0,90)]
cfg.MODEL.ANCHOR_GENERATOR.SIZES=[[8,16,32,64,128]]
cfg.MODEL.RPN.BBOX_REG_WEIGHTS=(1.0,1.0,1.0,1.0,1.0)
cfg.MODEL.ROI_HEADS.NAME='myRROIHeads'
cfg.MODEL.ROI_HEADS.NUM_CLASS=len(Train_Class_Name)
cfg.MODEL.ROI_BOX_HEAD.POOLER_TYPE='ROIAlignRotated'
cfg.OUTPUT_DIR='/root/yaogan/result'
cfg.MODEL.ROI_BOX_HEAD.BBOX_REG_WEIGHTS=(10.0,10.0,5.0,5.0,5.0)
cfg.DATASETS.TRAIN=('test',)
cfg.DATALOADER.NUM_WORKERS=1
cfg.SOLVER.IMS_PER_BATCH=2
cfg.SOLVER.MAX_ITER=5000
cfg.SOLVER.CHECKPOINT_PERIOD=500
mapper=test_mapper(cfg)
dataloader=build_detection_train_loader(cfg,mapper)
model=build_model(cfg)
optimizer=build_optimizer(cfg,model)
scheduler=build_lr_scheduler(cfg,optimizer)
checkpointer=DetectionCheckpointer(model,cfg.OUTPUT_DIR,optimizer=optimizer,scheduler=scheduler)
start_iter = (
        checkpointer.resume_or_load(cfg.MODEL.WEIGHTS, resume=False).get("iteration", -1) + 1
)
max_iter = cfg.SOLVER.MAX_ITER
periodic_checkpointer=PeriodicCheckpointer(checkpointer,cfg.SOLVER.CHECKPOINT_PERIOD,max_iter=max_iter)
writers = (
    [
        CommonMetricPrinter(max_iter),
        JSONWriter(os.path.join(cfg.OUTPUT_DIR, "metrics.json")),
    ]

)
from tqdm import tqdm
with EventStorage(start_iter) as storage:

    with tqdm(total=max_iter) as pbar:
        for data,iteration in zip(dataloader,range(start_iter,max_iter)):
            if data[0]['instances'].get('gt_classes').shape[0] == 0:
                continue

            iteration = iteration + 1
            storage.step()

            loss_dict = model(data)
            losses = sum(loss_dict.values())
            optimizer.zero_grad()
            losses.backward()
            optimizer.step()

            scheduler.step()

            if iteration - start_iter > 5 and (iteration % 20 == 0 or iteration == max_iter):
                for writer in writers:
                    writer.write()
            periodic_checkpointer.step(iteration)
            torch.cuda.empty_cache()
            pbar.update(1)

```
In order to reduce memory and understand the data situation in the middle of the model, I customized the RRPN and ROI parts, but added print and del operation, I don't know whether it will affect, so I also sent the code here

RRPN
```
def my_pairwise_iou(boxes1: RotatedBoxes, boxes2: RotatedBoxes) -> None:
    print(boxes1.tensor.shape)
    print(boxes2.tensor.shape)
    return pairwise_iou_rotated(boxes1.tensor, boxes2.tensor)


class myRRPNOutputs(RPNOutputs):
    def __init__(
            self,
            box2box_transform,
            anchor_matcher,
            batch_size_per_image,
            positive_fraction,
            images,
            pred_objectness_logits,
            pred_anchor_deltas,
            anchors,
            boundary_threshold=0,
            gt_boxes=None,
            smooth_l1_beta=0.0,
    ):
        super(myRRPNOutputs, self).__init__(
            box2box_transform,
            anchor_matcher,
            batch_size_per_image,
            positive_fraction,
            images,
            pred_objectness_logits,
            pred_anchor_deltas,
            anchors,
            boundary_threshold,
            gt_boxes,
            smooth_l1_beta,
        )

    def _get_ground_truth(self):
        gt_objectness_logits = []
        gt_anchor_deltas = []
        anchors = [RotatedBoxes.cat(anchors_i) for anchors_i in self.anchors]
        for image_size_i, anchors_i, gt_boxes_i in zip(self.image_sizes, anchors, self.gt_boxes):
            #             print("gt_boxes{},anchors:{}".format(gt_boxes_i,anchors_i))
            match_quality_matrix = retry_if_cuda_oom(my_pairwise_iou)(gt_boxes_i, anchors_i)

            matched_idxs, gt_objectness_logits_i = retry_if_cuda_oom(self.anchor_matcher)(match_quality_matrix)
            gt_objectness_logits_i = gt_objectness_logits_i.to(device=gt_boxes_i.device)
            del match_quality_matrix
            if self.boundary_threshold >= 0:
                # Discard anchors that go out of the boundaries of the image
                # NOTE: This is legacy functionality that is turned off by default in Detectron2
                anchors_inside_image = anchors_i.inside_box(image_size_i, self.boundary_threshold)
                gt_objectness_logits_i[~anchors_inside_image] = -1

            if len(gt_boxes_i) == 0:
                # These values won't be used anyway since the anchor is labeled as background
                gt_anchor_deltas_i = torch.zeros_like(anchors_i.tensor)
            else:
                # TODO wasted computation for ignored boxes
                matched_gt_boxes = gt_boxes_i[matched_idxs]
                gt_anchor_deltas_i = self.box2box_transform.get_deltas(
                    anchors_i.tensor, matched_gt_boxes.tensor
                )

            gt_objectness_logits.append(gt_objectness_logits_i)
            gt_anchor_deltas.append(gt_anchor_deltas_i)
        del anchors
        return gt_objectness_logits, gt_anchor_deltas


@PROPOSAL_GENERATOR_REGISTRY.register()
class myRRPN(RPN):

    def __init__(self, cfg, input_shape: Dict[str, ShapeSpec]):
        super().__init__(cfg, input_shape)
        self.box2box_transform = Box2BoxTransformRotated(weights=cfg.MODEL.RPN.BBOX_REG_WEIGHTS)

    def forward(self, images, features, gt_instances=None):
        # same signature as RPN.forward
        gt_boxes = [x.gt_boxes for x in gt_instances] if gt_instances is not None else None
        del gt_instances
        features = [features[f] for f in self.in_features]
        pred_objectness_logits, pred_anchor_deltas = self.rpn_head(features)
        anchors = self.anchor_generator(features)
        outputs = myRRPNOutputs(
            self.box2box_transform,
            self.anchor_matcher,
            self.batch_size_per_image,
            self.positive_fraction,
            images,
            pred_objectness_logits,
            pred_anchor_deltas,
            anchors,
            self.boundary_threshold,
            gt_boxes,
            self.smooth_l1_beta,
        )

        if self.training:
            losses = outputs.losses()
        else:
            losses = {}

        with torch.no_grad():
            proposals = find_top_rrpn_proposals(
                outputs.predict_proposals(),
                outputs.predict_objectness_logits(),
                images,
                self.nms_thresh,
                self.pre_nms_topk[self.training],
                self.post_nms_topk[self.training],
                self.min_box_side_len,
                self.training,
            )

        return proposals, losses
```

RROI
```
@ROI_HEADS_REGISTRY.register()
class myRROIHeads(RROIHeads):
    def __init__(self, cfg, input_shape: Dict[str, ShapeSpec]):
        super().__init__(cfg, input_shape)
        assert (
                not self.mask_on and not self.keypoint_on
        ), "Mask/Keypoints not supported in Rotated ROIHeads."

    @torch.no_grad()
    def label_and_sample_proposals(self, proposals, targets):

        gt_boxes = [x.gt_boxes for x in targets]
        if self.proposal_append_gt:
            proposals = add_ground_truth_to_proposals(gt_boxes, proposals)

        proposals_with_gt = []

        num_fg_samples = []
        num_bg_samples = []
        for proposals_per_image, targets_per_image in zip(proposals, targets):
            has_gt = len(targets_per_image) > 0
            match_quality_matrix = structures.pairwise_iou_rotated(
                targets_per_image.gt_boxes, proposals_per_image.proposal_boxes
            )
            if torch.all(match_quality_matrix >= 0) == False:
                print(targets)
                print(proposals)
            matched_idxs, matched_labels = self.proposal_matcher(match_quality_matrix)
            sampled_idxs, gt_classes = self._sample_proposals(
                matched_idxs, matched_labels, targets_per_image.gt_classes
            )
            del match_quality_matrix
            proposals_per_image = proposals_per_image[sampled_idxs]
            proposals_per_image.gt_classes = gt_classes

            if has_gt:
                sampled_targets = matched_idxs[sampled_idxs]
                proposals_per_image.gt_boxes = targets_per_image.gt_boxes[sampled_targets]
            else:
                gt_boxes = RotatedBoxes(
                    targets_per_image.gt_boxes.tensor.new_zeros((len(sampled_idxs), 5))
                )
                proposals_per_image.gt_boxes = gt_boxes

            num_bg_samples.append((gt_classes == self.num_classes).sum().item())
            num_fg_samples.append(gt_classes.numel() - num_bg_samples[-1])
            proposals_with_gt.append(proposals_per_image)

        # Log the number of fg/bg samples that are selected for training ROI heads
        storage = get_event_storage()
        storage.put_scalar("roi_head/num_fg_samples", np.mean(num_fg_samples))
        storage.put_scalar("roi_head/num_bg_samples", np.mean(num_bg_samples))

        return proposals_with_gt

```

## Environment:

PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
Please provide the data that generates negative `match_quality_matrix`, i.e. the two sets of boxes, in a way other people can load and verify your issue.
You can do this by pickle.dump it to a file and provide a script to load it.

**Comment by sunshuofeng** [comment]
[test_proposals.txt](https://github.com/facebookresearch/detectron2/files/4508607/test_proposals.txt)
[test_target.txt](https://github.com/facebookresearch/detectron2/files/4508608/test_target.txt)

You can use this code to load the boxes:
```
with open('test_target.txt','rb') as f:
    gt=pickle.load(f)
with open('test_proposals.txt','rb') as f:
    proposal=pickle.load(f)

match_matrix=pairwise_iou_rotated(gt,proposal)
assert torch.all(match_matrix>=0)
```

Experiments with these two types of boxes do result in assertion errors

**Comment by ppwwyyxx** [comment]
From the values of your proposals:
```
RotatedBoxes(tensor([[ 2.0695e+21, -3.7575e+21,  5.6569e+03,  1.1314e+04,  6.8795e+05],
        [ 2.0695e+21, -3.7575e+21,  5.6569e+03,  1.1314e+04,  6.8795e+05],
        [ 2.0611e+21, -3.7422e+21,  5.6569e+03,  1.1314e+04,  4.5857e+05],
        ...,
        [ 4.5586e+02,  9.2896e+02,  7.9000e+01,  1.9000e+01,  7.6691e+01],
        [ 2.6594e+02,  1.0833e+03,  6.6000e+01,  6.5000e+01,  1.8691e+01],
        [ 6.4930e+02,  5.5198e+02,  4.3000e+01,  3.7000e+01, -8.4309e+01]],
       device='cuda:0'))
```
the training has already diverged, so a failure is expected. Although we should detect and provide better errors.

**Comment by sunshuofeng** [comment]
Does that mean that the training has reached the optimum, and then the training is stopped by this error

**Comment by sunshuofeng** [comment]
So how do I handle this error?

**Comment by alekseynp** [comment]
You could try
`detection_utils.filter_empty_instances(instance, box_threshold=1)`
Your problem might be caused by tiny boxes? I saw this once.

**Comment by alekseynp** [comment]
I think you're training on random data?
I think you're training on an impossible task.
I think the training procedure "diverges", i.e. "fails" because of this.

**Comment by sunshuofeng** [comment]
In my experiment, I found that centerx of target can be negative, just like that：

```
RotatedBoxes(tensor([[ -73.3552, 1082.3668,  126.0000,   45.0000,   84.8475],
        [-313.9308,  940.3795,   74.0000,   19.0000,   73.8233],
        [-110.2340,  669.8381,   80.0000,    9.0000,   66.2491],
        [ 107.7796,  613.6237,   76.0000,   34.0000,  -88.1046],
        [ -28.9388,  439.5316,   99.0000,    8.0000,  -69.3442],
        [ 164.6709,  383.9862,   54.0000,    8.0000,  -71.0216],
        [ 140.8216,  147.7930,   81.0000,    7.0000,  -83.3476]],
       device='cuda:0'))
```

I wonder if this is the reason for the error.



So I went further and looked up why centerx was negative, and I found that because I used two data transforms, one rotate and one hlip, in the rotate data transform, I found that the changed centerx was actually larger than the width of the image, which caused centerx to be negative in hlip

**Comment by sunshuofeng** [comment]
[test_data.txt](https://github.com/facebookresearch/detectron2/files/4513608/test_data.txt)
The one above is datadict for an image

you can use this code to load it :
```
with open("test_data.txt",'rb') as f:
     data=pickle.load(f)
```

Here is the code for the rotate transform，It's basically a copy of github's source code：
```
class RandomRotation(TransformGen):
 
    def __init__(self, angle, expand=True, center=None, sample_style="range", interp=None):

        super().__init__()
        assert sample_style in ["range", "choice"], sample_style
        self.is_range = sample_style == "range"
        if isinstance(angle, (float, int)):
            angle = (angle, angle)
        if center is not None and isinstance(center[0], (float, int)):
            center = (center, center)
        self._init(locals())

    def get_transform(self, img):
        h, w = img.shape[:2]
        center = None
        if self.is_range:
            angle = np.random.uniform(self.angle[0], self.angle[1])
            if self.center is not None:
                center = (
                    np.random.uniform(self.center[0][0], self.center[1][0]),
                    np.random.uniform(self.center[0][1], self.center[1][1]),
                )
        else:
            angle = np.random.choice(self.angle)
            if self.center is not None:
                center = np.random.choice(self.center)

        if center is not None:
            center = (w * center[0], h * center[1])  # Convert to absolute coordinates

        return RotationTransform(h, w, angle, expand=self.expand, center=center, interp=self.interp),angle

class RotationTransform(Transform):


    def __init__(self, h, w, angle, expand=True, center=None, interp=None):

        super().__init__()
        image_center = np.array((w / 2, h / 2))
        if center is None:
            center = image_center
        if interp is None:
            interp = cv2.INTER_LINEAR
        abs_cos, abs_sin = abs(np.cos(np.deg2rad(angle))), abs(np.sin(np.deg2rad(angle)))
        if expand:
            # find the new width and height bounds
            bound_w, bound_h = np.rint(
                [h * abs_sin + w * abs_cos, h * abs_cos + w * abs_sin]
            ).astype(int)
        else:
            bound_w, bound_h = w, h

        self._set_attributes(locals())
        self.rm_coords = self.create_rotation_matrix()
        # Needed because of this problem https://github.com/opencv/opencv/issues/11784
        self.rm_image = self.create_rotation_matrix(offset=-0.5)

    def apply_image(self, img, interp=None):
        """
        img should be a numpy array, formatted as Height * Width * Nchannels
        """
        if len(img) == 0:
            return img
        assert img.shape[:2] == (self.h, self.w)
        interp = interp if interp is not None else self.interp
        return cv2.warpAffine(img, self.rm_image, (self.bound_w, self.bound_h), flags=interp)

    def apply_coords(self, coords):
        """
        coords should be a N * 2 array-like, containing N couples of (x, y) points
        """
        if len(coords) == 0:
            return coords
        coords = np.asarray(coords, dtype=float)
        return cv2.transform(coords[:, np.newaxis, :], self.rm_coords)[:, 0, :]

    def apply_segmentation(self, segmentation):
        segmentation = self.apply_image(segmentation, interp=cv2.INTER_NEAREST)
        return segmentation

    def create_rotation_matrix(self, offset=0):
        center = (self.center[0] + offset, self.center[1] + offset)
        rm = cv2.getRotationMatrix2D(tuple(center), self.angle, 1)
        if self.expand:
            # Find the coordinates of the center of rotation in the new image
            # The only point for which we know the future coordinates is the center of the image
            rot_im_center = cv2.transform(self.image_center[None, None, :] + offset, rm)[0, 0, :]
            new_center = np.array([self.bound_w / 2, self.bound_h / 2]) + offset - rot_im_center
            # shift the rotation center to the new coordinates
            rm[:, 2] += new_center
        return rm


class Rotate_Rotation:
    def __init__(self):
        self.tfms_gen = RandomRotation([-45., 45.])

    def __call__(self, datadict,output):
        image = datadict['image']
        tfms, angle = self.tfms_gen.get_transform(image)
        image = tfms.apply_image(image)
        datadict['image'] = image
        for anno in datadict['annotations']:
            box = (anno['bbox'])
            centeryx = np.array([(box[0], box[1])])
            new_centeryx = tfms.apply_coords(centeryx)
            new_angle = self.get_new_angle(box[-1], angle)
            box[0] = new_centeryx[0][0]
            box[1] = new_centeryx[0][1]
            box[-1] = new_angle
            if output:
                print("new_centerx:{}".format(box[0]))
            anno['bbox'] = box

    def get_new_angle(self, angle, rotate_angle):
        new_angle = angle + rotate_angle
        if new_angle > 90:
            new_angle = -(180 - new_angle)
        elif new_angle < -90:
            new_angle = -90 - (new_angle)

        return new_angle
```
The hlip code is also provided：


```
class Hlip_Rotation:
    def __init__(self):
        pass

    def __call__(self, datadict,output):
        image = datadict['image']
        w = datadict['width']
        new_image = A.HorizontalFlip(p=1)(image=image)['image']
        datadict['image'] = new_image
#         if a==True:
#             print("hlip,anno:{}".format(datadict['annotations']))
        for anno in datadict['annotations']:
            box = anno['bbox']
            new_box = self.hlip_box(w, box,output)
            anno['bbox'] = new_box

    def hlip_box(self, w, box,output):
        if a==True:
           print("w:{}.box:{}".format(w,box))
        box[0] = w - box[0]
        box[4] = -box[4]
        return box


def get_transform_list(min_angle=-45, max_angle=45):
    transorm_list = []
    rotate = Rotate_Rotation()
    hlip = Hlip_Rotation()
#     contrast = Contrast()
    transorm_list.append(rotate)
    transorm_list.append(hlip)
#     transorm_list.append(contrast)
    return transorm_list
    
```
DataMapper
```
class myDatasetMapper:
    def __init__(self,cfg,is_train=True):
        self.img_format = cfg.INPUT.FORMAT
        self.is_train=is_train
        self.tfms=get_transform_list()

    def __call__(self,dataset_dict):
        dataset_dict=copy.deepcopy(dataset_dict)
        image=detection_utils.read_image(dataset_dict['file_name'],format=self.img_format)
        detection_utils.check_image_size(dataset_dict,image)
        dataset_dict['image']=image
        image_shape=image.shape[:2]
        output=False
        if dataset_dict['file_name']=='/kaggle/input/resize-dota/images/P0521.png':
            file1=open('test_data.txt','wb+')
            pickle.dump(dataset_dict,file1)
            file1.close()
            print(dataset_dict)
            output=True
          

        if not self.is_train:
            dataset_dict.pop('annotations',None)
        for tfm in self.tfms:
            tfm(dataset_dict,output)
        dataset_dict["image"] = torch.as_tensor(np.ascontiguousarray(image.transpose(2, 0, 1)))
        anno=dataset_dict['annotations']
        dataset_dict.pop('annotations')
      
            
        instance=detection_utils.annotations_to_instances_rotated(anno,image_shape)
        
        dataset_dict['instances']=detection_utils.filter_empty_instances(instance)
        early_stop=False
        if dataset_dict['file_name']=='/kaggle/input/resize-dota/images/P0521.png':
            
            print(dataset_dict)
            early_stop=True

            
        return dataset_dict,early_stop
```
You can use this code to test:
```
cfg=get_cfg()
mapper=myDatasetMapper(cfg)
mapper(data)
```
Because of the uncertainty of rotate, a few more attempts should result in a negative centerx situation

I don't know if this situation is reasonable, how should I modify it
