### ISSUE TITLE
incompatible.missing_keys.remove(k). AttributeError: 'NoneType' object has no attribute 'missing_keys'

### ISSUE THREAD

**Issue by albertchristianto** [facebookresearch/detectron2#1267]
## Instructions To Reproduce the Issue:

1. Try to install detectron2 at 21 April 2020 1:25PM (GMT+8). I try to run simple demo code using this command below
```
python3.7 demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --input input1.jpg input2.jpg --opts MODEL.WEIGHTS /media/ion/ioNdrive/detectron2/weights/model_final_a54504.pkl
```
2. and I get this error
```
[04/21 13:12:35 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', input=['input1.jpg', 'input2.jpg'], opts=['MODEL.WEIGHTS', '/media/ion/ioNdrive/detectron2/weights/model_final_a54504.pkl'], output=None, video_input=None, webcam=False)
[04/21 13:12:38 fvcore.common.checkpoint]: Loading checkpoint from /media/ion/ioNdrive/detectron2/weights/model_final_a54504.pkl
[04/21 13:12:38 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
[04/21 13:12:38 fvcore.common.checkpoint]: Some model parameters are not in the checkpoint:
  pixel_std
  pixel_mean
Traceback (most recent call last):
  File "demo.py", line 79, in <module>
    demo = VisualizationDemo(cfg)
  File "/media/ion/ioNdrive/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/media/ion/ioNdrive/detectron2/detectron2/engine/defaults.py", line 185, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/ion/.local/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 104, in load
    self._load_model(checkpoint)
  File "/media/ion/ioNdrive/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 68, in _load_model
    incompatible.missing_keys.remove(k)
AttributeError: 'NoneType' object has no attribute 'missing_keys'
```
3. I am managed to solve it by comment some code at line 59-71 in THE_REPO/detectron2/checkpoint/detection_checkpoint.py. and add this code
```
super()._load_model(checkpoint)
```
4. So, here is the question. Is it okay? or How to solve this problem properly?

Thank you very much.

best regards,
Albert Christianto

**Comment by ppwwyyxx** [comment]
You need the latest version of fvcore.

**Comment by albertchristianto** [comment]
hi, @ppwwyyxx. 
thanks for the fast response. 

what is the latest version of fvcore?

my fvcore version is '0.1.dev200420'. I followed the detectron2 readme installation, so it didn't install the latest version?
thank you very much.

best regards,
Albert Christianto

**Comment by ppwwyyxx** [comment]
You actually need latest version from github: https://github.com/facebookresearch/fvcore#3-install-from-github
It seems the latest package hasn't been uploaded yet

**Comment by albertchristianto** [comment]
Hi @ppwwyyxx 
yes, you are right the latest version of fvcore hasn't been uploaded yet. 
I have installed the latest version of fvcore from github and it works very well.
thank you very much for your tips and hospitality.
best regards,
Albert Christianto

**Comment by ppwwyyxx** [comment]
update: the latest master of detectron2 (95b0b5d2f52dcd2ec98cd89f0bf7f0563d436e49) should work with older version of fvcore (at the cost of extra warnings)
