### ISSUE TITLE
How to converting a detectron2 model to Caffe2 format on GPU

### ISSUE THREAD

**Issue by limengfei3675** [facebookresearch/detectron2#1271]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
I have not do any change.
```
2. what exact command you run:

./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --output ./caffe2_model --run-eval MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl MODEL.DEVICE cuda

3. what you observed (including __full logs__):
```
Traceback (most recent call last):
  File "./caffe2_converter.py", line 52, in <module>
    caffe2_model = export_caffe2_model(cfg, torch_model, first_batch)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/api.py", line 57, in export_caffe2_model
    predict_net, init_net = export_caffe2_detection_model(c2_compatible_model, c2_format_input)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/caffe2_modeling.py", line 268, in forward
    proposals, _ = self._wrapped_model.proposal_generator(images, features)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py", line 223, in forward
    input_list = [to_device(x, "cpu") for x in (rpn_rois_list + rpn_roi_probs_list)]
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/c10.py", line 223, in <listcomp>
    input_list = [to_device(x, "cpu") for x in (rpn_rois_list + rpn_roi_probs_list)]
  File "/home/along/lmf_workspace/detectron2/detectron2/detectron2/export/shared.py", line 37, in to_device
    return torch.ops._caffe2.CopyGPUToCPU(t)
  File "/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator _caffe2::CopyGPUToCPU

```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

I noticed that "It has a runtime optimized for CPU & mobile inference, but not for GPU inference." so I want to konw how to converting a detectron2 model to Caffe2 format on GPU.

## Environment:

Provide your environment information using the following command:
```
------------------------  -----------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
numpy                     1.18.3
detectron2                0.1.1 @/home/along/lmf_workspace/detectron2/detectron2/detectron2
detectron2 compiler       GCC 7.5
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce RTX 2080 Ti
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
torchvision               0.5.0 @/home/along/anaconda3/envs/lmf/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  -----------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[Thread 0x7ffff7fcf740 (LWP 9810) exited]
[Inferior 1 (process 9810) exited normally]
No stack.
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/deployment.html#usage already about GPU conversion.
