### ISSUE TITLE
Unit test is broken currently

### ISSUE THREAD

**Issue by xkszltl** [facebookresearch/detectron2#1278]
Seems from recent changes.
Not urgent, just for awareness.

cpu_tests
```
./tests/data/test_detection_utils.py:7:1: F401 'torch' imported but unused
```

gpu_tests
```
======================================================================
ERROR: testMaskRCNN (test_export_caffe2.TestCaffe2Export)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/detectron2/tests/test_export_caffe2.py", line 61, in testMaskRCNN
    self._test_model("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/detectron2/tests/test_export_caffe2.py", line 28, in _test_model
    from detectron2.export import Caffe2Model, add_export_config, export_caffe2_model
  File "/detectron2/detectron2/export/__init__.py", line 3, in <module>
    from .api import *
  File "/detectron2/detectron2/export/api.py", line 10, in <module>
    from .caffe2_export import export_caffe2_detection_model
  File "/detectron2/detectron2/export/caffe2_export.py", line 8, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

You can find it in CI of this PR: https://github.com/facebookresearch/detectron2/pull/1223

**Comment by ppwwyyxx** [comment]
both are fixed in master already
