### ISSUE TITLE
program stucked when training on multi-gpus

### ISSUE THREAD

**Issue by Anikily** [facebookresearch/detectron2#1286]
when my code running to:
[04/24 01:01:49 detectron2]: Starting training from iteration 0
my program don't show any other things.

And after control+c, it shows:
CTraceback (most recent call last):
  File "plain_train_net.py", line 233, in <module>
    args=(args,),
  File "/ssd1/yulu/PS/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/yulu/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/yulu/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 77, in join
    timeout=timeout,
  File "/home/yulu/anaconda3/envs/detectron2/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/yulu/anaconda3/envs/detectron2/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt

when i run this code on a single gpu, it won't happen, how could solve this problem?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
