### ISSUE TITLE
TensorFlow code destroy everything (bugs related to tensorboard)

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detectron2#134]
When training a very simple own dataset, got error:

```
Config '../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (4, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (4,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (12, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (12,) in the model! Skipped.
'roi_heads.mask_head.predictor.weight' has shape (80, 256, 1, 1) in the checkpoint but (3, 256, 1, 1) in the model! Skipped.
'roi_heads.mask_head.predictor.bias' has shape (80,) in the checkpoint but (3,) in the model! Skipped.
Exception ignored in: <bound method TensorboardXWriter.__del__ of <detectron2.utils.events.TensorboardXWriter object at 0x7f78829160b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/utils/events.py", line 118, in __del__
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/writer.py", line 988, in close
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/writer.py", line 133, in flush
  File "/usr/local/lib/python3.6/dist-packages/tensorboard-2.0.0-py3.6.egg/tensorboard/summary/writer/event_file_writer.py", line 106, in flush
  File "/usr/local/lib/python3.6/dist-packages/tensorboard-2.0.0-py3.6.egg/tensorboard/summary/writer/event_file_writer.py", line 156, in flush
  File "/usr/local/lib/python3.6/dist-packages/tensorboard-2.0.0-py3.6.egg/tensorboard/summary/writer/record_writer.py", line 42, in flush
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 230, in flush
AttributeError: 'NoneType' object has no attribute 'raise_exception_on_not_ok_status'

```

Here is the training code:

```
import random
from detectron2.utils.visualizer import Visualizer
from detectron2.data.catalog import MetadataCatalog, DatasetCatalog
import fruitsnuts_data
import cv2
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os


if __name__ == "__main__":
    cfg = get_cfg()
    cfg.merge_from_file(
        "../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    )
    cfg.DATASETS.TRAIN = ("fruits_nuts",)
    cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.0025
    cfg.SOLVER.MAX_ITER = (300)  # 300 iterations seems good enough, but you can certainly train longer
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (128)  # faster, and good enough for this toy dataset
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
```

I am training on single GPU ...

What's the error could be?

**Comment by ppwwyyxx** [comment]
Upgrade to latest detectron2.

**Comment by jinfagang** [comment]
I just pulled the master code.....

**Comment by ppwwyyxx** [comment]
>   File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/utils/events.py", line 118, in __del__


In the master code, line 118 in this file is not `__del__`, so you're not using master code.

**Comment by jinfagang** [comment]
Sorry, let me check, I pulled and rerun `sudo pip3 install .` seems not effect.

**Comment by jinfagang** [comment]
Upgrade to master solves issue. May I ask how to set print interval inside cfg???

```
cfg = get_cfg()
    cfg.merge_from_file(
        "../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    )
    cfg.DATASETS.TRAIN = ("fruits_nuts",)
    cfg.DATASETS.TEST = ()  # no metrics implemented for this dataset
    cfg.DATALOADER.NUM_WORKERS = 2
    # cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
    cfg.MODEL.WEIGHTS = "./output/model_final.pth"  # initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.0025
    cfg.SOLVER.MAX_ITER = (2500)  # 300 iterations seems good enough, but you can certainly train longer
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = (128)  # faster, and good enough for this toy dataset
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
```

**Comment by ppwwyyxx** [comment]
Closing as the original issue is solved.
Follow up question was answered in #144
