### ISSUE TITLE
Getting "AssertionError: GroupNorm does not support empty inputs in PyTorch <=1.4!", while training ResNxt152 Mask RCNN Model

### ISSUE THREAD

**Issue by Swaroop11** [facebookresearch/detectron2#1395]
Hello All,
              I am training the ResNxt-152 Mask RCNN model, on the custom dataset. All the configurations are default. Training on 16 GPUs instance, with a small dataset of 4K images
    
cfg = get_cfg()    cfg.merge_from_file(model_zoo.get_config_file("Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml"))
cfg.DATASETS.TRAIN = ("exp_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml")
cfg.SOLVER.IMS_PER_BATCH = 16  
cfg.SOLVER.MAX_ITER = 10000  #Default for experiment is 5000
cfg.SOLVER.CHECKPOINT_PERIOD = 500
cfg.SOLVER.STEPS = [1000, 2000, 3000, 4000, 4500]
cfg.SOLVER.LRS = [0.02, 0.002, 0.0002, 0.00002, 0.000002]
cfg.SOLVER.WARMUP_ITERS = 200
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE =  1024
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2     

After completing 59 steps it is throwing error:
/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
  File "train_detectron_JLRdummy.py", line 144, in <module>
    launch(main, num_gpus_per_machine = 16, dist_url="auto")
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/engine/launch.py", line 54, in launch
    daemon=False,
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 11 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/engine/launch.py", line 89, in _distributed_worker
    main_func(*args)
  File "/home/ubuntu/jlrDamages/detectron2/train_detectron_JLRdummy.py", line 138, in main
    trainer.train()
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/engine/defaults.py", line 401, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/modeling/roi_heads/cascade_rcnn.py", line 97, in forward
    losses.update(self._forward_mask(features, proposals))
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 693, in _forward_mask
    return self.mask_head(mask_features, proposals)
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/modeling/roi_heads/mask_head.py", line 180, in forward
    x = self.layers(x)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/modeling/roi_heads/mask_head.py", line 267, in layers
    x = layer(x)
  File "/home/ubuntu/anaconda3/envs/jlrDamages/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/jlrDamages/detectron2/detectron2/layers/wrappers.py", line 72, in forward
    ), "GroupNorm does not support empty inputs in PyTorch <=1.4!"
AssertionError: GroupNorm does not support empty inputs in PyTorch <=1.4!

Can anyone help me with this issue?

Thanks and  Regards

**Comment by ppwwyyxx** [comment]
As the error says, `GroupNorm does not support empty inputs in PyTorch <=1.4`.

**Comment by Swaroop11** [comment]
Yes, I understood what is the meaning of this error. But my doubt is when I trained ResNet50 and ResNxt101 both with the same data, I haven't encountered this error. Can you help me with a possible solution for this error? 

Do I need to update my PyTorch version?? 

or I need to make any configuration change ??

Thanks and Regards

**Comment by ppwwyyxx** [comment]
You'll not have this error in pytorch 1.5
