### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by naturino** [facebookresearch/detectron2#1406]
**I have a problem when testing with demo:**

python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --input input.jpg  [--other-options]

**But it's showing that:**

Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/ubuntu/Adam/code/detectron2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/engine/defaults.py", line 218, in __call__
    predictions = self.model([inputs])[0]
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 170, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 595, in forward
    pred_instances = self._forward_box(features, proposals)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 648, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/modeling/poolers.py", line 229, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Adam/code/detectron2/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/ubuntu/Adam/code/detectron2/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: Not compiled with GPU support

**This is my environment：python -m detectron2.utils.collect_env**
----------------------
sys.platform              linux
Python                    3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.2 @/home/ubuntu/Adam/code/detectron2/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  not available
detectron2 arch flags     /home/ubuntu/Adam/code/detectron2/detectron2/_C.cpython-37m-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.0 @/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1                   GeForce RTX 2080
CUDA_HOME                 /usr/local/cuda-10.1/
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.1.2
torchvision               0.6.0a0+82fd1c8 @/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                    0.1.dev200506
cv2                       4.2.0
------------------------  ---------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

Please tell me how to do?

**Comment by ppwwyyxx** [comment]
answered in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
