### ISSUE TITLE
Multi-gpus Training Error

### ISSUE THREAD

**Issue by YiwuZhong** [facebookresearch/detectron2#1410]
I failed to train the default PointRend model on my custom dataset by setting `--num-gpus` to larger than 1. If it's set to 1, the training is totally fine. If I trained the model on COCO dataset, multi-GPUs training is also ok to run. 

The error details are as follow:
```
Command Line Args: Namespace(config_file='configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "train_net.py", line 244, in <module>
    launch(
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 50, in launch
    mp.spawn(
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function main at 0x7fa238dbb670>: attribute lookup main on __main__ failed
```
Appreciated if anyone can help with this multi-gpus training error!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by YiwuZhong** [comment]
Overview: I failed to train the default PointRend model on my custom dataset by setting `--num-gpus` to larger than 1. If `--num-gpus` is set to 1, the training is totally fine. If I trained the model on COCO dataset, multi-GPUs training is also ok to run.

1. what changes you made (`git diff`) or what code you wrote
I installed the newest Detectron2 and do the following: registered my custom dataset by `register_coco_instances()` in the file **train_net.py** at PointRend folder and trained the default PointRend model on the custom dataset.

2. what exact command you run:
run `python train_net.py \
--config-file configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml \
--num-gpus 2` at the PointRend folder.

3. what you observed (including __full logs__):
```
Command Line Args: Namespace(config_file='configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "train_net.py", line 244, in <module>
    launch(
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 50, in launch
    mp.spawn(
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/user/.conda/envs/det2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function main at 0x7fa238dbb670>: attribute lookup main on __main__ failed
```

## Expected behavior:
Since it's okay to train the default PointRend model on COCO dataset with `--num-gpus` larger than 1 and on the custom dataset with ``--num-gpus`` as 1, it should be fine to train the model on custom dataset with `--num-gpus` larger than 1. 

## Environment:
```
sys.platform              linux
Python                    3.8.2 (default, May  7 2020, 20:00:49) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.2 @/home/user/.conda/envs/det2/lib/python3.8/site-packages/detectron2
detectron2 compiler       GCC 5.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.0 @/home/user/.conda/envs/det2/lib/python3.8/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1                   TITAN Xp
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.1.2
torchvision               0.6.0a0+82fd1c8 @/home/user/.conda/envs/det2/lib/python3.8/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                    0.1.dev200506
cv2                       4.2.0
------------------------  ------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF
```

If you need further information, please let me know. Thanks!

Best regards,
Yiwu

**Comment by ppwwyyxx** [comment]
Since it happens only after adding your custom dataset, we'll need to know exactly how you added the custom dataset.

**Comment by YiwuZhong** [comment]
Thanks for your suggestion. The following is the only thing I changed in **train_net.py** at PointRend folder. 
```
+from detectron2.data.datasets.coco import load_coco_json
+import ipdb
 
 class Trainer(DefaultTrainer):
     """
@@ -96,13 +99,44 @@
     add_pointrend_config(cfg)
     cfg.merge_from_file(args.config_file)
     cfg.merge_from_list(args.opts)
-    cfg.freeze()
-    default_setup(cfg, args)
+    ################## Custom Dataset ##################
+    cfg.DATASETS.TRAIN = ("My_dataset_Train",)
+    cfg.DATASETS.TEST = ("My_dataset_Test",)
+    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 23 
+    cfg.MODEL.POINT_HEAD.NUM_CLASSES = 23 
+    cfg.SOLVER.IMS_PER_BATCH = 2
+    cfg.TEST.EVAL_PERIOD = cfg.SOLVER.CHECKPOINT_PERIOD  
+    cfg.VIS_PERIOD = 800
+    ################## Custom Dataset ##################
+    #cfg.freeze()
+    #default_setup(cfg, args)
     return cfg
 
 
 def main(args):
     cfg = setup(args)
+
+    ################## Custom Dataset ##################
+    root_path = "/home/user/Desktop/Cataract-Project/detectron2_repo/projects/PointRend/"
+    output_path = cfg.OUTPUT_DIR
+    # register custom dataset
+    from detectron2.data.datasets import register_coco_instances
+    register_coco_instances("My_dataset_Train", {}, \
+        output_path + "/data/My_Train.json", \
+        root_path + "datasets/My/Train/Images")
+    if args.eval_only: # test set
+        register_coco_instances("My_dataset_Test", {}, \
+            output_path + "/data/My_Test.json", \
+            root_path + "datasets/My/Test/Images")
+    else:  # validation set
+        register_coco_instances("My_dataset_Test", {}, \
+            output_path + "/data/My_Val.json", \
+            root_path + "datasets/My/Val/Images")
+    ################## Custom Dataset ##################    
 
     if args.eval_only:
         model = Trainer.build_model(cfg)
@@ -114,10 +148,15 @@
             verify_results(cfg, res)
         return res
 
+    ################## Custom Dataset ##################
+    cfg.MODEL.WEIGHTS = './model_final_3c3198.pkl'
+    cfg.freeze()
+    default_setup(cfg, args)
+    ################## Custom Dataset ##################
     trainer = Trainer(cfg)
     trainer.resume_or_load(resume=args.resume)
     return trainer.train()
 
 if __name__ == "__main__":
     args = default_argument_parser().parse_args()
```

**Comment by ppwwyyxx** [comment]
See https://github.com/gotcha/ipdb/issues/194. It's better to post __full changes__ and __full logs__ next time.

**Comment by YiwuZhong** [comment]
Thank you so much!
