### ISSUE TITLE
problems in training: image file is truncated?

### ISSUE THREAD

**Issue by sophia-hxw** [facebookresearch/detectron2#143]
It can work well in the beginning, and then broke down after a while.

My training order is:
python tools/train_net.py --resume --num-gpus 8 --config-file output/config.yaml SOLVER.IMS_PER_BATCH 8 SOLVER.BASE_LR 0.0025 MODEL.WEIGHTS output/model_0009999.pth

The error information is:
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/hxw/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/hxw/detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/hxw/detectron2/tools/train_net.py", line 149, in main
    return trainer.train()
  File "/home/hxw/detectron2/detectron2/engine/defaults.py", line 330, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/hxw/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/hxw/detectron2/detectron2/engine/train_loop.py", line 206, in run_step
    data = next(self._data_loader_iter)
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hxw/detectron2/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/hxw/detectron2/detectron2/data/dataset_mapper.py", line 72, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/home/hxw/detectron2/detectron2/data/detection_utils.py", line 53, in read_image
    image = image.convert(conversion_format)
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/PIL/Image.py", line 930, in convert
    self.load()
  File "/home/hxw/anaconda3/envs/xinwen/lib/python3.6/site-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (7 bytes not processed)

**Comment by ppwwyyxx** [comment]
As it says, your image file is broken and PIL cannot read it. Please make sure your image can be read by PIL.

**Comment by zylo117** [comment]
This framework is too fragile, no one can make sure all those tens of thousands of images are clean and intact.
Why can't it handle image corruption and skip to the next one?

**Comment by ppwwyyxx** [comment]
You can with a custom dataloader: https://detectron2.readthedocs.io/tutorials/data_loading.html

**Comment by zylo117** [comment]
I switched PIL to opencv, and no more oserror. 
PIL is not as fast and not as stable as opencv.
What are the things that PIL can do but opencv can't?
Considering this framework use them both, why not just kick PIL out of the game?

But still, the framework itself should take care of minor exceptions anyway.

**Comment by ppwwyyxx** [comment]
OpenCV historically can cause many crashes in forked processes in certain environment. We will evaluate whether to switch to it. Detectron2 does not require opencv currently - it is only an optional dependency.

Given that there is no standard way to handle data reading failure, I think we should not handle such failure by default to avoid surprise. It may make sense to provide tools that help handle them, though.

**Comment by briantse100** [comment]
I have the same error, and have solved by this. [OSError: image file is truncated (28 bytes not processed) during learning](https://discuss.pytorch.org/t/oserror-image-file-is-truncated-28-bytes-not-processed-during-learning/36815/21)
