### ISSUE TITLE
Inference with multi-GPU by Dataparallel

### ISSUE THREAD

**Issue by IFICL** [facebookresearch/detectron2#1438]
I have a batch of images, and I want to inference the batch by loading the pre-trained model.
But it seems only the model will only use one GPU: 'cuda:0'

```
model = build_model(cfg).to(device)
model = nn.DataParallel(model, device_ids=gpu_ids)
model.eval()
img_list = [{'image': img_tensor}, {
        'image': img_tensor}, {'image': img_tensor}, {'image': img_tensor}]
outputs = model(img_list)
```
 I can do the operation above, but the batched input is `list[dict]`, and it got error when I use multi-GPU. 
```
Traceback (most recent call last):
  File "detector.py", line 71, in <module>
    detect(DEVICE)
  File "detector.py", line 64, in detect
    outputs = model(img_list)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 160, in inference
    images = self.preprocess_image(batched_inputs)
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 185, in preprocess_image
    images = [(x - self.pixel_mean) / self.pixel_std for x in images]
  File "xxxxxxx/anaconda3/envs/torch/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 185, in <listcomp>
    images = [(x - self.pixel_mean) / self.pixel_std for x in images]
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0
```
I hope I can use several GPUs to accelerate inference by using data-parallel from PyTorch. 
Is detectron2 API supports this behavior? How can I achieve this?
Or I guess it that nn.DataParallel is not working for list input?

**Comment by ppwwyyxx** [comment]
Our models do not work with `nn.DataParallel`.

**Comment by mailvijayasingh** [comment]
Is there any other way to support inference on multiple GPUs?
