### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by marload** [facebookresearch/detectron2#1474]
If you do not know the root cause of the problem, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

I'm learning custom dataset using RetinaNet. However, the error below occurs.

1. what changes you made (`git diff`) or what code you wrote
```
<put diff or code here>
```
2. what exact command you run:
3. what you observed (including __full logs__):
```
[05/25 15:54:12 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
  fc1000_b
  fc1000_w
  conv1_b
[05/25 15:54:12 d2.engine.train_loop]: Starting training from iteration 0
ERROR [05/25 15:54:13 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 188, in forward
    gt_classes, gt_anchors_reg_deltas = self.get_ground_truth(anchors, gt_instances)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 294, in get_ground_truth
    for targets_per_image in targets:
TypeError: 'NoneType' object is not iterable
[05/25 15:54:13 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    trainer.train()
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 402, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 188, in forward
    gt_classes, gt_anchors_reg_deltas = self.get_ground_truth(anchors, gt_instances)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/testforte-gpu-2/anaconda3/envs/detectron/lib/python3.7/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 294, in get_ground_truth
    for targets_per_image in targets:
TypeError: 'NoneType' object is not iterable
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
No annotations are included in the dataset: https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
