### ISSUE TITLE
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by IsaacPatole** [facebookresearch/detectron2#1497]
I am trying to evaluate a model using the following script, in a new file.

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output2/'

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")

trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=True)

from detectron2.evaluation import sem_seg_evaluation, COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("train_500", cfg, False, output_dir=cfg.OUTPUT_DIR)
val_loader = build_detection_test_loader(cfg, "train_500")
inference_on_dataset(trainer.model, val_loader, evaluator)

I changes a coco file from, if type(resFile) == str or type(resFile) == unicode to if type(resFile) == str or type(resFile) == bytes as per #708 
 but getting the following error in numpy:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "ksh_train_val_data_mrcnn.py", line 113, in <module>
    inference_on_dataset(trainer.model, val_loader, evaluator)
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/evaluation/evaluator.py", line 176, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/evaluation/coco_evaluation.py", line 143, in evaluate
    self._eval_predictions(set(self._tasks), predictions)
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/evaluation/coco_evaluation.py", line 186, in _eval_predictions
    if len(coco_results) > 0
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/evaluation/coco_evaluation.py", line 494, in _evaluate_predictions_on_coco
    coco_eval = COCOeval(coco_gt, coco_dt, iou_type)
  File "/home/ubuntu/Documents/CMR_proj/tensorflow/models/research/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/ubuntu/Documents/CMR_proj/tensorflow/models/research/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/ubuntu/Documents/CMR_proj/tensorflow/models/research/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by IsaacPatole** [comment]
Solved it by changing numpy to 1.17 instead of 1.18 as per #580
