### ISSUE TITLE
Error while Running inference on CPU:

### ISSUE THREAD

**Issue by pratiksparwatwar** [facebookresearch/detectron2#1557]
## Error while Running inference on CPU:

1. This is my inference code. I have trained the model on AWS server (having gpu) and now I want to run the inference on cpu sytem. 
- I have detectron2 cpu version installed on my system
- Also pytorch cpu version is installed
```
<
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import matplotlib.pyplot as plt
import numpy as np
import cv2

from IPython.display import display
from PIL import Image

# import some common detectron2 utilities
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
import os

images_folder ='/home/user/Documents/maskrcnn/test_data/test/'
detected_folder = '/home/user/Documents/maskrcnn/test_data/detected/'

from detectron2.data.datasets import register_coco_instances
register_coco_instances("dataset", {}, "/home/user/Documents/maskrcnn/dataset.json", "/home/user/Documents/maskrcnn/data/")

dataset_metadata = MetadataCatalog.get("dataset")
dataset_dicts = DatasetCatalog.get("dataset")
print("----------", dataset_metadata.get("thing_classes"))

cfg = get_cfg()

cfg.merge_from_file("/home/user/Documents/maskrcnn/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 20

cfg.OUTPUT_DIR = '/home/user/Documents/maskrcnn/model/'
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.70   # set the testing threshold for this model

cfg.DATASETS.TEST = ("dataset")

#cfg.MODEL.DEVICE='cpu'

predictor = DefaultPredictor(cfg)


from detectron2.utils.visualizer import ColorMode
import cv2
import time

imgs=os.listdir(images_folder)
imgs.sort()
count = 0
start_globle = time.time()


for filepath in imgs:
    start = time.time()
    im = cv2.imread(images_folder+filepath)
    outputs = predictor(im)

    # add this to get black and white image except the segmentation: instance_mode=ColorMode.IMAGE_BW    
    v = Visualizer(im[:, :, ::-1],metadata=dataset_metadata, scale=0.8) 

    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    print("Inference time: ", time.time() - start)    
    cv2.imwrite(detected_folder+filepath, v.get_image()[:, :, ::-1])
    print("detected")
    
print("total time: ", time.time()-start_globle)>
```
2. I ran the command as :  python inference.py
3. The following are the logs of error :
```
<Traceback (most recent call last):
  File "inference.py", line 17, in <module>
    from detectron2.engine import DefaultPredictor
  File "/home/user/Documents/maskrcnn/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/home/user/Documents/maskrcnn/detectron2/engine/hooks.py", line 18, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/home/user/Documents/maskrcnn/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/home/user/Documents/maskrcnn/detectron2/evaluation/cityscapes_evaluation.py", line 12, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/user/Documents/maskrcnn/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/user/Documents/maskrcnn/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/user/Documents/maskrcnn/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/user/Documents/maskrcnn/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/home/user/Documents/maskrcnn/detectron2/layers/__init__.py", line 6, in <module>
    from .roi_align import ROIAlign, roi_align
  File "/home/user/Documents/maskrcnn/detectron2/layers/roi_align.py", line 7, in <module>
    from detectron2 import _C
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory>
```

## Environment:

Provide your environment information using the following command:
```
sys.platform           linux
Python                 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
numpy                  1.18.2
detectron2             0.1.2 @/home/user/Documents/maskrcnn/detectron2
detectron2._C          failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.5.0+cpu @/home/user/.virtualenvs/tf1/lib/python3.6/site-packages/torch
PyTorch debug build    False
CUDA available         False
Pillow                 6.2.2
torchvision            0.6.0+cpu @/home/user/.virtualenvs/tf1/lib/python3.6/site-packages/torchvision
fvcore                 0.1.1.post20200606
cv2                    4.2.0
---------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by pratiksparwatwar** [comment]
Okay. I've found the solution. After installing the Detectron2 cpu version. The detectron2 folder is to be removed from the directory from where we are running the code.

**Comment by guotong1988** [comment]
Thank you.

**Comment by guotong1988** [comment]
How to install the cpu versoin?

**Comment by pratiksparwatwar** [comment]
> How to install the cpu versoin?

1. installing torch and torchvision

pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

2. installing detectron2 cpu version for torch 1.5

python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.5/index.html
