### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by lzh420202** [facebookresearch/detectron2#1587]
I follow the official guide to train a model, however, when the number of iterations reaches 4973, the program will throw this exception, and then the retraining will throw this exception directly, 
How can I solve this problem?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/catalog.py", line 55, in get
    f = DatasetCatalog._REGISTERED[name]
KeyError: 's'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/workspace/code/detectron2_test/train.py", line 34, in <module>
    trainer = DefaultTrainer(cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 253, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 430, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py", line 297, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/catalog.py", line 59, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 's' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, airport_train, airport_test"

```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
