### ISSUE TITLE
Test inference for mask_rcnn_R_50_FPN problem

### ISSUE THREAD

**Issue by shidi518** [facebookresearch/detectron2#159]
Hi,
Very thank you for your project!

I am currently doing the instance segmentation of video based on detectron2's maskrcnn framework. But I found that running on my machine was slow. I have tested 

> mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl 

> mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl. 

The average processing speed of the two is only **1.75it/s** and **1.65it/s** respectively. This is much slower than the inference time shows in [MODEL_ZOO.]

So I test the reference time as you mentioned in [#106 ].(https://github.com/facebookresearch/detectron2/issues/106)

I run:
`python tools/train_net.py --num-gpus 1 --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --eval-only MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl_`

However, I encountered this mistake :
```
[10/24 11:46:02 fvcore.common.checkpoint]: Loading checkpoint from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[10/24 11:46:02 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached in /home/zbw/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[10/24 11:46:03 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 132, in main
    res = Trainer.test(cfg, model)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/engine/defaults.py", line 404, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/engine/defaults.py", line 371, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/build.py", line 387, in build_detection_test_loader
    else None,
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/build.py", line 256, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/build.py", line 256, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/datasets/register_coco.py", line 32, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/datasets/coco.py", line 54, in load_coco_json
    coco_api = COCO(json_file)
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
dataset = json.load(open(annotation_file, ))
**FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_val2017.json'**_
```

I want to know why I'm running so slowly, and I want to know how to solve this problem. Looking forward to your reply, thank you.

## Environment

sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                     1.17.2
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.0
PyTorch Debug Build       False
torchvision               0.4.1a0+d94043a
CUDA available            True
GPU 0                     GeForce GTX 1060 6GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.0
cv2                       4.1.1
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

[10/24 11:45:50 detectron2]: Command line arguments: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=True, machine_rank=0, num_gpus=1, num_machines=1, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], resume=False)
[10/24 11:45:50 detectron2]: Contents of args.config_file=configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml:
_BASE_: "../Base-RCNN-FPN.yaml"

**Comment by ppwwyyxx** [comment]
> **FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_val2017.json'**_

The script needs COCO data and the instruction to set it up is at https://github.com/facebookresearch/detectron2/tree/master/datasets.

The visualization, image resize, video reading, writing all take time.

**Comment by shidi518** [comment]
Hi,
I run the` ./prepare_for_tests.sh`. However I got  > instances_val2017_100.json
So I meet the problem again. `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_val2017.json'`

I want to know where I can change the file name.
Thank you very much.

**Comment by shidi518** [comment]
When I rename the `iinstances_val2017_100.json`to`instances_val2017.json`
It shows the following problem
`Start inference on 100 images
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 132, in main
    res = Trainer.test(cfg, model)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/engine/defaults.py", line 412, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/evaluation/evaluator.py", line 112, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/dataset_mapper.py", line 72, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/home/zbw/Pakinson/cuda9.2detectron2/detectron2/detectron2/data/detection_utils.py", line 45, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/file_io.py", line 328, in open
    return PathManager.__get_path_handler(path)._open(path, mode)
  File "/home/zbw/anaconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/file_io.py", line 197, in _open
    return open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/val2017/000000001268.jpg'
`

Looking forward for your reply,
Thank you very much!

**Comment by ppwwyyxx** [comment]
`prepare_for_test` is not the script to prepare COCO data. You need to download COCO data and extract it into this format: https://github.com/facebookresearch/detectron2/tree/master/datasets#expected-dataset-structure-for-coco-instancekeypoint-detection.

Alternatively you can use https://detectron2.readthedocs.io/modules/evaluation.html#detectron2.evaluation.inference_on_dataset to benchmark the speed of the model. It will not give you comparable speed with the model zoo since the time depends on the data you use. But at least it won't contain unnecessary time such as visualization.
