### ISSUE TITLE
Demo.py throws NotImplementedError

### ISSUE THREAD

**Issue by ankur7721** [facebookresearch/detectron2#1617]
Demo.py throws NotImplementedError 

Model taken from https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md
Architecture Name : Mask R-CNN X152
Model Name :  model_0039999_e76410.pkl
--

Command

`python demo.py --config-file config/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml --input imgs/21.JPG --output imgs/21_out.JPG --confidence-threshold 0.8 --opts MODEL.WEIGHTS output/model_0044999.pth MODEL.DEVICE cpu`

3. __full logs__ you observed:
```
(table) ubuntu@ip-172-31-16-80:~$ python demo.py --config-file config/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml --input imgs/21.JPG --output imgs/21_out.JPG --confidence-threshold 0.8 --opts MODEL.WEIGHTS output/model_0044999.pth MODEL.DEVICE cpu
[06/17 12:19:03 detectron2]: Arguments: Namespace(confidence_threshold=0.8, config_file='config/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml', input=['imgs/21.JPG'], opts=['MODEL.WEIGHTS', 'output/model_0044999.pth', 'MODEL.DEVICE', 'cpu'], output='imgs/21_out.JPG', video_input=None, webcam=False)
WARNING [06/17 12:19:03 d2.config.compat]: Config 'config/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Unable to load 'roi_heads.box_predictor.0.cls_score.weight' to the model due to incompatible shapes: (6, 1024) in the checkpoint but (81, 1024) in the model!
Unable to load 'roi_heads.box_predictor.0.cls_score.bias' to the model due to incompatible shapes: (6,) in the checkpoint but (81,) in the model!
Unable to load 'roi_heads.box_predictor.1.cls_score.weight' to the model due to incompatible shapes: (6, 1024) in the checkpoint but (81, 1024) in the model!
Unable to load 'roi_heads.box_predictor.1.cls_score.bias' to the model due to incompatible shapes: (6,) in the checkpoint but (81,) in the model!
Unable to load 'roi_heads.box_predictor.2.cls_score.weight' to the model due to incompatible shapes: (6, 1024) in the checkpoint but (81, 1024) in the model!
Unable to load 'roi_heads.box_predictor.2.cls_score.bias' to the model due to incompatible shapes: (6,) in the checkpoint but (81,) in the model!
Unable to load 'roi_heads.mask_head.predictor.weight' to the model due to incompatible shapes: (5, 256, 1, 1) in the checkpoint but (80, 256, 1, 1) in the model!
Unable to load 'roi_heads.mask_head.predictor.bias' to the model due to incompatible shapes: (5,) in the checkpoint but (80,) in the model!
  0%|                                                                                                                          | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 85, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/ubuntu/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 218, in __call__
    predictions = self.model([inputs])[0]
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in inference
    features = self.backbone(images.tensor)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/modeling/backbone/fpn.py", line 123, in forward
    bottom_up_features = self.bottom_up(x)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 463, in forward
    x = stage(x)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 321, in forward
    out = self.conv2(out, offset)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 384, in forward
    self.deformable_groups,
  File "/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 49, in forward
    raise NotImplementedError

```

## Expected behavior:

Demo.py should have run without any error

## Environment:

Provide your environment information using the following command:
```
------------------------  ------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.3 @/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  not available
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.5.0 @/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            False
Pillow                    7.1.2
torchvision               0.6.0a0+82fd1c8 @/home/ubuntu/anaconda3/envs/table/lib/python3.7/site-packages/torchvision
fvcore                    0.1.1.post20200611
cv2                       3.4.2
------------------------  ------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```

Is it because I am running model on CPU ?

**Comment by ppwwyyxx** [comment]
Yes. Most but not all models can run on CPUs.
