### ISSUE TITLE
Training Semantic Segmentation model without BBOX labels

### ISSUE THREAD

**Issue by vdabravolski** [facebookresearch/detectron2#1619]
**What I'm trying to do**

I'd like to fine-tune one of Semantic Segmentation D2 models (e.g. [R50-FPN, Cityscapes](https://github.com/facebookresearch/detectron2/blob/master/configs/Cityscapes/mask_rcnn_R_50_FPN.yaml)) on custom dataset. I have [aerial drone dataset](https://www.tugraz.at/index.php?id=22387) which comes with Ground Truth monochrome masks with label ids. In this regard, this dataset is similar to CityScapes. However, unlike CityScape, drone dataset doesn't have JSON files with polygons.

So i tried to re-use Cityscapes model and dataloader from D2 model zoo, however, RPN network is throwing exception because it doesn't get GT BBOX dicts.

I wonder if this is possible to fine-tune D2 baseline cityscape model without having BBOX labels. E.g. is it possible to freeze FPN head, disable Box ROI and only let SemSeg head to train?

**Code to reproduce the issue**
Here is my code/config which currently returns error:

```
############ Dataset Loader##########
import logging
import numpy as np
import os
from fvcore.common.file_io import PathManager
from PIL import Image

from detectron2.utils.logger import setup_logger
from collections import namedtuple

try:
    import cv2  # noqa
except ImportError:
    # OpenCV is an optional dependency at the moment
    pass


logger = logging.getLogger(__name__)

# Following approach from Cityscapes Scripts: https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py
Label = namedtuple( 'Label' , [

    'name'        , # The identifier of this label, e.g. 'car', 'person', ... .
                    # We use them to uniquely name a class

    'id'          , # An integer ID that is associated with this label.
                    # The IDs are used to represent the label in ground truth images
                    # An ID of -1 means that this label does not have an ID and thus
                    # is ignored when creating ground truth images (e.g. license plate).
                    # Do not modify these IDs, since exactly these IDs are expected by the
                    # evaluation server.

    'trainId'     , # Feel free to modify these IDs as suitable for your method. Then create
                    # ground truth images with train IDs, using the tools provided in the
                    # 'preparation' folder. However, make sure to validate or submit results
                    # to our evaluation server using the regular IDs above!
                    # For trainIds, multiple labels might have the same ID. Then, these labels
                    # are mapped to the same class in the ground truth images. For the inverse
                    # mapping, we use the label that is defined first in the list below.
                    # For example, mapping all void-type classes to the same ID in training,
                    # might make sense for some approaches.
                    # Max value is 255!

    'category'    , # The name of the category that this label belongs to

    'categoryId'  , # The ID of this category. Used to create ground truth images
                    # on category level.

    'hasInstances', # Whether this label distinguishes between single instances or not

    'ignoreInEval', # Whether pixels having this class as ground truth label are ignored
                    # during evaluations or not

    'color'       , # The color of this label
    ] )


labels = [
    #       name                  id    trainId   category            catId     hasInstances   ignoreInEval   color
    Label(  'unlabeled'          ,  0 ,      0 , 'unknown'         , 0       , False        , False        , (  0,  0,  0) ),
    Label(  'paved area'         ,  1 ,      7 , 'flat'            , 2       , False        , True         , ( 128, 64, 128) ),
    Label(  'dirt'               ,  2 ,      3 , 'flat'            , 1       , False        , True         , (130, 76, 0) ),
    Label(  'grass'              ,  3 ,      1 , 'nature'          , 0       , False        , True         , (0, 102, 0) ),
    Label(  'gravel'             ,  4 ,      4 , 'flat'            , 1       , False        , True         , (112, 103, 87) ),
    Label(  'water'              ,  5 ,      6 , 'flat'            , 1       , False        , False        , (228, 42, 168) ),
    Label(  'rocks'              ,  6 ,      5 , 'flat'            , 1       , False        , True         , (48, 41, 30) ),
    Label(  'pool'               ,  7 ,      8 , 'construction'    , 2       , False        , True         , (0, 50, 89) ),
    Label(  'vegetation'         ,  8 ,      2 , 'nature'          , 0       , False        , True         , ( 107, 142, 35) ),
    Label(  'roof'               ,  9 ,     13 , 'construction'    , 2       , False        , False        , (70, 70, 70) ),
    Label(  'wall'               , 10 ,     14 , 'construction'    , 2       , False        , True         , (102, 102, 156) ), 
    Label(  'window'             , 11 ,     17 , 'construction'    , 2       , False        , True         , (254, 228, 12) ),
    Label(  'door'               , 12 ,     18 , 'construction'    , 2       , False        , True         , (254, 148, 12) ),
    Label(  'fence'              , 13 ,     15 , 'object'          , 6       , False        , True         , (190, 153, 153) ),
    Label(  'fence-pole'         , 15 ,     16 , 'object'          , 6       , False        , True         , (153, 153, 153) ),
    Label(  'person'             , 14 ,      9 , 'human'           , 3       , True         , False        , (255, 22, 96) ),
    Label(  'dog'                , 16 ,     10 , 'animal'          , 4       , True         , False        , (102, 51, 0) ),
    Label(  'car'                , 17 ,     11 , 'vehicle'         , 5       , True         , False        , (9, 143, 150) ),
    Label(  'bicycle'            , 17 ,     12 , 'vehicle'         , 5       , True         , False        , (119, 11, 32) ),
    Label(  'tree'               , 19 ,      0 , 'nature'          , 0       , False        , False        , (51, 51, 0) ),
    Label(  'bald-tree'          , 20 ,      0 , 'nature'          , 0       , False        , False        , ( 190, 250, 190) ),
    Label(  'ar-marker'          , 21 ,      0 , 'object'          , 0       , False        , False        , ( 112, 150, 146) ),
    Label(  'obstacle'           , 22 ,     19 , 'object'          , 6       , False        , False        , (2, 135, 115) ),
]



def get_drone_files(image_dir, gt_dir):

    from os import listdir
    from os.path import isfile, join

    image_files = [f for f in listdir(image_dir) if isfile(join(image_dir, f))]

    # get corresponding GT file
    gt_files = []
    for file in image_files:
        filename = os.path.splitext(file)[0]
        gt_files.append(filename+".png")


    # add file path and combine image and gt files into list of tuples
    combined_files = []
    for image, gt in zip(image_files, gt_files):
        combined_files.append(
            (
                os.path.join(image_dir, image),
                os.path.join(gt_dir, gt)
            )
        )

    return combined_files


def load_drone_semantic(image_dir, gt_dir):

    results = []

    for image_file, gt_file in get_drone_files(image_dir, gt_dir):

        # PIL Image is efficient as it doesn't read image to retrieve size
        im = Image.open(image_file)
        width, height = im.size

        results.append({
            "file_name": image_file,
            "sem_seg_file_name": gt_file,
            "height": height,
            "width": width
            }
        )

    assert len(results),  f"No images found in {image_dir}!"
    assert PathManager.isfile(results[0]["sem_seg_file_name"]
    ), "Please generate labelTrainIds.png with cityscapesscripts/preparation/createTrainIdLabelImgs.py"  # noqa

    return results



############ Register Dataset########
from detectron2.data import DatasetCatalog, MetadataCatalog

dataset_name = "drone_semantic_train"
image_dir = "semantic_drone_dataset/original_images/" 
gt_dir = "semantic_drone_dataset/label_images_semantic/"
stuff_colors = [k.color for k in labels if k.trainId != 255]
stuff_classes = [k.name for k in labels if k.trainId != 255]


DatasetCatalog.register(dataset_name, lambda d=d: load_drone_semantic(image_dir, gt_dir))
MetadataCatalog.get(dataset_name).set(stuff_colors=stuff_colors, stuff_classes=stuff_classes,
                                      evaluator_type="sem_seg") # built-in evaluator for semantic seg task

drone_meta = MetadataCatalog.get(dataset_name)

############ Model Config/Training###########

config_file = "Cityscapes/mask_rcnn_R_50_FPN.yaml"

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file(config_file))
cfg.DATASETS.TRAIN = ("drone_semantic_train",)
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(config_file)
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = 23
cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE = 0 # ignore "unlabeled index"

cfg.OUTPUT_DIR = "sem_seg_output"

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Stacktrace**

```
[06/16 22:53:38 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelMaxPool()
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (proposal_generator): RPN(
    (rpn_head): StandardRPNHead(
      (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (objectness_logits): Conv2d(256, 3, kernel_size=(1, 1), stride=(1, 1))
      (anchor_deltas): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
    (anchor_generator): DefaultAnchorGenerator(
      (cell_anchors): BufferList()
    )
  )
  (roi_heads): StandardROIHeads(
    (box_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(7, 7), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(7, 7), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(7, 7), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (box_head): FastRCNNConvFCHead(
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=9, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=32, bias=True)
    )
    (mask_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(14, 14), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(14, 14), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(14, 14), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(14, 14), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (mask_head): MaskRCNNConvUpsampleHead(
      (mask_fcn1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_fcn4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (deconv): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
      (predictor): Conv2d(256, 8, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
[06/16 22:53:39 d2.data.common]: Serializing 400 elements to byte tensors and concatenating them all ...
[06/16 22:53:39 d2.data.common]: Serialized dataset takes 0.07 MiB
[06/16 22:53:39 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(800, 832, 864, 896, 928, 960, 992, 1024), max_size=2048, sample_style='choice'), RandomFlip()]
[06/16 22:53:39 d2.data.build]: Using training sampler TrainingSampler
[06/16 22:53:39 d2.engine.train_loop]: Starting training from iteration 0
ERROR [06/16 22:53:41 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 117, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 411, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 274, in label_and_sample_anchors
    gt_boxes = [x.gt_boxes for x in gt_instances]
TypeError: 'NoneType' object is not iterable
[06/16 22:53:41 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-6369bea6f979> in <module>
      1 trainer = DefaultTrainer(cfg)
      2 trainer.resume_or_load(resume=False)
----> 3 trainer.train()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/engine/defaults.py in train(self)
    400             OrderedDict of results, if evaluation is enabled. Otherwise None.
    401         """
--> 402         super().train(self.start_iter, self.max_iter)
    403         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    404             assert hasattr(

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    130                 for self.iter in range(start_iter, max_iter):
    131                     self.before_step()
--> 132                     self.run_step()
    133                     self.after_step()
    134             except Exception:

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/engine/train_loop.py in run_step(self)
    213         If you want to do something with the losses, you can wrap the model.
    214         """
--> 215         loss_dict = self.model(data)
    216         losses = sum(loss_dict.values())
    217         self._detect_anomaly(losses, loss_dict)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    115 
    116         if self.proposal_generator:
--> 117             proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
    118         else:
    119             assert "proposals" in batched_inputs[0]

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py in forward(self, images, features, gt_instances)
    409 
    410         if self.training:
--> 411             gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
    412             losses = self.losses(
    413                 anchors, pred_objectness_logits, gt_labels, pred_anchor_deltas, gt_boxes

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     13         def decorate_context(*args, **kwargs):
     14             with self:
---> 15                 return func(*args, **kwargs)
     16         return decorate_context
     17 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py in label_and_sample_anchors(self, anchors, gt_instances)
    272         anchors = Boxes.cat(anchors)
    273 
--> 274         gt_boxes = [x.gt_boxes for x in gt_instances]
    275         image_sizes = [x.image_size for x in gt_instances]
    276         del gt_instances

TypeError: 'NoneType' object is not iterable
```

**Comment by ppwwyyxx** [comment]
> fine-tune one of Semantic Segmentation D2 models (e.g. R50-FPN, Cityscapes) 

The model you linked to is not a semantic segmentation model. It's an instance detection/segmentation model so it must requires boxes.

**Comment by vdabravolski** [comment]
Okay, thanks. Is there any Semantic Segmentation models in the D2 model zoo? That's the task I'm trying to solve here anyways.

**Comment by ppwwyyxx** [comment]
There isn't any for now.

**Comment by vdabravolski** [comment]
Okay, thanks.

**Comment by yuvalgrossman** [comment]
If still relevant, as a workaround, you can use the panoptic segmentation models and set the ROI_heads to 1:
(here self.mConfiguration is a configuration I defined differently from the detectron standard)

        base_conf = "COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"
        cfg = get_cfg()
        cfg.merge_from_file(model_zoo.get_config_file(base_conf))
        cfg.DATASETS.TRAIN = ("Train_Dataset1",)
        cfg.DATASETS.TEST = ("Verify_Dataset1",)
        cfg.TEST.EVAL_PERIOD = 100
        cfg.DATALOADER.NUM_WORKERS = 1
        if mode=='Training':
            cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(base_conf)  # Let training initialize from model zoo
            cfg.SOLVER.IMS_PER_BATCH = self.mConfiguration.BatchSize
            cfg.SOLVER.BASE_LR = self.mConfiguration.LearningRate  # pick a good LR
            cfg.SOLVER.MAX_ITER = self.mConfiguration.MaxIter  
        # cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128  # faster, and good enough for this toy dataset (default: 512)
        cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
        cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = len(self.mConfiguration.SegmentationClasses)
