### ISSUE TITLE
Error in extract semantic annotations from panoptic annotations.

### ISSUE THREAD

**Issue by kaenkogashi** [facebookresearch/detectron2#1654]
To Reproduce
1. full code you wrote or full changes you made : Nothing
2. what exact command you run: followed instructions from https://github.com/facebookresearch/detectron2/tree/master/datasets
first, down load panoptic dataset from http://cocodataset.org/#download
2017 Panoptic Train/Val annotations [821MB] and push the dataset in expected dataset structure.
then Install panopticapi by:
pip install git+https://github.com/cocodataset/panopticapi.git
Then, cd datasets and run python prepare_panoptic_fpn.py, to extract semantic annotations from panoptic annotations.
3. __full logs__ you observed:
```
python prepare_panoptic_fpn.py
Start writing to coco/panoptic_stuff_val2017 ...
Finished. time: 2.59s
Start writing to coco/panoptic_stuff_train2017 ...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/kogashi/miniconda3/envs/detectron/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/kogashi/miniconda3/envs/detectron/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "prepare_panoptic_fpn.py", line 19, in _process_panoptic_to_semantic
    panoptic = np.asarray(Image.open(input_panoptic), dtype=np.uint32)
  File "/home/kogashi/miniconda3/envs/detectron/lib/python3.7/site-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'coco/panoptic_train2017/000000000540.png'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_panoptic_fpn.py", line 87, in <module>
    COCO_CATEGORIES,
  File "prepare_panoptic_fpn.py", line 75, in separate_coco_semantic_from_panoptic
    chunksize=100,
  File "/home/kogashi/miniconda3/envs/detectron/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/kogashi/miniconda3/envs/detectron/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'coco/panoptic_train2017/000000000540.png'
```

## Expected behavior:

extract semantic annotations from panoptic annotations.

## Environment:

Provide your environment information using the following command:
```
sys.platform              linux
Python                    3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/kogashi/miniconda3/envs/detectron/lib/python3.7/site-packages/detectron2
detectron2 compiler       GCC 7.3
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0+cu100 @/home/kogashi/miniconda3/envs/detectron/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla V100-SXM2-16GB
CUDA_HOME                 /home/kogashi/miniconda3/cuda-9.0
NVCC                      Cuda compilation tools, release 9.0, V9.0.176
Pillow                    7.0.0
torchvision               0.5.0+cu100 @/home/kogashi/miniconda3/envs/detectron/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  --------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```

**Comment by ppwwyyxx** [comment]
Currently the script has to be moved to the dataset directory defined by `DETECTRON2_DATASETS` and run there. The directory is expected to have `coco/panoptic_train2017/000000000540.png` according to https://github.com/facebookresearch/detectron2/tree/master/datasets.

**Comment by kaenkogashi** [comment]
thank you for your reply! I download panoptic dataset from official coco-site, but they do not have 000000000540.png. And COCO2017 have 118287 pictures, but Panoptic datasets only provide 52751. Where can I download full Panoptic dataset? Would you provide me some links?
>first, down load panoptic dataset from http://cocodataset.org/#download
>2017 Panoptic Train/Val annotations [821MB] and push the dataset in expected dataset structure.

**Comment by ppwwyyxx** [comment]
The file exists. You probably downloaded something wrong.

**Comment by erickulcyk** [comment]
@ppwwyyxx Ran into this problem today.  Downloaded the zip twice from https://cocodataset.org/#download http://images.cocodataset.org/annotations/panoptic_annotations_trainval2017.zip
The file does not exist.  Perhaps you are getting the data set from somewhere else?

**Comment by erickulcyk** [comment]
I just put a check in for whether the image exists, and It can't find like 80% of the images... strange seeing as the json file this is coming from is literally packaged in the same zip as the one with the missing files.

**Comment by erickulcyk** [comment]
It seems that downloading from FiftyOne downloads a much, much bigger training set (144 GB vs 18 GB)

**Comment by isksjsksk** [comment]
@erickulcyk @kaenkogashi Hi, I encounter the same problem. Did you solve it?

**Comment by ShubhamAgarwal12** [comment]
Unzipping using "tar -xf panoptic_train2017.zip" solved this issue for me.
