### ISSUE TITLE
 ModuleNotFoundError: No module named 'torch.utils.hipify'

### ISSUE THREAD

**Issue by onoderay** [facebookresearch/detectron2#1722]
Hello, I have following error to build detectron2 from branch of 45a4d970bb
https://github.com/facebookresearch/detectron2/blob/45a4d970bb2242ce0630c5ce03f860ad14382169/INSTALL.md
Can someone give me solution please? 
I think pytorch has sucesfully installed by conda 
~~~shell
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
~~~
Error is following
~~~shell
$ python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-pseh_9pr
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-pseh_9pr
    ERROR: Command errored out with exit status 1:
     command: /home/yuyonod/anaconda3/envs/yolact-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-pseh_9pr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-pseh_9pr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g3pazu1j
         cwd: /tmp/pip-req-build-pseh_9pr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-pseh_9pr/setup.py", line 12, in <module>
        from torch.utils.hipify import hipify_python
    ModuleNotFoundError: No module named 'torch.utils.hipify'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~~~

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by Jiejiegary** [comment]
You may need to upgrade your PyTorch ≥ 1.4.
