### ISSUE TITLE
get classname(not id) from MetadataCatalog

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#1755]
or another way other than loading Coco JSON and filtering it by hand

_ps: don't paste link to useless doc's_

```python
    outputs = predictor(im)
    o = outputs["instances"]

    s = o.scores
    c = o.pred_classes
    b = o.pred_boxes

    for s, с, b in zip(s, c, b):
        score = round(s.tolist(), 2)
        x1, y1, x2, y2 = b.tolist()
        print('с: ', с)
        print('score: ', score)
        print('x1, y1, x2, y2: ', x1, y1, x2, y2)
```

**Comment by chiboreache** [comment]
`labels = _create_text_labels(classes, scores, self.metadata.get("thing_classes", None))`

**Comment by chiboreache** [comment]
getting 

```
Traceback (most recent call last):
  File "/home/chibo/ML/fapp/FAPP/_1_DCNN/d2_eval.py", line 87, in <module>
    labels = _create_text_labels(c, s, meta_test.get("thing_classes", None))
  File "/usr/lib/python3.8/site-packages/detectron2/utils/visualizer.py", line 214, in _create_text_labels
    labels = ["{} {:.0f}%".format(l, s * 100) for l, s in zip(labels, scores)]
  File "/home/chibo/.local/lib/python3.8/site-packages/torch/tensor.py", line 462, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

**Comment by chiboreache** [comment]
problem was in a loop before, that screwed data

---

really nice sources btw, MUCH better that official useless docs..
