### ISSUE TITLE
'RuntimeError: expected scalar type Long but found Float' in torch.ops.torchvision.nms

### ISSUE THREAD

**Issue by qizhust** [facebookresearch/detectron2#1761]
Hi, anyone come across this?

When running the demo.py, the following error appears:
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 83, in batched_nms
        offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
        boxes_for_nms = boxes + offsets[:, None]
        keep = nms(boxes_for_nms, scores, iou_threshold)
               ~~~ <--- HERE
        return keep
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 41, in nms
        by NMS, sorted in decreasing order of scores
    """
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: expected scalar type Long but found Float
```

I am using
```
pytorch 1.5.0a0+4ff3872
torchvision 0.7.0a0+3d65fc6
python 3.8.2
cuda 10.2
```

**Comment by ppwwyyxx** [comment]
Please see the version requirement of torchvision in https://github.com/pytorch/vision/#installation
Randomly combining two non-release versions of pytorch and torchvision is not expected to work.

**Comment by qizhust** [comment]
> Please see the version requirement of torchvision in https://github.com/pytorch/vision/#installation
> Randomly combining two non-release versions of pytorch and torchvision is not expected to work.

I did not randomly combine two versions. It was the default one on my server, and the environment works well for other packages. You can also print the function
```
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.5.0a0+4ff3872'
>>> import torchvision
>>> torchvision.__version__
'0.7.0a0+3d65fc6'
>>> torch.ops.torchvision.nms
<built-in method nms of PyCapsule object at 0x2b59c7ebe540>
```

**Comment by ppwwyyxx** [comment]
Then the default on your server is unfortunately an invalid combination of versions and should be changed.
The valid combinations are listed in https://github.com/pytorch/vision/#installation

**Comment by qizhust** [comment]
Thanks for your suggestion. I downgrade the version of torchvision to 0.6.0, 

```
Python 3.8.2 (default, Mar 23 2020, 15:06:34)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.5.0a0+4ff3872'
>>> import torchvision
>>> torchvision.__version__
'0.6.0'

```

Now the error becomes

```
Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/engine/defaults.py", line 216, in __call__
    predictions = self.model([inputs])[0]
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 201, in inference
    proposals, _ = self.proposal_generator(images, features, None)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 443, in forward
    proposals = self.predict_proposals(
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 469, in predict_proposals
    return find_top_rpn_proposals(
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py", line 107, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/project/RDS-FEI-qiz-RW/reproduce/detectron2/detectron2/layers/nms.py", line 21, in batched_nms
    return box_ops.batched_nms(boxes, scores, idxs, iou_threshold)
  File "/home/qzhe6525/.local/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 75, in batched_nms
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/qzhe6525/.local/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 35, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/torch/_ops.py", line 61, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms
```

**Comment by qizhust** [comment]
Besides, detectron2 is both compiled and run under gcc 7.4.0.

**Comment by ppwwyyxx** [comment]
That's still a torchvision issue and should be reported to torchvision instead.

**Comment by qizhust** [comment]
Yes, I change to the matched version and it works. Thanks a lot!
