### ISSUE TITLE
Detectron2 install using Dockerfile

### ISSUE THREAD

**Issue by ividovic** [facebookresearch/detectron2#1830]
I have a problem with installation of Detectron2 using Dockerfile. Can you please help me to solve it?

## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
It is installation issue. I didn't make any changes.

2. what exact command you run:
docker build --build-arg USER_ID=$UID -t detectron2:v0 .

## Expected behavior:
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/appuser/detectron2_repo/setup.py'"'"'; __file__='"'"'/home/appuser/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/appuser/detectron2_repo/
    Complete output (102 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    running develop
    running egg_info
    creating detectron2.egg-info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    creating /home/appuser/detectron2_repo/build
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/cocoeval
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/nms_rotated
    creating /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/deformable
    Emitting ninja build file /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/cocoeval/cocoeval.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/cocoeval/cocoeval.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/cocoeval/cocoeval.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [2/13] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    Killed
    [3/13] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    Killed
    [4/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [5/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [6/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [7/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [8/13] c++ -MMD -MF /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/vision.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/vision.cpp -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [9/13] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    [10/13] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    [11/13] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/appuser/detectron2_repo/detectron2/layers/csrc -I/home/appuser/.local/lib/python3.6/site-packages/torch/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/TH -I/home/appuser/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/appuser/detectron2_repo/build/temp.linux-x86_64-3.6/home/appuser/detectron2_repo/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_75,code=sm_75 -std=c++14
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
        check=True)
      File "/usr/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/appuser/detectron2_repo/setup.py", line 202, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/home/appuser/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/appuser/.local/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/appuser/.local/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/appuser/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/appuser/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
        build_ext.build_extensions(self)
      File "/home/appuser/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/appuser/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/appuser/detectron2_repo/setup.py'"'"'; __file__='"'"'/home/appuser/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

## Environment:

OS: Ubuntu 20.04

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

Docker version 19.03.8, build afacb8b7f0

**Comment by ppwwyyxx** [comment]
Looks like `nvcc` was killed because your machine has insufficient RAM.
You can disable parallel compilation following the instructions in the logs, or try a better machine.

**Comment by ividovic** [comment]
> Looks like `nvcc` was killed because your machine has insufficient RAM.
> You can disable parallel compilation following the instructions in the logs, or try a better machine.

@ppwwyyxx thanks for your reply.

How much RAM do I need to install Detectron2? I have Asus ROG G752VY-GC100D (https://www.asus.com/ROG-Republic-Of-Gamers/ROG-G752VY/specifications/) with 8GB of RAM. Maybe I have some other problem?

![memory](https://user-images.githubusercontent.com/39398691/88623409-34120980-d0a5-11ea-8d01-6cf0fc765b68.png)

**Comment by 1786939789** [comment]
Hello, I have met same problem. Have you solved it?

**Comment by ividovic** [comment]
> Hello, I have met same problem. Have you solved it?

No, I didn't. How much RAM do you have?

@ppwwyyxx can you please help us with this bug?

**Comment by ppwwyyxx** [comment]
You can disable parallel compilation following the instructions in the logs:
>     Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)

**Comment by ividovic** [comment]
> You can disable parallel compilation following the instructions in the logs:
> 
> > ```
> > Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> > ```

You think that my GPU is not compatible with Detectron2?

**Comment by ppwwyyxx** [comment]
No. I think the machine does not have sufficient RAM.

**Comment by ividovic** [comment]
> No. I think the machine does not have sufficient RAM.

I think that you are wrong. :) I have successfully run the build command from the terminal. The above mentioned error was obtained when I was trying to run the command from Visual Studio Code Remote Container. Now, when we know that I have sufficient RAM, do you know what can be the problem? :)

I will also try to run builded image from VS Code Remote Container (without building in VS Code).

**Comment by ppwwyyxx** [comment]
> I have successfully run the build command from the terminal.

In that case it seems problem is solved. We do not help with issues that are specifically about certain IDEs or third-party softwares since we don't know what they do.
