### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by geo47** [facebookresearch/detectron2#1841]
I am getting this error when running pip install:

python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

I can't figure out problem by looking at the logs.
Kindly help me resolve the problem.

Thanks...

```
Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/muzamil/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/muzamil/detectron2/setup.py'"'"'; __file__='"'"'/home/muzamil/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/muzamil/detectron2/
    Complete output (96 lines):
    running develop
    running egg_info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    Emitting ninja build file /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [2/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [3/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [4/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [5/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [6/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    [7/7] /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/cuda_version.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/cuda_version.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/cuda_version.o
    /usr/bin/nvcc -DWITH_CUDA -I/home/muzamil/detectron2/detectron2/layers/csrc -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/home/muzamil/anaconda3/include/python3.8 -c -c /home/muzamil/detectron2/detectron2/layers/csrc/cuda_version.cu -o /home/muzamil/detectron2/build/temp.linux-x86_64-3.8/home/muzamil/detectron2/detectron2/layers/csrc/cuda_version.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_75'
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _run_ninja_build
        subprocess.run(
      File "/home/muzamil/anaconda3/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/muzamil/detectron2/setup.py", line 166, in <module>
        setup(
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
        build_ext.build_extensions(self)
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/muzamil/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 469, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1228, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/muzamil/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/muzamil/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/muzamil/detectron2/setup.py'"'"'; __file__='"'"'/home/muzamil/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.


```

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by yueluming** [comment]
I also have this problem, how did you solve it. Thanks.
