### ISSUE TITLE
detectron2 build results with windows 10, CUDA 10.1

### ISSUE THREAD

**Issue by apiszcz** [facebookresearch/detectron2#1842]
https://github.com/facebookresearch/detectron2/issues/1659

Windows 10, Cuda 10.1, CUDNN 8.1, Python 3.7, 

PyTorch 1.5.0 builds successfully with detectron2 v0.12
PyTorch 1.5.1 builds fails with detectron2 v0.12
PyTorch 1.5.0 builds fails with detectron2 v0.2 (ninja build errors)
PyTorch 1.6.0 builds fails with detectron2 v0.2 (ninja build errors)
NEW issue after setting this environment variable the build starts and fails with error_prefix='Error compiling objects for extension')
UserWarning: It seems that the VC environment is activated but DISTUTILS_USE_SDK is not set.This may lead to multiple activations of the VC env.Please set `DISTUTILS_USE_SDK=1` and try again.
cl : Command line warning D9025 : overriding '/MT' with '/MD'

multiple failures, one example

```
deform_conv_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

==

```
detectron2\layers\csrc\cocoeval\cocoeval.cpp(483): error C3861: 'localtime_r': identifier not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 202, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "C:\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

```

**Comment by yezz123** [comment]
I guess is not available to run this on Windows 🤔

**Comment by apiszcz** [comment]
#1659 indicates they are working on updates for windows.

**Comment by yezz123** [comment]
then i will try to see if that work on my Windows OS
also what Version ?

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues says:
> Although detectron2 can be installed on windows with some effort (similar to these), we do not provide official support for it.
PRs that improves code compatibility on windows are welcome

**Comment by apiszcz** [comment]
yezz123 PyTorch 1.5.0 builds successfully with detectron2 v0.12 works ok.

**Comment by hcyz33** [comment]
I met the similar problem. Could you tell me how to fix it .
