### ISSUE TITLE
Pickling error with more than 1 GPU

### ISSUE THREAD

**Issue by jcpayne** [facebookresearch/detectron2#1846]
I've got a Detectron2 model that trains when num_gpus_per_machine is set to 1, but produces a pickling error when it is set > 1.  This is very similar to the closed issue "Multi-gpus Training Error #1410," except that I don't import ipdb anywhere as far as I know, so that solution doesn't work in this case.  I am using a Linux VM (18.04) with 4 GPUs.

## Instructions To Reproduce the Issue:
This is a TridentNet variant of Detectron2, using a custom dataset and adding image augmentation. 
```
#Interactive config (Jupyter notebook)
cfg = get_cfg()
add_tridentnet_config(cfg)
cfg.INPUT.FORMAT = "RGB"
cfg.INPUT.MIN_SIZE_TRAIN = (400,420,440,460,480,500) 
cfg.INPUT.MIN_SIZE_TEST = 500
cfg.INPUT.corruption = 0.1 # Probability of adding custom augmentation
cfg.MODEL.PIXEL_MEAN = [137.473, 139.769, 106.912] #default was [103.530, 116.280, 123.675]
cfg.MODEL.PIXEL_STD = [26.428, 22.083, 26.153]
cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[32, 64, 128, 256, 512]]
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(CLASS_NAMES) 
cfg.MODEL.BACKBONE.FREEZE_AT = 2
cfg.MODEL.WEIGHTS:"detectron2://ImageNetPretrained/MSRA/R-101.pkl"
cfg.DATASETS.TRAIN = ("survey_train",) 
cfg.DATASETS.TEST = ("survey_valid",)
cfg.DATALOADER.NUM_WORKERS = 24
cfg.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False
cfg.OUTPUT_DIR = '/cdata/tanzania/temp/model_output'
cfg.LR_SCHEDULER='WarmupCosineLR'
cfg.SOLVER.STEPS: (2100, 2500) 
cfg.SOLVER.MAX_ITER = 2700 
cfg.SOLVER.WARMUP_ITERS = 500 
cfg.SOLVER.IMS_PER_BATCH: 4
cfg.SOLVER.BASE_LR: 0.001
cfg.SOLVER.CHECKPOINT_PERIOD = 500

#Overriding the default augmentation method (which is in detectron2/data/detection_utils.py)
def build_augmentation(cfg, is_train):
    #logger = logging.getLogger(__name__)

    result = utils.build_augmentation(cfg, is_train) 

    if is_train:
        random_corruption = RandomCorruption(cfg.INPUT.corruption)
        result.append(random_corruption)

        #logger.info("Random corruption augmentation used in training: " + str(random_corruption))
        print(result)
    return result

#Add a new class to do augmentation, using the 'imgaug' package
class RandomCorruption(Augmentation):
    """
    Randomly transforms image corruption using the 'imgaug' package 
    (which is only guaranteed to work for uint8 images).  
    Returns an Numpy ndarray.
    """
    def __init__(self, p):
        """
        Args: 
            p probability of applying corruption (p is on [0,1]) 
        """
        super().__init__()
        self._init(locals())
        self.p = p

    def get_transform(self, img):
        r = random.random()
        if(r <= self.p):
            #A selection of effects from imgaug
            #ia.seed(None)
            severity = random.randint(1,5)
            augmenter_list = [
                iaa.BlendAlphaSimplexNoise(
                    foreground=iaa.EdgeDetect(alpha=(0.5, 0.9)),
                    background=iaa.LinearContrast((0.5, 0.2)),
                    per_channel=0.5),
                iaa.CoarseDropout(p=0.25, size_px=8),
                iaa.imgcorruptlike.GaussianBlur(severity),
                iaa.imgcorruptlike.SpeckleNoise(severity),
                iaa.Cutout(fill_mode="gaussian", fill_per_channel=True,nb_iterations=(1, 5), size=0.2, squared=False),
                iaa.imgcorruptlike.Spatter(severity)]
            #Blend noise with the source image
            augmenter = random.choice(augmenter_list)
            blended_img = augmenter.augment_image(img)
            return BlendTransform(src_image=blended_img, src_weight=1, dst_weight=0)
        else:
            return(NoOpTransform())

#A custom DatasetMapper; not shown in its entirety here because I only changed one line, to make it call the local version of build_augmentation() instead of utils.build_augmentation().
class TridentDatasetMapper(DatasetMapper):
    @classmethod
    def from_config(cls, cfg, is_train: bool = True):
        augs = build_augmentation(cfg, is_train)
        ...[the rest is the same]
        return ret

#A Trainer class that allows for a custom DatasetMapper
class Trainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=TridentDatasetMapper(cfg, True))

#Define a trainer 
trainer = Trainer(cfg)

#Define the main function (for running interactively)
def maintrainer(trainer):
    trainer.resume_or_load(resume=False)
    return trainer.train()
```
Launch command (interactively from Jupyter Notebook):
```
args = (trainer,)
launch(maintrainer, num_gpus_per_machine=4, num_machines=1, machine_rank=0, dist_url=None,args=args)
```
3. __full logs__ you observed:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-03904d221969> in <module>
      4 
      5 args = (trainer,)
----> 6 launch(maintrainer, num_gpus_per_machine=4, num_machines=1, machine_rank=0, dist_url=None,args=args)
      7 #trainer.train()
      8 #Last time:

/anaconda/envs/trident/lib/python3.8/site-packages/detectron2/engine/launch.py in launch(main_func, num_gpus_per_machine, num_machines, machine_rank, dist_url, args)
     53             )
     54 
---> 55         mp.spawn(
     56             _distributed_worker,
     57             nprocs=num_gpus_per_machine,

/anaconda/envs/trident/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    198                ' torch.multiprocessing.start_process(...)' % start_method)
    199         warnings.warn(msg)
--> 200     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

/anaconda/envs/trident/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    147             daemon=daemon,
    148         )
--> 149         process.start()
    150         error_queues.append(error_queue)
    151         processes.append(process)

/anaconda/envs/trident/lib/python3.8/multiprocessing/process.py in start(self)
    119                'daemonic processes are not allowed to have children'
    120         _cleanup()
--> 121         self._popen = self._Popen(self)
    122         self._sentinel = self._popen.sentinel
    123         # Avoid a refcycle if the target function holds an indirect

/anaconda/envs/trident/lib/python3.8/multiprocessing/context.py in _Popen(process_obj)
    281         def _Popen(process_obj):
    282             from .popen_spawn_posix import Popen
--> 283             return Popen(process_obj)
    284 
    285     class ForkServerProcess(process.BaseProcess):

/anaconda/envs/trident/lib/python3.8/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
     30     def __init__(self, process_obj):
     31         self._fds = []
---> 32         super().__init__(process_obj)
     33 
     34     def duplicate_for_child(self, fd):

/anaconda/envs/trident/lib/python3.8/multiprocessing/popen_fork.py in __init__(self, process_obj)
     17         self.returncode = None
     18         self.finalizer = None
---> 19         self._launch(process_obj)
     20 
     21     def duplicate_for_child(self, fd):

/anaconda/envs/trident/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     45         try:
     46             reduction.dump(prep_data, fp)
---> 47             reduction.dump(process_obj, fp)
     48         finally:
     49             set_spawning_popen(None)

/anaconda/envs/trident/lib/python3.8/multiprocessing/reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

TypeError: cannot pickle '_io.TextIOWrapper' object
```

## Expected behavior:
Since it trains fine with 1 GPU, I would expect it to work for >1 GPUs.  The _io.TextIOWrapper object is not one that I added, at least as far as I know.  In earlier tries, it failed to pickle a different object.

## Environment:
```
----------------------  --------------------------------------------------------
sys.platform            linux
Python                  3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
numpy                   1.19.0
detectron2              0.2 @/anaconda/lib/python3.7/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.5.1 @/anaconda/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             Tesla K80
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.6.1 @/anaconda/lib/python3.7/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200704
cv2                     4.3.0
----------------------  --------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

Thanks for looking!

**Comment by ppwwyyxx** [comment]
Could you verify that the official training script does not have such error?

If that's true, the error still probably comes from your code, including libraries you use such as `iaa`. Jupyter notebook itself can be a source of errors as well so please also run things without jupyter.

**Comment by jcpayne** [comment]
OK I will try that; thanks.  BTW, I noticed [on SO](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) a suggestion to fix a pickling problem with multiprocessing by using a different pickling library: 
> "I'd use pathos.multiprocesssing, instead of multiprocessing.  pathos.multiprocessing is a fork of multiprocessing that uses dill. dill can serialize almost anything in python..." 
Does that suggestion have any merit?  I don't know whether pathos and ForkingPickler would work together.

**Comment by jcpayne** [comment]
Update: you were right (as far as I can tell) that the problem was Jupyter Lab.  I wrote a .py script to run the model directly from the command line and now it works.  Thanks again for your help.

**Comment by sadransh** [comment]
I am experiencing the same problem. using a 4 GPU system and using **DefaultTrainer**. when trying to use 4 GPUs getting pickle error with both Jupyter and .py script 
It works fine when I set num_gpus_per_machine=1
`Traceback (most recent call last):
  File "untitled.py", line 159, in <module>
    launch(maintrainer, num_gpus_per_machine=4, num_machines=1, machine_rank=0, dist_url=None,args=args)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DefaultTrainer.build_hooks.<locals>.test_and_save_results'
[W CudaIPCTypes.cpp:22] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]`

Any Idea? 

@jcpayne @ppwwyyxx

**Comment by jcpayne** [comment]
If you are using a Linux build of Detectron2, make sure that the version of Detectron2 you are using matches the CUDA version _on the machine where you are trying to run it_, because Detectron2 is very picky about that.  Check the table [here](https://detectron2.readthedocs.io/tutorials/install.html) (click on the little arrows) to make sure you got the right one.

**Comment by psoleni** [comment]
Hi had a similar problem, namely `can't pickle module objects` .
i've managed to solve it removing the argument passed to my custom train function.
seems like the dictionary i was passing caused some issue (didn't dive into details, i've just try removing it and voilà).
