### ISSUE TITLE
Unused parameters problem occurs when training on 2 gpus

### ISSUE THREAD

**Issue by JasonmorrowGuo** [facebookresearch/detectron2#1853]
Sorry to bother you.

When I tried to train a new model on two GPUs, I changed ```8``` to ```2``` in ```--num-gpus 8```.

Then an error occurred as below:
```
Traceback (most recent call last):
  File "./train_net.py", line 170, in <module>
    args=(args,),
  File "/media/ubuntu/Samsung_T5/instance/detectron2/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/ubuntu/Samsung_T5/instance/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/media/ubuntu/Samsung_T5/instance/detectron2/tools/train_net.py", line 156, in main
    return trainer.train()
  File "/media/ubuntu/Samsung_T5/instance/detectron2/detectron2/engine/defaults.py", line 399, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/ubuntu/Samsung_T5/instance/detectron2/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/media/ubuntu/Samsung_T5/instance/detectron2/detectron2/engine/train_loop.py", line 226, in run_step
    loss_dict = self.model(data)
  File "/home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 464, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:514)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f65b5e58193 in /home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x731 (0x7f65b70796f1 in /home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0xa168ea (0x7f65b70658ea in /home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x295a74 (0x7f65b68e4a74 in /home/ubuntu/anaconda3/envs/instance/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x55c363a5ec94 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x55c363a5edb1 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x51d1 (0x55c363aca9a1 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x55c363a0e2b9 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #8: _PyFunction_FastCallDict + 0x1d5 (0x55c363a0f3e5 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x55c363a2db93 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #10: PyObject_Call + 0x6e (0x55c363a2095e in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1d4a (0x55c363ac751a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x55c363a0e2b9 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #13: _PyFunction_FastCallDict + 0x1d5 (0x55c363a0f3e5 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x55c363a2db93 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #15: <unknown function> + 0x16c16a (0x55c363a6516a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #16: _PyObject_FastCallKeywords + 0x48b (0x55c363a6600b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x51d1 (0x55c363aca9a1 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #18: _PyFunction_FastCallKeywords + 0xfb (0x55c363a5e20b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x6a0 (0x55c363ac5e70 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #20: _PyFunction_FastCallKeywords + 0xfb (0x55c363a5e20b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x4a59 (0x55c363aca229 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #22: _PyEval_EvalCodeWithName + 0x5da (0x55c363a0e59a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #23: _PyFunction_FastCallKeywords + 0x387 (0x55c363a5e497 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x6a0 (0x55c363ac5e70 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #25: _PyEval_EvalCodeWithName + 0xb40 (0x55c363a0eb00 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #26: _PyFunction_FastCallDict + 0x1d5 (0x55c363a0f3e5 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x1d4a (0x55c363ac751a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #28: _PyFunction_FastCallDict + 0x10b (0x55c363a0f31b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x1d4a (0x55c363ac751a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #30: _PyFunction_FastCallDict + 0x10b (0x55c363a0f31b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x1d4a (0x55c363ac751a in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #32: _PyFunction_FastCallKeywords + 0xfb (0x55c363a5e20b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x6a0 (0x55c363ac5e70 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #34: _PyFunction_FastCallKeywords + 0xfb (0x55c363a5e20b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x6a0 (0x55c363ac5e70 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #36: _PyFunction_FastCallKeywords + 0xfb (0x55c363a5e20b in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x416 (0x55c363ac5be6 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #38: _PyEval_EvalCodeWithName + 0x2f9 (0x55c363a0e2b9 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #39: _PyFunction_FastCallKeywords + 0x387 (0x55c363a5e497 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x14ea (0x55c363ac6cba in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #41: _PyEval_EvalCodeWithName + 0x2f9 (0x55c363a0e2b9 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #42: PyEval_EvalCodeEx + 0x44 (0x55c363a0f1d4 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #43: PyEval_EvalCode + 0x1c (0x55c363a0f1fc in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #44: <unknown function> + 0x22bf44 (0x55c363b24f44 in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #45: PyRun_StringFlags + 0x7d (0x55c363b3021d in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #46: PyRun_SimpleStringFlags + 0x3f (0x55c363b3027f in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #47: <unknown function> + 0x23737d (0x55c363b3037d in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #48: _Py_UnixMain + 0x3c (0x55c363b306fc in /home/ubuntu/anaconda3/envs/instance/bin/python)
frame #49: __libc_start_main + 0xe7 (0x7f65bb8cab97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #50: <unknown function> + 0x1dc3c0 (0x55c363ad53c0 in /home/ubuntu/anaconda3/envs/instance/bin/python)
```
It seems that there are unused parameters which result in this error.

Unused parameters are shown in the log:
```
[08/02 18:29:38 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
  fc1000_b
  fc1000_w
  conv1_b
``` 
However, when I train the same model on a single GPU, the error won't occur and the model is trained successfully.

My training environment is shown as bellow:
* CUDA 10.0
* pytorch 1.4.0
* torchvision 0.5.0
* python 3.7.7(anaconda3)
* GPU 1080Ti*2
* GCC 7.5.0

This puzzles me a lot. I really need some advises, thanks!

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
