### ISSUE TITLE
Index mapping error while using custom dataset with COCO format

### ISSUE THREAD

**Issue by b02202050** [facebookresearch/detectron2#189]
running command `python train_net.py --eval-only --config-file configs/tridentnet_myconfig.yaml --num-gpus 2 --dist-url tcp://127.0.0.1:49153` under `[detectron2 dir]/projects/TridentNet` folder
error msg:  
```
[10/29 01:23:41 d2.evaluation.evaluator]: Start inference on 77 images
[10/29 01:23:51 d2.evaluation.evaluator]: Inference done 50/77. 0.1697 s / img. ETA=0:00:04
[10/29 01:23:56 d2.evaluation.evaluator]: Total inference time: 0:00:12 (0.166667 s / img per device, on 2 devices)
[10/29 01:23:56 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:12 (0.166912 s / img per device, on 2 devices)
[10/29 01:24:07 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
Traceback (most recent call last):
  File "train_net.py", line 75, in <module>
    args=(args,),
  File "/workspace/code/object_detection/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/code/object_detection/detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/workspace/code/object_detection/detectron2/projects/TridentNet/train_net.py", line 56, in main
    res = Trainer.test(cfg, model)
  File "/workspace/code/object_detection/detectron2/detectron2/engine/defaults.py", line 451, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/workspace/code/object_detection/detectron2/detectron2/evaluation/evaluator.py", line 151, in inference_on_dataset
    results = evaluator.evaluate()
  File "/workspace/code/object_detection/detectron2/detectron2/evaluation/coco_evaluation.py", line 138, in evaluate
    self._eval_predictions(set(self._tasks))
  File "/workspace/code/object_detection/detectron2/detectron2/evaluation/coco_evaluation.py", line 156, in _eval_predictions
    result["category_id"] = reverse_id_mapping[result["category_id"]]
KeyError: 35

```
My dataset only has one label. I register my dataset in`train_net.py`as:  
```
from detectron2.data.datasets import register_coco_instances
data_root = '/workspace/dataset/my_data_detection/'
register_coco_instances('my_data_train', {}, data_root+'labels/train.json', data_root+'images/train')
register_coco_instances('my_data_val', {}, data_root+'labels/val.json', data_root+'images/val')
from detectron2.data import MetadataCatalog
MetadataCatalog.get('my_data_train').thing_classes = ['my_class']
MetadataCatalog.get('my_data_val').thing_classes = ['my_class']
```
Have I forgot something to do?
## Environment
---------------------  --------------------------------------------------
Python                 Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Detectron2 Compiler    GCC 7.4.0
PyTorch                1.3.0
CUDA available         True
GPU 0                  Tesla V100-SXM2-16GB
GPU 1                  Tesla V100-SXM2-16GB

**Comment by xiongzubiao** [comment]
I believe that `thing_dataset_id_to_contiguous_id` in metadata was not properly created. `load_coco_json` should do the job. But it has never been called even you registered you dataset through  `register_coco_instances`.

You can try calling `DatasetCatalog.get('my_data_train')` and `DatasetCatalog.get('my_data_val')` once each after registering your datasets.  That will force `load_coco_json` being called.

**Comment by b02202050** [comment]
Thanks for xiongzubiao.
Sorry I miss to specify `--resume` to the `train_net.py` to load the model.
but I suggest the documentation could be more clear for metric evaluations.

**Comment by xinlong007** [comment]
> Thanks for xiongzubiao.
> Sorry I miss to specify `--resume` to the `train_net.py` to load the model.
> but I suggest the documentation could be more clear for metric evaluations.

hello，could you tell me how to solve that problem? 您好，請問您後來是如何解決這個問題的？
