### ISSUE TITLE
PointRend custom dataset problem - KeyError: 1

### ISSUE THREAD

**Issue by Adblu** [facebookresearch/detectron2#1893]
I want to train the model using pointrend on my own custom dataset which has only 1 class.
As you describes in: 

```
python train_net.py --config-file configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_1x_coco.yaml --num-gpus 8
```
Here is the directory structure:
└── custom_dataset
    ├── annotations
    ├── train
    └── val

Dataset is correctly registered by:
```
register_coco_instances("xlass_x", {}, "/home/user/car/datasets/xlass_x/annotations/train.json",
                                "/home/user/car/datasets/xlass_x/train/")
```
which is in main():

Im getting strange error:

```
Traceback (most recent call last):
  File "train_net.py", line 143, in <module>
    args=(args,),
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/engine/launch.py", line 54, in launch
    daemon=False,
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/engine/launch.py", line 89, in _distributed_worker
    main_func(*args)
  File "/home/user/car/train_net.py", line 129, in main
    trainer = Trainer(cfg)
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 276, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/user/car/train_net.py", line 91, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/build.py", line 297, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/catalog.py", line 62, in get
    return f()
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/datasets/register_coco.py", line 37, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/detectron2/data/datasets/coco.py", line 66, in load_coco_json
    cats = coco_api.loadCats(cat_ids)
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/pycocotools/coco.py", line 220, in loadCats
    return [self.cats[id] for id in ids]
  File "/home/user/anaconda3/envs/car/lib/python3.7/site-packages/pycocotools/coco.py", line 220, in <listcomp>
    return [self.cats[id] for id in ids]
KeyError: 1

```

Here is the full log:
https://paste.ofcode.org/rAm24rXCyWTeQMdqMC8H49

What might be the reason of this error ? I have successfully registered the dataset.

**Comment by ppwwyyxx** [comment]
`load_coco_json(json_file, image_root, name)` failed which means the json file is probably not in correct COCO format.
