### ISSUE TITLE
Exporting Torch script for the custom dataset fails with the error RuntimeError: [enforce fail at batch_permutation_op.cu:66] X.dim32(0) > 0. 0 vs 0

### ISSUE THREAD

**Issue by harishkool** [facebookresearch/detectron2#1915]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
Trained the custom dataset by following the tutorial in this colab https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
and saved the weights as 'model_final.pth' file.
```
2. what exact command you run:
`python export_jit.py --format torchscript --output /home/hxk/Downloads/detectron2/output_jit --model model_path --config_file configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml`

3. what you observed (including __full logs__):
```
/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/jit/__init__.py:863: UserWarning: `optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead    
  warnings.warn("`optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead")                                                                                              
/home/hxk/Downloads/detectron2/detectron2/export/c10.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so $
his value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!                                                                                        
  assert tensor.dim() == 2 and tensor.size(-1) in [4, 5, 6], tensor.size()                                                                                                                                    
/home/hxk/Downloads/detectron2/detectron2/export/c10.py:370: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so 
this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!                                                                                       
  assert box_regression.shape[1] % box_dim == 0
/home/hxk/Downloads/detectron2/detectron2/export/c10.py:377: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so
this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_tensor_mode:
/home/hxk/Downloads/detectron2/detectron2/export/c10.py:424: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so
this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  legacy_plus_one=False,
/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/tensor.py:467: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape $on't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/hxk/Downloads/detectron2/detectron2/export/c10.py:438: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so $his value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i, b in enumerate(int(x.item()) for x in roi_batch_splits_nms)
Traceback (most recent call last):
  File "export_jit.py", line 117, in <module>
    script_model = tracer.export_torchscript()
  File "/home/hxk/Downloads/detectron2/detectron2/export/api.py", line 140, in export_torchscript
    return torch.jit.trace(model, (inputs,), optimize=True)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/jit/__init__.py", line 1027, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/hxk/Downloads/detectron2/detectron2/export/caffe2_modeling.py", line 272, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/hxk/Downloads/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 676, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/home/hxk/Downloads/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 702, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/home/hxk/Downloads/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 776, in _forward_mask
    mask_features = self.mask_pooler(features, pred_boxes)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/hxk/Downloads/detectron2/detectron2/export/c10.py", line 341, in forward
    roi_feat = torch.ops._caffe2.BatchPermutation(roi_feat_shuffled, rois_idx_restore_int32)
RuntimeError: [enforce fail at batch_permutation_op.cu:66] X.dim32(0) > 0. 0 vs 0
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
```
1. Trained the model with the custom dataset using the config file configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml.
2. Saved the weights in modelf_final.pth file.
3. Exporting a torch script using these saved weights.
4. Working as expected when I export the torch script for the models provided by detectron2 like detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl.
5. Already doing the thing mentioned here https://github.com/facebookresearch/detectron2/issues/1566
```

## Expected behavior:
Traced model of the model trained with the custom dataset

## Environment:

Provide your environment information using the following command:
```

sys.platform            linux
Python                  3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
numpy                   1.18.5
detectron2              0.1.3 @/home/hxk/Downloads/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.5.1 @/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce RTX 2080 Ti
CUDA_HOME               /usr/local/cuda-10.1
Pillow                  7.2.0
torchvision             0.6.0a0+35d732a @/home/hxk/miniconda3/envs/pytorch_latest/lib/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200630
cv2                     4.3.0
----------------------  -------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
Please find existing issues at https://github.com/facebookresearch/detectron2/issues?q=%5Benforce+fail+at+batch_permutation_op.cu%3A66%5D+X.dim32%280%29+%3E+0.+0+vs+0
