### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by anthonymakela** [facebookresearch/detectron2#1917]
I keep running to the following error whilst trying to train a model on Colab. 

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-49586a36f2d4> in <module>()
     15 cfg.TEST.EVAL_PERIOD = 500
     16 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
---> 17 trainer = CocoTrainer(cfg)
     18 trainer.resume_or_load(resume=False)
     19 trainer.train()

6 frames
/usr/local/lib/python3.6/dist-packages/detectron2/data/build.py in short_name(x)
    172     def short_name(x):
    173         # make long class names shorter. useful for lvis
--> 174         if len(x) > 13:
    175             return x[:11] + ".."
    176         return x

TypeError: object of type 'int' has no len()
```

The output is from the following cell:

```python
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("fplan_detect_train",)
cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.0125 
cfg.SOLVER.MAX_ITER = 1500   
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256  
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 20
cfg.TEST.EVAL_PERIOD = 500
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = CocoTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

Also my dicts looks as follows:

```python
{'annotations': [{'bbox': [129, 153, 129, 177],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 7,
   'segmentation': []},
  {'bbox': [169, 318, 169, 349],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 2,
   'segmentation': []},
  {'bbox': [212, 158, 212, 168],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 0,
   'segmentation': []},
  {'bbox': [226, 219, 226, 242],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 3,
   'segmentation': []},
  {'bbox': [162, 85, 162, 85],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [129, 258, 129, 258],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [170, 149, 170, 193],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [243, 258, 243, 258],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [103, 85, 103, 85],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [194, 435, 194, 435],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [140, 435, 140, 435],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 5,
   'segmentation': []},
  {'bbox': [257, 85, 257, 85],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [257, 85, 257, 435],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [257, 435, 257, 435],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [24, 85, 24, 435],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [257, 258, 257, 258],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [170, 85, 170, 200],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [138, 200, 138, 258],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [257, 200, 257, 200],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': []},
  {'bbox': [63, 89, 63, 193],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 4,
   'segmentation': []},
  {'bbox': [251, 89, 251, 144],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 1,
   'segmentation': []},
  {'bbox': [251, 131, 251, 162],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 10,
   'segmentation': []},
  {'bbox': [252, 168, 252, 197],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 8,
   'segmentation': []},
  {'bbox': [59, 193, 59, 222],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 10,
   'segmentation': []},
  {'bbox': [165, 89, 165, 125],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 6,
   'segmentation': []}],
 'file_name': 'fplan_data/floorplan_image/train/0001.jpg',
 'height': 480,
 'image_id': 1,
 'width': 278}
```

What could be the cause of this? This doesn't seem very rational to be crashing the whole training due to "large class names".

**Comment by ppwwyyxx** [comment]
The registered dataset or metadata is in wrong format.
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by anthonymakela** [comment]
The dataset passes through the Visualizer without exceptions. One could assume that if the format was wrong this wouldn't be possible.

**Comment by ppwwyyxx** [comment]
The assumption may not be right.

**Comment by anthonymakela** [comment]
@ppwwyyxx It doesn't seem that the dataset would be in the wrong format. The following sample from a different dataset passes through as expected

```python
{'annotations': [{'bbox': [903, 162, 985, 252],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 0,
   'iscrowd': 0,
   'segmentation': [[903, 162, 985, 162, 985, 252, 903, 252]]}],
 'file_name': 'faces/face_1.jpeg',
 'height': 697,
 'image_id': 1,
 'width': 1280}
```

and I don't see any difference between this and the one I'm using except the empty `segmentation` and missing `iscrowd` which both seem to be optional(?). Also, my `segmentation` value is not a `list[list[float]]`, but a `[list[float]]`, however changing this didn't make any difference whatsoever.

```python
{'annotations': [{'bbox': [391.7503926822,
    139.1115217592,
    491.7503926822,
    189.1115217592],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 9,
   'segmentation': [[]]},
  {'bbox': [631.0, 212.0, 678.0, 252.0],
   'bbox_mode': <BoxMode.XYXY_ABS: 0>,
   'category_id': 13,
   'segmentation': [[]]}],
 'file_name': 'fplan_data/floorplan_image/train/0000.jpg',
 'height': 631,
 'image_id': 0,
 'width': 800}
```

**Comment by anthonymakela** [comment]
Converting `category_id` to `str` serializes the dataset, but returns the following error

```python
ERROR [08/18 14:07:00 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 220, in run_step
    data = next(self._data_loader_iter)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 142, in __iter__
    for d in self.dataset:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/dataset_mapper.py", line 174, in __call__
    annos, image_shape, mask_format=self.instance_mask_format
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py", line 379, in annotations_to_instances
    classes = torch.tensor(classes, dtype=torch.int64)
ValueError: too many dimensions 'str'
[08/18 14:07:00 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-18b8fc5be08c> in <module>()
     17 trainer = CocoTrainer(cfg)
     18 trainer.resume_or_load(resume=False)
---> 19 trainer.train()

11 frames
/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py in annotations_to_instances(annos, image_size, mask_format)
    377 
    378     classes = [obj["category_id"] for obj in annos]
--> 379     classes = torch.tensor(classes, dtype=torch.int64)
    380     target.gt_classes = classes
    381 

ValueError: too many dimensions 'str'
```

which is expected since the documentation states that `category_id` should be `int`.

**Comment by anthonymakela** [comment]
Problem solved, `thing_classes` has to be an `str`.
