### ISSUE TITLE
'Non-existent config key: MODEL.PROPOSAL_GENERATOR.HID_CHANNELS'Please read & provide the following

### ISSUE THREAD

**Issue by mamingyang112** [facebookresearch/detectron2#1927]
Config '../configs/VG-Detection/faster_rcnn_R_101_C4_caffe.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo_feature_extraction.py", line 46, in <module>
    cfg.merge_from_file("../configs/VG-Detection/faster_rcnn_R_101_C4_caffe.yaml")
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/detectron2/config/config.py", line 49, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/fvcore/common/config.py", line 120, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/admin/anaconda3/envs/python3.6/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.PROPOSAL_GENERATOR.HID_CHANNELS'

after I delete the wrong key in yaml, the predict result is wrong. How can I with it with out changing the version
torch                     1.5.1+cu101
torchvision               0.6.1+cu101
detectron2                0.2.1

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
