### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1 (while training detectron2 for 294 classes)

### ISSUE THREAD

**Issue by amrahsmaytas** [facebookresearch/detectron2#1971]
1. full code you wrote or full changes you made (`git diff`)
```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("4sample_fashion_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.DEVICE = "cuda"
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml") 
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 10
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 294 
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = FashionTrainer(cfg) 
trainer.resume_or_load(resume=False)

```
2. what exact command you run:

trainer.train()

3. __full logs__ you observed:
```
[08/27 17:06:33 d2.engine.train_loop]: Starting training from iteration 0
ERROR [08/27 17:06:34 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 226, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 666, in forward
    losses = self._forward_box(features, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 733, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 467, in losses
    self.box_reg_loss_type,
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 321, in losses
    return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 229, in softmax_cross_entropy_loss
    self._log_accuracy()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 206, in _log_accuracy
    fg_pred_classes = pred_classes[fg_inds]
IndexError: too many indices for tensor of dimension 1
[08/27 17:06:34 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    139                     self.before_step()
--> 140                     self.run_step()
    141                     self.after_step()

14 frames
IndexError: too many indices for tensor of dimension 1

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/detectron2/engine/hooks.py in after_train(self)
    352         # func is likely a closure that holds reference to the trainer
    353         # therefore we clean it to avoid circular reference in the end
--> 354         del self._func
    355 
    356 

AttributeError: _func
```

## Expected behavior:

I expect my model to start training normally on the registered dataset  for 294 classes

## Environment:

Provide your environment information using the following command:
```
detectron2-0.2.1+cu101
torch.__version__ = 1.6.0+cu101

```

##  This is my first time, raising issues on Github, so, I may miss some of the guidelines, but feel free to ask for more info or for discussion!

**Comment by MathijsNL** [comment]
Hi,

Can you print out the MetaData from your dataset?

```
metadatadict = MetadataCatalog.get("4sample_fashion_train").as_dict()
print(len(metadatadict["thing_classes"]))
```
This will show you the number of classes you have which should be 294. If the number is the same then you can rule this out, if not the same this is your problem.

**Comment by amrahsmaytas** [comment]
Hi, 
I tried running the code :

```
metadatadict = MetadataCatalog.get("4sample_fashion_train").as_dict()
print(len(metadatadict["thing_classes"]))

```
OUTPUT: 294 same as the NUM CLASSES used

Getting the same error : 
IndexError: too many indices for tensor of dimension 1

**Comment by ppwwyyxx** [comment]
Most likely the dataset format is wrong. However, not knowing how to reproduce the error we cannot tell how it is wrong. You may double check with https://detectron2.readthedocs.io/tutorials/datasets.html

**Comment by MathijsNL** [comment]
Could you share your dataset if possible, or a small anonimized sample to take a look at?

**Comment by amrahsmaytas** [comment]
Thanks for the guidance, its a dataset format issue
