### ISSUE TITLE
Can't Evaluate a Model Trained With Pytorch 1.6 under Pytorch 1.4 env, but the opposite works

### ISSUE THREAD

**Issue by CMobley7** [facebookresearch/detectron2#1972]
**Describe the bug**
When I train a model under Detection2 0.2.1 with Pytorch 1.6 and Torchvision 0.7.0 using Detection2's train_net.py script, I can't evaluate or run inference on said model if Pytorch and Torchvision are downgraded to 1.4 and 0.5.0 respectively. I don't believe this was an issue when downgrading from Pytorch 1.5 and Torchvision 0.6.1 to Pytorch 1.4 and Torchvision 0.5.0, but I'll recheck this. When I try to run evaluation using Detection2's train_net.py script, I receive the error below. Is this not possible and if so is there a way to make it possible? I can do the opposite, as in evaluate and perform inference using a model trained under Pytorch 1.4 and Torchvision 0.5.0 under an environment with Pytorch 1.6 and Torchvision 0.7.0. Thanks in advance!
 
```
Traceback (most recent call last):
  File "/podc/src/detectron2/tools/train_net.py", line 181, in <module>
    args=(args,),
  File "/podc/src/detectron2/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/podc/src/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/podc/src/detectron2/tools/train_net.py", line 149, in main
    cfg.MODEL.WEIGHTS, resume=args.resume
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py", line 189, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py", line 117, in load
    checkpoint = self._load_file(path)
  File "/podc/src/detectron2/detectron2/checkpoint/detection_checkpoint.py", line 42, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/checkpoint.py", line 213, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2a1d56d193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f29369669eb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2936967c04 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c53a6 (0x7f2a1e6163a6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x7f2a1e1e71c4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallDict + 0x35c (0x566ddc in /usr/bin/python3)
frame #6: /usr/bin/python3() [0x594b71]
frame #7: /usr/bin/python3() [0x54a325]
frame #8: /usr/bin/python3() [0x5517c1]
frame #9: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #10: /usr/bin/python3() [0x50a783]
frame #11: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #12: /usr/bin/python3() [0x507f24]
frame #13: _PyFunction_FastCallDict + 0x2e2 (0x509202 in /usr/bin/python3)
frame #14: /usr/bin/python3() [0x594b01]
frame #15: /usr/bin/python3() [0x54a17f]
frame #16: /usr/bin/python3() [0x5517c1]
frame #17: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x50a783]
frame #19: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #20: /usr/bin/python3() [0x507f24]
frame #21: /usr/bin/python3() [0x509c50]
frame #22: /usr/bin/python3() [0x50a64d]
frame #23: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #24: /usr/bin/python3() [0x509918]
frame #25: /usr/bin/python3() [0x50a64d]
frame #26: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #27: /usr/bin/python3() [0x507f24]
frame #28: /usr/bin/python3() [0x509c50]
frame #29: /usr/bin/python3() [0x50a64d]
frame #30: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #31: /usr/bin/python3() [0x507f24]
frame #32: /usr/bin/python3() [0x509c50]
frame #33: /usr/bin/python3() [0x50a64d]
frame #34: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x507f24]
frame #36: /usr/bin/python3() [0x509c50]
frame #37: /usr/bin/python3() [0x50a64d]
frame #38: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #39: /usr/bin/python3() [0x507f24]
frame #40: /usr/bin/python3() [0x588ddb]
frame #41: PyObject_Call + 0x3e (0x59fe1e in /usr/bin/python3)
frame #42: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in /usr/bin/python3)
frame #43: /usr/bin/python3() [0x507f24]
frame #44: /usr/bin/python3() [0x588ddb]
frame #45: PyObject_Call + 0x3e (0x59fe1e in /usr/bin/python3)
frame #46: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in /usr/bin/python3)
frame #47: /usr/bin/python3() [0x507f24]
frame #48: /usr/bin/python3() [0x588e91]
frame #49: PyObject_Call + 0x3e (0x59fe1e in /usr/bin/python3)
frame #50: _PyEval_EvalFrameDefault + 0x17e6 (0x50d596 in /usr/bin/python3)
frame #51: /usr/bin/python3() [0x509918]
frame #52: /usr/bin/python3() [0x50a64d]
frame #53: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #54: /usr/bin/python3() [0x509918]
frame #55: /usr/bin/python3() [0x50a64d]
frame #56: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #57: /usr/bin/python3() [0x509918]
frame #58: /usr/bin/python3() [0x50a64d]
frame #59: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #60: /usr/bin/python3() [0x507f24]
frame #61: /usr/bin/python3() [0x509c50]
frame #62: /usr/bin/python3() [0x50a64d]
frame #63: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
```

**Environment**
Included below is the environment I was using to evaluate. It should be the same as the one used to train under but just different versions of PyTorch and Torchvision.
```
----------------------  ---------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy                   1.19.1
detectron2              0.2 @/podc/src/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 Tesla P100-SXM2-16GB
CUDA_HOME               /usr/local/cuda
TORCH_CUDA_ARCH_LIST    3.5 3.7 5.0 5.2 5.3 6.0 6.1 6.2 7.0+PTX 7.2+PTX 7.5+PTX
Pillow                  7.2.0
torchvision             0.5.0 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200716
----------------------  ---------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
PyTorch cannot load a model saved by future versions of PyTorch
