### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by shijing001** [facebookresearch/detectron2#2011]
When I try to reproduce the R50-C4 model by running the command line

python tools/train_net.py --config-file configs/Base-RCNN-C4.yaml --num-gpus 2 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025

I got error: dataset not found
Traceback (most recent call last):
  File "tools/train_net.py", line 169, in <module>
    args=(args,),
  File "/home/appuser/detectron2_repo/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/appuser/detectron2_repo/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/appuser/detectron2_repo/tools/train_net.py", line 151, in main
    trainer = Trainer(cfg)
  File "/home/appuser/detectron2_repo/detectron2/engine/defaults.py", line 277, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/appuser/detectron2_repo/detectron2/engine/defaults.py", line 452, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/home/appuser/detectron2_repo/detectron2/data/build.py", line 326, in build_detection_train_loader
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/home/appuser/detectron2_repo/detectron2/data/build.py", line 219, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/appuser/detectron2_repo/detectron2/data/build.py", line 219, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/appuser/detectron2_repo/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/home/appuser/detectron2_repo/detectron2/data/datasets/register_coco.py", line 37, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/appuser/detectron2_repo/detectron2/data/datasets/coco.py", line 58, in load_coco_json
    coco_api = COCO(json_file)
  File "/home/appuser/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/coco/annotations/instances_train2017.json'

I tried to export DETECTRON2_DATASETS= ./datasets... Still doesn't work

**Comment by MathijsNL** [comment]
> python tools/train_net.py --config-file configs/Base-RCNN-C4.yaml \\
--num-gpus 2 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025

The config files are located in the parent directory

```
python tools/train_net.py --config-file ../configs/Base-RCNN-C4.yaml --num-gpus 2 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
```

For more information see [tutorials/getting_started.html](https://detectron2.readthedocs.io/tutorials/getting_started.html#training-evaluation-in-command-line)

**Comment by ppwwyyxx** [comment]
See https://detectron2.readthedocs.io/tutorials/builtin_datasets.html
