### ISSUE TITLE
No such file or directory issue in training code

### ISSUE THREAD

**Issue by ousim97** [facebookresearch/detectron2#2045]
Hello,

After I run the following code to train my dataset:

`from detectron2.engine import DefaultTrainer
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("/content/images/train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()`

I get the following error even if my images are in the right directory:

`FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/dataset_mapper.py", line 123, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.image_format)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py", line 175, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py", line 649, in open
    path, mode, buffering=buffering, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/fvcore/common/file_io.py", line 383, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: '6215.jpg'`

Please note that everytime, the error is changing to another jpeg file.

Can you tell me how to solve this please?

Thanks in advance

**Comment by ousim97** [comment]
**EDIT:** 
Problem solved, I had to write all the directory of my images.
Thanks anyway :)
