### ISSUE TITLE
How to debug with detectron2 under single gpu

### ISSUE THREAD

**Issue by trevor-taeyeop** [facebookresearch/detectron2#2115]
Thanks for sharing the good work. 
I tried to debugging in the pycharm using a single gpu 
There are some related issues, but I couldn't find how to handle.
https://github.com/facebookresearch/detectron2/issues/882 https://github.com/facebookresearch/detectron2/issues/1598

Can you share how to solve this problem?? 
It would be appreciated if you let me know what needs to be changed for debug
 

**[Command]**
```
./train_net.py \
--num-gpus 1 --config-file \
 ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
SOLVER.IMS_PER_BATCH 1
```

**[Error Message]**
```
[10/09 01:43:02 d2.engine.train_loop]: Starting training from iteration 0
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
ERROR [10/09 01:43:27 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 5161) is killed by signal: Aborted. 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 142, in train
    self.run_step()
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 229, in run_step
    data = next(self._data_loader_iter)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 5161) exited unexpectedly
[10/09 01:43:27 d2.engine.hooks]: Total training time: 0:00:25 (0:00:00 on hooks)
[10/09 01:43:27 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 238M
python-BaseException
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 5161) is killed by signal: Aborted. 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 142, in train
    self.run_step()
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 229, in run_step
    data = next(self._data_loader_iter)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 5161) exited unexpectedly
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

```

**Comment by ppwwyyxx** [comment]
It seems pycharm is unable to debug parallel programs. you can disable parallel data loading  by `DATALOADER.NUM_WORKERS 0`

**Comment by trevor-taeyeop** [comment]
Thanks, it really works well.
