### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got int

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#2151]
Dear all, 
I used detectron2 for months, everything works well, but suddenly today when inference maskrcnnr50fpn3x on an image I got error: 
`TypeError: expected Tensor as element 0 in argument 0, but got int
`
## Instructions To Reproduce the Issue:
I make a clear installation by cloning detectron2 from github and install it following INSTALL.md.
I test a demo as instructions at https://detectron2.readthedocs.io/tutorials/getting_started.html
1. full code you wrote or full changes you made (`git diff`)
I don' change anything.
I download this image and put in it detectron2/demo/download.png
![download](https://user-images.githubusercontent.com/25927039/96577344-7b252a80-12a1-11eb-9671-7263db3b3edc.png)

2. what exact command you run:
```
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input ./download.png  --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
3. __full logs__ you observed:
```
[10/20 06:48:24 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['./download.png'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
[10/20 06:48:25 fvcore.common.checkpoint]: Loading checkpoint from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[10/20 06:48:25 fvcore.common.file_io]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl cached in /home/n/.torch/fvcore_cache/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
[10/20 06:48:25 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
Traceback (most recent call last):
  File "demo.py", line 92, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/n/detectron2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/n/detectron2/detectron2/engine/defaults.py", line 223, in __call__
    predictions = self.model([inputs])[0]
  File "/home/n/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/n/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/home/n/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 196, in inference
    images = self.preprocess_image(batched_inputs)
  File "/home/n/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 222, in preprocess_image
    images = ImageList.from_tensors(images, self.backbone.size_divisibility)
  File "/home/n/detectron2/detectron2/structures/image_list.py", line 85, in from_tensors
    image_sizes = tuple(torch.stack(x) for x in image_sizes)
  File "/home/n/detectron2/detectron2/structures/image_list.py", line 85, in <genexpr>
    image_sizes = tuple(torch.stack(x) for x in image_sizes)
TypeError: expected Tensor as element 0 in argument 0, but got int
```

## Environment:

Provide your environment information using the following command:
```
(base) n@n:~/detectron2$ wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
Traceback (most recent call last):
  File "collect_env.py", line 187, in <module>
    print(collect_env_info())
  File "/home/n/detectron2/detectron2/utils/collect_env.py", line 136, in collect_env_info
    msg = " - invalid!" if not os.path.isdir(CUDA_HOME) else ""
  File "/home/n/anaconda3/lib/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```
Maybe this relates to my own machine environment.
Any suggestion?
Thanks,

**Comment by pvtien96** [comment]
Yes! I got it. This relate to the latest commit 1081708. When I git checkout e883afb9afe2b5196b7cba7485583a1d063a9991 it works!
Please fix this!

**Comment by benski2011** [comment]
> 
> 
> Yes! I got it. This relate to the latest commit [1081708](https://github.com/facebookresearch/detectron2/commit/1081708f67826ae8fe4ae39f4d65e3fbd80fa8da). When I git checkout [e883afb](https://github.com/facebookresearch/detectron2/commit/e883afb9afe2b5196b7cba7485583a1d063a9991) it works!
> Please fix this!

how do i checkout a spesific commit in google colab?

**Comment by ppwwyyxx** [comment]
Thanks for reporting! #2158 will fix the version requirement.
