### ISSUE TITLE
Default process group is not initialized

### ISSUE THREAD

**Issue by aabbas90** [facebookresearch/detectron2#2174]
## Instructions To Reproduce the 🐛 Bug:

1. Call any training code with num_gpus = 1, and num_machines=1. Gives the following error:

```
Traceback (most recent call last):
  File "train_net.py", line 172, in <module>
    args=(args,),
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net.py", line 160, in main
    return trainer.train()
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/engine/defaults.py", line 410, in train
    super().train(self.start_iter, self.max_iter)
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/engine/train_loop.py", line 142, in train
    self.run_step()
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/engine/train_loop.py", line 235, in run_step
    loss_dict = self.model(data)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/panoptic_seg.py", line 87, in forward
    features = self.backbone(images.tensor)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/modeling/backbone/resnet.py", line 432, in forward
    x = self.stem(x)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/projects/DeepLab/deeplab/resnet.py", line 59, in forward
    x = self.conv1(x)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/BS/ahmed_projects/work/projects/conseg/depends/detectron2/detectron2/layers/wrappers.py", line 106, in forward
    x = self.norm(x)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 493, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 620, in get_world_size
    return _get_group_size(group)
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 219, in _get_group_size
    _check_default_pg()
  File "/home/ahabbas/software/anaconda3/envs/conseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

```

## Possible fix:
The error goes away when I change `>1` to `>=1` at:
https://github.com/facebookresearch/detectron2/blob/200c66e7a9ece92e6fb7f78856b9fd3ca5eb1925/detectron2/engine/launch.py#L41

**Comment by ppwwyyxx** [comment]
SyncBatchNorm cannot run on 1 GPU by its definition.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
