### ISSUE TITLE
How to Generate ScriptModule with torch.jit.trace for MaskRcnn

### ISSUE THREAD

**Issue by lsy643** [facebookresearch/detectron2#2175]
## ❓ How to Generate ScriptModule with torch.jit.trace for MaskRcnn

I want to deploy the Models trained by Detectron2 with TVM, and the first step is using `torch.jit.trace` to create the ScriptModule.

The script I use
```
import torch
from detectron2.config import get_cfg
from detectron2 import model_zoo

class TraceWrapper(torch.nn.Module):
    def __init__(self, model, height, width):
        super().__init__()
        self.model = model
        self.height = height
        self.width = width

    def forward(self, inp):
        inputs = {"image": inp, "height": self.height, "width": self.width}
        #out = self.model(inp)
        predictions = self.model([inputs])[0]
        instances = predictions['instances']
        return instances.pred_classes, instances.pred_boxes.tensor, instances.scores

def get_test_image(cfg):
    original_image = cv2.imread("data/000000439715.jpg")
    aug = T.ResizeShortestEdge(
        [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
    )
    height, width = original_image.shape[:2]
    image = aug.get_transform(original_image).apply_image(original_image)
    image = image.astype("float32").transpose(2, 0, 1)
    return image, height, width

def main():
    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
    
    predictor = DefaultPredictor(cfg)

    org_image, height, width = get_test_image(cfg)
    image = torch.as_tensor(org_image)


    trace_wrapper_model = TraceWrapper(predictor.model, height, width)
    trace_wrapper_model.eval()

    with torch.no_grad():
        model_trace = torch.jit.trace(trace_wrapper_model, image)
        model_trace.eval()


if __name__ == '__main__':
    main()

```

The error I get
```
Traceback (most recent call last):
  File "mask_rcnn_lab.py", line 92, in <module>
    det_lab()
  File "mask_rcnn_lab.py", line 79, in det_lab
    model_trace = torch.jit.trace(trace_wrapper_model, image)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1119, in trace_module
    check_tolerance, strict, _force_outplace, True, _module_class)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 736, in _check_trace
    if compare_outputs(traced_outs, fn_outs, 'Python function'):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 724, in compare_outputs
    atol=torch.testing._get_default_tolerance(orig, ref)[1])
  File "/root/anaconda3/lib/python3.7/site-packages/torch/testing/__init__.py", line 207, in assert_allclose
    expected = expected.expand_as(actual)
RuntimeError: The expanded size of the tensor (0) must match the existing size (15) at non-singleton dimension 0.  Target sizes: [0].  Tensor sizes: [15]

```

**Comment by ppwwyyxx** [comment]
Tracing is not yet an officially supported feature.
However it can work correctly if you:
* use github master of detectron2
* use github master of pytorch
* call `jit.trace` under this context: https://github.com/facebookresearch/detectron2/blob/d35c3c36dcee1b01faf46144625193f8979996d2/detectron2/export/torchscript_patch.py#L182-L184

Or use the caffe2 tracer described in https://detectron2.readthedocs.io/tutorials/deployment.html - in that case the resulting graph will contain many ops not yet supported by tvm or any other runtime that's not caffe2.
