### ISSUE TITLE
RETINA NET fails to train in different environment

### ISSUE THREAD

**Issue by youssefoum** [facebookresearch/detectron2#2222]
## Issue

1. Full runnable code or full changes you made:
I use the same Detectron2 Beginner tutorial https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 with two modifications:
 -RetinaNet pretrained model
 -Different Environment (Please check the environment section)
```
from detectron2.engine import DefaultTrainer
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/retinanet_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("balloon_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/retinanet_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.MODEL.RETINANET.NUM_CLASSES = 1 
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```
2. What exact command you run:
I use Jupyter notebook
3. __Full logs__ you observed:
```
[11/02 16:04:36 d2.engine.defaults]: Model:
RetinaNet(
  (backbone): FPN(
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelP6P7(
      (p6): Conv2d(2048, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (p7): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    )
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (head): RetinaNetHead(
    (cls_subnet): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU()
      (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU()
      (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (5): ReLU()
      (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU()
    )
    (bbox_subnet): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU()
      (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU()
      (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (5): ReLU()
      (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU()
    )
    (cls_score): Conv2d(256, 720, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bbox_pred): Conv2d(256, 36, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (anchor_generator): DefaultAnchorGenerator(
    (cell_anchors): BufferList()
  )
)
[11/02 16:04:37 d2.data.build]: Removed 0 images with no usable annotations. 61 images left.
[11/02 16:04:37 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|  balloon   | 255          |
|            |              |
[11/02 16:04:37 d2.data.common]: Serializing 61 elements to byte tensors and concatenating them all ...
[11/02 16:04:37 d2.data.common]: Serialized dataset takes 0.17 MiB
[11/02 16:04:37 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[11/02 16:04:37 d2.data.build]: Using training sampler TrainingSampler
[11/02 16:04:37 d2.engine.train_loop]: Starting training from iteration 0
/home/youssef/.local/lib/python3.6/site-packages/detectron2/layers/wrappers.py:125: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  return x.nonzero().unbind(1)
ERROR [11/02 16:04:38 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/youssef/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/home/youssef/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/home/youssef/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/home/youssef/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/youssef/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 260, in forward
    losses = self.losses(anchors, pred_logits, gt_labels, pred_anchor_deltas, gt_boxes)
  File "/home/youssef/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 323, in losses
    reduction="sum",
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void func_1(float* t0, float v1, float* t2, float* t3, float* aten_mul_flat, float* aten_pow_flat, float* aten_add_flat, float* aten_add_flat_1, float* aten_add_flat_2, float* aten_sigmoid_flat) {
{
  if (512 * blockIdx.x + threadIdx.x<22944720 ? 1 : 0) {
    float v = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    aten_sigmoid_flat[512 * blockIdx.x + threadIdx.x] = 1.f / (1.f + (expf(0.f - v)));
    float v_1 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat_1[512 * blockIdx.x + threadIdx.x] = (0.f - v_1) + 1.f;
    float v_2 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat_2[512 * blockIdx.x + threadIdx.x] = (0.f - 1.f / (1.f + (expf(0.f - v_2)))) + 1.f;
    float v_3 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_4 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_5 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_6 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat[512 * blockIdx.x + threadIdx.x] = (0.f - ((1.f / (1.f + (expf(0.f - v_3)))) * v_4 + ((0.f - 1.f / (1.f + (expf(0.f - v_5)))) + 1.f) * ((0.f - v_6) + 1.f))) + 1.f;
    float v_7 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_8 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_9 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_10 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_pow_flat[512 * blockIdx.x + threadIdx.x] = powf((0.f - ((1.f / (1.f + (expf(0.f - v_7)))) * v_8 + ((0.f - 1.f / (1.f + (expf(0.f - v_9)))) + 1.f) * ((0.f - v_10) + 1.f))) + 1.f, v1);
    float v_11 = __ldg(t0 + 512 * blockIdx.x + threadIdx.x);
    float v_12 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_13 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_14 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_15 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_mul_flat[512 * blockIdx.x + threadIdx.x] = v_11 * (powf((0.f - ((1.f / (1.f + (expf(0.f - v_12)))) * v_13 + ((0.f - 1.f / (1.f + (expf(0.f - v_14)))) + 1.f) * ((0.f - v_15) + 1.f))) + 1.f, v1));
  }
}
}

[11/02 16:04:38 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[11/02 16:04:38 d2.utils.events]:  iter: 1  total_loss: 3.28  loss_cls: 3.152  loss_box_reg: 0.1277  data_time: 0.1314  lr: 2.5e-07  max_mem: 2639M
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-eecc611b341a> in <module>
     16 trainer = DefaultTrainer(cfg)
     17 trainer.resume_or_load(resume=False)
---> 18 trainer.train()

~/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py in train(self)
    411             OrderedDict of results, if evaluation is enabled. Otherwise None.
    412         """
--> 413         super().train(self.start_iter, self.max_iter)
    414         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    415             assert hasattr(

~/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    132                 for self.iter in range(start_iter, max_iter):
    133                     self.before_step()
--> 134                     self.run_step()
    135                     self.after_step()
    136                 # self.iter == max_iter can be used by `after_train` to

~/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py in run_step(self)
    421     def run_step(self):
    422         self._trainer.iter = self.iter
--> 423         self._trainer.run_step()
    424 
    425     @classmethod

~/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py in run_step(self)
    226         If you want to do something with the losses, you can wrap the model.
    227         """
--> 228         loss_dict = self.model(data)
    229         losses = sum(loss_dict.values())
    230 

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/retinanet.py in forward(self, batched_inputs)
    258 
    259             gt_labels, gt_boxes = self.label_anchors(anchors, gt_instances)
--> 260             losses = self.losses(anchors, pred_logits, gt_labels, pred_anchor_deltas, gt_boxes)
    261 
    262             if self.vis_period > 0:

~/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/retinanet.py in losses(self, anchors, pred_logits, gt_labels, pred_anchor_deltas, gt_boxes)
    321             alpha=self.focal_loss_alpha,
    322             gamma=self.focal_loss_gamma,
--> 323             reduction="sum",
    324         )
    325 

RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void func_1(float* t0, float v1, float* t2, float* t3, float* aten_mul_flat, float* aten_pow_flat, float* aten_add_flat, float* aten_add_flat_1, float* aten_add_flat_2, float* aten_sigmoid_flat) {
{
  if (512 * blockIdx.x + threadIdx.x<22944720 ? 1 : 0) {
    float v = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    aten_sigmoid_flat[512 * blockIdx.x + threadIdx.x] = 1.f / (1.f + (expf(0.f - v)));
    float v_1 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat_1[512 * blockIdx.x + threadIdx.x] = (0.f - v_1) + 1.f;
    float v_2 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat_2[512 * blockIdx.x + threadIdx.x] = (0.f - 1.f / (1.f + (expf(0.f - v_2)))) + 1.f;
    float v_3 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_4 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_5 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_6 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_add_flat[512 * blockIdx.x + threadIdx.x] = (0.f - ((1.f / (1.f + (expf(0.f - v_3)))) * v_4 + ((0.f - 1.f / (1.f + (expf(0.f - v_5)))) + 1.f) * ((0.f - v_6) + 1.f))) + 1.f;
    float v_7 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_8 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_9 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_10 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_pow_flat[512 * blockIdx.x + threadIdx.x] = powf((0.f - ((1.f / (1.f + (expf(0.f - v_7)))) * v_8 + ((0.f - 1.f / (1.f + (expf(0.f - v_9)))) + 1.f) * ((0.f - v_10) + 1.f))) + 1.f, v1);
    float v_11 = __ldg(t0 + 512 * blockIdx.x + threadIdx.x);
    float v_12 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_13 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    float v_14 = __ldg(t3 + 512 * blockIdx.x + threadIdx.x);
    float v_15 = __ldg(t2 + 512 * blockIdx.x + threadIdx.x);
    aten_mul_flat[512 * blockIdx.x + threadIdx.x] = v_11 * (powf((0.f - ((1.f / (1.f + (expf(0.f - v_12)))) * v_13 + ((0.f - 1.f / (1.f + (expf(0.f - v_14)))) + 1.f) * ((0.f - v_15) + 1.f))) + 1.f, v1));
  }
}
}
```

## Expected behavior:
Training the model with no errors

## Environment:

```
----------------------  -------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.3
detectron2              0.2.1 @/home/youssef/.local/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 11.1
detectron2 arch flags   8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0+cu110 @/home/youssef/.local/lib/python3.6/site-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0                   GeForce RTX 3090 (arch=8.6)
GPU 1                   TITAN RTX (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  8.0.1
torchvision             0.8.1+cu110 @/home/youssef/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.2.post20201020
cv2                     4.4.0
----------------------  -------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by ppwwyyxx** [comment]
The environment info shows cuda version mismatch. See https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
