### ISSUE TITLE
Heroku deploy failed

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#2260]
```
remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing python-3.8.6
remote: -----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting git+https://github.com/facebookresearch/detectron2.git (from -r /tmp/build_b3696647/requirements.txt (line 13))
remote:          Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-xohwcfs8
remote:          Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-xohwcfs8
remote:            ERROR: Command errored out with exit status 1:
remote:             command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xohwcfs8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xohwcfs8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mdpjz_by
remote:                 cwd: /tmp/pip-req-build-xohwcfs8/
remote:            Complete output (5 lines):
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-req-build-xohwcfs8/setup.py", line 10, in <module>
remote:                import torch
remote:            ModuleNotFoundError: No module named 'torch'
remote:            ----------------------------------------
remote:        ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected
```

requirements.txt
```
torch
torchvision
git+https://github.com/facebookresearch/detectron2.git
```

**Comment by ppwwyyxx** [comment]
As the error says, it requires pytorch during installation and it doesn't find it.
How to satisfy that requirement is unrelated to this project.

**Comment by chiboreache** [comment]
@ppwwyyxx since Heroku is the most popular free Python hosting, would be nice to have some info in docs

or maybe even list of best hosting solutions

_____


and the right answer was - move d2 from r.txt to Procfile

```
release: python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
web: gunicorn app:app --log-file=-
```

______

but it failed anyway

```
remote: -----> Compressing...
remote:  !     Compiled slug size: 1.5G is too large (max is 500M).
remote:  !     See: http://devcenter.heroku.com/articles/slug-size
remote: 
remote:  !     Push failed
```
