### ISSUE TITLE
Can't rebuild the build folder after deleting it because of an AssertionError

### ISSUE THREAD

**Issue by MatthiasMatze** [facebookresearch/detectron2#2265]
Hello.

I just installed Detectron2 on Ubuntu 18.04 and tried to run the example from the Getting Started (https://detectron2.readthedocs.io/tutorials/getting_started.html) and got the following error.

```
matthias@matthias:~/detectron2/demo$ python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
>   --input Spitzer.mp4 \
>   --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl 
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from detectron2.config import get_cfg
ImportError: No module named detectron2.config
matthias@matthias:~/detectron2/demo$ 
```

I asked Google to solve this and it showed me this which i tried:
https://github.com/facebookresearch/detectron2/issues/600

I used "rm -rf build **/*" and NOT "rm -rf build **/*.so" to delete the built folder.
I reinstalled it and got the same error.

Info: This is the installation comand that i used:
`pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

Thank you.

Side Question: Why do i need CUDA, or do i really need it? This is not clear to me.

Best regards
Matthias

**Comment by ppwwyyxx** [comment]
> I just installed Detectron2 on Ubuntu 18.04 

how did you install it? what is the command? what is the output?

Please also include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by MatthiasMatze** [comment]
Hello @ppwwyyxx and Thank you.

I installed it with the (now) 3 commands i already posted:
-I used these two comands to install detectron2:
```
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2
```
-and this one for the prerequisites
`pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

What do you mean with "What is the output?"
The output of the installation process? or the output that showed when i encountered the error (see first post)?

**Comment by ppwwyyxx** [comment]
I mean the output of installation.

Please also include the environment information details following the instructions in the issue template.

**Comment by MatthiasMatze** [comment]
I can't provide you the environment informations because i get an error message

> matthias@matthias:~$ wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
  File "collect_env.py", line 88
    data.append(("detectron2._C", f"not built correctly: {e}"))
                                                            ^
SyntaxError: invalid syntax

Output of the installation process is the following:

```

> matthias@matthias:~$ sudo python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
> 
> The directory '/home/matthias/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/matthias/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting git+https://github.com/facebookresearch/detectron2.git
>   Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-hj0hs4g3-build
> Requirement already satisfied: Pillow>=7.1 in ./.local/lib/python3.6/site-packages (from detectron2==0.3)
> Collecting cloudpickle (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/e7/e3/898487e5dbeb612054cf2e0c188463acb358167fef749c53c8bb8918cea1/cloudpickle-1.6.0-py3-none-any.whl
> Requirement already satisfied: future in ./.local/lib/python3.6/site-packages (from detectron2==0.3)
> Collecting fvcore>=0.1.2 (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/c4/c3/ac3e539a258fe94b92237a6851838c412a440e7b65025becb43135267c7a/fvcore-0.1.2.post20201111.tar.gz
> Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from detectron2==0.3)
> Collecting pycocotools>=2.0.2 (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/de/df/056875d697c45182ed6d2ae21f62015896fdb841906fe48e7268e791c467/pycocotools-2.0.2.tar.gz
> Requirement already satisfied: pydot in /usr/lib/python3/dist-packages (from detectron2==0.3)
> Collecting tabulate (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/c4/f4/770ae9385990f5a19a91431163d262182d3203662ea2b5739d0fcfc080f1/tabulate-0.8.7-py3-none-any.whl
> Collecting tensorboard (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/02/83/179c8f76e5716030cc3ee9433721161cfcc1d854e9ba20c9205180bb100a/tensorboard-2.4.0-py3-none-any.whl (10.6MB)
>     100% |████████████████████████████████| 10.6MB 126kB/s 
> Collecting termcolor>=1.1 (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
> Collecting tqdm>4.29.0 (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/93/3a/96b3dc293aa72443cf9627444c3c221a7ba34bb622e4d8bf1b5d4f2d9d08/tqdm-4.51.0-py2.py3-none-any.whl (70kB)
>     100% |████████████████████████████████| 71kB 1.3MB/s 
> Collecting yacs>=0.1.6 (from detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/38/4f/fe9a4d472aa867878ce3bb7efb16654c5d63672b86dc0e6e953a67018433/yacs-0.1.8-py3-none-any.whl
> Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from fvcore>=0.1.2->detectron2==0.3)
> Collecting portalocker (from fvcore>=0.1.2->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/89/a6/3814b7107e0788040870e8825eebf214d72166adf656ba7d4bf14759a06a/portalocker-2.0.0-py2.py3-none-any.whl
> Collecting pyyaml>=5.1 (from fvcore>=0.1.2->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
>     100% |████████████████████████████████| 276kB 992kB/s 
> Collecting cython>=0.27.3 (from pycocotools>=2.0.2->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/19/49/91ebe4a00bf894d08dd9680cd9dfb05936eb2848eebd9402b43885aa74cf/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
>     100% |████████████████████████████████| 2.0MB 447kB/s 
> Requirement already satisfied: setuptools>=18.0 in /usr/lib/python3/dist-packages (from pycocotools>=2.0.2->detectron2==0.3)
> Collecting grpcio>=1.24.3 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/cc/1e/5d65ae830536fdb67f10f4bcedca6eb59190ad60d20d796ef3ccdfda4797/grpcio-1.33.2.tar.gz (20.9MB)
>     100% |████████████████████████████████| 20.9MB 64kB/s 
> Collecting werkzeug>=0.11.15 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
>     100% |████████████████████████████████| 307kB 557kB/s 
> Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from tensorboard->detectron2==0.3)
> Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/lib/python3/dist-packages (from tensorboard->detectron2==0.3)
> Collecting requests<3,>=2.21.0 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl (61kB)
>     100% |████████████████████████████████| 61kB 731kB/s 
> Collecting google-auth<2,>=1.6.3 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/1d/60/81e68e70eea91ef05bb00bcdac243d67b61f826c65aaca6961de622dffd7/google_auth-1.23.0-py2.py3-none-any.whl (114kB)
>     100% |████████████████████████████████| 122kB 1.0MB/s 
> Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/b6/85/5c5ac0a8c5efdfab916e9c6bc18963f6a6996a8a1e19ec4ad8c9ac9c623c/tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779kB)
>     100% |████████████████████████████████| 788kB 906kB/s 
> Collecting markdown>=2.6.8 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/ac/ef/24a91ca96efa0d7802dffb83ccc7a3c677027bea19ec3c9ee80be740408e/Markdown-3.3.3-py3-none-any.whl (96kB)
>     100% |████████████████████████████████| 102kB 1.2MB/s 
> Collecting protobuf>=3.6.0 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/fe/fd/247ef25f5ec5f9acecfbc98ca3c6aaf66716cf52509aca9a93583d410493/protobuf-3.14.0-cp36-cp36m-manylinux1_x86_64.whl (1.0MB)
>     100% |████████████████████████████████| 1.0MB 465kB/s 
> Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/81/67/e2c34bb0628984c7ce71cce6ba6964cb29c418873847fc285f826e032e6e/google_auth_oauthlib-0.4.2-py2.py3-none-any.whl
> Collecting absl-py>=0.4 (from tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/bc/58/0aa6fb779dc69cfc811df3398fcbeaeefbf18561b6e36b185df0782781cc/absl_py-0.11.0-py3-none-any.whl (127kB)
>     100% |████████████████████████████████| 133kB 1.3MB/s 
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3)
> Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3)
> Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl (155kB)
>     100% |████████████████████████████████| 163kB 1.6MB/s 
> Collecting rsa<5,>=3.1.4; python_version >= "3.5" (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/1c/df/c3587a667d6b308fadc90b99e8bc8774788d033efcc70f4ecaae7fad144b/rsa-4.6-py3-none-any.whl (47kB)
>     100% |████████████████████████████████| 51kB 1.0MB/s 
> Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/cd/5c/f3aa86b6d5482f3051b433c7616668a9b96fbe49a622210e2c9781938a5c/cachetools-4.1.1-py3-none-any.whl
> Collecting importlib-metadata; python_version < "3.8" (from markdown>=2.6.8->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/6d/6d/f4bb28424bc677bce1210bc19f69a43efe823e294325606ead595211f93e/importlib_metadata-2.0.0-py2.py3-none-any.whl
> Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
> Collecting pyasn1<0.5.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
>     100% |████████████████████████████████| 81kB 1.1MB/s 
> Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
> Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3)
>   Downloading https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl (147kB)
>     100% |████████████████████████████████| 153kB 1.6MB/s 
> Installing collected packages: cloudpickle, portalocker, pyyaml, tabulate, termcolor, tqdm, yacs, fvcore, cython, pycocotools, grpcio, werkzeug, requests, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, tensorboard-plugin-wit, zipp, importlib-metadata, markdown, protobuf, oauthlib, requests-oauthlib, google-auth-oauthlib, absl-py, tensorboard, detectron2
>   Found existing installation: PyYAML 3.12
>     Not uninstalling pyyaml at /usr/lib/python3/dist-packages, outside environment /usr
>   Running setup.py install for pyyaml ... done
>   Running setup.py install for termcolor ... done
>   Running setup.py install for fvcore ... done
>   Running setup.py install for pycocotools ... done
>   Running setup.py install for grpcio ... done
>   Found existing installation: requests 2.18.4
>     Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
>   Found existing installation: protobuf 3.0.0
>     Not uninstalling protobuf at /usr/lib/python3/dist-packages, outside environment /usr
>   Running setup.py install for detectron2 ... done
> Successfully installed absl-py-0.11.0 cachetools-4.1.1 cloudpickle-1.6.0 cython-0.29.21 detectron2-0.3 fvcore-0.1.2.post20201111 google-auth-1.23.0 google-auth-oauthlib-0.4.2 grpcio-1.33.2 importlib-metadata-2.0.0 markdown-3.3.3 oauthlib-3.1.0 portalocker-2.0.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycocotools-2.0.2 pyyaml-5.3.1 requests-2.25.0 requests-oauthlib-1.3.0 rsa-4.6 tabulate-0.8.7 tensorboard-2.4.0 tensorboard-plugin-wit-1.7.0 termcolor-1.1.0 tqdm-4.51.0 werkzeug-1.0.1 yacs-0.1.8 zipp-3.4.0
> matthias@matthias:~$ 

```

Thank you.
Regards
Matt

**Comment by ppwwyyxx** [comment]
> I can't provide you the environment informations because i get an error message

you probably need to replace `python` by `python3` if your `python` is something else

**Comment by MatthiasMatze** [comment]
Silly me...
The output of 
`wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python3 collect_env.py`
is:

```
matthias@matthias:~/detectron2$ wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python3 collect_env.py
---------------------  ------------------------------------------------------------------------
sys.platform           linux
Python                 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                  1.19.4
detectron2             0.3 @/home/matthias/detectron2/detectron2
Compiler               GCC 7.5
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.7.0+cpu @/home/matthias/.local/lib/python3.6/site-packages/torch
PyTorch debug build    True
GPU available          False
Pillow                 8.0.1
torchvision            0.8.1+cpu @/home/matthias/.local/lib/python3.6/site-packages/torchvision
fvcore                 0.1.2.post20201111
cv2                    3.4.0
---------------------  ------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

matthias@matthias:~/detectron2$ 

```

**Comment by ppwwyyxx** [comment]
This output looks correct. If you run this command right after the failure (i.e., inside `demo/`), does the output become different? 
I guess you might incorrectly set something in `PYTHONPATH`  that affects how import works.

**Comment by MatthiasMatze** [comment]
Yes it looks different.
` wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python3 collect_env.py
---------------------  ------------------------------------------------------------------------
sys.platform           linux
Python                 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                  1.19.4
detectron2             0.3 @/home/matthias/detectron2/detectron2
Compiler               GCC 7.5
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.7.0+cpu @/home/matthias/.local/lib/python3.6/site-packages/torch
PyTorch debug build    True
GPU available          False
Pillow                 8.0.1
torchvision            0.8.1+cpu @/home/matthias/.local/lib/python3.6/site-packages/torchvision
fvcore                 0.1.2.post20201111
cv2                    3.4.0
---------------------  ------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 
`

ant the error message that i get now is also different:

`python3 demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --input Spitzer.mp4   --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl 
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-p0ncpu0y because the default path (/home/matthias/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[11/19 20:35:26 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['Spitzer.mp4'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 82, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/matthias/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/matthias/detectron2/detectron2/engine/defaults.py", line 188, in __init__
    self.model = build_model(self.cfg)
  File "/home/matthias/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/matthias/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
`

**Comment by ppwwyyxx** [comment]
That means your original issue is solved.
The new issue is explained by the error message:"Torch not compiled with CUDA enabled"
