### ISSUE TITLE
Error for scripting resnet: too many indices for tensor of dimension 3

### ISSUE THREAD

**Issue by aryan461** [facebookresearch/detectron2#2266]
This is the config file for the resnet101 that I use:
```python
        cfg = get_cfg()
        cfg.MODEL.ATTRIBUTE_ON = False
        cfg.INPUT.MAX_ATTR_PER_INS = 16
        cfg.MODEL.ROI_ATTRIBUTE_HEAD = CN()
        cfg.MODEL.ROI_ATTRIBUTE_HEAD.OBJ_EMBED_DIM = 256
        cfg.MODEL.ROI_ATTRIBUTE_HEAD.FC_DIM = 512
        cfg.MODEL.ROI_ATTRIBUTE_HEAD.LOSS_WEIGHT = 0.2
        cfg.MODEL.ROI_ATTRIBUTE_HEAD.NUM_CLASSES = 400
        cfg.MODEL.RPN.BBOX_LOSS_WEIGHT = 1.0
        cfg.MODEL.ROI_BOX_HEAD.BBOX_LOSS_WEIGHT = 1.0
        cfg.merge_from_file(os.path.join(root_path, 'configs/X-101-grid.yaml'))
        cfg.dataset = 'coco_2015_test'
        cfg.MODEL.RESNETS.RES5_DILATION = 1
        cfg.MODEL.DEVICE = 'cpu'
        cfg.freeze()
        default_setup(cfg, None)
```

I build my res101 model by:
```python
model.backbone = build_model(cfg)
```

for scripting the model:
```python      
 with torch.no_grad():
            ts_model = torch.jit.trace(model, (torch.rand(2, 3, 224, 224),))
```

but I got Error:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-community/214/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/214/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/myPath/d2_export_torchscript.py", line 205, in <module>
    util_class.tes_dump_IR_tracing()
  File "/home/myPath/d2_export_torchscript.py", line 193, in tes_dump_IR_tracing
    ts_model = torch.jit.trace(model, (torch.rand(2, 3, 224, 224),))
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/jit/_trace.py", line 733, in trace
    return trace_module(
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/jit/_trace.py", line 934, in trace_module
    module._c._create_method_from_trace(
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/nn/modules/module.py", line 742, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/nn/modules/module.py", line 726, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/myPath/d2_export_torchscript.py", line 178, in forward
    return tuple(self.backbone(x).values())
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/nn/modules/module.py", line 742, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/torch/nn/modules/module.py", line 726, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 203, in inference
    images = self.preprocess_image(batched_inputs)
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 228, in preprocess_image
    images = [x["image"].to(self.device) for x in batched_inputs]
  File "/home/anaconda3/envs/d2script/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 228, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
IndexError: too many indices for tensor of dimension 3

```

**Comment by aryan461** [comment]
@ppwwyyxx do you have any idea about how to solve this error?

**Comment by ppwwyyxx** [comment]
The correct way to use tracing on detectron2 models is demonstrated in unittest: https://github.com/facebookresearch/detectron2/blob/master/tests/test_export_torchscript.py#L23-L150. The method in your code is not expected to work.

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment]
Also, I noticed this was originally related to the other project: https://github.com/facebookresearch/grid-feats-vqa/  Since this project for now requires old version of detectron2, we can't help much about it. If there are any efforts trying to upgrade the project for latest version of detectron2, I can help review the code.

**Comment by aryan461** [comment]
@ppwwyyxx  thank you for the response. yes, I try to make a script code of D2 in grid-feats-vqa. as you can see in the history of this issue I had a problem using updated D2 with the same config. But I found [a commit](https://github.com/facebookresearch/grid-feats-vqa/commit/d9a14fbb7580fb377353d8b397c5a8e5443b4117) that helps me to build the model with the same config but in the last D2 version. Do you think it's the correct way to use the new D2?

So I put the config in [](https://github.com/facebookresearch/detectron2/blob/master/tests/test_export_torchscript.py#L154) and changed the `build_backbone(cfg)` to `build_model(cfg)` to be the same as before. But got that error. What do you suggest?

**Comment by ppwwyyxx** [comment]
> But I found a commit that helps me to build the model with the same config but in the last D2 version. Do you think it's the correct way to use the new D2?

the commit looks right

> I put the config in test_export_torchscript.py and changed the build_backbone(cfg) to build_model(cfg) to be the same as before. But got that error.

I don't know what exactly you did. Please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by aryan461** [comment]
> I don't know what exactly you did. 

This is the exact code(I hope that it follows "Unexpected behaviors" issue template), I just used the [test_export_torchscript](https://github.com/facebookresearch/detectron2/blob/master/tests/test_export_torchscript.py) :

```python
class TesTorchscriptUtils(unittest.TestCase):
    # TODO: add test to dump scripting
    def setup(self, root_path):
        """
        Create configs and perform basic setups.
        """
        cfg = get_cfg()
        add_attribute_config(cfg)
        cfg.merge_from_file(os.path.join(root_path, 'configs/X-101-grid.yaml'))
        cfg.dataset = 'coco_2015_test'
        # force the final residual block to have dilations 1
        cfg.MODEL.RESNETS.RES5_DILATION = 1
        cfg.MODEL.DEVICE = 'cpu'
        cfg.freeze()
        default_setup(cfg, None)
        return cfg

    def tes_dump_IR_tracing(self):
        cfg = self.setup('./')

        class Mod(nn.Module):
            def forward(self, x):
                return tuple(self.backbone(x).values())


        model = Mod()
        # model.backbone = build_backbone(cfg)
        model.backbone = build_model(cfg)
        model.eval()
        DetectionCheckpointer(model.backbone, save_dir=cfg.OUTPUT_DIR).resume_or_load('./models/LN_models/LN_v3/X-101.pth',
                                                                             resume=True)

        with torch.no_grad():
            ts_model = torch.jit.trace(model, (torch.rand(2, 3, 224, 224),))
            # ts_model = torch.jit.script(model)

        with tempfile.TemporaryDirectory(prefix="detectron2_test") as d:
            dump_torchscript_IR(ts_model, d)
            # check that the files are created
            for name in ["model_ts_code", "model_ts_IR", "model_ts_IR_inlined", "model"]:
                fname = os.path.join(d, name + ".txt")
                self.assertTrue(os.stat(fname).st_size > 0, fname)
        torch.jit.save(ts_model, 'd2101_traced.pt')


util_class = TesTorchscriptUtils()
util_class.tes_dump_IR_tracing()
```
the `add_attribute_config(cfg)` is from [here](https://github.com/facebookresearch/grid-feats-vqa/blob/8e1bd774b4f1b8987c7e170f218863561e7c6af5/grid_feats/config.py).

when I use `build_backbone(cfg)` it scripts without errors but the result of the scripted model is different. And the `build_model(cfg)` ends up with this error(as mentioned above) for the `ts_model = torch.jit.trace(model, (torch.rand(2, 3, 224, 224),))` line:
too many indices for tensor of dimension 3

**Comment by ppwwyyxx** [comment]
This is an irrelevant test. The test that demonstrated the usage of `torch.jit.trace` is `TestTracing.testMaskRCNN`: https://github.com/facebookresearch/detectron2/blob/84a09834f6d838534951907fd9ef90fec73614d2/tests/test_export_torchscript.py#L72-L102

**Comment by aryan461** [comment]
Thank you very much for all your answers. Finally I could script the resnet backbone using [this comment](https://github.com/facebookresearch/detectron2/issues/46#issuecomment-725675495) and with `torch.jit.script`. This is the final code:

```python
class TesTorchscriptUtils(unittest.TestCase):
    # TODO: add test to dump scripting
    def setup(self, root_path):
        """
        Create configs and perform basic setups.
        """
        cfg = get_cfg()
        add_attribute_config(cfg)
        cfg.merge_from_file(os.path.join(root_path, 'configs/X-101-grid.yaml'))
        cfg.dataset = 'coco_2015_test'
        # force the final residual block to have dilations 1
        cfg.MODEL.RESNETS.RES5_DILATION = 1
        cfg.MODEL.DEVICE = 'cpu'
        cfg.freeze()
        default_setup(cfg, None)
        return cfg

    def tes_dump_IR_tracing(self):
        cfg = self.setup('./')

        class Mod(nn.Module):
            def forward(self, x):
                return tuple(self.backbone(x).values())


        model = Mod()
        model.backbone = build_model(cfg)
        model.eval()
        DetectionCheckpointer(model.backbone, save_dir=cfg.OUTPUT_DIR).resume_or_load('./X-101.pth', resume=True)

        model.backbone.backbone.stages = nn.ModuleList(model.backbone.backbone.stages)

        with torch.no_grad():
            # ts_model = torch.jit.trace(model, torch.rand(1, 3, 224, 224))
            ts_model = torch.jit.script(model.backbone.backbone)

        with tempfile.TemporaryDirectory(prefix="detectron2_test") as d:
            dump_torchscript_IR(ts_model, d)
            # check that the files are created
            for name in ["model_ts_code", "model_ts_IR", "model_ts_IR_inlined", "model"]:
                fname = os.path.join(d, name + ".txt")
                self.assertTrue(os.stat(fname).st_size > 0, fname)
        torch.jit.save(ts_model, 'd2101_scripted.pt')


util_class = TesTorchscriptUtils()
util_class.tes_dump_IR_tracing()
```

the `add_attribute_config(cfg)` is from [here](https://github.com/facebookresearch/grid-feats-vqa/blob/8e1bd774b4f1b8987c7e170f218863561e7c6af5/grid_feats/config.py).
envirenment information can be found [here](https://drive.google.com/file/d/1KvUJGqANsInOpTeKyq_6bcsQ0_WX-Cjy/view?usp=sharing).
