### ISSUE TITLE
Can't you surely convert detectron2 to TensorTR?

### ISSUE THREAD

**Issue by DonggeunYu** [facebookresearch/detectron2#2281]
Looking at the issue, the opinion that detectron2 cannot be converted to TensorTR is dominant. Can't you surely convert detectron2 to TensorTR? I have to convert it to TensorTR by modifying the code. I would appreciate it if you let me know in detail why it can't be converted.

https://github.com/facebookresearch/detectron2/issues/1424

https://github.com/facebookresearch/detectron2/blob/84a09834f6d838534951907fd9ef90fec73614d2/detectron2/export/api.py#L115-L125

**Comment by ppwwyyxx** [comment]
TensorRT is one of the "different runtimes". As you have mentioned, we do not provide support for them: 

>  Post-processing or transformation passes 
         may be applied on the model to accommodate different runtimes, but we currently do not 
         provide support for them.

It doesn't mean the models can't be converted. We know some company have implemented the conversion, but our team don't support this feature.

**Comment by DonggeunYu** [comment]
Other issues also have a hard time converting to onnx. Can't you surely convert to onnx?
Probably because of the custom instances object, the export to onnx doesn't seem to work.
If i modify the source code to convert to onnx, should we retrain the model?

~~~
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/src/optimize/model_to_onnx.py", line 91, in <module>
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 350, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type Instances
~~~

**Comment by DonggeunYu** [comment]
@ppwwyyxx 
Other issues also have a hard time converting to onnx. Can't you surely convert to onnx?
Probably because of the custom instances object, the export to onnx doesn't seem to work.
If i modify the source code to convert to onnx, should we retrain the model?

~~~
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/src/optimize/model_to_onnx.py", line 91, in <module>
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 350, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type Instances
~~~

**Comment by ppwwyyxx** [comment]
The code you link to can convert models to onnx.

**Comment by DonggeunYu** [comment]
However, like the above error, an error occurs for the instances object. I think I need to modify the detectron2 source code, but if I do it, should I train again?

**Comment by DonggeunYu** [comment]
@ppwwyyxx 
However, like the above error, an error occurs for the instances object. I think I need to modify the detectron2 source code, but if I do it, should I train again?

**Comment by ppwwyyxx** [comment]
Error is not expected to happen if you use the code (`Caffe2Tracer`) in detectron2 you linked to, instead of some code you wrote.

The tool documented in https://detectron2.readthedocs.io/tutorials/deployment.html#id2 can produce an onnx model with no issues:
```
./caffe2_converter.py --config-file ../../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
--format onnx  --output ./model MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl \
  MODEL.DEVICE cpu
```

If you need help to solve any unexpected issues, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by DonggeunYu** [comment]
A: configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
B: configs/Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml

A converts fine. But B gets the following error.

~~~
Traceback (most recent call last):
  File "caffe2_converter.py", line 67, in <module>
    onnx_model = tracer.export_onnx()
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/api.py", line 129, in export_onnx
    return export_onnx_model_impl(model, (inputs,))
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_modeling.py", line 273, in forward
    with self.roi_heads_patcher.mock_roi_heads():
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_patch.py", line 151, in mock_roi_heads
    stack.enter_context(mgr)
  File "/usr/local/lib/python3.7/contextlib.py", line 426, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_patch.py", line 86, in mock_fastrcnn_outputs_inference
    side_effect=Caffe2FastRCNNOutputsInference(tensor_mode),
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1259, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1233, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <class 'torch.nn.modules.container.ModuleList'> does not have the attribute 'inference'
~~~

**Comment by DonggeunYu** [comment]
@ppwwyyxx 
A: configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
B: configs/Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml

A converts fine. But B gets the following error.

~~~
Traceback (most recent call last):
  File "caffe2_converter.py", line 67, in <module>
    onnx_model = tracer.export_onnx()
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/api.py", line 129, in export_onnx
    return export_onnx_model_impl(model, (inputs,))
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_modeling.py", line 273, in forward
    with self.roi_heads_patcher.mock_roi_heads():
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_patch.py", line 151, in mock_roi_heads
    stack.enter_context(mgr)
  File "/usr/local/lib/python3.7/contextlib.py", line 426, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_patch.py", line 86, in mock_fastrcnn_outputs_inference
    side_effect=Caffe2FastRCNNOutputsInference(tensor_mode),
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1259, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1233, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <class 'torch.nn.modules.container.ModuleList'> does not have the attribute 'inference'
~~~

**Comment by ppwwyyxx** [comment]
Duplicate of #988

**Comment by DonggeunYu** [comment]
I have tried the above issue in the past, but I got the following error. The same error occurred when changing the image.
~~~
Traceback (most recent call last):
  File "caffe2_converter.py", line 67, in <module>
    onnx_model = tracer.export_onnx()
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/api.py", line 129, in export_onnx
    return export_onnx_model_impl(model, (inputs,))
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_modeling.py", line 280, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/cascade_rcnn.py", line 150, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 725, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 802, in _forward_mask
    features = self.mask_pooler(features, boxes)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/c10.py", line 341, in forward
    roi_feat = torch.ops._caffe2.BatchPermutation(roi_feat_shuffled, rois_idx_restore_int32)
RuntimeError: [enforce fail at batch_permutation_op.cc:64] X.dim32(0) > 0. 0 vs 0
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f4c097c7d37 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x31d5189 (0x7f4b60f39189 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x2f5883d (0x7f4b60cbc83d in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x31d6643 (0x7f4b60f3a643 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x31a7035 (0x7f4b60f0b035 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x33eb009 (0x7f4b6114f009 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x40e8547 (0x7f4b61e4c547 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x6df26f (0x7f4c0a50126f in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x6aa484 (0x7f4c0a4cc484 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x295a74 (0x7f4c0a0b7a74 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
~~~

**Comment by DonggeunYu** [comment]
@ppwwyyxx 
I have tried the above issue in the past, but I got the following error. The same error occurred when changing the image in val2017. If I really only fix this error, I would feel so good.
~~~
Traceback (most recent call last):
  File "caffe2_converter.py", line 67, in <module>
    onnx_model = tracer.export_onnx()
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/api.py", line 129, in export_onnx
    return export_onnx_model_impl(model, (inputs,))
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 277, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 360, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/__init__.py", line 347, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/caffe2_modeling.py", line 280, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/cascade_rcnn.py", line 150, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 725, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 802, in _forward_mask
    features = self.mask_pooler(features, boxes)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/detectron2-0.3-py3.7-linux-x86_64.egg/detectron2/export/c10.py", line 341, in forward
    roi_feat = torch.ops._caffe2.BatchPermutation(roi_feat_shuffled, rois_idx_restore_int32)
RuntimeError: [enforce fail at batch_permutation_op.cc:64] X.dim32(0) > 0. 0 vs 0
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f4c097c7d37 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x31d5189 (0x7f4b60f39189 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x2f5883d (0x7f4b60cbc83d in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x31d6643 (0x7f4b60f3a643 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x31a7035 (0x7f4b60f0b035 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x33eb009 (0x7f4b6114f009 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x40e8547 (0x7f4b61e4c547 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x6df26f (0x7f4c0a50126f in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x6aa484 (0x7f4c0a4cc484 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x295a74 (0x7f4c0a0b7a74 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
~~~

**Comment by ppwwyyxx** [comment]
That issue is open - which means it's not solved, so I don't understand what you "tried".

The error is because the inputs and model checkpoint you provide to the script do not produce valid detections.

**Comment by DonggeunYu** [comment]
@ppwwyyxx 
Thanks for your help.

**Comment by batrlatom** [comment]
Just a question... Facebook would not benefit from Tensorrt implementation?

**Comment by ysyyork** [comment]
i'm very confused too on this :/

**Comment by Tony-Hou** [comment]
https://github.com/facebookresearch/detectron2/issues/2281#issuecomment-729404404
How to solve the problem? @DonggeunYu
