### ISSUE TITLE
TypeError: _train_loader_from_config() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wincle** [facebookresearch/detectron2#2291]
Traceback (most recent call last):
File "tools/train_net.py", line 237, in 
launch(
File "/root/anaconda3/lib/python3.8/site-packages/detectron2/engine/launch.py", line 62, in launch
main_func(*args)
File "tools/train_net.py", line 225, in main
trainer = Trainer(cfg)
File "tools/train_net.py", line 62, in init
data_loader = self.build_train_loader(cfg)
File "tools/train_net.py", line 128, in build_train_loader
return build_detection_train_loader(cfg, mapper)
File "/root/anaconda3/lib/python3.8/site-packages/detectron2/config/config.py", line 201, in wrapped
explicit_args = _get_args_from_config(from_config, *args, **kwargs)
File "/root/anaconda3/lib/python3.8/site-packages/detectron2/config/config.py", line 236, in _get_args_from_config
ret = from_config_func(*args, **kwargs)
TypeError: _train_loader_from_config() takes 1 positional argument but 2 were given

I don't know why it comes up, anyone could help me? Thx!

**Comment by ppwwyyxx** [comment]
It appears that we accidentally require `mapper` argument to be explicit, i.e. it must be `build_detection_train_loader(cfg, mapper=mapper)`.
We will revert this requirement.

**Comment by wincle** [comment]
> It appears that we accidentally require `mapper` argument to be explicit, i.e. it must be `build_detection_train_loader(cfg, mapper=mapper)`.
> We will revert this requirement.

Thx for your help, it worked, but I met another problem.

Traceback (most recent call last):
  File "tools/train_net.py", line 237, in <module>
    launch(
  File "/root/anaconda3/lib/python3.8/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 225, in main
    trainer = Trainer(cfg)
  File "tools/train_net.py", line 69, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given

I thought may be another version issue, how could I fix it?

**Comment by ppwwyyxx** [comment]
I can't see your code so I cannot answer this one. There is an [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) that asks for enough details.

**Comment by wincle** [comment]
> I can't see your code so I cannot answer this one. There is an [issue template](https://github.com/facebookresearch/detectron2/issues/new/choose) that asks for enough details.

I'm using AdelaiDet training code, below link is the code I used.
https://github.com/aim-uofa/AdelaiDet/blob/master/tools/train_net.py
exception happened in line 69.

**Comment by ppwwyyxx** [comment]
Then please use https://github.com/aim-uofa/AdelaiDet/issues/235 instead.
