### ISSUE TITLE
Can't run demo.py - missing FileNotFoundError: [Errno 2] No such file or directory: 'input1.png'

### ISSUE THREAD

**Issue by rakshitagouni** [facebookresearch/detectron2#2313]
I'm trying to run demo.py after a clean setup. However, after placing 2 of my own images (input1.png, input2.png) in the demo folder, I get the following error:
```
$ python3 demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.png input2.png 
Traceback (most recent call last):
  File "demo.py", line 90, in <module>
    img = read_image(path, format="BGR")
  File "/home/appuser/detectron2_repo/detectron2/data/detection_utils.py", line 178, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/common/file_io.py", line 648, in open
    path, mode, buffering=buffering, **kwargs
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/common/file_io.py", line 383, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: 'input1.png'

```
Where are the input images supposed to be located?

**Comment by ppwwyyxx** [comment]
They can be located in any location as long as you provide the correct path, either absolute or relative, to that location.
