### ISSUE TITLE
Cannot save the scripted model with export_torchscript_with_instances, runtime error of unknown device

### ISSUE THREAD

**Issue by yaoli** [facebookresearch/detectron2#2321]
1. Full runnable code or full changes you made:
```
# The following is a simple modification of detectron2/tests/test_export_torchscript.py
def _test_rcnn_model(self, config_path):
        model = model_zoo.get(config_path, trained=True)
        model.eval()

        fields = {
            "proposal_boxes": Boxes,
            "objectness_logits": Tensor,
            "pred_boxes": Boxes,
            "scores": Tensor,
            "pred_classes": Tensor,
            "pred_masks": Tensor,
        }
        script_model = export_torchscript_with_instances(model, fields)
        dump_torchscript_IR(script_model, '.')
        # saving error!
        torch.jit.save(script_model, 'script_model.zip')
        inputs = [{"image": get_sample_coco_image()}]
```
2. What exact command you run:
`python -m unittest test_export_torchscript.TestScripting.testMaskRCNN`
3. __Full logs__ you observed:
```
ERROR: testMaskRCNN (test_export_torchscript.TestScripting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lyao/repos/detectron2/tests/test_export_torchscript.py", line 30, in testMaskRCNN
    self._test_rcnn_model("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/home/lyao/repos/detectron2/tests/test_export_torchscript.py", line 50, in _test_rcnn_model
    torch.jit.save(script_model, 'script_model.zip')
  File "/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torch/jit/_serialization.py", line 81, in save
    m.save(f, _extra_files=_extra_files)
  File "/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torch/jit/_script.py", line 487, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: Unknown device: 20. If you have recently updated the caffe2.proto file to add a new device type, did you forget to update the DeviceTypeName() function to reflect such recent changes?
```

## Expected behavior:
Expect scripted model to be saved.
## Environment:

Provide your environment information using the following command:
```
----------------------  ----------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.19.1
detectron2              0.3 @/home/lyao/repos/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0.dev20201124 @/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-32GB (arch=7.0)
CUDA_HOME               /home/lyao/miniconda3/envs/11242020
Pillow                  7.2.0
torchvision             0.9.0.dev20201124 @/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20200912
cv2                     4.4.0
----------------------  ----------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

I'm not sure I even understand the error at this point, not along debugging it. Any insight is much much appreciated. Thank you in advance!

**Comment by ppwwyyxx** [comment]
Should be fixed by cd60faf1427f95d357ba30365a415d0309a8618f already.

**Comment by yaoli** [comment]
@ppwwyyxx Thanks for pointing this out. Could you please shed some light on what's the base of the issue and how the patch turned out to solve it? It would be nice to actually understand this issue further.

**Comment by ppwwyyxx** [comment]
According to the referenced pytorch issue we cannot use `torch.device` in torchscript, so we stopped using it.
