### ISSUE TITLE
How to resume training model that is saved under "output" directory

### ISSUE THREAD

**Issue by Ifrahmaqsood** [facebookresearch/detectron2#2334]
## ❓ How to do something using detectron2
I am pretraining a model using visual genome dataset my training got interupted but the checkpoint is now created under "output" directory. How can I resume a training?
I'm using this code

python3.6 train_net.py --num-gpus 1 --config-file configs/R-50-grid.yaml OUTPUT_DIR output --resume

but it gives me an error 

Command Line Args: Namespace(config_file='configs/R-50-grid.yaml', dist_url='tcp://127.0.0.1:50170', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['OUTPUT_DIR', 'output', '--resume'], resume=True)
Traceback (most recent call last):
File "train_net.py", line 127, in
args=(args,),
File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/launch.py", line 52, in launch
main_func(*args)
File "train_net.py", line 101, in main
cfg = setup(args)
File "train_net.py", line 94, in setup
cfg.merge_from_list(args.opts)
File "/usr/local/lib/python3.6/dist-packages/fvcore/common/config.py", line 135, in merge_from_list
return super().merge_from_list(cfg_list)
File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 226, in merge_from_list
cfg_list
File "/usr/local/lib/python3.6/dist-packages/yacs/config.py", line 545, in _assert_with_logging
assert cond, msg
AssertionError: Override list has odd length: ['OUTPUT_DIR', 'output', '--resume']; it must be a list of pairs
$

**Comment by ppwwyyxx** [comment]
> python3.6 train_net.py --num-gpus 1 --config-file configs/R-50-grid.yaml OUTPUT_DIR output --resume

`--resume` has to come before `OUTPUT_DIR`
