### ISSUE TITLE
scripted model cannot be loaded properly: runtime error

### ISSUE THREAD

**Issue by yaoli** [facebookresearch/detectron2#2335]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
from detectron2.export.torchscript import export_torchscript_with_instances
from detectron2.utils.testing import assert_instances_allclose, get_sample_coco_image
from detectron2.structures import Boxes, Instances
import torch
from torch import Tensor

def dump_model():
    config_path = 'COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
    model = model_zoo.get(config_path, trained=True)
    model.eval()

    fields = {
        "proposal_boxes": Boxes,
        "objectness_logits": Tensor,
        "pred_boxes": Boxes,
        "scores": Tensor,
        "pred_classes": Tensor,
        "pred_masks": Tensor,
    }
    script_model = export_torchscript_with_instances(model, fields)
    torch.jit.save(script_model, 'script_model.zip')
    inputs = [{"image": get_sample_coco_image()}]
    with torch.no_grad():
        instance = model.inference(inputs, do_postprocess=False)[0]
        scripted_instance = script_model.inference(inputs, do_postprocess=False)[
            0
        ].to_instances()
    assert_instances_allclose(instance, scripted_instance)

def load_model():
    script_model = torch.jit.load('script_model.zip')
    inputs = [{"image": get_sample_coco_image()}]
    with torch.no_grad():
        scripted_instance = script_model.inference(inputs, do_postprocess=False)

dump_model()
load_model()
```
2. What exact command you run: `python bug.py`
3. __Full logs__ you observed:
 When I run `dump_model()` and `load_model()` in one go, all is good. But, when commented out *only* `load_model()`, run it, then followed by commenting out *only* `dump_model()`, the following error occurs. This prevents the scripted model from being loaded and used elsewhere as it appears to rely on the scripting process itself to have some kind of "memory" in order to run.
```
Traceback (most recent call last):
  File "bug.py", line 38, in <module>
    load_model()
  File "bug.py", line 35, in load_model
    scripted_instance = script_model.inference(inputs, do_postprocess=False)
RuntimeError: classType INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1606813341434/work/torch/csrc/jit/python/pybind_utils.h":986, please report a bug to PyTorch.
```

## Expected behavior:

When dumping and loading are run in the same process, things work fine. When they are executed in separate runs, things should be fine as well. 

## Environment:

Provide your environment information using the following command:
```
----------------------  ----------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.19.1
detectron2              0.3 @/home/lyao/repos/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0.dev20201124 @/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-32GB (arch=7.0)
CUDA_HOME               /home/lyao/miniconda3/envs/11242020
Pillow                  7.2.0
torchvision             0.9.0.dev20201124 @/home/lyao/miniconda3/envs/11242020/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20200912
cv2                     4.4.0
----------------------  ----------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

This issue may be related to https://github.com/pytorch/pytorch/issues/42258. I've tried to parse the discussion there but it is at the level that I find hard to understand. Also models here are much more complicated.

**Comment by ppwwyyxx** [comment]
This is caused by the pytorch issue you linked to. The workaround for now is to wrap `load_model` inside `with patch_instances(fields): ... `
