### ISSUE TITLE
installing detectron2 for PyTorch 1.14

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/detectron2#2353]
I am using [PHOSA](https://github.com/facebookresearch/phosa/issues/5#issuecomment-739565739) by FAIR and that uses Detectron 2 but also uses PyTorch 1.14. Is there a way to install Detectron2 for PyTorch 1.4?
However, I get this error:
```
(phosa) mona@mona:~/research/phosa$ pip install external/detectron2
Processing ./external/detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/mona/anaconda3/envs/phosa/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-x3biagt4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-x3biagt4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-njs4oy9g
         cwd: /tmp/pip-req-build-x3biagt4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-x3biagt4/setup.py", line 15, in <module>
        assert torch_ver >= [1, 5], "Requires PyTorch >= 1.5"
    AssertionError: Requires PyTorch >= 1.5
    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have:

```
(phosa) mona@mona:~/research/phosa/external/detectron2$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.4.0'

$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```

**Comment by ppwwyyxx** [comment]
As https://detectron2.readthedocs.io/tutorials/install.html says we support Pytorch>=1.5
