### ISSUE TITLE
CUDA error: device-side assert triggered occurs during the training

### ISSUE THREAD

**Issue by dhirajsuvarna** [facebookresearch/detectron2#2365]
## Instructions To Reproduce the Issue:

I am trying to do object detection on the custom dataset using detectron2. 

1. Full runnable code or full changes you made:

#### Preparing the dataset 
```
import json
import os
from detectron2.structures import BoxMode

def get_dataset(imgdir):
  json_file = os.path.join(imgdir, 'dataset.json')

  with open(json_file) as f:
    dataset_dicts = json.load(f)

  for i in dataset_dicts:
    filename = i["file_name"]
    i["file_name"] = os.path.join(imgdir, 'Images', filename)

    for j in i["annotations"]:
      j["bbox_mode"] = BoxMode.XYWH_ABS 
      j["category_id"] = int(j["category_id"])
    
  return dataset_dicts
```
#### Registering the dataset 
```
#Register the dataset 
dataset_path = '/content/mydrive/MyDrive/Projects/dataset/Text_Detection_Dataset'
for d in ["train", "val"]:
  DatasetCatalog.register("text_" + d, lambda d=d: get_dataset(dataset_path + "/" + d))
  MetadataCatalog.get("text_" + d).set(thing_classes=["hindi", "english", "others"])
```
#### Setting the config file 

```
from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))

cfg.DATASETS.TRAIN = ("text_train",)
cfg.DATASETS.TEST = ("text_val",)

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.DATALOADER.NUM_WORKERS = 4
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.0125
cfg.SOLVER.MAX_ITER = 1500
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3

cfg.TEST.EVAL_PERIOD = 500
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

```
#### Training 
```
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```

3. __Full logs__ you observed:
```
[12/10 05:12:15 d2.data.build]: Removed 0 images with no usable annotations. 401 images left.
[12/10 05:12:15 d2.data.build]: Distribution of instances among all 3 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   hindi    | 1881         |  english   | 491          |   others   | 18           |
|            |              |            |              |            |              |
|   total    | 2390         |            |              |            |              |
[12/10 05:12:15 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[12/10 05:12:15 d2.data.build]: Using training sampler TrainingSampler
[12/10 05:12:15 d2.data.common]: Serializing 401 elements to byte tensors and concatenating them all ...
[12/10 05:12:15 d2.data.common]: Serialized dataset takes 0.16 MiB

model_final_280758.pkl: 167MB [00:15, 10.6MB/s]                           
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (4, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (12, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (12,) in the model! You might want to double check if this is expected.

[12/10 05:12:37 d2.engine.train_loop]: Starting training from iteration 0

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py:217: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  num_fg = fg_inds.nonzero().numel()

[12/10 05:13:32 d2.utils.events]:  eta: 1:08:26  iter: 19  total_loss: 2.125  loss_cls: 1.03  loss_box_reg: 0.4514  loss_rpn_cls: 0.4628  loss_rpn_loc: 0.1048  time: 2.8002  data_time: 0.0577  lr: 0.00024976  max_mem: 4957M
[12/10 05:14:27 d2.utils.events]:  eta: 1:07:11  iter: 39  total_loss: 1.519  loss_cls: 0.5672  loss_box_reg: 0.7788  loss_rpn_cls: 0.07907  loss_rpn_loc: 0.05311  time: 2.7695  data_time: 0.0130  lr: 0.00049951  max_mem: 4957M
[12/10 05:15:22 d2.utils.events]:  eta: 1:06:47  iter: 59  total_loss: 1.233  loss_cls: 0.398  loss_box_reg: 0.6458  loss_rpn_cls: 0.04818  loss_rpn_loc: 0.05698  time: 2.7579  data_time: 0.0146  lr: 0.00074926  max_mem: 4957M
ERROR [12/10 05:15:44 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 688, in forward
    losses = self._forward_box(features, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 754, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 483, in losses
    self.box_reg_loss_type,
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 334, in losses
    return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 267, in box_reg_loss
    fg_inds = nonzero_tuple((self.gt_classes >= 0) & (self.gt_classes < bg_class_ind))[0]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py", line 128, in nonzero_tuple
    return x.nonzero(as_tuple=True)
RuntimeError: CUDA error: device-side assert triggered
[12/10 05:15:44 d2.engine.hooks]: Overall training speed: 65 iterations in 0:03:02 (2.8027 s / it)
[12/10 05:15:44 d2.engine.hooks]: Total training time: 0:03:02 (0:00:00 on hooks)
[12/10 05:15:44 d2.utils.events]:  eta: 1:06:33  iter: 67  total_loss: 1.216  loss_cls: 0.375  loss_box_reg: 0.617  loss_rpn_cls: 0.04435  loss_rpn_loc: 0.0666  time: 2.7588  data_time: 0.0135  lr: 0.00083668  max_mem: 4957M

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-8-159e26e6ebc2> in <module>()
      1 trainer = DefaultTrainer(cfg)
      2 trainer.resume_or_load(resume=False)
----> 3 trainer.train()

12 frames

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in train(self)
    411             OrderedDict of results, if evaluation is enabled. Otherwise None.
    412         """
--> 413         super().train(self.start_iter, self.max_iter)
    414         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    415             assert hasattr(

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    132                 for self.iter in range(start_iter, max_iter):
    133                     self.before_step()
--> 134                     self.run_step()
    135                     self.after_step()
    136                 # self.iter == max_iter can be used by `after_train` to

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in run_step(self)
    421     def run_step(self):
    422         self._trainer.iter = self.iter
--> 423         self._trainer.run_step()
    424 
    425     @classmethod

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in run_step(self)
    226         If you want to do something with the losses, you can wrap the model.
    227         """
--> 228         loss_dict = self.model(data)
    229         losses = sum(loss_dict.values())
    230 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    164             proposal_losses = {}
    165 
--> 166         _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
    167         if self.vis_period > 0:
    168             storage = get_event_storage()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in forward(***failed resolving arguments***)
    686         if self.training:
    687             assert not torch.jit.is_scripting()
--> 688             losses = self._forward_box(features, proposals)
    689             # Usually the original proposals used by the box head are used by the mask, keypoint
    690             # heads. But when `self.train_on_pred_boxes is True`, proposals will contain boxes

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in _forward_box(self, features, proposals)
    752         if self.training:
    753             assert not torch.jit.is_scripting()
--> 754             losses = self.box_predictor.losses(predictions, proposals)
    755             # proposals is modified in-place below, so losses must be computed first.
    756             if self.train_on_pred_boxes:

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self, predictions, proposals)
    481             proposals,
    482             self.smooth_l1_beta,
--> 483             self.box_reg_loss_type,
    484         ).losses()
    485         return {k: v * self.loss_weight.get(k, 1.0) for k, v in losses.items()}

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self)
    332             A dict of losses (scalar tensors) containing keys "loss_cls" and "loss_box_reg".
    333         """
--> 334         return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
    335 
    336     def predict_boxes(self):

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in box_reg_loss(self)
    265         # arg to smooth_l1_loss is False (otherwise it uses torch.mean internally
    266         # and would produce a nan loss).
--> 267         fg_inds = nonzero_tuple((self.gt_classes >= 0) & (self.gt_classes < bg_class_ind))[0]
    268         if cls_agnostic_bbox_reg:
    269             # pred_proposal_deltas only corresponds to foreground class for agnostic

/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py in nonzero_tuple(x)
    126         return x.nonzero().unbind(1)
    127     else:
--> 128         return x.nonzero(as_tuple=True)

RuntimeError: CUDA error: device-side assert triggered
```

## Observations:
1. In my search I found that people have got similar errors and were due to mismatch in the number of classes - i checked this and it seems to be correct for me. (3 number of classes)
2. I have also check the cuda version mismatch issue, which also seems to be ok in my case
3. This error occurs after a couple of iterations has been carried out. 
4. **Weird observation** - this code runs perfectly fine if I use `detectron2==0.1.3`  with `torch=1.5`

## Environment:

Provide your environment information using the following command:
```
----------------------  ---------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.18.5
detectron2              0.3 @/usr/local/lib/python3.6/dist-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0+cu101 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0                   Tesla T4 (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  8.0.1
torchvision             0.8.1+cu101 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201209
cv2                     4.1.2
----------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by ppwwyyxx** [comment]
Following https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution, could you run it under `CUDA_LAUNCH_BLOCKING=1` and provide the logs again?

**Comment by dhirajsuvarna** [comment]
@ppwwyyxx as per your suggestion did the following,

#### Set Env variable in colab
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
```

#### Error Log 
```
[12/10 08:37:02 d2.data.build]: Removed 0 images with no usable annotations. 401 images left.
[12/10 08:37:03 d2.data.build]: Distribution of instances among all 3 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   hindi    | 1881         |  english   | 491          |   others   | 18           |
|            |              |            |              |            |              |
|   total    | 2390         |            |              |            |              |
[12/10 08:37:03 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[12/10 08:37:03 d2.data.build]: Using training sampler TrainingSampler
[12/10 08:37:03 d2.data.common]: Serializing 401 elements to byte tensors and concatenating them all ...
[12/10 08:37:03 d2.data.common]: Serialized dataset takes 0.16 MiB

model_final_280758.pkl: 167MB [00:08, 20.4MB/s]                           
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (4, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (12, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (12,) in the model! You might want to double check if this is expected.

[12/10 08:37:16 d2.engine.train_loop]: Starting training from iteration 0

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py:217: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  num_fg = fg_inds.nonzero().numel()

[12/10 08:37:37 d2.utils.events]:  eta: 0:24:11  iter: 19  total_loss: 2.016  loss_cls: 1.113  loss_box_reg: 0.4051  loss_rpn_cls: 0.2657  loss_rpn_loc: 0.08211  time: 0.9726  data_time: 0.0606  lr: 0.00024976  max_mem: 4967M
[12/10 08:37:57 d2.utils.events]:  eta: 0:25:03  iter: 39  total_loss: 1.492  loss_cls: 0.5918  loss_box_reg: 0.7448  loss_rpn_cls: 0.07715  loss_rpn_loc: 0.05487  time: 1.0045  data_time: 0.0089  lr: 0.00049951  max_mem: 4967M
[12/10 08:38:18 d2.utils.events]:  eta: 0:25:09  iter: 59  total_loss: 1.243  loss_cls: 0.4254  loss_box_reg: 0.7131  loss_rpn_cls: 0.04198  loss_rpn_loc: 0.05155  time: 1.0233  data_time: 0.0100  lr: 0.00074926  max_mem: 4967M
ERROR [12/10 08:38:20 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 688, in forward
    losses = self._forward_box(features, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 754, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 483, in losses
    self.box_reg_loss_type,
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 334, in losses
    return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 243, in softmax_cross_entropy_loss
    return F.cross_entropy(self.pred_class_logits, self.gt_classes, reduction="mean")
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2264, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:115
[12/10 08:38:20 d2.engine.hooks]: Overall training speed: 59 iterations in 0:01:00 (1.0338 s / it)
[12/10 08:38:20 d2.engine.hooks]: Total training time: 0:01:01 (0:00:00 on hooks)
[12/10 08:38:20 d2.utils.events]:  eta: 0:25:10  iter: 61  total_loss: 1.226  loss_cls: 0.4065  loss_box_reg: 0.7131  loss_rpn_cls: 0.03869  loss_rpn_loc: 0.05155  time: 1.0243  data_time: 0.0098  lr: 0.00076175  max_mem: 4967M

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-11-159e26e6ebc2> in <module>()
      1 trainer = DefaultTrainer(cfg)
      2 trainer.resume_or_load(resume=False)
----> 3 trainer.train()

13 frames

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in train(self)
    411             OrderedDict of results, if evaluation is enabled. Otherwise None.
    412         """
--> 413         super().train(self.start_iter, self.max_iter)
    414         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    415             assert hasattr(

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    132                 for self.iter in range(start_iter, max_iter):
    133                     self.before_step()
--> 134                     self.run_step()
    135                     self.after_step()
    136                 # self.iter == max_iter can be used by `after_train` to

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in run_step(self)
    421     def run_step(self):
    422         self._trainer.iter = self.iter
--> 423         self._trainer.run_step()
    424 
    425     @classmethod

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in run_step(self)
    226         If you want to do something with the losses, you can wrap the model.
    227         """
--> 228         loss_dict = self.model(data)
    229         losses = sum(loss_dict.values())
    230 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    164             proposal_losses = {}
    165 
--> 166         _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
    167         if self.vis_period > 0:
    168             storage = get_event_storage()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in forward(***failed resolving arguments***)
    686         if self.training:
    687             assert not torch.jit.is_scripting()
--> 688             losses = self._forward_box(features, proposals)
    689             # Usually the original proposals used by the box head are used by the mask, keypoint
    690             # heads. But when `self.train_on_pred_boxes is True`, proposals will contain boxes

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in _forward_box(self, features, proposals)
    752         if self.training:
    753             assert not torch.jit.is_scripting()
--> 754             losses = self.box_predictor.losses(predictions, proposals)
    755             # proposals is modified in-place below, so losses must be computed first.
    756             if self.train_on_pred_boxes:

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self, predictions, proposals)
    481             proposals,
    482             self.smooth_l1_beta,
--> 483             self.box_reg_loss_type,
    484         ).losses()
    485         return {k: v * self.loss_weight.get(k, 1.0) for k, v in losses.items()}

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self)
    332             A dict of losses (scalar tensors) containing keys "loss_cls" and "loss_box_reg".
    333         """
--> 334         return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
    335 
    336     def predict_boxes(self):

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in softmax_cross_entropy_loss(self)
    241         else:
    242             self._log_accuracy()
--> 243             return F.cross_entropy(self.pred_class_logits, self.gt_classes, reduction="mean")
    244 
    245     def box_reg_loss(self):

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   2466     if size_average is not None or reduce is not None:
   2467         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2468     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   2469 
   2470 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2262                          .format(input.size(0), target.size(0)))
   2263     if dim == 2:
-> 2264         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   2265     elif dim == 4:
   2266         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:115
```

**Comment by ppwwyyxx** [comment]
Similar to existing issues your data annotation contains invalid classes.

**Comment by dhirajsuvarna** [comment]
That's awesome awesome troubleshooting!!! 
Can you throw some light on which statements in the log lead you to diagnose the issue?

**Comment by huangfeng95** [comment]
> Can you throw some light on which statements in the log lead you to diagnose the issu

@dhirajsuvarna hello,I had the same problem.Could you clarify what is "the values which were not present in my classes"? As I understand it, the category_id In the range of 0 to 2 in your case, Is this correct?

**Comment by dhirajsuvarna** [comment]
@huangfeng95 , yes, it was expected to be in the range of 0-2, but i found that somehow values other than these values were present for.eg i found one category_id = "333"

**Comment by ppwwyyxx** [comment]
It fails in the classification loss: `--> 243             return F.cross_entropy(self.pred_class_logits, self.gt_classes, reduction="mean")` so it must have invalid classes.

2bf306d63c6f1029130bd52aefbd23071709b272 was added to check such errors earlier.
