### ISSUE TITLE
the problem of  runing the BlendMask ?

### ISSUE THREAD

**Issue by gong-lei** [facebookresearch/detectron2#2374]
[12/11 11:43:01 d2.data.build]: Using training sampler TrainingSampler
[12/11 11:43:01 d2.data.common]: Serializing 117266 elements to byte tensors and concatenating them all ...
[12/11 11:43:05 d2.data.common]: Serialized dataset takes 451.21 MiB
Traceback (most recent call last):
  File "tools/train_net.py", line 246, in <module>
    args=(args,),
  File "/home/zgm/cocoapi/PythonAPI/detectron2/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 227, in main
    trainer = Trainer(cfg)                                  ## lu's modify
  File "tools/train_net.py", line 72, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given
all the requirements i  meet as same as the readme.txt,, but  why i happen the  problem  and what i should do? thanks

**Comment by ppwwyyxx** [comment]
BlendMask is not provided by this repo. Please ask in the right repo.
AdelaiDet says it requires a specific version of detectron2: https://github.com/aim-uofa/AdelaiDet#installation
