### ISSUE TITLE
Following the Tutorial in Multi-GPUs Task and Got Runtime Error

### ISSUE THREAD

**Issue by Cowboy-Lee** [facebookresearch/detectron2#2398]
Hi, friends.
I followed the tutorial "Getting Started with Detectron2" and tried to train with multi-GPUs, I got  an Runtime Error.

=========================
The command is:
```
cd tools/
python train_net.py --num-gpus 4 --config-file ../configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
```

=========================
Here is the results:
```
[12/17 16:54:32 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[12/17 16:54:32 d2.data.build]: Using training sampler TrainingSampler
Traceback (most recent call last):
  File "train_net.py", line 161, in <module>
    launch(
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/engine/launch.py", line 55, in launch
    mp.spawn(
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/lyq/tools/detectron2/tools/train_net.py", line 149, in main
    trainer = Trainer(cfg)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 284, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 467, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/config/config.py", line 201, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/config/config.py", line 236, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/data/build.py", line 318, in _train_loader_from_config
    sampler = TrainingSampler(len(dataset))
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/data/samplers/distributed_sampler.py", line 37, in __init__
    seed = comm.shared_random_seed()
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/utils/comm.py", line 230, in shared_random_seed
    all_ints = all_gather(ints)
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/utils/comm.py", line 154, in all_gather
    group = _get_global_gloo_group()
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/detectron2/utils/comm.py", line 89, in _get_global_gloo_group
    return dist.new_group(backend="gloo")
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2019, in new_group
    pg = _new_process_group_helper(group_world_size,
  File "/home/lyq/condaEnv/ML/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 504, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError: [enforce fail at /opt/conda/conda-bld/pytorch_1603729062494/work/third_party/gloo/gloo/transport/tcp/device.cc:208] ifa != nullptr. Unable to find interface for: [::1]
```

I have no idea what happened. -_-!!
Thank you very much if you could help me.

**Comment by ppwwyyxx** [comment]
Please configure the environment variables of pytorch following https://pytorch.org/docs/stable/distributed.html#common-environment-variables. If this does not work, please find help in pytorch forums as the issue does not come from detectron2.
