### ISSUE TITLE
How to use specific GPU to train my models?

### ISSUE THREAD

**Issue by ModestYjx** [facebookresearch/detectron2#2423]
Now my GPU0-3 is busy,how can i train my model in using specific GPU 4-5?
When I use the next command,it tell me memory is not enough？
Here are my commond, GPUs in using and bug:
```
python ./tools/train_net.py --num-gpus 2   --config-file ./configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
```
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:42:00.0 Off |                    0 |
| N/A   81C    P0   108W / 250W |   9831MiB / 22919MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:43:00.0 Off |                    0 |
| N/A   69C    P0    92W / 250W |  11077MiB / 22919MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:44:00.0 Off |                    0 |
| N/A   71C    P0   108W / 250W |  11371MiB / 22919MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:45:00.0 Off |                    0 |
| N/A   71C    P0   117W / 250W |   9553MiB / 22919MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           On   | 00000000:49:00.0 Off |                    0 |
| N/A   39C    P0    51W / 250W |  21812MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:4A:00.0 Off |                    0 |
| N/A   29C    P8     9W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           On   | 00000000:4B:00.0 Off |                    0 |
| N/A   25C    P8    10W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           On   | 00000000:4C:00.0 Off |                    0 |
| N/A   23C    P8    10W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     21245      C   /ssd1/anaconda3/bin/python                  9821MiB |
|    1     21246      C   /ssd1/anaconda3/bin/python                 11067MiB |
|    2     21247      C   /ssd1/anaconda3/bin/python                 11361MiB |
|    3     21248      C   /ssd1/anaconda3/bin/python                  9543MiB |
+-----------------------------------------------------------------------------+
```

```
Traceback (most recent call last):
  File "/ssd1/anaconda3/envs/yjx/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/ssd1/yjx/code/detectron2/detectron2/engine/launch.py", line 77, in _distributed_worker
    raise e
  File "/ssd1/yjx/code/detectron2/detectron2/engine/launch.py", line 71, in _distributed_worker
    dist.init_process_group(
  File "/ssd1/anaconda3/envs/yjx/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/ssd1/anaconda3/envs/yjx/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 133, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
```

Hope to  reply me when you are free,thank you very much!!

**Comment by ppwwyyxx** [comment]
> ,how can i train my model in using specific GPU 4-5?

https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
