### ISSUE TITLE
Error when converting model to onnx format

### ISSUE THREAD

**Issue by mucozcan** [facebookresearch/detectron2#2446]
I'm trying to convert my faster-RCNN model(faster_rcnn_R_101_FPN_3x) to onnx format and then to tensorRT format. But I get IndexError and can't figure out what causes this. My code: 

```
import torch.onnx
import torch
from detectron2.modeling import build_model
from detectron2.config import get_cfg
cfg = get_cfg()
cfg.merge_from_file(
    'my_model.yml'
    )
model = build_model(cfg)

model.train(False)

dummy_input = torch.randn(1, 3, 800, 1333)

state_dict = torch.load('my_model.pth')["model"]
model.load_state_dict(state_dict,strict=False)
torch.onnx.export(model, dummy_input,"my_model.onnx", export_params=True)
```

this is my full log:
```
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/tensor.py:590: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  warnings.warn('Iterating over a tensor might cause the trace to be incorrect. '
Traceback (most recent call last):
  File "/home/muco/ML-CV/person-detection-dev/pth_to_onnx.py", line 24, in <module>
    torch.onnx.export(model, dummy_input,"my_model.onnx", export_params=True)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    graph, params, torch_out = _create_jit_graph(model, args,
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 197, in inference
    images = self.preprocess_image(batched_inputs)
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 221, in preprocess_image
    images = [x["image"].to(self.device) for x in batched_inputs]
  File "/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 221, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
IndexError: too many indices for tensor of dimension 3
```

My Environment:

```
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.3 @/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.2
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1050 (arch=6.1)
CUDA_HOME               /usr/local/cuda-10.2
Pillow                  8.0.1
torchvision             0.8.2 @/home/muco/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201218
cv2                     4.4.0
----------------------  --------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 


```

**Comment by ppwwyyxx** [comment]
Failure is expected because `torch.onnx.export` doesn't work like this and the model doesn't take the input format you provided either.

We do not support running the model on tensorrt.

**Comment by mucozcan** [comment]
@ppwwyyxx can you please help me about the usage of `torch.onnx.export` ?

**Comment by ysyyork** [comment]
I'm confused, this is a lib built on top of torch and onnx is built into the torch package so I assume this is an official way. It doesn't matter about tensorrt but at least this model should support onnx to provide more use cases. onnx to tensorrt conversion is already mature so this lib doesn't need to handle that. Is it possible to modify the input format so it can help support onnx?
