### ISSUE TITLE
HOW TO TRAIN DETECTRON2+AdelaiNet

### ISSUE THREAD

**Issue by KHKHG** [facebookresearch/detectron2#2447]
## ❓ HOW TO TRAIN DETECTRON2+AdelaiNet

Datasets format is COCO，to ensure it can run，I use coco2017:
wget -c http://images.cocodataset.org/zips/train2017.zip
wget -c http://images.cocodataset.org/annotations/annotations_trainval2017.zip

wget -c http://images.cocodataset.org/zips/test2017.zip
wget -c http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip
wget -c http://images.cocodataset.org/annotations/image_info_test2017.zip
unzip train2017.zip
unzip annotations_trainval2017.zip
unzip test2017.zip
unzip stuff_annotations_trainval2017.zip
unzip image_info_test2017.zip

 AND BUGS AS FOLLOW
[01/04 16:08:56 d2.data.build]: Using training sampler TrainingSampler
Traceback (most recent call last):
  File "tools/train_net.py", line 237, in <module>
    launch(
  File "/media/user/_dev_sda6.1/AdelaiDet/detectron2/detectron2/engine/launch.py", line 55, in launch
    mp.spawn(
  File "/home/user/miniconda3/envs/ADNET/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/miniconda3/envs/ADNET/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/user/miniconda3/envs/ADNET/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/ADNET/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/media/user/_dev_sda6.1/AdelaiDet/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/media/user/_dev_sda6.1/AdelaiDet/tools/train_net.py", line 225, in main
    trainer = Trainer(cfg)
  File "/media/user/_dev_sda6.1/AdelaiDet/tools/train_net.py", line 69, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
  File "/media/user/_dev_sda6.1/AdelaiDet/detectron2/detectron2/engine/train_loop.py", line 194, in __init__
    self.model = model
AttributeError: can't set attribute

1. HOW TO FIX IT?

**Comment by ppwwyyxx** [comment]
Not an issue of this project.

Please use the latest version of https://github.com/aim-uofa/AdelaiDet/blob/master/tools/train_net.py
