### ISSUE TITLE
ImportError with matchor

### ISSUE THREAD

**Issue by guist** [facebookresearch/detectron2#2452]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

I installed a project called InstanceShadowDetection based on detectron2. I followed the installation procedure described on their website (https://github.com/stevewongv/InstanceShadowDetection/), defined a conda environment with all required packages and I ran the demo, but I got an error related to detectron2.

2. What exact command you run:
```
$ conda activate shadow_detection
$ git clone https://github.com/stevewongv/InstanceShadowDetection.git
$ cd InstanceShadowDetection
$ python setup.py install
$ cd PythonAPI
$ python setup.py install
$ cd ../projects/LISA/
$ python demo.py --input ./demo/web-shadow0573.jpg --output ./ --config ./config/LISA_101_FPN_3x_demo.yaml
```
3. __Full logs__ you observed:
```
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from predictor import VisualizationDemo
  File "/home/guillaume/InstanceShadowDetection/projects/LISA/predictor.py", line 14, in <module>
    from LISA import add_lisa_config
  File "/home/guillaume/InstanceShadowDetection/projects/LISA/LISA/__init__.py", line 3, in <module>
    from .LISA_meta_arch import LISARCNN
  File "/home/guillaume/InstanceShadowDetection/projects/LISA/LISA/LISA_meta_arch.py", line 10, in <module>
    from detectron2.modeling.postprocessing import detector_postprocess, matchor, combine_association
ImportError: cannot import name 'matchor' from 'detectron2.modeling.postprocessing' (/home/guillaume/miniconda3/envs/shadow_detection/lib/python3.7/site-packages/detectron2/modeling/postprocessing.py)
```
## Expected behavior:

I expect to get a segmented image with instances and their shadows.

## Environment:

Provide your environment information using the following command:
```
---------------------  -----------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
numpy                  1.19.2
detectron2             0.3 @/home/guillaume/miniconda3/envs/shadow_detection/lib/python3.7/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.6.0 @/home/guillaume/miniconda3/envs/shadow_detection/lib/python3.7/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.0.1
torchvision            0.7.0 @/home/guillaume/miniconda3/envs/shadow_detection/lib/python3.7/site-packages/torchvision
fvcore                 0.1.2.post20201216
cv2                    4.4.0
---------------------  -----------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
There is no such thing as "matchor". Please report bugs to the project that throws this error.
