### ISSUE TITLE
RuntimeError: Expected object of scalar type long int but got scalar type float for sequence element 1.

### ISSUE THREAD

**Issue by shilongshen** [facebookresearch/detectron2#2454]
(densepose2) wag@wag-SYS-7049GP-TRT:/home/ssl/ssl/detectron2/projects/DensePose$ python apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl image.jpg dp_contour,bbox --output image_densepose_contour.png
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

Traceback (most recent call last):
  File "apply_net.py", line 345, in <module>
    main()
  File "apply_net.py", line 341, in main
    args.func(args)
  File "apply_net.py", line 100, in execute
    cls.execute_on_outputs(context, {"file_name": file_name, "image": img}, outputs)
  File "apply_net.py", line 276, in execute_on_outputs
    image_vis = visualizer.visualize(image, data)
  File "/home/ssl/ssl/detectron2/projects/DensePose/densepose/vis/base.py", line 186, in visualize
    image = visualizer.visualize(image, data[i])
  File "/home/ssl/ssl/detectron2/projects/DensePose/densepose/vis/densepose_results.py", line 25, in visualize
    iuv_array = torch.cat((result.labels[None], result.uv * 255.0)).type(torch.uint8)
**RuntimeError: Expected object of scalar type long int but got scalar type float for sequence element 1.**

**Comment by giahaowjx** [comment]
Change line 24 of DensePoseResultsVisualizer in /detectron2/projects/DensePose/densepose/vis/densepose_results.py
to iuv_array = torch.cat((result.labels[None].type(torch.float32), result.uv * 255.0)).type(torch.uint8)
