### ISSUE TITLE
TypeError: create_context() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by shilongshen** [facebookresearch/detectron2#2456]
(densepose2) wag@wag-SYS-7049GP-TRT:/home/ssl/ssl/detectron2/projects/DensePose$ python apply_net.py dump configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl /home/ssl/ssl/dataset/Fashion-Video/image_frames/train/91-2Jb8DkfS/ --output train/91-2Jb8DkfSdump/dump.pkl -v
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

[01/07 15:48:31 apply_net]: Loading config from configs/densepose_rcnn_R_50_FPN_s1x.yaml
[01/07 15:48:31 apply_net]: Loading model from densepose_rcnn_R_50_FPN_s1x.pkl
[01/07 15:48:38 apply_net]: Loading data from /home/ssl/ssl/dataset/Fashion-Video/image_frames/train/91-2Jb8DkfS/
Traceback (most recent call last):
  File "apply_net.py", line 350, in <module>
    main()
  File "apply_net.py", line 346, in main
    args.func(args)
  File "apply_net.py", line 95, in execute
    context = cls.create_context(args, cfg)
TypeError: create_context() takes 2 positional arguments but 3 were given

**Comment by sangminwoo** [comment]
Did you manage the issue below?

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

**Comment by patodichayan** [comment]
> (densepose2) wag@wag-SYS-7049GP-TRT:/home/ssl/ssl/detectron2/projects/DensePose$ **python apply_net.py dump configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl /home/ssl/ssl/dataset/Fashion-Video/image_frames/train/91-2Jb8DkfS/ --output train/91-2Jb8DkfSdump/dump.pkl -v**
> ** fvcore version of PathManager will be deprecated soon. **
> ** Please migrate to the version in iopath repo. **
> https://github.com/facebookresearch/iopath
> 
> ** fvcore version of PathManager will be deprecated soon. **
> ** Please migrate to the version in iopath repo. **
> https://github.com/facebookresearch/iopath
> 
> [01/07 15:48:31 apply_net]: Loading config from configs/densepose_rcnn_R_50_FPN_s1x.yaml
> [01/07 15:48:31 apply_net]: Loading model from densepose_rcnn_R_50_FPN_s1x.pkl
> [01/07 15:48:38 apply_net]: Loading data from /home/ssl/ssl/dataset/Fashion-Video/image_frames/train/91-2Jb8DkfS/
> Traceback (most recent call last):
> File "apply_net.py", line 350, in
> main()
> File "apply_net.py", line 346, in main
> args.func(args)
> File "apply_net.py", line 95, in execute
> context = cls.create_context(args, cfg)
> **TypeError: create_context() takes 2 positional arguments but 3 were given**

change line 95 from "context = cls.create_context(args, cfg)" to context = cls.create_context(args)

**Comment by shilongshen** [comment]
> te to the version in i

thank you

**Comment by vkhalidov** [comment]
resolved by #2481
