### ISSUE TITLE
RuntimeError: Not compiled with GPU support although print(torch.cuda.is_available(), CUDA_HOME) successfully

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#2501]
## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. Full runnable code or full changes you made:
```
Nothing 
```
2. What exact command you run:
```
python roi_test.py

##### roi_test.py  #####
import torch
from detectron2.layers import ROIAlign
image = torch.ones(1,3,32, 32)
image = torch.ones(1,3,32, 32).cuda()
pooler = ROIAlign(output_size=(7,7), spatial_scale=1.0, sampling_ratio=0)
boxes = torch.Tensor([[1.0, 1.0, 2.0, 3.0, 4.0]]).cuda()
out = pooler(image, boxes)
```

3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "roi_test.py", line 8, in <module>
    out = pooler(image, boxes)
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 558, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/chenshoufa/workspace/detectron2_torch16dw/detectron2/layers/roi_align.py", line 106, in forward
    return roi_align(
  File "/mnt/lustre/chenshoufa/workspace/detectron2_torch16dw/detectron2/layers/roi_align.py", line 31, in forward
    output = _C.roi_align_forward(
RuntimeError: Not compiled with GPU support
```

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

```
cuobjdump info    : File '/mnt/lustre/chenshoufa/workspace/detectron2_torch16dw/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
----------------------  -----------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.18.5
detectron2              0.3 @/mnt/lustre/chenshoufa/workspace/detectron2_torch16dw/detectron2
Compiler                GCC 5.4
CUDA compiler           not available
detectron2 arch flags   /mnt/lustre/chenshoufa/workspace/detectron2_torch16dw/detectron2/_C.cpython-38-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0a0+b4553b7 @/mnt/lustre/chenshoufa/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             GeForce GTX 1080 Ti (arch=6.1)
CUDA_HOME               /mnt/lustre/share/cuda-9.0
Pillow                  8.1.0
torchvision             0.6.0a0+b68adcf @/mnt/lustre/chenshoufa/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torchvision
torchvision arch flags  6.1
fvcore                  0.1.2.post20210115
cv2                     4.5.1
----------------------  -----------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 5.4
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.1-Product Build 20201104 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 9.0
  - NVCC architecture flags: -gencode;arch=compute_61,code=sm_61
  - CuDNN 7.0.4
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=-D__STDC_FORMAT_MACROS -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DU
SE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parame
ter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-c
ast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXC
EPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```

I have tried the related solutions:

https://github.com/facebookresearch/detectron2/issues/55
https://github.com/facebookresearch/detectron2/issues/62

I build pytorch, torchvision, detectron2 all from source.

The command: `python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'`
returns:
```
True /mnt/lustre/share/cuda-9.0
```

Please let me know if you need other information.

**Comment by ShoufaChen** [comment]
Problem is solved by adding `/mnt/lustre/share/cuda-9.0`
to `~/.bashrc` and `source ~/.bashrc`

Besides,
```
CUDA_HOME=/mnt/lustre/share/cuda-9.0  python -m pip install -e detectron2
```
does **NOT** work in my case.
