### ISSUE TITLE
RuntimeError: "ROIAlign_forward" not implemented for 'Half'

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#2502]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. Full runnable code or full changes you made:
```
nothing
```
2. What exact command you run:
```
import torch
import torch.nn as nn
from detectron2.layers import ROIAlign
from torch.cuda.amp import GradScaler, autocast


class MyModel(nn.Module):
    def __init__(self, ):
        super(MyModel, self).__init__()
        self.pooler = ROIAlign(output_size=(7,7), spatial_scale=1.0, sampling_ratio=0)
        self.conv = nn.Conv2d(3, 3, 1)
    def forward(self, image, boxes):
        image = self.conv(image)
        out = self.pooler(image, boxes)
        #import pdb; pdb.set_trace()
        return out.mean()


grad_scaler = GradScaler()

mymodel = MyModel().cuda()
optimizer = torch.optim.SGD(mymodel.parameters(), lr=0.1, momentum=0.9)
image = torch.ones(1,3,32, 32).cuda()
boxes = torch.Tensor([[1.0, 1.0, 2.0, 3.0, 4.0]]).cuda()

with autocast():
    out = mymodel(image, boxes)
    loss = (out - 0.6)**2
    optimizer.zero_grad()
    grad_scaler.scale(loss).backward()
    grad_scaler.step(optimizer)
    grad_scaler.update()
    print(loss, loss.dtype)
```

3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "roi_test.py", line 27, in <module>
    out = mymodel(image, boxes)
  File "/home/visial/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "roi_test.py", line 14, in forward
    out = self.pooler(image, boxes)
  File "/home/visial/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/visial/sfc/code/detectron2/detectron2/layers/roi_align.py", line 106, in forward
    return roi_align(
  File "/home/visial/sfc/code/detectron2/detectron2/layers/roi_align.py", line 31, in forward
    output = _C.roi_align_forward(
RuntimeError: "ROIAlign_forward" not implemented for 'Half'
```

## Environment:

Provide your environment information using the following command:
```
----------------------  --------------------------------------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.3 @/home/visial/sfc/code/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0a0+4a03290 @/home/visial/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /home/visial/usr/local/cuda-10.2
Pillow                  8.1.0
torchvision             0.6.0a0+b68adcf @/home/visial/anaconda3/envs/pytorch1.6dw/lib/python3.8/site-packages/torchvision-0.6.0a0+b68adcf-py3.8-linux-x86_64.egg/torchvision
torchvision arch flags  7.5
fvcore                  0.1.2.post20210113
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment]
Half is supported if you use torchvision >= 0.7

**Comment by ShoufaChen** [comment]
Hi, @ppwwyyxx 

Is there a workaround if I can only use torchvision 0.6?
