### ISSUE TITLE
RuntimeError: when training MaskRCNN for keypoints estimation:  element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by emmeduz** [facebookresearch/detectron2#2507]
Dear all,
I would like to retrain Mask R-CNN for human pose estimation on the Coco2017 dataset. My objective is actually train the model on a custom dataset for pose estimation, but I am using coco to get familiar with the framework.

The documentation and the tutorial are pretty clear about how to set-up the framework and retrain a model. I downloaded the dataset and registered a new dataset by using the [guidelines](https://detectron2.readthedocs.io/tutorials/datasets.html).

Inference is fine and model loading too. However, I got a weird error when calling
```
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```
Below you can find the stacktrace:
```
[01/19 18:47:27 d2.engine.train_loop]: Starting training from iteration 0
ERROR [01/19 18:47:28 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/content/detectron2/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/content/detectron2/detectron2/engine/defaults.py", line 429, in run_step
    self._trainer.run_step()
  File "/content/detectron2/detectron2/engine/train_loop.py", line 236, in run_step
    losses.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
[01/19 18:47:28 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[01/19 18:47:28 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 2184M
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-169-a9e2a919bb89> in <module>()
      2 trainer = DefaultTrainer(cfg)
      3 trainer.resume_or_load(resume=False)
----> 4 trainer.train()

5 frames
/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133 
    134 

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

I was able to solve it by setting up an external training loop (not using the DefaultTrainer) and setting the `requires_grad` parameters of the `losses` variable as following:
```
losses = sum(outputs.values())
losses.requires_grad = True
```

I have few experience with PyTorch. However I do not think this workaround is the proper way of handling it. Can you provide some suggestions?

Thank you in advance

# Your Environment
I am using Google Colaboratory for all the experiments

## Instructions To Reproduce the Issue and Full Logs
The whole code can be found in [Colab](https://drive.google.com/file/d/1os9MnUObYYQpLt7DBcVSHmSJN-NlBhji/view?usp=sharing)
You can reporoduce the issue by using the following settings:
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml")) # tried all the models
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml")

cfg.DATASETS.TRAIN = ("new_coco",)

cfg.DATALOADER.NUM_WORKERS = 4
#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml") 
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.01  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 2   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon). (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
# NOTE: this config means the number of classes, but a few popular unofficial tutorials incorrect uses num_classes+1 here.
#cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 5
```

**Comment by ppwwyyxx** [comment]
We can investigate if there is full runnable code to reproduce it.

> cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 2 

May not be relevant to the problem, but this setting is not good. Please take the values used in tutorials or official configs.

**Comment by emmeduz** [comment]
Dear @ppwwyyxx,
I uploaded the whole code in this [https://drive.google.com/file/d/1os9MnUObYYQpLt7DBcVSHmSJN-NlBhji/view?usp=sharing](Colab).

I was trying several settings while investigating. However, the same behaviour occurs even with default parameters

Thanks for you prompt reply!

**Comment by ppwwyyxx** [comment]
`torch.set_grad_enabled(False)` should be removed from your code.
