### ISSUE TITLE
Export model with Caffe2Tracer to TorschScript CPU / GPU

### ISSUE THREAD

**Issue by AmiTitus** [facebookresearch/detectron2#2589]
## 📚 Documentation
Hello everyone, 
There are some points that I do not understand in the deployment process of detectron2. I've train a maskrcnn using detectron2 and now I'd like to export it in torchscript in order to load in my C++ app.
I'm testing my export in Python by doing an inference. But I do not understand why the input of my model has to be different between an export via CPU or GPU.

Below the code I'm using to perform the inference. (I've hardcoded the values so it's more clear)

```python
def export_tracing(model: Caffe2Tracer):
    torchscript_model = model.export_torchscript()
    return torchscript_model

def test_inference_torchscript(model_path):
    # Load model
    model = torch.jit.load(model_path)
     # Reshape input
    img_resized = torchvision.transforms.Resize((320, 320))(test_img_tensor).numpy()
    # Test inference
    if MODEL.DEVICE == 'cpu':
        input = (torch.Tensor([img_resized]).to('cpu'), torch.Tensor([[768., 1024., 1.]]).to('cpu'))
    else:
        input = (torch.Tensor([img_resized]).to('cuda:0'), torch.Tensor([[768., 1024., 1.], [768., 1024., 1.], [768., 1024., 1.]]).to('cuda:0'))
    res = model(input)
    return res
```

If I'm using the input like the gpu in CPU mode I'm getting this error

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/export/caffe2_modeling.py", line 16, in forward
    x = torch.div(torch.sub(data, _4, alpha=1), _3)
    _5, _6, _7, _8, _9, _10, _11, = (_2).forward(x, )
    _12 = (_1).forward(_5, _6, _7, _8, _9, im_info, )
           ~~~~~~~~~~~ <--- HERE
    _13 = (_0).forward(_12, _5, _6, _7, _10, im_info, _11, )
    _14, _15, _16, _17, = _13
  File "code/__torch__/detectron2/export/c10.py", line 23, in forward
    scores = torch.detach(_6)
    bbox_deltas = torch.detach(_7)
    _16, _17 = ops._caffe2.GenerateProposals(scores, bbox_deltas, im_info, _4, 0.25, 1000, 1000, 0.69999999999999996, 0., True, -180, 180, 1., False, None)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    scores0 = torch.detach(_8)
    bbox_deltas0 = torch.detach(_9)

Traceback of TorchScript, original code (most recent call last):
/opt/conda/lib/python3.7/site-packages/detectron2/export/c10.py(206): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/opt/conda/lib/python3.7/site-packages/detectron2/export/caffe2_modeling.py(272): forward
/opt/conda/lib/python3.7/contextlib.py(74): inner
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(940): trace_module
/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py(742): trace
/opt/conda/lib/python3.7/site-packages/detectron2/export/api.py(132): export_torchscript
export_to_cpp.py(23): export_tracing
export_to_cpp.py(107): <module>
RuntimeError: [enforce fail at generate_proposals_op.cc:289] im_info_tensor.sizes() == (vector<int64_t>{num_images, 3}). [3, 3] vs 1 3
```

Also second topic.
Exporting in ONNX and Caffe2 is totally unclear. In the documentation I can read this 

> Export the model to ONNX format. Note that the exported model contains custom ops only available in caffe2, therefore it cannot be directly executed by other runtime (such as onnxruntime or TensorRT). Post-processing or transformation passes may be applied on the model to accommodate different runtimes, but we currently do not provide support for them.

How to fix it ? Isn't there any example of how to do that ? I'm seeing many people struggling with this but I couldn't find any clear or explicit solution and I still don't know how to fix that. (e.g. AliasWithName)

* Links to the relevant documentation/comment:
https://detectron2.readthedocs.io/en/latest/modules/export.html#detectron2.export.Caffe2Tracer

**Comment by ppwwyyxx** [comment]
1. > torch.Tensor([[768., 1024., 1.], [768., 1024., 1.], [768., 1024., 1.]]).to('cuda:0'))

As the doc and logs says, `im_info` should be an 1x3 tensor. 

2.  onnx provides APIs for users to modify the graph. As you quoted, we do not provide support (including help) for running models in other runtime, but contributions are welcome.

**Comment by AmiTitus** [comment]
I would like to understand why. I also read it but why this difference between CUDA and CPU, still unclear
> As the doc and logs says, im_info should be an 1x3 tensor.

**Comment by ppwwyyxx** [comment]
> I also read it but why this difference between CUDA and CPU

There is no difference between CUDA and CPU. `im_info` should always be an 1x3 tensor.

**Comment by AmiTitus** [comment]
Okay thank you !

**Comment by AmiTitus** [comment]
Hello !
I'm really sorry to bother you again but I'm running into a new problem using the export using `export_torchscript_with_instances`.
I have the following code (everything is running on CPU):

```python
model = build_model(cfg)
DetectionCheckpointer(model).resume_or_load(cfg.MODEL.WEIGHTS)
model.eval()
export_path = 'model.pt'

assert TORCH_VERSION >= (1, 8)
fields = {
    "proposal_boxes": Boxes,
    "objectness_logits": torch.Tensor,
    "pred_boxes": Boxes,
    "scores": torch.Tensor,
    "pred_classes": torch.Tensor,
    "pred_masks": torch.Tensor,
}

ts_model: torch.jit.ScriptModule = export_torchscript_with_instances(model, fields)
ts_model.save(export_path)

test_img_tensor = torchvision.io.read_image('test_img.png')

inputs = [{"image": test_img_tensor}]
model_test: torch.jit.ScriptModule = torch.jit.load(export_path)
scripted_instance = model_test(inputs)[0].to_instances()
print(scripted_instance)
```
Using this code (it's not the full script, just the important part I think) I'm running into this issue:

```bash
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:207: UserWarning: 'keypoint_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:207: UserWarning: 'mask_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:889: UserWarning: Output 0 of SelectBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:547.)
  result = self.forward(*input, **kwargs)
Traceback (most recent call last):
  File "export_to_cpp.py", line 235, in <module>
    export_module.export()
  File "export_to_cpp.py", line 53, in export
    self.export_torchscript_scripting()
  File "export_to_cpp.py", line 112, in export_torchscript_scripting
    print(self.__test_torschript_scripting())
  File "export_to_cpp.py", line 123, in __test_torschript_scripting
    scripted_instance = model(inputs)[0].to_instances()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/modeling/meta_arch/rcnn.py", line 44, in forward
      results = results1
    if do_postprocess:
      ops.prim.RaiseException(_1)
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      _11 = _2
    else:

Traceback of TorchScript, original code (most recent call last):
  File "/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 218, in forward
    
        if do_postprocess:
            assert not torch.jit.is_scripting(), "Scripting is not supported for postprocess."
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            return GeneralizedRCNN._postprocess(results, batched_inputs, images.image_sizes)
        else:
       RuntimeError: AssertionError: Scripting is not supported for postprocess.
```
``
     So i'm editing my code to add the `do_postprocess=False` argument like following. ```scripted_instance = model(inputs, do_postprocess=False)[0].to_instances()``` . But I got the new following error:
   
```bash
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.
/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:207: UserWarning: 'mask_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:207: UserWarning: 'keypoint_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Traceback (most recent call last):
  File "export_to_cpp.py", line 235, in <module>
    export_module.export()
  File "export_to_cpp.py", line 53, in export
    self.export_torchscript_scripting()
  File "export_to_cpp.py", line 112, in export_torchscript_scripting
    print(self.__test_torschript_scripting())
  File "export_to_cpp.py", line 123, in __test_torschript_scripting
    scripted_instance = model(inputs, do_postprocess=False)[0].to_instances()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: forward() expected at most 2 argument(s) but received 3 argument(s). Declaration: forward(__torch__.detectron2.modeling.meta_arch.rcnn.GeneralizedRCNN self, (Dict(str, Tensor)) batched_inputs) -> (__torch__.detectron2.export.torchscript_patch1.ScriptedInstances1[])
```
     
Sorry again to bother you, and thank you for your help !

**Comment by ppwwyyxx** [comment]
Check https://github.com/facebookresearch/detectron2/blob/f69ba01ab102b402d2fc807a22600dcaf59a9a7d/tests/test_export_torchscript.py#L48-L56

(also note: we'll have to remove the "to_instances" method very soon and replace it by a function, due to a coming change in pytorch jit)

**Comment by AmiTitus** [comment]
Oh nice ! I've totally missed the .inference method, my bad !
Thank you

**Comment by adithyashankar-97** [comment]
Hi @AmiTitus I am trying to convert the complete maskrcnn model to torchscript inference as well.. Can you share your code for conversion and inference using torchscript?
