### ISSUE TITLE
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by chiboreache** [facebookresearch/detectron2#2616]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```python
# wget http://images.cocodataset.org/val2017/000000439715.jpg -q -O input.jpg


# Some basic setup:
# Setup detectron2 logger
import detectron2
from detectron2.utils.logger import setup_logger

setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random

# import some common detectron2 utilities
from detectron2 import model_zoo

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog


im = cv2.imread("./input.jpg")

cfg = get_cfg()
# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file(
    model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
    "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
)

predictor = DefaultPredictor(cfg)

```
2. What exact command you run: run module in terminal
3. __Full logs__ or other relevant observations:
```sh
username@asdasdads:~$ /usr/bin/python /home/username/det-test.py
Traceback (most recent call last):
  File "/home/username/det-test.py", line 36, in <module>
    predictor = DefaultPredictor(cfg)
  File "/home/username/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 216, in __init__
    self.model = build_model(self.cfg)
  File "/home/username/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
username@asdasdads:~$ 
```

## Environment:

Provide your environment information using the following command:
```sh
username@asdasd:~$ wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
----------------------  ------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.5
detectron2              0.3 @/home/username/.local/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.5
CUDA compiler           not available
detectron2 arch flags   /home/username/.local/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/home/username/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GRID V100D-8Q (arch=7.0)
CUDA_HOME               None - invalid!
Pillow                  8.1.0
torchvision             0.8.2 @/home/username/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  /home/username/.local/lib/python3.6/site-packages/torchvision/_C.so
fvcore                  0.1.3.post20210204
cv2                     4.5.1
----------------------  ------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

Unable to copy tensor to device=cuda:0: CUDA error: all CUDA-capable devices are busy or unavailable. Your CUDA environment is broken.
```

**Comment by ppwwyyxx** [comment]
> Unable to copy tensor to device=cuda:0: CUDA error: all CUDA-capable devices are busy or unavailable. Your CUDA environment is broken.

Your CUDA environment is broken and this is unrelated to detectron2.

**Comment by chiboreache** [comment]
@ppwwyyxx any ideas how to fix it? Google didn't give an anwser
