### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by yousaf446** [facebookresearch/detectron2#2624]
I am getting this issue when I try to load torhcscript model in python generated by export_model.py file

Traceback (most recent call last):
  File "test_model.py", line 38, in <module>
    model = torch.jit.load("/media/kv/11020DE711020DE7/output_X101_gpu/model.ts")
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
:
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 42
    """
    _assert_has_ops()
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 26
  _8 = __torch__.torchvision.extension._assert_has_ops
  _9 = _8()
  _10 = ops.torchvision.nms(boxes, scores, iou_threshold)
        ~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _10
'nms' is being compiled since it was called from 'batched_nms'
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 88
        offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
        boxes_for_nms = boxes + offsets[:, None]
        keep = nms(boxes_for_nms, scores, iou_threshold)
               ~~~ <--- HERE
        return keep
Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 18
    _7 = torch.slice(offsets, 0, 0, 9223372036854775807, 1)
    boxes_for_nms = torch.add(boxes, torch.unsqueeze(_7, 1), alpha=1)
    keep = __torch__.torchvision.ops.boxes.nms(boxes_for_nms, scores, iou_threshold, )
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _0 = keep
  return _0
'batched_nms' is being compiled since it was called from 'batched_nms'
Serialized   File "code/__torch__/detectron2/layers/nms.py", line 5
    idxs: Tensor,
    iou_threshold: float) -> Tensor:
  _0 = __torch__.torchvision.ops.boxes.batched_nms
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _1 = __torch__.torch.functional._return_output
  if torch.eq((torch.size(boxes))[-1], 4):
'batched_nms' is being compiled since it was called from 'find_top_rpn_proposals'
Serialized   File "code/__torch__/detectron2/modeling/proposal_generator/proposal_utils.py", line 12
  _1 = "Predicted boxes or scores contain Inf/NaN. Training has diverged."
  _2 = __torch__.detectron2.modeling.proposal_generator.proposal_utils._is_tracing
  _3 = __torch__.detectron2.layers.nms.batched_nms
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  num_images = torch.len(image_sizes)
  device = ops.prim.device(proposals[0])
'find_top_rpn_proposals' is being compiled since it was called from 'RPN.predict_proposals'
Serialized   File "code/__torch__/detectron2/modeling/proposal_generator/rpn.py", line 51
    pred_anchor_deltas: List[Tensor],
    image_sizes: List[Tuple[int, int]]) -> List[__torch__.detectron2.export.torchscript_patch1.ScriptedInstances1]:
    _11 = __torch__.detectron2.modeling.proposal_generator.proposal_utils.find_top_rpn_proposals
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _12 = __torch__.torch.autograd.grad_mode.no_grad.__new__(__torch__.torch.autograd.grad_mode.no_grad)
    _13 = (_12).__init__()
'RPN.predict_proposals' is being compiled since it was called from 'RPN.forward'
Serialized   File "code/__torch__/detectron2/modeling/proposal_generator/rpn.py", line 44
      _10 = torch.append(pred_anchor_deltas0, torch.flatten(_9, 1, -2))
    losses = annotate(Dict[str, Tensor], {})
    proposals = (self).predict_proposals(anchors, pred_objectness_logits0, pred_anchor_deltas0, images.image_sizes, )
                                                                                                ~~~~~~~~~~~~~~~~~~ <--- HERE
    return (proposals, losses)
  def predict_proposals(self: __torch__.detectron2.modeling.proposal_generator.rpn.RPN,

As torch.ops.torchvision.nms(boxes, scores, iou_threshold) is undefined so I changed it to torchvision.ops.nms(boxes, scores, iou_threshold) in following file

/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torchvision/ops/boxes.py

Now when I run the following command for generating torchscript model again

./tools/deploy/export_model.py --config-file detectron2_X-101_FPN_v1/config.yaml --output ./output_X101_gpu --export-method tracing --format torchscript MODEL.WEIGHTS detectron2_X-101_FPN_v1/model_final.pth MODEL.DEVICE cuda

I am getting following error logs

/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py:214: UserWarning: 'mask_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  "Consider removing it.".format(name))
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py:214: UserWarning: 'keypoint_on' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  "Consider removing it.".format(name))
/home/kv/Photo-Gauge/detectron2/detectron2/structures/image_list.py:92: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert t.shape[:-2] == tensors[0].shape[:-2], t.shape
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/tensor.py:559: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1613117257127/work/aten/src/ATen/native/BinaryOps.cpp:341.)
  return torch.floor_divide(self, other)
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:161: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  tensor = torch.as_tensor(tensor, dtype=torch.float32, device=device)
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert tensor.dim() == 2 and tensor.size(-1) == 4, tensor.size()
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:78: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  topk_scores_i = logits_i.narrow(1, 0, num_proposals_i)
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:79: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  topk_idx = idx.narrow(1, 0, num_proposals_i)
/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py:101: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not valid_mask.all():
/home/kv/Photo-Gauge/detectron2/detectron2/structures/boxes.py:203: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert torch.isfinite(self.tensor).all(), "Box tensor contains infinite or NaN!"
/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/tensor.py:590: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/kv/Photo-Gauge/detectron2/detectron2/layers/nms.py:16: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.shape[-1] == 4
Traceback (most recent call last):
  File "./tools/deploy/export_model.py", line 165, in <module>
    exported_model = export_tracing(torch_model, first_batch)
  File "./tools/deploy/export_model.py", line 104, in export_tracing
    ts_model = torch.jit.trace(WrapModel(), (image,))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_trace.py", line 957, in trace_module
    argument_names,
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./tools/deploy/export_model.py", line 92, in forward
    outputs = self.torch_model.inference(inputs, do_postprocess=False)[0]
  File "/home/kv/Photo-Gauge/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 207, in inference
    proposals, _ = self.proposal_generator(images, features, None)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 449, in forward
    anchors, pred_objectness_logits, pred_anchor_deltas, images.image_sizes
  File "/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 482, in predict_proposals
    self.training,
  File "/home/kv/Photo-Gauge/detectron2/detectron2/modeling/proposal_generator/proposal_utils.py", line 116, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/home/kv/Photo-Gauge/detectron2/detectron2/layers/nms.py", line 21, in batched_nms
    return box_ops.batched_nms(boxes.float(), scores, idxs, iou_threshold, count)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_trace.py", line 1110, in wrapper
    compiled_fn = script(wrapper.__original_fn)  # type: ignore
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_script.py", line 995, in script
    qualified_name, ast, _rcb, get_default_args(obj)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_recursive.py", line 766, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/_script.py", line 991, in script
    ast = get_jit_def(obj, obj.__name__)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 271, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 305, in build_def
    build_stmts(ctx, body))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 129, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 445, in build_Return
    return Return(r, None if stmt.value is None else build_expr(ctx, stmt.value))
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 589, in build_Call
    func = build_expr(ctx, expr.func)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 572, in build_Attribute
    base = build_expr(ctx, expr.value)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 572, in build_Attribute
    base = build_expr(ctx, expr.value)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 279, in __call__
    return method(ctx, node)
  File "/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch/jit/frontend.py", line 620, in build_Name
    return Var(Ident(r, expr.id))
RecursionError: maximum recursion depth exceeded while calling a Python object

My Environment

----------------------  ----------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.3 @/home/kv/Photo-Gauge/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0.dev20210212 @/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr
Pillow                  8.1.0
torchvision             0.9.0.dev20210212 @/home/kv/anaconda3/envs/detectron2-export/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20210115
cv2                     4.2.0
----------------------  ----------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

Please help.

**Comment by yousaf446** [comment]
@ppwwyyxx Can you please help?

**Comment by ppwwyyxx** [comment]
> RuntimeError:
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.

Torchvision is required and need to be imported first, in order to load the model.

**Comment by yousaf446** [comment]
@ppwwyyxx I already fixed torchvision issue. I need help regarding following issue after importing torchvision.

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by ppwwyyxx** [comment]
> As torch.ops.torchvision.nms(boxes, scores, iou_threshold) is undefined so I changed it to torchvision.ops.nms(boxes, scores, iou_threshold) in following file


This is a wrong fix. The fix is to import torchvision before loading the model.

**Comment by yousaf446** [comment]
It's already imported before the line. Please check code for boxes.py. Let me know if I need to make any change.

import torch
from torch import Tensor
from typing import Tuple
from ._box_convert import _box_cxcywh_to_xyxy, _box_xyxy_to_cxcywh, _box_xywh_to_xyxy, _box_xyxy_to_xywh
import torchvision # Torchvision already imported
from torchvision.extension import _assert_has_ops


def nms(boxes: Tensor, scores: Tensor, iou_threshold: float) -> Tensor:
    """
    Performs non-maximum suppression (NMS) on the boxes according
    to their intersection-over-union (IoU).

    NMS iteratively removes lower scoring boxes which have an
    IoU greater than iou_threshold with another (higher scoring)
    box.

    If multiple boxes have the exact same score and satisfy the IoU
    criterion with respect to a reference box, the selected box is
    not guaranteed to be the same between CPU and GPU. This is similar
    to the behavior of argsort in PyTorch when repeated values are present.

    Args:
        boxes (Tensor[N, 4])): boxes to perform NMS on. They
            are expected to be in (x1, y1, x2, y2) format
        scores (Tensor[N]): scores for each one of the boxes
        iou_threshold (float): discards all overlapping boxes with IoU > iou_threshold

    Returns:
        keep (Tensor): int64 tensor with the indices
            of the elements that have been kept
            by NMS, sorted in decreasing order of scores
    """
    _assert_has_ops()
    # return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
    return torchvision.ops.nms(boxes, scores, iou_threshold)

**Comment by ppwwyyxx** [comment]
It is required to import torchvision before loading the model, in the program that loads the model.

**Comment by yousaf446** [comment]
@ppwwyyxx Thanks a lot. I am able to run test_model.py file now.
