### ISSUE TITLE
ImportError: cannot import name '_get_trace_graph'

### ISSUE THREAD

**Issue by ramadevsaiteja** [facebookresearch/detectron2#2652]
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

Traceback (most recent call last):
  File "object_det_pipeline.py", line 31, in <module>
    from modules.deep_learning.MaskRCNN_detectron2.api import RunModel as RunModel_Object
  File "/home/Saiteja/pipeline/modules/object_detection/source/../../../modules/deep_learning/MaskRCNN_detectron2/api.py", line 3, in <module>
    from detectron2.engine import DefaultPredictor
  File "/home/Saiteja/detectron2/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/home/Saiteja/detectron2/detectron2/engine/hooks.py", line 15, in <module>
    from fvcore.nn.precise_bn import get_bn_modules, update_bn_stats
  File "/home/Saiteja/venv_Pipeline/lib/python3.6/site-packages/fvcore-0.1.3.post20210223-py3.6.egg/fvcore/nn/__init__.py", line 2, in <module>
  File "/home/Saiteja/venv_Pipeline/lib/python3.6/site-packages/fvcore-0.1.3.post20210223-py3.6.egg/fvcore/nn/activation_count.py", line 9, in <module>
  File "/home/Saiteja/venv_Pipeline/lib/python3.6/site-packages/fvcore-0.1.3.post20210223-py3.6.egg/fvcore/nn/jit_analysis.py", line 14, in <module>
ImportError: cannot import name '_get_trace_graph'

How to resolve this? Can somebody help me

## Environment:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

GPU: GeForce RTX 3070 
Cuda: 10.0

torch installation: pip3.6 install torch==1.3.1+cu100 torchvision==0.4.2+cu100 -f https://download.pytorch.org/whl/torch_stable.html

git commit ID:  94d0f13

**Comment by ppwwyyxx** [comment]
We do not support pytorch 1.3 as https://detectron2.readthedocs.io/en/latest/tutorials/install.html says

**Comment by ramadevsaiteja** [comment]
> We do not support pytorch 1.3 as https://detectron2.readthedocs.io/en/latest/tutorials/install.html says

But I am able to train and test on Ubuntu 16.04, NVIDIA TITAN RTX, CUDA 10.0 using torch 1.3

**Comment by voldemortX** [comment]
@ramadevsaiteja I met a similar issue with torch1.3 since the lastest fvcore does not support torch1.3 anymore. Rolling fvcore back to earlier versions can solve this.
For example, I use [this version](https://github.com/facebookresearch/fvcore/tree/c0ba80ac330ac08dd27ef1ce2e69c455d6f48e56). You can do this by:

```
pip uninstall fvcore
git clone https://github.com/facebookresearch/fvcore.git
cd fvcore
git checkout c0ba80ac330ac08dd27ef1ce2e69c455d6f48e56
cd ..
pip install -e fvcore
```

**Comment by ramadevsaiteja** [comment]
Just do  pip install fvcore=='0.1.dev200114'
