### ISSUE TITLE
Difficulty running DeepLab on Cityscapes – FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cityscapes/leftImg8bit/train/'

### ISSUE THREAD

**Issue by michelewang** [facebookresearch/detectron2#2664]
## Instructions To Reproduce the 🐛 Bug:
I cloned Detectron2, set up the data structure outlined [here](https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html), and ran the [exact code stated for training the model ](https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab)here: 
```
 cd /path/to/detectron2/projects/DeepLab
python train_net.py --config-file configs/Cityscapes-SemanticSegmentation/deeplab_v3_plus_R_103_os16_mg124_poly_90k_bs16.yaml --num-gpus 8
```
This was my data structure:
detectron2 /datasets contains 2 folders, gtFine and leftImg8bit which each individually have three empty folders: test, train, and val. Within the gtFine folder, I did **not ** include any generated Cityscapes panoptic annotation -- should those be included? I followed [this](https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html) for setting up my dataset structure. 
3. __Full logs__ or other relevant observations:
```
cuobjdump info    : File '/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
cuobjdump info    : File '/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
cuobjdump info    : File '/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
cuobjdump info    : File '/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
Traceback (most recent call last):
  File "train_net.py", line 132, in <module>
    launch(
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/engine/launch.py", line 55, in launch
    mp.spawn(
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/n/home07/michelewang/thesis/detectron2/projects/DeepLab/train_net.py", line 124, in main
    trainer = Trainer(cfg)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 312, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/n/home07/michelewang/thesis/detectron2/projects/DeepLab/train_net.py", line 89, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/config/config.py", line 201, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/config/config.py", line 238, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/build.py", line 310, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/build.py", line 229, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/build.py", line 229, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/datasets/builtin.py", line 208, in <lambda>
    sem_key, lambda x=image_dir, y=gt_dir: load_cityscapes_semantic(x, y)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/datasets/cityscapes.py", line 108, in load_cityscapes_semantic
    for image_file, _, label_file, json_file in _get_cityscapes_files(image_dir, gt_dir):
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/datasets/cityscapes.py", line 30, in _get_cityscapes_files
    cities = PathManager.ls(image_dir)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/iopath/common/file_io.py", line 1087, in ls
    return self.__get_path_handler(path)._ls(path, **kwargs)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/iopath/common/file_io.py", line 634, in _ls
    return os.listdir(self._get_path_with_cwd(path))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cityscapes/leftImg8bit/train/'

```

## Environment:

I downloaded the dependencies specified by DeepLab.

**Comment by ppwwyyxx** [comment]
> detectron2 /datasets contains 2 folders, gtFine and leftImg8bit 

The two folders should be inside `/cityscapes`. (https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html#expected-dataset-structure-for-cityscapes)

Also, please point `DETECTRON2_DATASETS` environment variable to the `datasets` directory  (see https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html#use-builtin-datasets)

**Comment by michelewang** [comment]
Hi, thank you so much! I just pointed the DETECTRON2_DATASETS environment variable to the datasets directory.

However, I'm still getting the same error: `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cityscapes/leftImg8bit/train/'` even though I have a train set in my folder:
![image](https://user-images.githubusercontent.com/10359314/109252822-6e1ec780-77bc-11eb-80ab-2e7b78e104f7.png)

Do you know what might be causing the issue?

**Comment by ppwwyyxx** [comment]
Then the environment variable is not in effect. You most likely need to set it before import detectron2
