### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Darkpaladi** [facebookresearch/detectron2#2686]
## Instructions To Reproduce the 🐛 Bug:

After creating an example and train dataset following these steps:

1) Create a COCO detection format dataset
2) Use PanopticApi
https://github.com/cocodataset/panopticapi/blob/master/CONVERTERS.md
COCO detection format to COCO panoptic format --> Extract semantic segmentation from data in COCO panoptic format

Full runnable code :
```
import torch, torchvision
import detectron2

# Some basic setup:
# Setup detectron2 logger
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog


# Registering dataset
from detectron2.data.datasets import register_coco_instances
register_coco_instances("example_train", {}, "datasets/example/example_train/panopticai/semantic_segmentation_coco_format.json", "datasets/example/example_train/panopticai/semantic_segmentation")
register_coco_instances("example_val", {}, "datasets/example/example_val/panopticai/semantic_segmentation_coco_format.json", "datasets/example/example_val/panopticai/semantic_segmentation")

from detectron2.engine import DefaultTrainer


cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"))
cfg.DATASETS.TRAIN = ("example_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.SOLVER.STEPS = []        # do not decay learning rate
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon). (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
cfg.INPUT.MASK_FORMAT = "bitmask"
# NOTE: this config means the number of classes, but a few popular unofficial tutorials incorrect uses num_classes+1 here.

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

# Look at training curves in tensorboard:
#%load_ext tensorboard
#%tensorboard --logdir output
```
Relevant observations:
```
[03/02 18:37:00 d2.engine.train_loop]: Starting training from iteration 0
/home/.local/lib/python3.8/site-packages/detectron2/data/detection_utils.py:414: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  torch.stack([torch.from_numpy(np.ascontiguousarray(x)) for x in masks])
ERROR [03/02 18:37:01 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/panoptic_fpn.py", line 91, in forward
    sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 163, in forward
    return None, self.losses(x, targets)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 183, in losses
    loss = F.cross_entropy(
  File "/home/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2260, in nll_loss
    if input.size(0) != target.size(0):
AttributeError: 'NoneType' object has no attribute 'size'
[03/02 18:37:01 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[03/02 18:37:01 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 3099M
Traceback (most recent call last):
  File "detect_surfer.py", line 47, in <module>
    trainer.train()
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 413, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/home/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/panoptic_fpn.py", line 91, in forward
    sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 163, in forward
    return None, self.losses(x, targets)
  File "/home/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 183, in losses
    loss = F.cross_entropy(
  File "/home/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2260, in nll_loss
    if input.size(0) != target.size(0):
AttributeError: 'NoneType' object has no attribute 'size'
```

## Expected behavior:

I expect to train the "COCO-PanopticSegmentation/panoptic_fpn_R_101_3x" model with a custom dataset.

**Comment by ppwwyyxx** [comment]
The function `register_coco_instances` is not meant for panoptic segmentation, so the error is expected. See: https://detectron2.readthedocs.io/en/latest/modules/data.html#detectron2.data.datasets.register_coco_instances 

`register_coco_panoptic_separated` is needed for PanopticFPN.

**Comment by Darkpaladi** [comment]
Thank you for answering @ppwwyyxx ,
After implementing the function into my code I get this error:

`[03/03 12:53:18 d2.data.datasets.coco]: Loaded 120 images in COCO format from /datasets/example/example_train/coco_annotations/coco_instances_surfer.json
WARNING [03/03 12:53:18 d2.data.datasets.coco]: Directory /datasets/example/example_val/panopticai/semantic_segmentation and /datasets/example/example_train/masks has 0 and 120 files, respectively.
WARNING [03/03 12:53:18 d2.data.datasets.coco]: Will use their intersection of 0 files.
[03/03 12:53:18 d2.data.datasets.coco]: Loaded 0 images with semantic segmentation from /datasets/example/example_val/panopticai/semantic_segmentation
Traceback (most recent call last):
  File "detect_surfer.py", line 78, in <module>
    trainer = DefaultTrainer(cfg) 
  File "/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 284, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 467, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/.local/lib/python3.8/site-packages/detectron2/config/config.py", line 201, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/.local/lib/python3.8/site-packages/detectron2/config/config.py", line 236, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/detectron2/data/build.py", line 301, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/.local/lib/python3.8/site-packages/detectron2/data/build.py", line 220, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/.local/lib/python3.8/site-packages/detectron2/data/build.py", line 220, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/.local/lib/python3.8/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/.local/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 142, in <lambda>
    lambda: merge_to_panoptic(
  File "/.local/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 180, in merge_to_panoptic
    assert len(sem_seg_file_to_entry) > 0
AssertionError
`
Any ideas what the problem might be? It says it has loaded 0 and 120 but the thing is I have changed the inputs in many ways and it always says 0 and 120, even though I change the order and the folder that supposedly had 120 has 0 when it is the image_root input.

**Comment by ppwwyyxx** [comment]
we don't have support now for training panoptic segmentation on custom datasets (that's https://github.com/facebookresearch/detectron2/issues/1691). So unfortunately you're on your own in figuring out what's wrong

**Comment by Darkpaladi** [comment]
Thanks @ppwwyyxx , what happened was it wanted jpg instead of pgn.
