### ISSUE TITLE
Problem in using visualizer.draw_dataset_dict()

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#2692]
Hi, I'm trying to visualize some samples of my custom dataset but cann't figout what's wrong.
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
I have already write get_dicts(), now I visualize random samples through this function:
```
def verify_load_data(dataset_dicts, num_samples, metadata):
    for d in random.sample(dataset_dicts, num_samples):
        img = cv2.imread(d["file_name"])
        visualizer = Visualizer(img[:, :, ::-1], metadata=metadata, scale=0.5)
        print(d)
        vis = visualizer.draw_dataset_dict(d)
        cv2.imwrite("samples/"+os.path.basename(d["file_name"]), vis.get_image()[:, :, ::-1]) 
    return 0
```
2. What exact command you run:
`verify_load_data(dataset_dicts, 10, vinbigdata_metadata)`
3. __Full logs__ or other relevant observations:
```
Load from cache dataset_dicts_cache_original_14class0_debug0.pkl
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/69ea3cb5de2b638097e68aa955ad1087.png', 'image_id': '69ea3cb5de2b638097e68aa955ad1087', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/6ce5bd11a68f6646835418b9df612ff1.png', 'image_id': '6ce5bd11a68f6646835418b9df612ff1', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/10c2c095faefa7a57e1869682ccfb033.png', 'image_id': '10c2c095faefa7a57e1869682ccfb033', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/74020b6dc972ca270c3ab6887efff81f.png', 'image_id': '74020b6dc972ca270c3ab6887efff81f', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/826cff99f07a59af9eca51ff161f1e08.png', 'image_id': '826cff99f07a59af9eca51ff161f1e08', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/7e3c5ce1a0c08ee25ac09948c7656387.png', 'image_id': '7e3c5ce1a0c08ee25ac09948c7656387', 'height': 256, 'width': 256, 'annotations': []}
{'file_name': 'vinbigdata-chest-xray-resized-png-256x256/train/e1c7cdc2d2faec46612191158a77a38a.png', 'image_id': 'e1c7cdc2d2faec46612191158a77a38a', 'height': 256, 'width': 256, 'annotations': [{'bbox': [35.03494176372712, 155.64954682779455, 108.51247920133112, 188.51963746223564], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 7}, {'bbox': [99.6738768718802, 152.36253776435046, 225.86356073211314, 194.41691842900303], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 3}, {'bbox': [131.51414309484193, 82.65861027190333, 162.0765391014975, 111.75830815709969], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 0}, {'bbox': [97.97004991680532, 147.72205438066464, 218.3028286189684, 187.8429003021148], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 3}, {'bbox': [148.87188019966723, 50.85196374622357, 176.23960066555742, 57.522658610271904], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 11}, {'bbox': [18.955074875207988, 169.95770392749245, 40.572379367720465, 193.16012084592145], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 10}, {'bbox': [100.95174708818635, 154.97280966767372, 221.81697171381032, 188.809667673716], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 3}, {'bbox': [130.1297836938436, 84.78549848942598, 160.79866888519135, 103.34743202416918], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 0}, {'bbox': [35.03494176372712, 155.64954682779455, 108.51247920133112, 188.51963746223564], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 4}, {'bbox': [148.87188019966723, 94.45317220543807, 161.0116472545757, 105.37764350453172], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 2}, {'bbox': [40.25291181364393, 159.80664652567975, 100.52579034941763, 173.4380664652568], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 7}, {'bbox': [24.49251247920133, 168.12084592145015, 45.89683860232945, 188.90634441087613], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 11}, {'bbox': [131.94009983361065, 82.94864048338368, 161.97004991680532, 119.78247734138972], 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'category_id': 0}]}
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    verify_load_data(dataset_dicts, 10, vinbigdata_metadata)
  File "main.py", line 37, in verify_load_data
    vis = visualizer.draw_dataset_dict(d)
  File "/home/tienpv/detectron2/detectron2/utils/visualizer.py", line 560, in draw_dataset_dict
    labels = _create_text_labels(
  File "/home/tienpv/detectron2/detectron2/utils/visualizer.py", line 247, in _create_text_labels
    labels = [l + ("|crowd" if crowd else "") for l, crowd in zip(labels, is_crowd)]
TypeError: 'NoneType' object is not iterable
```
## Expected behavior:
Element in dict is normal so why can't I draw this dict?
I expect that the program can pass this line `vis = visualizer.draw_dataset_dict(d)`
## Environment:
I confirm that my environment is ok.

Any help is appreciated! Many thanks,

**Comment by ppwwyyxx** [comment]
It seems the dataset doesn't have correct metadata for class names (https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#metadata-for-datasets) so visualizer doesn't know how to draw labels.
Although in this case it would be better to just draw the category ids.

**Comment by pvtien96** [comment]
@ppwwyyxx you're a genius! I forgot to set the metadata. It works now, thanks you.
