### ISSUE TITLE
Unable to set ignore_label in DeepLab for SemSegEvaluator in inference script

### ISSUE THREAD

**Issue by michelewang** [facebookresearch/detectron2#2706]
## Instructions To Reproduce the 🐛 Bug:
Thank you Yuxin for all of your helpful answers to my questions, I really appreciate it and the work you and your team have done making this resource!! 
Please see section 3 for a full description of my issue. The problematic code is highlighted under section 1 in the asterisks ***.
1. Full runnable code or full changes you made:
This is my  training script, train_net_xbd.py
```
#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates.

"""
DeepLab Training Script.

This script is a simplified version of the training script in detectron2/tools.
"""

import os
import torch

import detectron2.data.transforms as T
import detectron2.utils.comm as comm
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.config import get_cfg
from detectron2.data import DatasetMapper, MetadataCatalog, build_detection_train_loader
from detectron2.engine import DefaultTrainer, default_argument_parser, default_setup, launch
from detectron2.evaluation import CityscapesSemSegEvaluator, DatasetEvaluators, SemSegEvaluator
from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler

import numpy as np
import json
import matplotlib.pyplot as plt
import cv2
import random
import glob
from datetime import datetime
import pickle
from pathlib import Path
from tqdm import tqdm

from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.structures import BoxMode
from detectron2.utils.visualizer import ColorMode

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer

def build_sem_seg_train_aug(cfg):
    augs = [
        T.ResizeShortestEdge(
            cfg.INPUT.MIN_SIZE_TRAIN, cfg.INPUT.MAX_SIZE_TRAIN, cfg.INPUT.MIN_SIZE_TRAIN_SAMPLING
        )
    ]
    if cfg.INPUT.CROP.ENABLED:
        augs.append(
            T.RandomCrop_CategoryAreaConstraint(
                cfg.INPUT.CROP.TYPE,
                cfg.INPUT.CROP.SIZE,
                cfg.INPUT.CROP.SINGLE_CATEGORY_MAX_AREA,
                cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE,
            )
        )
    augs.append(T.RandomFlip())
    return augs


class Trainer(DefaultTrainer):
    """
    We use the "DefaultTrainer" which contains a number pre-defined logic for
    standard training workflow. They may not work for you, especially if you
    are working on a new research project. In that case you can use the cleaner
    "SimpleTrainer", or write your own training loop.
    """

    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        """
        Create evaluator(s) for a given dataset.
        This uses the special metadata "evaluator_type" associated with each builtin dataset.
        For your own dataset, you can simply create an evaluator manually in your
        script and do not have to worry about the hacky if-else logic here.
        """
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        evaluator_list = []
        evaluator_type = MetadataCatalog.get(dataset_name).evaluator_type
        if evaluator_type == "sem_seg":
            return SemSegEvaluator(
                dataset_name,
                distributed=True,
                output_dir=output_folder,
            )
        if evaluator_type == "cityscapes_sem_seg":
            assert (
                torch.cuda.device_count() >= comm.get_rank()
            ), "CityscapesEvaluator currently do not work with multiple machines."
            return CityscapesSemSegEvaluator(dataset_name)
        if len(evaluator_list) == 0:
            raise NotImplementedError(
                "no Evaluator for the dataset {} with the type {}".format(
                    dataset_name, evaluator_type
                )
            )
        if len(evaluator_list) == 1:
            return evaluator_list[0]
        return DatasetEvaluators(evaluator_list)

    @classmethod
    def build_train_loader(cls, cfg):
        if "SemanticSegmentor" in cfg.MODEL.META_ARCHITECTURE:
            mapper = DatasetMapper(cfg, is_train=True, augmentations=build_sem_seg_train_aug(cfg))
        else:
            mapper = None
        return build_detection_train_loader(cfg, mapper=mapper)

    @classmethod
    def build_lr_scheduler(cls, cfg, optimizer):
        """
        It now calls :func:`detectron2.solver.build_lr_scheduler`.
        Overwrite it if you'd like a different scheduler.
        """
        return build_lr_scheduler(cfg, optimizer)


def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    add_deeplab_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    default_setup(cfg, args)
    return cfg

def get_building_dicts(img_dir):
    """This function loads the JSON file created with the annotator and converts it to
    the detectron2 metadata specifications.
    """
    img_links = glob.glob(img_dir+"labels/*.json")
    # only keep the images that include post
    img_anns = list(filter(lambda x: "post" in x, img_links)) 

    dataset_dicts = []
    # loop through the entries in the JSON file
    for idx, single in enumerate(img_anns):
        v = json.load(open(single))
        record = {}
        # add file_name, image_id, height and width information to the records
        filename = os.path.join(img_dir, "images/", v["metadata"]["img_name"])
        height, width = (v["metadata"]["height"], v["metadata"]["width"])

        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width
        record["sem_seg_file_name"] = img_dir+"bin_masks/" + v["metadata"]["img_name"]
        dataset_dicts.append(record)

    return dataset_dicts


def main(args):
    # set up 
#     img_anns = glob.glob('/n/tambe_lab/Users/michelewang/train/'+"labels/*.json")
#     # the data has to be registered within detectron2, once for the train and once for
#     # the val data

    for d in ["train", "test"]:
        DatasetCatalog.register(
            "xbddata_" + d, lambda d=d: get_building_dicts("/n/tambe_lab/Users/michelewang/" + d+"/"),
        )
        MetadataCatalog.get("xbddata_"+d).stuff_classes = ["0","1","2"] 
        #*************************************THIS IS WHERE THE ISSUE IS***************************************
        MetadataCatalog.get("xbddata_"+d).evaluator_type = SemSegEvaluator(
                "xbddata_"+d,
                distributed=True,
                output_dir='./output',
                #ignore_label=-1
            )
        #*************************************THIS IS WHERE THE ISSUE IS***************************************
#         building_metadata = MetadataCatalog.get("xbddata_" + d)
    
    print("Dataset Catalog", DatasetCatalog.list())
    print("XBDDATA_TRAIN", DatasetCatalog.get("xbddata_train"))
    xbdtrain_metadata = MetadataCatalog.get("xbddata_train")
    xbdtest_metadata = MetadataCatalog.get("xbddata_test")

    cfg = setup(args)

    if args.eval_only:
        print("hi, we're in eval only")
        model = Trainer.build_model(cfg)
        print("cfg.MODEL.WEIGHTS", cfg.MODEL.WEIGHTS)
        print("cfg.OUTPUT_DIR", cfg.OUTPUT_DIR)
        DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
            cfg.MODEL.WEIGHTS, resume=args.resume
        )
        res = Trainer.test(cfg, model)
        return res

    trainer = Trainer(cfg)
    trainer.resume_or_load(resume=args.resume)
    return trainer.train()


if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    launch(
        main,
        args.num_gpus,
        num_machines=args.num_machines,
        machine_rank=args.machine_rank,
        dist_url=args.dist_url,
        args=(args,),
    )
```
2. What exact command you run:
```
#!/bin/bash
#SBATCH -p tambe_gpu # partition (queue)
#SBATCH --gres=gpu:8
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem 184000 # memory pool for all cores
#SBATCH -t 8:00:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
cd /n/home07/michelewang/thesis/detectron2/projects/DeepLab
python train_net_xbd.py --config-file configs/xBD-configs/base-deeplabv3.yaml --eval-only MODEL.WEIGHTS ./output/model_0024999.pth
```
3. __Full logs__ or other relevant observations:
I am trying to use DeepLab for image semantic segmentation. However, I've been getting errors about "ignore_label" in my evaluator for my dataset (I flagged the problem code with *** asterisks). I have two datasets, xbddata_train and xbddata_test, and I created an [SemSegEvaluator](https://detectron2.readthedocs.io/en/latest/modules/evaluation.html) for the metadata of each dataset. The Detectron2 documentation says the `ignore_label` field is deprecated so I initially did not include it (see code above), but I got this error 

```
Traceback (most recent call last):
  File "train_net_xbd.py", line 204, in <module>
    launch(
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net_xbd.py", line 170, in main
    MetadataCatalog.get("xbddata_"+d).evaluator_type = SemSegEvaluator(
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/evaluation/sem_seg_evaluation.py", line 66, in __init__
    self._ignore_label = ignore_label if ignore_label is not None else meta.ignore_label
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/data/catalog.py", line 126, in __getattr__
    raise AttributeError(
AttributeError: Attribute 'ignore_label' does not exist in the metadata of dataset 'xbddata_train'. Available keys are dict_keys(['name', 'stuff_classes']).
```

However, when I did include `ignore_label=-1` or `ignore_label=0` (i.e. uncommenting the line in the code above) I got the error:
```
SemSegEvaluator(ignore_label) is deprecated! It should be obtained from metadata.
SemSegEvaluator(ignore_label) is deprecated! It should be obtained from metadata.
cuobjdump info    : File '/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so' does not contain device code
```

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

I don't know how to create my evaluator because I get errors when I include or don't include ignore_label as an attribute of my SemSegEvaluator (which I'm using because I am doing image segmentation).

## Environment:

Provide your environment information using the following command:
```
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.3 @/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2
Compiler                GCC 9.2
CUDA compiler           not available
detectron2 arch flags   /n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla V100-PCIE-32GB (arch=7.0)
CUDA_HOME               /n/helmod/apps/centos7/Core/cuda/10.2.89-fasrc01/cuda
Pillow                  8.1.0
torchvision             0.8.2 @/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3.post20210220
cv2                     4.4.0
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by michelewang** [comment]
I think I resolved this by just setting the evaluator_type to be "sem_seg"!

**Comment by michelewang** [comment]
I think I resolved this by just setting the evaluator_type to be "sem_seg"!
