### ISSUE TITLE
DeepLab Inference seems to not be working / Unable to display predictions

### ISSUE THREAD

**Issue by michelewang** [facebookresearch/detectron2#2707]
Hi, thank you Yuxin and team for making this amazing resource and for all of your support answering questions!!!

I'm running into an issue where I think I am either **not running inference properly** or I'm just having **difficulty displaying my predictions** because I keep getting an error when trying to run `visualize_data.py`.

## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
This is my file `train_net_xbd.py` (removing imports)
```
def build_sem_seg_train_aug(cfg):
    augs = [
        T.ResizeShortestEdge(
            cfg.INPUT.MIN_SIZE_TRAIN, cfg.INPUT.MAX_SIZE_TRAIN, cfg.INPUT.MIN_SIZE_TRAIN_SAMPLING
        )
    ]
    if cfg.INPUT.CROP.ENABLED:
        augs.append(
            T.RandomCrop_CategoryAreaConstraint(
                cfg.INPUT.CROP.TYPE,
                cfg.INPUT.CROP.SIZE,
                cfg.INPUT.CROP.SINGLE_CATEGORY_MAX_AREA,
                cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE,
            )
        )
    augs.append(T.RandomFlip())
    return augs


class Trainer(DefaultTrainer):
    """
    We use the "DefaultTrainer" which contains a number pre-defined logic for
    standard training workflow. They may not work for you, especially if you
    are working on a new research project. In that case you can use the cleaner
    "SimpleTrainer", or write your own training loop.
    """
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        """
        Create evaluator(s) for a given dataset.
        This uses the special metadata "evaluator_type" associated with each builtin dataset.
        For your own dataset, you can simply create an evaluator manually in your
        script and do not have to worry about the hacky if-else logic here.
        """
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        evaluator_list = []
        evaluator_type = MetadataCatalog.get(dataset_name).evaluator_type
        if evaluator_type == "sem_seg":
            print("datasetname", dataset_name)
            return SemSegEvaluator(
                dataset_name,
                distributed=True,
                num_classes=cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES,
                ignore_label=cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE,
                output_dir=output_folder,
            )
        return DatasetEvaluators(evaluator_list)

    @classmethod
    def build_train_loader(cls, cfg):
        if "SemanticSegmentor" in cfg.MODEL.META_ARCHITECTURE:
            mapper = DatasetMapper(cfg, is_train=True, augmentations=build_sem_seg_train_aug(cfg))
        else:
            mapper = None
        return build_detection_train_loader(cfg, mapper=mapper)

    @classmethod
    def build_lr_scheduler(cls, cfg, optimizer):
        """
        It now calls :func:`detectron2.solver.build_lr_scheduler`.
        Overwrite it if you'd like a different scheduler.
        """
        return build_lr_scheduler(cfg, optimizer)


def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    add_deeplab_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    default_setup(cfg, args)
    return cfg

def get_building_dicts(img_dir):
    """This function loads the JSON file created with the annotator and converts it to
    the detectron2 metadata specifications.
    """
    img_links = glob.glob(img_dir+"labels/*.json")
    # only keep the images that include post
    img_anns = list(filter(lambda x: "post" in x, img_links)) 

    dataset_dicts = []
    # loop through the entries in the JSON file
    for idx, single in enumerate(img_anns):
        v = json.load(open(single))
        record = {}
        # add file_name, image_id, height and width information to the records
        filename = os.path.join(img_dir, "images/", v["metadata"]["img_name"])
        height, width = (v["metadata"]["height"], v["metadata"]["width"])

        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width
        record["sem_seg_file_name"] = img_dir+"bin_masks/" + v["metadata"]["img_name"]
        dataset_dicts.append(record)

    return dataset_dicts


def main(args):

    for d in ["train", "test"]:
        DatasetCatalog.register(
            "xbddata_" + d, lambda d=d: get_building_dicts("/n/tambe_lab/Users/michelewang/" + d+"/"),
        )
        MetadataCatalog.get("xbddata_"+d).stuff_classes = ["0","1","2"]
        MetadataCatalog.get("xbddata_"+d).evaluator_type = "sem_seg"
    
    print("Dataset Catalog", DatasetCatalog.list())
    print("XBDDATA_TRAIN", DatasetCatalog.get("xbddata_train"))
    xbdtrain_metadata = MetadataCatalog.get("xbddata_train")
    xbdtest_metadata = MetadataCatalog.get("xbddata_test")

    cfg = setup(args)

    if args.eval_only:
        print("hi, we're in eval only")
        model = Trainer.build_model(cfg)
        print("cfg.MODEL.WEIGHTS", cfg.MODEL.WEIGHTS)
        print("cfg.OUTPUT_DIR", cfg.OUTPUT_DIR)
        DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
            cfg.MODEL.WEIGHTS, resume=args.resume
        )
        res = Trainer.test(cfg, model)
        return res

    trainer = Trainer(cfg)
    trainer.resume_or_load(resume=args.resume)
    return trainer.train()


if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    launch(
        main,
        args.num_gpus,
        num_machines=args.num_machines,
        machine_rank=args.machine_rank,
        dist_url=args.dist_url,
        args=(args,),
    )

```
This is my file `visualize_data.py`:
```
#!/usr/bin/env python
# Copyright (c) Facebook, Inc. and its affiliates.
import argparse
import os
from itertools import chain
import cv2
import tqdm

from detectron2.config import get_cfg
from detectron2.data import DatasetCatalog, MetadataCatalog, build_detection_train_loader
from detectron2.data import detection_utils as utils
from detectron2.data.build import filter_images_with_few_keypoints
from detectron2.utils.logger import setup_logger
from detectron2.utils.visualizer import Visualizer


def setup(args):
    cfg = get_cfg()
    if args.config_file:
        cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.DATALOADER.NUM_WORKERS = 0
    cfg.freeze()
    return cfg


def parse_args(in_args=None):
    parser = argparse.ArgumentParser(description="Visualize ground-truth data")
    parser.add_argument(
        "--source",
        choices=["annotation", "dataloader"],
        required=True,
        help="visualize the annotations or the data loader (with pre-processing)",
    )
    parser.add_argument("--config-file", metavar="FILE", help="path to config file")
    parser.add_argument("--output-dir", default="./", help="path to output directory")
    parser.add_argument("--show", action="store_true", help="show output in a window")
    parser.add_argument(
        "opts",
        help="Modify config options using the command-line",
        default=None,
        nargs=argparse.REMAINDER,
    )
    return parser.parse_args(in_args)


if __name__ == "__main__":
    args = parse_args()
    logger = setup_logger()
    logger.info("Arguments: " + str(args))
    cfg = setup(args)

    dirname = args.output_dir
    os.makedirs(dirname, exist_ok=True)
    metadata = MetadataCatalog.get(cfg.DATASETS.TRAIN[0])

    def output(vis, fname):
        if args.show:
            print(fname)
            cv2.imshow("window", vis.get_image()[:, :, ::-1])
            cv2.waitKey()
        else:
            filepath = os.path.join(dirname, fname)
            print("Saving to {} ...".format(filepath))
            vis.save(filepath)

    scale = 1.0
    if args.source == "dataloader":
        train_data_loader = build_detection_train_loader(cfg)
        for batch in train_data_loader:
            for per_image in batch:
                # Pytorch tensor is in (C, H, W) format
                img = per_image["image"].permute(1, 2, 0).cpu().detach().numpy()
                img = utils.convert_image_to_rgb(img, cfg.INPUT.FORMAT)

                visualizer = Visualizer(img, metadata=metadata, scale=scale)
                target_fields = per_image["instances"].get_fields()
                labels = [metadata.thing_classes[i] for i in target_fields["gt_classes"]]
                vis = visualizer.overlay_instances(
                    labels=labels,
                    boxes=target_fields.get("gt_boxes", None),
                    masks=target_fields.get("gt_masks", None),
                    keypoints=target_fields.get("gt_keypoints", None),
                )
                output(vis, str(per_image["image_id"]) + ".jpg")
    else:
        dicts = list(chain.from_iterable([DatasetCatalog.get(k) for k in cfg.DATASETS.TRAIN]))
        if cfg.MODEL.KEYPOINT_ON:
            dicts = filter_images_with_few_keypoints(dicts, 1)
        for dic in tqdm.tqdm(dicts):
            img = utils.read_image(dic["file_name"], "RGB")
            visualizer = Visualizer(img, metadata=metadata, scale=scale)
            vis = visualizer.draw_dataset_dict(dic)
            output(vis, os.path.basename(dic["file_name"]))
```
2. What exact command you run:
This was the script I ran for inference (It finished in <1 min so I think something is wrong here):
```
cd /n/home07/michelewang/thesis/detectron2/projects/DeepLab
python train_net_xbd.py --config-file configs/xBD-configs/base-deeplabv3.yaml --eval-only MODEL.WEIGHTS ./output/model_0024999.pth
```

This was the script I ran to try to view my predictions:
```
cd /n/home07/michelewang/thesis/detectron2/tools
python visualize_data.py --source annotation --config-file ../projects/DeepLab/configs/xBD-configs/base-deeplabv3.yaml --output-dir ../projects/DeepLab/output/inference --show
```
3. __Full logs__ or other relevant observations:
Logs from Inference:
```
[5m[31mWARNING[0m [32m[03/07 21:38:53 d2.evaluation.sem_seg_evaluation]: [0mSemSegEvaluator(num_classes) is deprecated! It should be obtained from metadata.
[5m[31mWARNING[0m [32m[03/07 21:38:53 d2.evaluation.sem_seg_evaluation]: [0mSemSegEvaluator(ignore_label) is deprecated! It should be obtained from metadata.
[32m[03/07 21:38:54 d2.evaluation.evaluator]: [0mStart inference on 933 images
[32m[03/07 21:38:56 d2.evaluation.evaluator]: [0mInference done 11/933. 0.0817 s / img. ETA=0:01:55
[32m[03/07 21:39:01 d2.evaluation.evaluator]: [0mInference done 51/933. 0.0817 s / img. ETA=0:01:50
[32m[03/07 21:39:06 d2.evaluation.evaluator]: [0mInference done 70/933. 0.0817 s / img. ETA=0:02:26
[32m[03/07 21:39:11 d2.evaluation.evaluator]: [0mInference done 110/933. 0.0818 s / img. ETA=0:02:06
[32m[03/07 21:39:17 d2.evaluation.evaluator]: [0mInference done 150/933. 0.0818 s / img. ETA=0:01:54
[32m[03/07 21:39:22 d2.evaluation.evaluator]: [0mInference done 190/933. 0.0819 s / img. ETA=0:01:45
[32m[03/07 21:39:27 d2.evaluation.evaluator]: [0mInference done 229/933. 0.0820 s / img. ETA=0:01:38
[32m[03/07 21:39:32 d2.evaluation.evaluator]: [0mInference done 270/933. 0.0820 s / img. ETA=0:01:30
[32m[03/07 21:39:37 d2.evaluation.evaluator]: [0mInference done 310/933. 0.0819 s / img. ETA=0:01:24
[32m[03/07 21:39:42 d2.evaluation.evaluator]: [0mInference done 351/933. 0.0819 s / img. ETA=0:01:18
[32m[03/07 21:39:47 d2.evaluation.evaluator]: [0mInference done 391/933. 0.0819 s / img. ETA=0:01:12
[32m[03/07 21:39:52 d2.evaluation.evaluator]: [0mInference done 432/933. 0.0819 s / img. ETA=0:01:06
[32m[03/07 21:39:57 d2.evaluation.evaluator]: [0mInference done 473/933. 0.0819 s / img. ETA=0:01:00
[32m[03/07 21:40:02 d2.evaluation.evaluator]: [0mInference done 514/933. 0.0819 s / img. ETA=0:00:54
[32m[03/07 21:40:07 d2.evaluation.evaluator]: [0mInference done 554/933. 0.0818 s / img. ETA=0:00:49
[32m[03/07 21:40:12 d2.evaluation.evaluator]: [0mInference done 595/933. 0.0818 s / img. ETA=0:00:44
[32m[03/07 21:40:17 d2.evaluation.evaluator]: [0mInference done 636/933. 0.0818 s / img. ETA=0:00:38
[32m[03/07 21:40:23 d2.evaluation.evaluator]: [0mInference done 677/933. 0.0818 s / img. ETA=0:00:33
[32m[03/07 21:40:28 d2.evaluation.evaluator]: [0mInference done 717/933. 0.0818 s / img. ETA=0:00:27
[32m[03/07 21:40:33 d2.evaluation.evaluator]: [0mInference done 758/933. 0.0818 s / img. ETA=0:00:22
[32m[03/07 21:40:38 d2.evaluation.evaluator]: [0mInference done 799/933. 0.0818 s / img. ETA=0:00:17
[32m[03/07 21:40:43 d2.evaluation.evaluator]: [0mInference done 840/933. 0.0818 s / img. ETA=0:00:11
[32m[03/07 21:40:48 d2.evaluation.evaluator]: [0mInference done 881/933. 0.0818 s / img. ETA=0:00:06
[32m[03/07 21:40:53 d2.evaluation.evaluator]: [0mInference done 922/933. 0.0818 s / img. ETA=0:00:01
[32m[03/07 21:40:54 d2.evaluation.evaluator]: [0mTotal inference time: 0:01:59.094921 (0.128335 s / img per device, on 1 devices)
[32m[03/07 21:40:54 d2.evaluation.evaluator]: [0mTotal inference pure compute time: 0:01:15 (0.081782 s / img per device, on 1 devices)
[32m[03/07 21:40:56 d2.evaluation.sem_seg_evaluation]: [0mOrderedDict([('sem_seg', {'mIoU': 14.286231780375028, 'fwIoU': 30.412502468859948, 'IoU-0': 31.958253593820217, 'IoU-1': 5.555678249276511, 'IoU-2': 5.344763498028353, 'mACC': 53.518182755044954, 'pACC': 34.17634953767668, 'ACC-0': 32.13264257356594, 'ACC-1': 69.63928432518483, 'ACC-2': 58.78262136638409})])
[32m[03/07 21:40:56 d2.engine.defaults]: [0mEvaluation results for xbddata_test in csv format:
[32m[03/07 21:40:56 d2.evaluation.testing]: [0mcopypaste: Task: sem_seg
[32m[03/07 21:40:56 d2.evaluation.testing]: [0mcopypaste: mIoU,fwIoU,mACC,pACC
[32m[03/07 21:40:56 d2.evaluation.testing]: [0mcopypaste: 14.2862,30.4125,53.5182,34.1763
```

**The Semantic Segmentation JSON created in my Outputs folder, `sem_seg_predictions.json`**  -- is this normal??
![image](https://user-images.githubusercontent.com/10359314/110288187-9de87f00-7fb5-11eb-8895-068c860c7447.png)

**The Error I got from my second script to visualize_data.py:**
```
Traceback (most recent call last):
  File "visualize_data.py", line 51, in <module>
    cfg = setup(args)
  File "visualize_data.py", line 20, in setup
    cfg.merge_from_file(args.config_file)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/n/home07/michelewang/.conda/envs/active/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
```

4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:
I first ran the inference script. It ran really fast, taking less than a minute. Then I ran the script to visualize my predictions, because I wanted to see how accurate Deeplab's semantic segmentation predictions for my model were. **However, I was blocked by syntax errors for the model and I don't think I did inference correctly given that it ran so fast, and the Json file of predictions, is gibberish, but I'm not sure how to do it correctly.**

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
Showing full logs that contain the error would help. I guess you missed `add_deeplab_config(cfg)` in the second script.

Also, `visualize_data` does not visualize predictions (see https://github.com/facebookresearch/detectron2/tree/master/tools/ ).

**Comment by michelewang** [comment]
Hi @ppwwyyxx, thanks so much for your response and for pointing out that `visualize_data` does not visualize predictions, and instead just visualizes the data itself. Is there any way to visualize the predictions of DeepLab's segmentation, to see if my inference ran correctly, and to see if the model was somewhat close in its predictions? 

Also, the only outputs I received were the `sem_seg_evaluation.pth `and `sem_seg_predictions.json` files in output/inference, but my json file looked like the photo attached where it was totally unparseable – is that normal? That was why I was wondering whether inference worked and also whether there was code to turn that into masks for me. 

Thank you so much again for your response!!!

**Comment by michelewang** [comment]
I also just attached the full error log from the inference script and a different error I was getting from running `visualize_data.py` since I had attached the wrong error!

**Comment by michelewang** [comment]
@ppwwyyxx Sorry, I thought about this issue more and I think there's something wrong with my inference rather than my visualizations. Do you happen to know if this might be an inference issue, and how to resolve it? I don't think my json output is supposed to be unparseable / undecipherable so just want to make sure.

**Comment by ppwwyyxx** [comment]
To visualize the prediction: once you obtain the prediction (the mask) you can draw it use other libraries, or https://detectron2.readthedocs.io/en/latest/modules/utils.html#detectron2.utils.visualizer.Visualizer.draw_sem_seg.

The masks in the json file are encoded in COCO RLE format and is normal.

**Comment by michelewang** [comment]
thanks @ppwwyyxx , it's good to know the json file is normal! However, how does the `pycocotools/mask.py ` or [mask.pyx](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/_mask.pyx) suggested by @pieterbl86 work with the Detectron2 Json output? 

When I try to decode it by doing `m = mask_util.decode(data[0]['segmentation']['counts'])
` which is the only way I can access the RLE part of the output, I get a `TypeError: string indices must be integers`. 

My Json was something like this: 
```
{'file_name': '/n/tambe_lab/Users/michelewang/test/images/hurricane-matthew_00000118_post_disaster.png', 'category_id': 0, 'segmentation': {'size': [1024, 1024], 'counts': ']h09>K1:CGn02h2MVe05`WOK1:CGn02h2M`f09lUOFm04g2Mbf02TWOM`n0NiP`00Wo_O101O000O11N10hhe00WWZO2N20N^l2M^jf31WYVL0bTd33Yk[L4N1O1N2O1N3VTODjg0>UXOEhg0;WXOGig00dTOMb36gg0McXO3]g0McXO4]g0KcXO7\\g0HdXO9\\g0GcXO9ag0AaXO?`k0O1N2O1O2N2O1O0O10000000N3L4M2001O1HbPOL_o01YP1NQPO101OO1O`S50`lJ21Mbm?0^R@2O01N`RT14\\mkN2O0WP4NeoK7M23M2M3Mie=L[ZB1O100001OH1_POOao017OTmh02jRWO1N2N3N1O10O1N200O2O001N[^5MgaJ2G:M3N1O2N1001N7J001N10hFFkB9U=GlB7U=IlB6_f0O10Z^O0\\30dL1\\3MeL2ga0M2O0OSbS13j]lN2O1O1VFIjC6U<LkC2U<OlCOo:0Y\\O2i8Ln:3\\[O1c00mm0O_QO1e00lm0O_QO1d01lm00^QO0f00lm00^QO0g0Kom05ZQOObo00^PO0bo01]POOdo0NSme00USZO1dPOOhn00XQO0hn0OYQO0\\o00O1M4N1O1RNITTO7kk0IUTO7kk0IVTO6jk0JVTO6km0O1O1NVn`1MnQ_N00001kT4OUkK2N5ZPOKWo0`0O0O001OO1O2M2N3O2N1L4O2Mekh00\\TWO2eSO1QNLlh06RYONQNOih05VYOLQNN_h0a0aYO@Rh0b0e31001O1O1O1O1N2O]VOBec07_VOKj53fc0OdVOKg57mi01`POHUo09gPOJYo0>00O2M2O100000_OkPO7Vo0EmPO:^o0OO1O26I000O1N1O^XO0dg001OPP3OnoL4N1000O001OfGNi@0TX21__N00OUb5OQaI1gi0OYVO0oe>2jVB2O0O100000000O010000O01VUOKie04XZOMmj011OO01O00TTj00URm00fiXN2O1nPO0d=0k1Ob@1a=2]a00N1O11O4L^c6Nd\\I2O1O01NQP4OmlK2VVOOii02VVONji03R37KNO0iROGhj06RUOJlM2Rm02QUO7Zk0GWTO`0cm00100O001O0KcPOH^o08411O00fPOGnn07QQOLon03PQONPo02QQOMPo01RQOMon02SQOMil5OhRK0O1N2O1000O1O2MYb61g]I20O1NaYd00_f[O4TQh1'}} {'file_name': '/n/tambe_lab/Users/michelewang/test/images/hurricane-matthew_00000118_post_disaster.png', 'category_id': 1, 'segmentation': {'size': [1024, 1024], 'counts': '04X15jN>9ZO>7n42_J3_26cNFTOe0KJNn1S2bMYNh0HZO5O0Ij1e1B]N^O5jN>9ZO>7n42_J3_26cNFTOe0KJNn1S2bMYNh00  #THERE IS MORE, JUST DID NOT DISPLAY HERE
```
I ran this command: 
```
import pycocotools.mask as mask_util
m = mask_util.decode(data[0]['segmentation']['counts'])
```
and this was my full error trace; I'm just not sure how to resolve this since data[0]['segmentation']['counts'] seems to be the only way I can access the RLE format. 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-20-4f4ddf7b39fd> in <module>
      1 # theres gotta be a. way
----> 2 m = mask_util.decode(data[0]['segmentation']['counts'])

~/.conda/envs/active/lib/python3.8/site-packages/pycocotools/mask.py in decode(rleObjs)
     89         return _mask.decode(rleObjs)
     90     else:
---> 91         return _mask.decode([rleObjs])[:,:,0]
     92 
     93 def area(rleObjs):

pycocotools/_mask.pyx in pycocotools._mask.decode()

pycocotools/_mask.pyx in pycocotools._mask._frString()

TypeError: string indices must be integers
```

**Comment by ppwwyyxx** [comment]
The json file is not meant to be used directly. Best way to obtain prediction is to just run the model (like https://detectron2.readthedocs.io/en/latest/tutorials/models.html#use-a-model or https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5)

pycocotools probably should be used like `mask_util.decode(data[0]['segmentation'])`. But that's not related to detectron2

**Comment by michelewang** [comment]
Hi @ppwwyyxx, thanks so much for your response! I saw that section of the Colab tutorial but how would that work with DeepLab? Since the DeepLab readme here says to run an inference script.
![image](https://user-images.githubusercontent.com/10359314/110568696-6860a480-8121-11eb-9a87-ca299899157e.png)
Would I basically need to replace COCOevaluator with SemSegEvaluator and replace inference_on_dataset with part of the code from `train_net.py` in DeepLab?

**Comment by ppwwyyxx** [comment]
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=U5LhISJqWXgM this is the section that display predictions - as I understand that's the goal of this issue

**Comment by michelewang** [comment]
Sorry about that / all the questions, but I think my issue is less about displaying the predictions and rather getting predictions in an accessible way (ie masks, like is done in the tutorial). The DeepLab Readme seems to say the only way to get predictions is by running the script; does the Tutorial work for DeepLab too? I don't know if `DefaultTrainer` or `predictor` work for DeepLab.

**Comment by studentWUR** [comment]
Normally the predictor should work in DeepLab; it is also in the documentation. I tried changing the code from colab to get it working with deeplab, but I get an error using the v.draw_sem_seg(). The output of a semantic segmentation is a shape of C,H,W, but these output format is numpy float 32. v.draw_sem_seg expect an integer corresponding with the predicted label. @ppwwyyxx do you have any clue how to solve this? maybe a softmax?
`out = v.draw_sem_seg(outputs.to("cpu"))
File "/home/ubuntu16/detectron2/detectron2/utils/visualizer.py", line 439, in draw_sem_seg
    text = self.metadata.stuff_classes[label]
TypeError: list indices must be integers or slices, not numpy.float32`

`from detectron2.engine import DefaultTrainer, DefaultPredictor`
`import os`
`from itertools import chain`
`import cv2`
`import tqdm`

`from detectron2.config import get_cfg`
`from detectron2.data import DatasetCatalog, MetadataCatalog, build_detection_train_loader`
`from detectron2.utils.visualizer import Visualizer`
`from detectron2.projects.deeplab import add_deeplab_config`

`dataset_dicts = DatasetCatalog.get('cityscapes_fine_sem_seg_train')`
`metadata = MetadataCatalog.get('cityscapes_fine_sem_seg_train')`

`cfg = get_cfg()`
`add_deeplab_config(cfg)`
`cfg.merge_from_file('configs/Cityscapes-SemanticSegmentation/deeplab_v3_plus_R_103_os16_mg124_poly_90k_bs16.yaml')`
`cfg.MODEL.WEIGHTS = 'model_final_a8a355_deeplabv3+.pkl'`
`cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set a custom testing threshold`
`predictor = DefaultPredictor(cfg)`
`from detectron2.utils.visualizer import ColorMode`
`import random`
`# dataset_dicts = get_balloon_dicts("balloon/val")`
`for d in random.sample(dataset_dicts, 3): `
`    im = cv2.imread(d["file_name"])`
`    outputs = predictor(im)["sem_seg"]`
`    v = Visualizer(im[:, :, ::-1],metadata=metadata,scale=0.5) `
`    out = v.draw_sem_seg(outputs.to("cpu"))`
`    cv2_imshow(out.get_image()[:, :, ::-1])`

**Comment by git-haddadz** [comment]
> 
> 
> Normally the predictor should work in DeepLab; it is also in the documentation. I tried changing the code from colab to get it working with deeplab, but I get an error using the v.draw_sem_seg(). The output of a semantic segmentation is a shape of C,H,W, but these output format is numpy float 32. v.draw_sem_seg expect an integer corresponding with the predicted label. @ppwwyyxx do you have any clue how to solve this? maybe a softmax?
> `out = v.draw_sem_seg(outputs.to("cpu")) File "/home/ubuntu16/detectron2/detectron2/utils/visualizer.py", line 439, in draw_sem_seg text = self.metadata.stuff_classes[label] TypeError: list indices must be integers or slices, not numpy.float32`
> 
> `from detectron2.engine import DefaultTrainer, DefaultPredictor`
> `import os`
> `from itertools import chain`
> `import cv2`
> `import tqdm`
> 
> `from detectron2.config import get_cfg`
> `from detectron2.data import DatasetCatalog, MetadataCatalog, build_detection_train_loader`
> `from detectron2.utils.visualizer import Visualizer`
> `from detectron2.projects.deeplab import add_deeplab_config`
> 
> `dataset_dicts = DatasetCatalog.get('cityscapes_fine_sem_seg_train')`
> `metadata = MetadataCatalog.get('cityscapes_fine_sem_seg_train')`
> 
> `cfg = get_cfg()`
> `add_deeplab_config(cfg)`
> `cfg.merge_from_file('configs/Cityscapes-SemanticSegmentation/deeplab_v3_plus_R_103_os16_mg124_poly_90k_bs16.yaml')`
> `cfg.MODEL.WEIGHTS = 'model_final_a8a355_deeplabv3+.pkl'`
> `cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7 # set a custom testing threshold`
> `predictor = DefaultPredictor(cfg)`
> `from detectron2.utils.visualizer import ColorMode`
> `import random`
> `# dataset_dicts = get_balloon_dicts("balloon/val")`
> `for d in random.sample(dataset_dicts, 3): `
> ` im = cv2.imread(d["file_name"])`
> ` outputs = predictor(im)["sem_seg"]`
> ` v = Visualizer(im[:, :, ::-1],metadata=metadata,scale=0.5)`
> ` out = v.draw_sem_seg(outputs.to("cpu"))`
> ` cv2_imshow(out.get_image()[:, :, ::-1])`

@studentWUR I have the same problem did you find a solution to obtain integer label from the prediction? or any other solution to visualize the prediction of the Deeplab? thanks

**Comment by studentWUR** [comment]
I had the following solution. It works for my custom dataset in which my background correspond with an output of '0'. For the cityscapes every class works, except for the background class. Of course it is also possible to write a custom drawing function since the output is already an integer. 

`    values2, outputs2 = torch.max(F.softmax(outputs,dim=0),axis=0)`
`out = v.draw_sem_seg(outputs2.to("cpu"))`

**Comment by ananthu-aniraj** [comment]
Hi everyone, this is the code that works for me (for DeepLab inference). This can be used for running deeplab on a webcam:
`cap = cv2.VideoCapture(0)
cfg_file = "configs/custom_configs/deeplab_v3_plus_R_103_os16_mg124_poly_90k_bs16_imow_without_background.yaml"
cfg = get_cfg()
add_deeplab_config(cfg)
cfg.merge_from_file(cfg_file)
cfg.INPUT.CROP.ENABLED = False
cfg.MODEL.WEIGHTS = "output/model_v3_plus_without_bg_c1.pth"
cfg.freeze()
predictor = DefaultPredictor(cfg)



while(cap.isOpened()):
    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret==True:
    
        outputs = predictor(frame)

        #print(outputs.keys())
        v = Visualizer(frame[:,:,::-1],
                        metadata=val_metadata_imow_nb,
                        scale=1,
                        instance_mode=ColorMode.SEGMENTATION
                        )


        sem_seg = torch.max(outputs["sem_seg"],dim=0)[1]
        sem_seg = sem_seg.to("cpu")
        sem_seg = sem_seg.numpy()
        cv2.imshow("Image",frame)


        out = v.draw_sem_seg(sem_seg, area_threshold=None, alpha=0.8)
        
        cv2.imshow("Seg_out",out.get_image()[:, :, ::-1])
        # Display the resulting frame

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# When everything is done, release the capture
cap.release()

cv2.destroyAllWindows()`

**Comment by hydrangea3000** [comment]
Hello @ppwwyyxx , 
Could you please help with the similar issue:
'''
cfg = get_cfg()
add_deeplab_config(cfg)

cfg_path = 'C:/Users/.../detectron2/projects/Panoptic-DeepLab/configs/Cityscapes-PanopticSegmentation/'

yaml =  "panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml"
cfg.merge_from_file(cfg_path + yaml)

'''
And I get error  KeyError: 'Non-existent config key: MODEL.SEM_SEG_HEAD.HEAD_CHANNELS'

same code for Object detecion on COCO (from /detectron2/configs/)  works without errors
