### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/detectron2#2745]
python -m pip install -e detectron2  happen  error

**Comment by mathpopo** [comment]
[error.log](https://github.com/facebookresearch/detectron2/files/6139411/error.log)
Obtaining file:///home/chenxin/Downloads/d2go/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (1.1.0)
Requirement already satisfied: Pillow>=7.1 in /home/chenxin/.local/lib/python3.6/site-packages/Pillow-8.1.0-py3.6-linux-x86_64.egg (from detectron2==0.4) (8.1.0)
Requirement already satisfied: yacs>=0.1.6 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.1.8)
Requirement already satisfied: tabulate in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.8.9)
Requirement already satisfied: cloudpickle in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (1.6.0)
Requirement already satisfied: matplotlib in /home/chenxin/.local/lib/python3.6/site-packages (from detectron2==0.4) (3.3.2)
Requirement already satisfied: tqdm>4.29.0 in /home/chenxin/.local/lib/python3.6/site-packages (from detectron2==0.4) (4.31.1)
Requirement already satisfied: tensorboard in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (2.4.1)
Requirement already satisfied: fvcore<0.1.4,>=0.1.3 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.1.3.post20210311)
Requirement already satisfied: iopath>=0.1.2 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.1.6)
Requirement already satisfied: pycocotools>=2.0.2 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (2.0.2)
Requirement already satisfied: future in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.18.2)
Requirement already satisfied: pydot in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (1.4.2)
Requirement already satisfied: omegaconf>=2 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (2.0.6)
Requirement already satisfied: dataclasses in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from detectron2==0.4) (0.8)
Requirement already satisfied: numpy in /home/chenxin/.local/lib/python3.6/site-packages (from fvcore<0.1.4,>=0.1.3->detectron2==0.4) (1.17.3)
Requirement already satisfied: pyyaml>=5.1 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from fvcore<0.1.4,>=0.1.3->detectron2==0.4) (5.4.1)
Requirement already satisfied: portalocker in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from iopath>=0.1.2->detectron2==0.4) (2.2.1)
Requirement already satisfied: typing-extensions in /home/chenxin/.local/lib/python3.6/site-packages (from omegaconf>=2->detectron2==0.4) (3.7.4.2)
Requirement already satisfied: setuptools>=18.0 in /home/chenxin/.local/lib/python3.6/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (47.1.1)
Requirement already satisfied: cython>=0.27.3 in /home/chenxin/.local/lib/python3.6/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (0.29.21)
Requirement already satisfied: certifi>=2020.06.20 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from matplotlib->detectron2==0.4) (2020.12.5)
Requirement already satisfied: cycler>=0.10 in /home/chenxin/.local/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg (from matplotlib->detectron2==0.4) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/chenxin/.local/lib/python3.6/site-packages/python_dateutil-2.8.0-py3.6.egg (from matplotlib->detectron2==0.4) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/chenxin/.local/lib/python3.6/site-packages/kiwisolver-1.1.0-py3.6-linux-x86_64.egg (from matplotlib->detectron2==0.4) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/chenxin/.local/lib/python3.6/site-packages/pyparsing-2.4.2-py3.6.egg (from matplotlib->detectron2==0.4) (2.4.2)
Requirement already satisfied: six in /home/chenxin/.local/lib/python3.6/site-packages (from cycler>=0.10->matplotlib->detectron2==0.4) (1.15.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/chenxin/.local/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (3.12.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (0.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (1.27.1)
Requirement already satisfied: markdown>=2.6.8 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (3.3.4)
Requirement already satisfied: absl-py>=0.4 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (0.12.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (1.8.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (1.0.1)
Requirement already satisfied: grpcio>=1.24.3 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (1.36.1)
Requirement already satisfied: wheel>=0.26 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from tensorboard->detectron2==0.4) (0.36.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (1.3.0)
Requirement already satisfied: importlib-metadata in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard->detectron2==0.4) (3.7.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (1.26.3)
Requirement already satisfied: oauthlib>=3.0.0 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (3.1.0)
Requirement already satisfied: zipp>=0.5 in /home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard->detectron2==0.4) (3.4.1)

**Comment by mathpopo** [comment]
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2

**Comment by mathpopo** [comment]
/home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    FAILED: /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    nvcc fatal   : Could not open output file '/tmp/tmpxft_0000426a_00000000'
    [4/6] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    FAILED: /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    nvcc fatal   : Could not open output file '/tmp/tmpxft_0000426b_00000000'
    [5/6] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/cuda_version.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/cuda_version.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    FAILED: /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/cuda_version.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/cuda_version.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/cuda_version.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    nvcc fatal   : Could not open output file '/tmp/tmpxft_0000426d_00000000'
    [6/6] /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    FAILED: /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o
    /usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/TH -I/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chenxin/anaconda/envs/d2go/include/python3.6m -c -c /home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/chenxin/Downloads/d2go/detectron2/build/temp.linux-x86_64-3.6/home/chenxin/Downloads/d2go/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
    nvcc fatal   : Could not open output file '/tmp/tmpxft_0000426c_00000000'
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
        env=env)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/chenxin/Downloads/d2go/detectron2/setup.py", line 238, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/home/chenxin/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/chenxin/.local/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/chenxin/.local/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/chenxin/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/chenxin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/home/chenxin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/chenxin/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/chenxin/anaconda/envs/d2go/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/chenxin/anaconda/envs/d2go/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/chenxin/Downloads/d2go/detectron2/setup.py'"'"'; __file__='"'"'/home/chenxin/Downloads/d2go/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by wshilaji** [comment]
How did you solve it？

**Comment by wshilaji** [comment]
> chenxin

Can I add you a wechat？

**Comment by Tony-Hou** [comment]
How to fix the issue?
