### ISSUE TITLE
Can not run on pytorch docker image

### ISSUE THREAD

**Issue by matthewchung74** [facebookresearch/detectron2#2771]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
# get this docker image https://hub.docker.com/r/pytorch/pytorch
docker pull pytorch/pytorch
# run it
docker run --rm -it  pytorch/pytorch:latest
# https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html prebuilt 1.8 cpu
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.8/index.html
```

in python shell
```
import dectron2.engine

```
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
>>> import dectron2.engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dectron2'
>>> import detectron2
>>> import detectron2.engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/hooks.py", line 18, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/opt/conda/lib/python3.7/site-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/opt/conda/lib/python3.7/site-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/opt/conda/lib/python3.7/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/opt/conda/lib/python3.7/site-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/opt/conda/lib/python3.7/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/opt/conda/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
>>> ```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
NA
## Expected behavior:

would expect import to work
## Environment:
# get this docker image https://hub.docker.com/r/pytorch/pytorch

Provide your environment information using the following command:
```

```
(base) root@7e9e58fcb0cf:~# python -m detectron2.utils.collect_env
---------------------  -------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
numpy                  1.19.2
detectron2             0.4 @/opt/conda/lib/python3.7/site-packages/detectron2
detectron2._C          not built correctly: libcudart.so.10.1: cannot open shared object file: No such file or directory
Compiler ($CXX)        c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.8.0 @/opt/conda/lib/python3.7/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.1.1
torchvision            0.9.0 @/opt/conda/lib/python3.7/site-packages/torchvision
fvcore                 0.1.3.post20210317
cv2                    Not found
---------------------  -------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by ppwwyyxx** [comment]
The given instructions are incomplete (missing gcc) and when I added gcc installation, it does not reproduce any failure: https://asciinema.org/a/gr0TkCK3aYzJsyO05x3c0Q9pt
