### ISSUE TITLE
BBox conversion error to coco format.

### ISSUE THREAD

**Issue by djaym7** [facebookresearch/detectron2#2801]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```zzz
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>z
```zz
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
<put logs here>
```zzz
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:
zzz
If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
zzz
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

sys.platform linux
Python 3.6.10 |Anaconda, Inc.| (default, Jan 7 2020, 21:14:29) [GCC 7.3.0]
numpy 1.18.1
detectron2 0.4 @/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2
Compiler GCC 7.3
CUDA compiler CUDA 10.1
detectron2 arch flags 7.0
DETECTRON2_ENV_MODULE
PyTorch 1.7.0 @/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch
PyTorch debug build True
GPU available True
GPU 0 Tesla V100-SXM2-16GB (arch=7.0)
CUDA_HOME /usr/local/cuda-10.1
Pillow 8.0.1
torchvision 0.8.1 @/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torchvision
torchvision arch flags 3.5, 5.0, 6.0, 7.0, 7.5
fvcore 0.1.3.post20210317
cv2 4.5.1

PyTorch built with:

GCC 7.3
C++ Version: 201402
Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
OpenMP 201511 (a.k.a. OpenMP 4.5)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 10.1
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
CuDNN 7.6.3
Magma 2.5.2
Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
TEST:
AUG:
ENABLED: False
FLIP: True
MAX_SIZE: 4000
MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
DETECTIONS_PER_IMAGE: 100
EVAL_PERIOD: 0
EXPECTED_RESULTS: []
KEYPOINT_OKS_SIGMAS: []
PRECISE_BN:
ENABLED: False
NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0
VIS_THRESH: 0.3

[03/23 23:59:52 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[03/23 23:59:52 d2.data.common]: Serializing 598 elements to byte tensors and concatenating them all ...
[03/23 23:59:52 d2.data.common]: Serialized dataset takes 1.48 MiB
WARNING [03/23 23:59:52 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[03/23 23:59:52 d2.evaluation.coco_evaluation]: 'val_ds7' is not registered by register_coco_instances. Therefore trying to convert it to COCO format ...
[03/23 23:59:52 d2.data.datasets.coco]: Converting annotations of dataset 'val_ds7' to COCO format ...)
[03/24 00:00:36 d2.data.datasets.coco]: Converting dataset dicts into COCO format
Traceback (most recent call last):
File "train_net.py", line 247, in
args=(args,),
File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
main_func(*args)
File "train_net.py", line 212, in main
return do_test(cfg, model)
File "train_net.py", line 57, in do_test
evaluator = COCOEvaluator(dataset_name, cfg, True, output_folder)
File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2/evaluation/coco_evaluation.py", line 111, in init
convert_to_coco_json(dataset_name, cache_path)
File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2/data/datasets/coco.py", line 459, in convert_to_coco_json
coco_dict = convert_to_coco_dict(dataset_name)
File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2/data/datasets/coco.py", line 358, in convert_to_coco_dict
bbox = BoxMode.convert(bbox, from_bbox_mode, to_bbox_mode)
File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/detectron2/structures/boxes.py", line 123, in convert
arr[:, 2] -= arr[:, 0]
IndexError: too many indices for tensor of dimension 1

**Comment by djaym7** [comment]
array([552.,  79., 727., 380.]) and

**Comment by djaym7** [comment]
Proposed changes : 
file - detectron2/structures/boxes.py

add to line 65 : 
`        reshape_on_return=False
        if len(box.shape)==1:
            box=box.reshape(1,-1)
            reshape_on_return=True
`
at line 131:

`
if reshape_on_return:
            arr = arr.reshape(-1)
`

**Comment by djaym7** [comment]
@ppwwyyxx @SuperIRabbit @sampepose  @chenbohua3 @apivovarov @SplitInfinity @Trouble404 @pakornvs
simple PR

**Comment by ppwwyyxx** [comment]
I believe your dataset does not follow the format we documented in https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html.

If further help is needed to investigate the issue, please provide reproducible instructions following the issue template.

**Comment by djaym7** [comment]
It follows the same format bbox : list of 4 floats!

**Comment by djaym7** [comment]
bbox (list[float], required): list of 4 numbers representing the bounding box of the instance.

arr is arr/list of shape 4, dtype=float

**Comment by ppwwyyxx** [comment]
> If further help is needed to investigate the issue, please provide reproducible instructions following the issue template.

**Comment by SuperIRabbit** [comment]
> if len(box.shape)==1:

Could you print out the content of `box` you are using here?

**Comment by djaym7** [comment]
https://github.com/facebookresearch/detectron2/issues/2801#issuecomment-805378275 this is where i posted it

**Comment by SuperIRabbit** [comment]
> [#2801 (comment)](https://github.com/facebookresearch/detectron2/issues/2801#issuecomment-805378275) this is where i posted it

What you posted was `arr`, but `arr` is derived from `box` - so what is the `box` you are using?

**Comment by djaym7** [comment]
arr is not derived, it is the copy of box. Here is the datadict which had no problems in training model.
![image](https://user-images.githubusercontent.com/12378820/112393684-b694ac80-8cb8-11eb-8df2-c24788a77917.png)

**Comment by djaym7** [comment]
Modified from array to list and testing if that is handled
![image](https://user-images.githubusercontent.com/12378820/112394049-46d2f180-8cb9-11eb-83ce-4f800f2b53a8.png)

**Comment by djaym7** [comment]
Hence edge cases found are :

1] single box -type==list ------------not converted to numpy!
2] single box -type==np.arr ---------not handled well while slicing


Proposed changes :
convert the box to numpy even if its a single box by putting https://github.com/facebookresearch/detectron2/blob/bbfd61ea76da6228e73c4c0195c394a2337b8f98/detectron2/structures/boxes.py#L77 outside else.

file - detectron2/structures/boxes.py

add to line 65 : 

`
reshape_on_return=False;
if len(box.shape)==1:
        box=box.reshape(1,-1)
        reshape_on_return=True
`
at line 131:
if reshape_on_return: arr = arr.reshape(-1)

**Comment by ppwwyyxx** [comment]
So it is true that your data does not follow the format documented in https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html.

Though it makes sense to add support for it in `BoxMode.convert`

**Comment by ppwwyyxx** [comment]
Closing as the code is working correctly when the format is correct.

Feel free to submit PR to let `BoxMode.convert` support 1d numpy array.

**Comment by djaym7** [comment]
yes, I assumed list and arrays would be handled but only list is supported as of now ...
