### ISSUE TITLE
AttributeError: module 'portalocker' has no attribute 'Lock'

### ISSUE THREAD

**Issue by Wei-i** [facebookresearch/detectron2#2825]
I am sorry that I have a bug when I use
python ./tools/train_net.py --num-gpus 1 --config-file ./configs/yolof_R_50_C5_1x.yaml

Bug log below as :

[03/26 07:38:03 d2.data.build]: Using training sampler TrainingSampler
[03/26 07:38:03 d2.data.common]: Serializing 117266 elements to byte tensors and concatenating them all ...
[03/26 07:38:10 d2.data.common]: Serialized dataset takes 451.21 MiB
[03/26 07:38:15 fvcore.common.checkpoint]: Loading checkpoint from detectron2://ImageNetPretrained/MSRA/R-50.pkl
Traceback (most recent call last):
File "./tools/train_net.py", line 234, in
args=(args,),
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
main_func(*args)
File "./tools/train_net.py", line 215, in main
trainer.resume_or_load(resume=args.resume)
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 353, in resume_or_load
checkpoint = self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
return self.load(path, checkpointables=[])
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 140, in load
path = self.path_manager.get_local_path(path)
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/iopath/common/file_io.py", line 1100, in get_local_path
path, force=force, **kwargs
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/detectron2/utils/file_io.py", line 29, in _get_local_path
return PathManager.get_local_path(self.S3_DETECTRON2_PREFIX + name, **kwargs)
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/iopath/common/file_io.py", line 1100, in get_local_path
path, force=force, **kwargs
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/iopath/common/file_io.py", line 755, in _get_local_path
with file_lock(cached):
File "/home/cw/miniconda3/envs/yolof/lib/python3.6/site-packages/iopath/common/file_io.py", line 82, in file_lock
return portalocker.Lock(path + ".lock", timeout=3600) # type: ignore
AttributeError: module 'portalocker' has no attribute 'Lock'

It seems that there may be wrong with 'Loading checkpoint from detectron2://ImageNetPretrained/MSRA/R-50.pkl
'?
I woule be grateful if you could give me some advice. Thanks.

**Comment by ppwwyyxx** [comment]
`portalocker` has `Lock` according to its official documentation: https://pypi.org/project/portalocker/

It seems this dependency is not installed correctly, that's unrelated to detectron2.

**Comment by Wei-i** [comment]
first
pip uninstall portalocker
and
conda install portalocker
then bug will be fixed.

 Thanks a lot for your help!
