### ISSUE TITLE
GPU failed to start. CUDA driver initialization failed, you might not have a CUDA gpu.

### ISSUE THREAD

**Issue by huang229** [facebookresearch/detectron2#2847]
I installed detectron2 with the following command:
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/index.html

I'm ready for the data and weight files, too.
input1.jpg 
input2.jpg
model_final_f10217.pkl

Test in window demo.py , error:

(pytorch1.8.0) huang@ubuntu:/detectron2/demo$ python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.jpg input2.jpg [--other-options] --opts MODEL.WEIGHTS ../configs/COCO-InstanceSegmentation/model_final_f10217.pkl
[03/31 16:18:10 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['input1.jpg', 'input2.jpg', '[--other-options]'], opts=['MODEL.WEIGHTS', '../configs/COCO-InstanceSegmentation/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 82, in <module>
    demo = VisualizationDemo(cfg)
  File "/media/disk1/03_Al_Group/HCL/project-python/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 216, in __init__
    self.model = build_model(self.cfg)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/huangchaolin/anaconda3/envs/pytorch1.8.0/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

**Comment by huang229** [comment]
@github-actions  okay, thank you.
