### ISSUE TITLE
Error when training 2 GPUs on 1 device

### ISSUE THREAD

**Issue by kangdaejang** [facebookresearch/detectron2#2861]
1. Full runnable code or full changes you made:
```
from detectron2.engine import launch

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False) 
launch(main_func=trainer.train(), num_gpus_per_machine=2, dist_url="auto")

```
2. What exact command you run:
I'm coding a Jupyter notebook, and I got an error with the following command:
launch(main_func=trainer.train(), num_gpus_per_machine=2, dist_url="auto")

I have referenced the following:
https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html#training-evaluation-in-command-line

https://github.com/facebookresearch/detectron2/issues/753

3. __Full logs__ or other relevant observations:
```
[04/02 06:29:08 d2.engine.train_loop]: Starting training from iteration 0
[04/02 06:29:18 d2.utils.events]:  eta: 0:00:00  iter: 19  total_loss: 2.574  loss_cls: 0.931  loss_box_reg: 0.5276  loss_mask: 0.6911  loss_rpn_cls: 0.355  loss_rpn_loc: 0.05296  time: 0.4628  data_time: 0.0132  lr: 1.9981e-06  max_mem: 4727M
[04/02 06:29:18 d2.engine.hooks]: Overall training speed: 18 iterations in 0:00:08 (0.4628 s / it)
[04/02 06:29:18 d2.engine.hooks]: Total training time: 0:00:09 (0:00:00 on hooks)
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
<ipython-input-35-b6f07aa0badf> in <module>
      5 #trainer = MyTrainer(cfg)
      6 trainer.resume_or_load(resume=False)
----> 7 launch(main_func=trainer.train(), num_gpus_per_machine=2, dist_url="auto")

/notebooks/detectron2_repo/detectron2/engine/launch.py in launch(main_func, num_gpus_per_machine, num_machines, machine_rank, dist_url, args)
     58             _distributed_worker,
     59             nprocs=num_gpus_per_machine,
---> 60             args=(main_func, world_size, num_gpus_per_machine, machine_rank, dist_url, args),
     61             daemon=False,
     62         )

~/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    228                ' torch.multiprocessing.start_process(...)' % start_method)
    229         warnings.warn(msg)
--> 230     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

~/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

~/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    148         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    149         msg += original_trace
--> 150         raise ProcessRaisedException(msg, error_index, failed_process.pid)
    151 
    152 

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/notebooks/detectron2_repo/detectron2/engine/launch.py", line 101, in _distributed_worker
    main_func(*args)
TypeError: 'NoneType' object is not callable

```

## Expected behavior: 
Training completed with 2 GPUs

## Environment:

Paste the output of the following command:
```
----------------------  -------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
numpy                   1.19.5
detectron2              0.3 @/notebooks/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0+cu101 @/home/appuser/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
TORCH_CUDA_ARCH_LIST    Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing
Pillow                  8.1.2
torchvision             0.9.0+cu101 @/home/appuser/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3
cv2                     4.5.1
----------------------  -------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

```

**Comment by ppwwyyxx** [comment]
`launch` function is not correctly used. Please follow its documentation https://detectron2.readthedocs.io/en/latest/modules/engine.html#detectron2.engine.launch or the official examples.
