### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by baiyubaiyu** [facebookresearch/detectron2#291]
```
Traceback (most recent call last):
  File "demo/demo.py", line 10, in <module>
    from detectron2.config import get_cfg
  File "/home/baiyu/ObjectDetection/detectron2/detectron2/__init__.py", line 3, in <module>
    from .utils.env import setup_environment
  File "/home/baiyu/ObjectDetection/detectron2/detectron2/utils/env.py", line 2, in <module>
    import torch
  File "/root/anaconda3/envs/baiyu_env/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS
```

Has anyone encountered this problem?

**Comment by ppwwyyxx** [comment]
Yes. Please follow https://github.com/pytorch/pytorch/issues/2575 instead.
