### ISSUE TITLE
 Please read & provide the following

### ISSUE THREAD

**Issue by steven5clu884** [facebookresearch/detectron2#2928]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
```
2. What exact command you run:
3. __Full logs__ or other relevant observations:
```
<put logs here>
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by steven5clu884** [comment]
I am using anaconda 
/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

I think I installed everything correctly

For command line
/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

Traceback (most recent call last):
  File "train_net.py", line 13, in <module>
    import detectron2.data.transforms as T
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/wizzerking/develop/anaconda3/envs/detectron2/lib/python3.6/site-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

**Comment by steven5clu884** [comment]
Ubuntuu 20.4
