### ISSUE TITLE
Dataset is not registered when performing hyperparameter tuning

### ISSUE THREAD

**Issue by rvdinter** [facebookresearch/detectron2#3057]
## Instructions To Reproduce the Issue:

I am looking at hyperparameter tuning a PointRend model on a custom dataset. Until now, Detectron2 has been a fantastic framework, but registering custom datasets has given me a problem. The error while running the hyperparameter tuning algorithm mentions that the dataset is not registered. However, the plain code in the Expected behavior shows that it is working. I am wondering whether it is an issue due to the multiple threats Ray Tune has. Is there any way that the registered dataset persists to exist?

1. Full runnable code or full changes you made:
```
def train_model(hp, checkpoint_dir=None):
    # register a mydataset_train and mydataset_test set 
    register_train_test_coco_instances("mydataset", {}, "/kaggle/input/dataset/mydataset_coco.json", "/kaggle/input/dataset/images") 
    cfg = set_cfg_values(hp)
    # Train the model
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = CustomTrainer(cfg, hp)
    trainer.resume_or_load(resume=False)
    trainer.train()

def main(num_samples=10, max_num_epochs=10, gpus_per_trial=1):
    # Set the hyperparameter configuration dict with viable ranges
    hp = {"epochs": tune.randint(8,15),
              "lr": tune.loguniform(1e-3, 1e-2),
              "batch_size": tune.choice([2, 4, 8]),
              "anchorboxes": False,
              "hflip": tune.choice([0, 0.5]),
              "vflip": tune.choice([0, 0.5]),
              "blur": tune.choice([0, 0.5]),
              "contrast": tune.choice([0, 0.2]),
              "brightness": tune.choice([0, 0.2])}
    
    # initialize tha Asynchronous Successive Halving Algorithm Scheduler
    scheduler = ASHAScheduler(
        metric="loss_mask",
        mode="min",
        max_t=max_num_epochs,
        grace_period=1,
        reduction_factor=4)
    
    # Report results to the CLI
    reporter = JupyterNotebookReporter(overwrite=False, 
                                       metric_columns=["loss_mask", "segm_map_small", 
                                                       "segm_map_medium", "training_iteration"])
    
    # Run the ASHA algorithm
    result = tune.run(
        train_model,
        resources_per_trial={"cpu": 2, "gpu": gpus_per_trial},
        config=hp,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter)

    # Get the best model
    best_trial = result.get_best_trial("loss_mask", "min", "last")
    print("Best trial config: {}".format(best_trial.config))
    print("Best trial final validation loss: {}".format(
        best_trial.last_result["loss_mask"]))
    print("Best trial final validation segm_map_small: {}".format(
        best_trial.last_result["segm_map_small"]))
    print("Best trial final validation segm_map_medium: {}".format(
        best_trial.last_result["segm_map_medium"]))

if __name__ == "__main__":
    # You can change the number of GPUs per trial here:
    main(num_samples=2, max_num_epochs=3, gpus_per_trial=1)
```
2. What exact command you run: I run the code via kaggle.
3. __Full logs__ or other relevant observations:
```
2021-05-19 08:04:37,881	ERROR trial_runner.py:616 -- Trial train_crystal_d8256_00000: Error processing event.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=1141, ip=172.19.2.2)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/function_runner.py", line 513, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=1141, ip=172.19.2.2)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/catalog.py", line 51, in get
    f = self[name]
  File "/opt/conda/lib/python3.7/collections/__init__.py", line 1027, in __getitem__
    raise KeyError(key)
KeyError: 'mydataset_train'

The above exception was the direct cause of the following exception:

ray::ImplicitFunc.train_buffered() (pid=1141, ip=172.19.2.2)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
    output = fn()
  File "<ipython-input-16-ea06a3bf7310>", line 11, in train_crystal
  File "<ipython-input-6-1fd4f0f0e908>", line 129, in __init__
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 379, in __init__
    data_loader = self.build_train_loader(cfg)
  File "<ipython-input-6-1fd4f0f0e908>", line 139, in build_train_loader
  File "/opt/conda/lib/python3.7/site-packages/detectron2/config/config.py", line 192, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py", line 316, in _train_loader_from_config
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py", line 227, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py", line 227, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/catalog.py", line 57, in get
    ) from e
KeyError: "Dataset 'mydataset_train' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"
```

## Expected behavior:
I expect that when I register a dataset, it also works when hyperparameter tuning. I can approve that running the code without hyperparameter tuning works:

```
hp = {"epochs": 8,
              "lr": 1e-3,
              "batch_size": 2,
              "anchorboxes": False,
              "hflip": 0.5,
              "vflip": 0.5,
              "blur": 0.5,
              "contrast": 0.2,
              "brightness": 0.2}
train_model(hp)
```

## Environment:
```
2021-05-19 08:15:08 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/master/detectron2/utils/collect_env.py [7340/7340] -> "collect_env.py" [1]
----------------------  -------------------------------------------------------------------------------
sys.platform            linux
Python                  3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
numpy                   1.19.5
detectron2              0.4 @/opt/conda/lib/python3.7/site-packages/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 11.0
detectron2 arch flags   6.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0 @/opt/conda/lib/python3.7/site-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0                   Tesla P100-PCIE-16GB (arch=6.0)
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.8.1 @/opt/conda/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.5.post20210518
iopath                  0.1.8
cv2                     4.5.1
----------------------  -------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, ```

**Comment by ppwwyyxx** [comment]
The provided code is not runnable so I cannot verify the issue. 

Maybe it helps to register datasets at the module's global scope instead of in a function. That's my only guess

**Comment by rvdinter** [comment]
The code below is edited to made runnable. The last two cells show the 'plain' training function, and the hyperparameter tuning function. In this example, the balloon dataset is registered globally, but the error remains to persist.

```
# %% [code] {"_kg_hide-output":true}
!pip install 'git+https://github.com/facebookresearch/detectron2.git'
# clone the repo at the same version, in order to access pre-defined configs
!git clone --branch v0.4 https://github.com/facebookresearch/detectron2.git detectron2_repo
!pip uninstall dataclasses --yes

# %% [code]
!wget https://github.com/matterport/Mask_RCNN/releases/download/v2.1/balloon_dataset.zip
!unzip balloon_dataset.zip > /dev/null

# %% [code]
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()


import detectron2.data.transforms as T

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.data import detection_utils as utils
from detectron2.data import MetadataCatalog, DatasetCatalog, build_detection_train_loader, DatasetMapper, build_detection_test_loader 
from detectron2.engine import DefaultTrainer, DefaultPredictor
from detectron2.config import get_cfg 
from detectron2.evaluation import COCOEvaluator, inference_on_dataset 
from detectron2.engine.hooks import HookBase
from detectron2.data.datasets import register_coco_instances, load_coco_json
from detectron2.utils.visualizer import Visualizer, ColorMode
from detectron2.structures.boxes import BoxMode


import numpy as np
import os, json, cv2, random


# import PointRend project
from detectron2.projects import point_rend

import copy
import torch
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw

from torchvision.transforms import functional as F
import random
import albumentations as A

# Hyperparametertuning
import ray
from functools import partial
from ray import tune
from ray.tune import JupyterNotebookReporter
from ray.tune.schedulers import ASHAScheduler

# %% [markdown]
# # Register the train and test dataset

# %% [code]
from detectron2.structures import BoxMode

def get_balloon_dicts(img_dir):
    json_file = os.path.join(img_dir, "via_region_data.json")
    with open(json_file) as f:
        imgs_anns = json.load(f)

    dataset_dicts = []
    for idx, v in enumerate(imgs_anns.values()):
        record = {}
        
        filename = os.path.join(img_dir, v["filename"])
        height, width = cv2.imread(filename).shape[:2]
        
        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width
      
        annos = v["regions"]
        objs = []
        for _, anno in annos.items():
            assert not anno["region_attributes"]
            anno = anno["shape_attributes"]
            px = anno["all_points_x"]
            py = anno["all_points_y"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = [p for x in poly for p in x]

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": 0,
                'iscrowd': 0,
            }
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts

for d in ["train", "val"]:
    DatasetCatalog.register("balloon_" + d, lambda d=d: get_balloon_dicts("balloon/" + d))
    MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])
balloon_metadata = MetadataCatalog.get("balloon_train")

# %% [markdown]
# # Generate the custom Trainer class using augmentations and hook

# %% [code]
def masks_coords2img(dataset_dict):
    """ Make a list of binary mask images from a list of coordinates
    
    :param dataset_dict: dataset dictionary
    :return: list of mask images
    """
    # note that we haven't converted the mask to RGB,
    # because each color corresponds to a different instance
    # with 0 being background
    mask = Image.new('L', (dataset_dict['width'],dataset_dict['height']))
    mask_coords = [augmentation['segmentation'] for augmentation in dataset_dict['annotations']]
    
    # Draw each annotation's segmentation on the mask image
    for itr, ann in enumerate(mask_coords):
        ImageDraw.Draw(mask).polygon(list(ann[0]), fill=itr+1)
        
    # Convert to np array
    mask = np.array(mask)
    # instances are encoded as different colors
    obj_ids = np.unique(mask)
    # first id is the background, so remove it
    obj_ids = obj_ids[1:]
    # split the color-encoded mask into a set
    # of binary masks
    masks = mask == obj_ids[:, None, None]
    return list(masks)

def masks_img2coords(imgs):
    """ Convert list of mask images to to list of polygon coordinates
    
    :param imgs: list of mask images
    :return: list of coordinates
    """
    coords = []
    for mask in imgs:
        coord = np.column_stack(np.where(mask > 0))
        coord[:,[0, 1]] = coord[:,[1, 0]]
        coords.append([coord.flatten()])
    return coords

class CustomMapper(DatasetMapper):
    def __init__(self, hp):
        self._transform = A.Compose(
            [A.HorizontalFlip(p=hp['hflip']), 
             A.VerticalFlip(p=hp['vflip']), 
             A.Blur(p=hp['blur']), 
             A.RandomBrightnessContrast(p=0.5, 
                                        brightness_limit=hp['brightness'], 
                                        contrast_limit=hp['contrast'])
            ],
            bbox_params=A.BboxParams(format="pascal_voc", label_fields=["category_id"]),
        )
        
    def __call__(self, dataset_dict):
        """Implement a mapper, similar to the default DatasetMapper, but with your own customizations
        We implement different data augmentation techniques.

        :param dataset_dict: dictionary of datasample
        :return: dictionary of augmented datasample
        """
        dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below

        # Get all essential data from a sample for albumentations
        image = np.asarray(Image.open(dataset_dict["file_name"]).convert("RGB"))
        bboxes = [augmentation['bbox'] for augmentation in dataset_dict['annotations']]
        category_id = [augmentation['category_id'] for augmentation in dataset_dict['annotations']]
        masks = masks_coords2img(dataset_dict)
        iscrowd = [augmentation['iscrowd'] for augmentation in dataset_dict['annotations']]
        bbox_mode = [augmentation['bbox_mode'] for augmentation in dataset_dict['annotations']]

        # Apply Albumentations transformations
        transformed = self._transform(
                          image=image,
                          masks=masks,
                          bboxes=bboxes,
                          category_id=category_id,
                        )

        # Convert the bounding boxes to XYXY format from XYWH
        new_bbox_mode = BoxMode(0)
        converted_bbox = [list(new_bbox_mode.convert(box, 1, 0)) for box in transformed.pop('bboxes')]

        # Implement the transformations in the transformed dict
        dataset_dict["image"] = torch.as_tensor(transformed['image'].transpose(2, 0, 1).astype("float32"))
        transformed['iscrowd'] = iscrowd
        transformed['bbox_mode'] = [new_bbox_mode] * len(bbox_mode) # Change BBOX mode
        transformed['bbox'] = [np.array(list(map(int, coordinate))) for coordinate in converted_bbox] # Change to list of numpy arrays of list of int from lists of tuples of floats
        transformed['segmentation'] = transformed.pop('masks')#masks_img2coords(transformed.pop('masks'))

        # From dict of lists to list of dicts
        annos = [dict(zip(transformed,t)) for t in zip(*transformed.values())]

        # Remove original annotations from the dict
        dataset_dict.pop("annotations")

        # Add new instances to the dict
        instances = utils.annotations_to_instances(annos, image.shape[:2], mask_format="bitmask")
        dataset_dict["instances"] = utils.filter_empty_instances(instances)
        return dataset_dict

class RayTuneReporterHook(HookBase):
    """ SEMI IMPLEMENTED: Hook for Ray Tune Reporter"""
    def __init__(self, eval_period):
        self._eval_period = eval_period
        
    def after_step(self):
        next_iter = self.trainer.iter + 1
        is_final = next_iter == self.trainer.max_iter
        if is_final or (self._eval_period > 0 and next_iter % self._eval_period == 0):
            loss_mask_latest = self.trainer.storage.history('loss_mask').latest()
            loss_segm_aps_latest = self.trainer.storage.history('segm/APs').latest()
            loss_segm_apm_latest = self.trainer.storage.history('segm/APm').latest()
            tune.report(loss_mask=loss_mask_latest, 
                    segm_map_small=loss_segm_aps_latest, 
                    segm_map_medium=loss_segm_apm_latest)
            print(f'{self.trainer.iter}: losses and mAPs {loss_mask_latest} {loss_segm_aps_latest} {loss_segm_apm_latest}')

class CustomTrainer(DefaultTrainer):
    """ Custom trainer class"""

    def __init__(self, cfg, hp):
        self._hp = hp
        super().__init__(cfg)
    
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        return COCOEvaluator(dataset_name, ("bbox", "segm"), False, output_folder)
    
#     @classmethod
    def build_train_loader(self, cfg):
        return build_detection_train_loader(cfg, mapper=CustomMapper(self._hp)) 
    
    def build_hooks(self):
        # build hooks from super class 
        # and add ray tune reporter hook
        hooks = super().build_hooks()
        hooks.insert(-1,RayTuneReporterHook(self.cfg.TEST.EVAL_PERIOD))
        return hooks

# %% [markdown]
# # Train the PointRend model

# %% [code]
def set_cfg_values(hp):
    """ Set the Config values for the PointRend model"""
    cfg = get_cfg()
    # Add PointRend-specific config
    point_rend.add_pointrend_config(cfg)
    # Load a config from file
    cfg.merge_from_file("/kaggle/working/detectron2_repo/projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml")
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
    cfg.DATASETS.TRAIN = ("balloon_train",)
    cfg.DATASETS.TEST = ("balloon_val",)
    cfg.DATALOADER.NUM_WORKERS = 4
    # Use a model from PointRend model zoo: https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend#pretrained-models
    cfg.MODEL.WEIGHTS = "detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_edd263.pkl"
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512 #128   # faster, and good enough for this toy dataset (default: 512)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon). (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
    cfg.MODEL.POINT_HEAD.NUM_CLASSES = 1  # only has one class (ballon). (see https://detectron2.readthedocs.io/tutorials/datasets.html#update-the-config-for-new-datasets)
    # NOTE: this config means the number of classes, but a few popular unofficial tutorials incorrect uses num_classes+1 here.
    cfg.SEED = 1
    cfg.INPUT.FORMAT = 'RGB'
    cfg.INPUT.RANDOM_FLIP = 'none'
    cfg.TEST.EVAL_PERIOD = 1
    
    # Hyperparams that need to be solved
    cfg.OUTPUT_DIR = '/kaggle/working/output'
    cfg.SOLVER.IMS_PER_BATCH = hp['batch_size']
    cfg.SOLVER.BASE_LR = hp['lr'] #0.00025  # pick a good LR
    cfg.SOLVER.MAX_ITER = hp['epochs'] #300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
    cfg.SOLVER.STEPS = (3,) #[]        # do not decay learning rate
    
    if hp['anchorboxes']:
        cfg.MODEL.ANCHOR_GENERATOR.SIZES = [[8, 16, 32, 64, 128]]
        cfg.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.25, 0.5, 1.0, 2.0]]
    return cfg

# %% [code]
def train_model(hp, checkpoint_dir=None):
    cfg = set_cfg_values(hp)
    # Train the model
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = CustomTrainer(cfg, hp)
    trainer.resume_or_load(resume=False)
    trainer.train()

# %% [code]
# This plain cell works
hp = {"epochs": 8,
              "lr": 1e-3,
              "batch_size": 2,
              "anchorboxes": False,
              "hflip": 0.5,
              "vflip": 0.5,
              "blur": 0.5,
              "contrast": 0.2,
              "brightness": 0.2}
train_model(hp)

# %% [code]
# And this hyperparameter function cell does not
def main(num_samples=10, max_num_epochs=10, gpus_per_trial=1):
    # Set the hyperparameter configuration dict with viable ranges
    hp = {"epochs": tune.randint(8,15),
              "lr": tune.loguniform(1e-3, 1e-2),
              "batch_size": tune.choice([2, 4, 8]),
              "anchorboxes": False,
              "hflip": tune.choice([0, 0.5]),
              "vflip": tune.choice([0, 0.5]),
              "blur": tune.choice([0, 0.5]),
              "contrast": tune.choice([0, 0.2]),
              "brightness": tune.choice([0, 0.2])}
    
    # initialize tha Asynchronous Successive Halving Algorithm Scheduler
    scheduler = ASHAScheduler(
        metric="loss_mask",
        mode="min",
        max_t=max_num_epochs,
        grace_period=1,
        reduction_factor=4)
    
    # Report results to the CLI
    reporter = JupyterNotebookReporter(overwrite=False, 
                                       metric_columns=["loss_mask", "segm_map_small", 
                                                       "segm_map_medium", "training_iteration"])
    
    # Run the ASHA algorithm
    result = tune.run(
        train_model,
        resources_per_trial={"cpu": 2, "gpu": gpus_per_trial},
        config=hp,
        num_samples=num_samples,
        scheduler=scheduler,
        progress_reporter=reporter)

    # Get the best model
    best_trial = result.get_best_trial("loss_mask", "min", "last")
    print("Best trial config: {}".format(best_trial.config))
    print("Best trial final validation loss: {}".format(
        best_trial.last_result["loss_mask"]))
    print("Best trial final validation segm_map_small: {}".format(
        best_trial.last_result["segm_map_small"]))
    print("Best trial final validation segm_map_medium: {}".format(
        best_trial.last_result["segm_map_medium"]))

if __name__ == "__main__":
    # You can change the number of GPUs per trial here:
    main(num_samples=2, max_num_epochs=3, gpus_per_trial=1)
```

**Comment by ppwwyyxx** [comment]
This seems to be a limitation of ray. It's reported in https://github.com/ray-project/ray/issues/15946

**Comment by DeekshithShetty** [comment]
@rvdinter Thanks for the info. The hp optimizations tools link you mentioned seems super useful. I'll check it out :)

**Comment by gfiameni** [comment]
> @DeekshithShetty it seemed like it was because Ray Tune creates multiple processes for distributed hyperparameter tuning. As a result, it can't see the global variables, such as our Detectron2 Dataset anymore. Unfortunately, I could not create a workaround. Instead of Ray Tune's distributed hp tuning, I was forced to use a simpler technique. I opted for [Talos's](https://github.com/autonomio/talos) random optimization. However, you could opt for a lot of other hp optimization tools listed [here](https://github.com/ml-tooling/best-of-ml-python#hyperparameter-optimization--automl).

Hi @DeekshithShetty, have you managed to integrate Talos into your code? Wondering if it provides any benefits. Thanks!

**Comment by Deam0on** [comment]
> 



> @DeekshithShetty it seemed like it was because Ray Tune creates multiple processes for distributed hyperparameter tuning. As a result, it can't see the global variables, such as our Detectron2 Dataset anymore. Unfortunately, I could not create a workaround. Instead of Ray Tune's distributed hp tuning, I was forced to use a simpler technique. I opted for [Talos's](https://github.com/autonomio/talos) random optimization. However, you could opt for a lot of other hp optimization tools listed [here](https://github.com/ml-tooling/best-of-ml-python#hyperparameter-optimization--automl).

Hi, I tried using Talos, but I cant seem to impelemt it into my code. Could you show me how you did it? Thx

**Comment by heng2j** [comment]
Hi everyone, for people who are still interested in integrating Ray with Detectron2, I have a new discussion thread in [Ray Discuss](https://discuss.ray.io/t/seeking-recommendation-for-training-detectron2-with-ray-tune/8849/3?u=heng2j).

**Comment by jonathanberr** [comment]
Sorry for necro-ing this thread, does anyone have any viable solution to integrate any hp optimizing tools so far? So far I#ve tried ray and wandb with no luck
