### ISSUE TITLE
AttributeError: Cannot find field 'gt_masks' in the given Instances!

### ISSUE THREAD

**Issue by BaptisteLauras** [facebookresearch/detectron2#3089]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
I'm using Detectron2 as a package, I didn't changed anything in the original code. 

2. What exact command you run:
I created a class dedicated to model training and I'm using the class in a jupyter notebook so I'm not running any command to launch my code.

3. __Full logs__ or other relevant observations:
```
[05/26 13:59:57 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelMaxPool()
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (proposal_generator): RPN(
    (rpn_head): StandardRPNHead(
      (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (objectness_logits): Conv2d(256, 3, kernel_size=(1, 1), stride=(1, 1))
      (anchor_deltas): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
    (anchor_generator): DefaultAnchorGenerator(
      (cell_anchors): BufferList()
    )
  )
  (roi_heads): StandardROIHeads(
    (box_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(7, 7), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(7, 7), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(7, 7), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (box_head): FastRCNNConvFCHead(
      (flatten): Flatten()
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc_relu1): ReLU()
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
      (fc_relu2): ReLU()
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=13, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=48, bias=True)
    )
    (mask_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(14, 14), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(14, 14), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(14, 14), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(14, 14), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (mask_head): MaskRCNNConvUpsampleHead(
      (mask_fcn1): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (mask_fcn2): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (mask_fcn3): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (mask_fcn4): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (deconv): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
      (deconv_relu): ReLU()
      (predictor): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
[05/26 13:59:57 d2.data.datasets.coco]: Loaded 21 images in COCO format from Dataset/train_annots.json
[05/26 13:59:57 d2.data.build]: Removed 0 images with no usable annotations. 21 images left.
[05/26 13:59:57 d2.data.build]: Distribution of instances among all 12 categories:
|   category    | #instances   |   category    | #instances   |   category    | #instances   |
|:-------------:|:-------------|:-------------:|:-------------|:-------------:|:-------------|
| metalic pip.. | 222          |     other     | 21           |     rust      | 557          |
|     text      | 44           | concrete wall | 0            | metalic str.. | 303          |
| plastic pow.. | 17           | metalic gro.. | 43           |     grid      | 13           |
|     valve     | 44           |  rust danger  | 0            |     bolt      | 697          |
|               |              |               |              |               |              |
|     total     | 1961         |               |              |               |              |
[05/26 13:59:57 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[05/26 13:59:57 d2.data.build]: Using training sampler TrainingSampler
[05/26 13:59:57 d2.data.common]: Serializing 21 elements to byte tensors and concatenating them all ...
[05/26 13:59:57 d2.data.common]: Serialized dataset takes 0.22 MiB
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (13, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (13,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (48, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (48,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.mask_head.predictor.weight' to the model due to incompatible shapes: (80, 256, 1, 1) in the checkpoint but (12, 256, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.mask_head.predictor.bias' to the model due to incompatible shapes: (80,) in the checkpoint but (12,) in the model! You might want to double check if this is expected.
[05/26 13:59:57 d2.engine.train_loop]: Starting training from iteration 0
/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/structures/masks.py:348: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  item = item.nonzero().squeeze(1).cpu().numpy().tolist()
/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/structures/masks.py:348: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  item = item.nonzero().squeeze(1).cpu().numpy().tolist()
/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py:103: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  num_fg = fg_inds.nonzero().numel()
ERROR [05/26 14:00:07 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/train_loop.py", line 234, in run_step
    loss_dict = self.model(data)
  File "/home/bapt/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/bapt/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 736, in forward
    losses.update(self._forward_mask(features, proposals))
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 839, in _forward_mask
    return self.mask_head(features, instances)
  File "/home/bapt/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/mask_head.py", line 193, in forward
    return {"loss_mask": mask_rcnn_loss(x, instances, self.vis_period) * self.loss_weight}
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/mask_head.py", line 64, in mask_rcnn_loss
    gt_masks_per_image = instances_per_image.gt_masks.crop_and_resize(
  File "/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!
[05/26 14:00:07 d2.engine.hooks]: Overall training speed: 13 iterations in 0:00:07 (0.5849 s / it)
[05/26 14:00:07 d2.engine.hooks]: Total training time: 0:00:07 (0:00:00 on hooks)
[05/26 14:00:07 d2.utils.events]:  eta: 0:00:02  iter: 15  total_loss: 8.231  loss_cls: 2.544  loss_box_reg: 0.6147  loss_mask: 0.6924  loss_rpn_cls: 3.677  loss_rpn_loc: 0.6603  time: 0.5690  data_time: 0.0348  lr: 3.7465e-06  max_mem: 4325M
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-3c68c81494ab> in <module>
----> 1 worker.train_model()

~/Desktop/Travail/Mediamap/segmentations/Code/my_worker.py in train_model(self)
     58         self.trainer = MyTrainer(self.cfg)
     59         self.trainer.resume_or_load(resume=False)
---> 60         self.trainer.train()
     61 
     62     def move_plot_model_train_metrics(self):

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/defaults.py in train(self)
    429             OrderedDict of results, if evaluation is enabled. Otherwise None.
    430         """
--> 431         super().train(self.start_iter, self.max_iter)
    432         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    433             assert hasattr(

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    138                 for self.iter in range(start_iter, max_iter):
    139                     self.before_step()
--> 140                     self.run_step()
    141                     self.after_step()
    142                 # self.iter == max_iter can be used by `after_train` to

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/defaults.py in run_step(self)
    439     def run_step(self):
    440         self._trainer.iter = self.iter
--> 441         self._trainer.run_step()
    442 
    443     @classmethod

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/engine/train_loop.py in run_step(self)
    232         If you want to do something with the losses, you can wrap the model.
    233         """
--> 234         loss_dict = self.model(data)
    235         losses = sum(loss_dict.values())
    236 

~/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    164             proposal_losses = {}
    165 
--> 166         _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
    167         if self.vis_period > 0:
    168             storage = get_event_storage()

~/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/roi_heads.py in forward(***failed resolving arguments***)
    734             # heads. But when `self.train_on_pred_boxes is True`, proposals will contain boxes
    735             # predicted by the box head.
--> 736             losses.update(self._forward_mask(features, proposals))
    737             losses.update(self._forward_keypoint(features, proposals))
    738             return proposals, losses

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/roi_heads.py in _forward_mask(self, features, instances)
    837         else:
    838             features = {f: features[f] for f in self.mask_in_features}
--> 839         return self.mask_head(features, instances)
    840 
    841     def _forward_keypoint(self, features: Dict[str, torch.Tensor], instances: List[Instances]):

~/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/mask_head.py in forward(self, x, instances)
    191         x = self.layers(x)
    192         if self.training:
--> 193             return {"loss_mask": mask_rcnn_loss(x, instances, self.vis_period) * self.loss_weight}
    194         else:
    195             mask_rcnn_inference(x, instances)

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/modeling/roi_heads/mask_head.py in mask_rcnn_loss(pred_mask_logits, instances, vis_period)
     62             gt_classes.append(gt_classes_per_image)
     63 
---> 64         gt_masks_per_image = instances_per_image.gt_masks.crop_and_resize(
     65             instances_per_image.proposal_boxes.tensor, mask_side_len
     66         ).to(device=pred_mask_logits.device)

~/Desktop/Travail/Mediamap/Code/detectron2/detectron2/structures/instances.py in __getattr__(self, name)
     63     def __getattr__(self, name: str) -> Any:
     64         if name == "_fields" or name not in self._fields:
---> 65             raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
     66         return self._fields[name]
     67 

AttributeError: Cannot find field 'gt_masks' in the given Instances!
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.
To help you understand what I'm doing, here's my custom class code for training:

```
class MyTrainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "inference")
        return COCOEvaluator(dataset_name, ["bbox", "segm"], True, output_folder)

class MyWorker:

    def __init__(self,
                 train_instance=[
                     "my_train", "path to train annots", "path to train images"],
                 val_instance=[
                     "my_val", "path to val annots", "path to val images"]
                 ):

        for instance in [train_instance, val_instance]:
            if instance[0] in DatasetCatalog.list():
                DatasetCatalog.remove(instance[0])
            register_coco_instances(instance[0], {}, instance[1], instance[2])
        self.metadata = MetadataCatalog.get(train_instance[0])
        self.plotter = Plotter()

    def init_config(self,
                    base_config_file="COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml",
                    custom_config_file="Code/configs/custom_config.yaml",
                    weights_config_file="COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml",
                    redefine_output_dir=True
                    ):
        self.cfg = get_cfg()
        self.cfg.merge_from_file(model_zoo.get_config_file(base_config_file))
        self.cfg.merge_from_file(custom_config_file)
        self.cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
            weights_config_file)  # Let training initialize from model zoo
        if redefine_output_dir:
            self.date = datetime.now().strftime("%d-%m-%Y_%H:%M")
            self.cfg.OUTPUT_DIR = self.cfg.OUTPUT_DIR + "/" + self.date
        os.makedirs(self.cfg.OUTPUT_DIR, exist_ok=True)
        os.makedirs(self.cfg.OUTPUT_DIR + "/images", exist_ok=True)

    def train_model(self):
        self.trainer = MyTrainer(self.cfg)
        self.trainer.resume_or_load(resume=False)
        self.trainer.train()
```

Here's my custom config file, others remains the same as they came in Detectron2 package:
```
DATASETS:
  TRAIN: ("my_train",)
  TEST: ("my_val",)
DATALOADER:
  NUM_WORKERS: 2
MODEL:
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128   
    NUM_CLASSES: 12 

SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 0.00025  
  MAX_ITER: 21   
  STEPS: []       
OUTPUT_DIR: "outputs"
VERSION: 2
```

The problem comes when I run my train_model() method from custom class, it launch the training well but it fail saying "AttributeError: Cannot find field 'gt_masks' in the given Instances!". So I searched in existing issues and found the #485 where someone say that the problem is due to the fact that the used dataset has no masks. The problem is that I'm using a custom coco style dataset, every images has bounding boxes and segmentation masks. I also noticed a strange behavior, when I set a low value (less than 10) for SOLVER.MAX_ITER, the training goes well. But when I set higher values (between 10 and 30), it becomes random and sometime it would work until the training is done and other times it throw me the error. When I set values higher than 30, it just fails everytime.

## Environment:
```
sys.platform            linux
Python                  3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.4 @/home/bapt/Desktop/Travail/Mediamap/Code/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/home/bapt/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce RTX 2060 SUPER (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  8.1.2
torchvision             0.7.0 @/home/bapt/anaconda3/envs/Detectron2/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20210330
iopath                  0.1.7
cv2                     4.5.1
----------------------  -----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
The data does not contain masks. Since no way to reproduce the issue is given, that's all we can tell from the logs.

**Comment by BaptisteLauras** [comment]
After further researches I figured out my problem, my dataset export from my annotations service contained some corrupted masks which I had to remove to make it work.

Sorry for the inconvenience, issue is resolved
