### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by jianrun** [facebookresearch/detectron2#3107]
## Instructions To Reproduce the Issue:

Running demo.py on the CPU in Docker works fine, but reporting an error on the GPU

command :
```
appuser@2c33616b558b:/det2/demo$ python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input test.jpg --output out.jpg --opts MODEL.WEIGHTS 
detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849
600/model_final_f10217.pkl
```
error output:
```
Failed to load OpenCL runtime
[05/31 15:30:09 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['test.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_
R_50_FPN_3x/137849600/model_final_f10217.pkl'], output='out.jpg', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 102, in <module>
    demo = VisualizationDemo(cfg)
  File "/det2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/appuser/detectron2_repo/detectron2/engine/defaults.py", line 283, in __init__
    self.model = build_model(self.cfg)
  File "/home/appuser/detectron2_repo/detectron2/modeling/meta_arch/build.py", line 23, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

## Environment:
```
win10 + docker + NVIDIA GeForce GTX 1660
//docker source: /docker/docker-compose.yml
```

**Comment by ppwwyyxx** [comment]
Unrelated to this project because the error comes from pytorch's cuda init function.
