### ISSUE TITLE
COCO Evaluator - Error in evaluation step

### ISSUE THREAD

**Issue by rathishkumar** [facebookresearch/detectron2#3115]
## Instructions To Reproduce the 🐛 Bug:

Getting error with evaluation step, let me share the codes I have tried and its output including error.

1. Full runnable code or full changes you made:

I have started with Method 1 and after getting error - tried Method 2 & 3.

Note: To reproduce this error trained with smaller iterations. Training was successful so included only the evaluation related logs.

Method 1:

```
evaluator = COCOEvaluator(dataset_name="dataset_test", 
                           cfg=cfg, 
                           distributed=False,
                           output_dir="./output/")

trainer.test(cfg=cfg,
             model=trainer.model,
             evaluators=evaluator)
```

Output:

```
[06/04 11:51:04 d2.engine.hooks]: Overall training speed: 2 iterations in 0:00:00 (0.9981 s / it)
[06/04 11:51:04 d2.engine.hooks]: Total training time: 0:00:03 (0:00:02 on hooks)
Traceback (most recent call last):
  File "ml-train.py", line 100, in <module>
    output_dir="./output/")
TypeError: __init__() got an unexpected keyword argument 'cfg'
```

Method 2:

```
evaluator = COCOEvaluator("dataset_test", cfg, False, output_dir="./output/")
trainer.test(cfg=cfg,
             model=trainer.model,
             evaluators=evaluator)

```
Output:

```
[06/04 11:16:57 d2.engine.hooks]: Total training time: 0:05:14 (0:00:02 on hooks)
WARNING [06/04 11:16:57 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecate
d behavior. Please pass tasks in directly
[06/04 11:16:57 d2.data.datasets.coco]: Loaded 20 images in COCO format from test.json
[06/04 11:16:57 d2.data.build]: Distribution of instances among all 2 categories:

....
Continuing with evaluation output - running fine except WARNING
....

```
Method 3:
```
evaluator = COCOEvaluator("dataset_test", ("bbox", "segm"), False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "dataset_test")
inference_on_dataset(trainer.model, val_loader, evaluator)

```
Output:

```
[06/04 16:56:47 d2.engine.hooks]: Total training time: 0:00:14 (0:00:01 on hooks)
Traceback (most recent call last):
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/ml-lab/data-engine/ml-train.py", line 91, in <module>
    evaluator = COCOEvaluator("dataset_test", ("bbox", "segm"), False, output_dir="./output/")
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 61, in __init__
    self._tasks = self._tasks_from_config(cfg)
  File "/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 97, in _tasks_from_config
    if cfg.MODEL.MASK_ON:
AttributeError: 'tuple' object has no attribute 'MODEL'
```

2. What exact command you run:

`python ml-train.py`

3. __Full logs__ or other relevant observations:

As the issue is with COCOEvaluation part added the evaluation code block - will share the complete logs, if required. 

4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

Execution of model evaluation - it is working in method 2 with a warning.

## Environment:

Provide your environment information using the following command:
```
sys.platform            linux
Python                  3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
numpy                   1.19.4
detectron2              0.3 @/tools/mlengine/lib64/python3.6/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.0
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0+cu110 @/tools/mlengine/lib64/python3.6/site-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0,1                 Tesla T4 (arch=7.5)
CUDA_HOME               /usr/local/cuda-11.0
Pillow                  8.0.1
torchvision             0.8.1+cu110 @/tools/mlengine/lib64/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.2.post20201111
cv2                     4.4.0
----------------------  -----------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=
compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute
_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHR
EADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -
fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-b
ounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-u
nused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declaration
s -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiag
nostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapp
ing-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON,
 USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK
=ON, USE_OPENMP=ON, 

```

I have tried above mentioned methods, not sure whether it is issue with my environment or in code. Please help on this.

**Comment by ppwwyyxx** [comment]
Method 3 is correct for detectron2 >= 0.3.

> File "/root/anaconda3/envs/ml-engine/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 61, in __init__
    self._tasks = self._tasks_from_config(cfg)

This line does not look like this in detectron2 0.3: https://github.com/facebookresearch/detectron2/blob/v0.3/detectron2/evaluation/coco_evaluation.py#L61 so you must be usin ga different version.

**Comment by rathishkumar** [comment]
Thanks @ppwwyyxx,  let me update to latest version and test.
