### ISSUE TITLE
Detectron2 installation with undefined symbol in _C

### ISSUE THREAD

**Issue by jhwang7628** [facebookresearch/detectron2#3117]
I have installed detectron2 seemingly successfully by following all the steps but got an unexpected undefined symbol error when trying to use the code. 

Here are the steps I used to repro the issue:

```
# create a new conda env
conda create --name test-detectron2 python=3
# switch to new env
conda activate test-detectron2
# install pytorch 1.8 and torchvision with cuda 11
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
# install detectron2 by fetching
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
# above step printed: Successfully installed detectron2-0.4 
# then, if I tried to import detectron, an undefined symbol error appears
python -c 'from detectron2.engine.defaults import DefaultPredictor'
```
The last step prints this for me:
```
± % python -c 'from detectron2.engine.defaults import DefaultPredictor'                                                          !10721
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 18, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask, ROIMasks
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/structures/masks.py", line 10, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```

My environment:
```
± % wget -nc -nv https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py                                                                                                                                      !10722
2021-06-04 15:26:32 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/master/detectron2/utils/collect_env.py [7340/7340] -> "collect_env.py" [1]
----------------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.10 (default, May 19 2021, 18:05:58) [GCC 7.3.0]
numpy                   1.18.1
detectron2              0.4 @/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2
detectron2._C           not built correctly: /home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
Compiler ($CXX)         c++ (GCC) 11.1.0
CUDA compiler           Build cuda_11.3.r11.3/compiler.29745058_0
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1 @/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   NVIDIA GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /opt/cuda
Pillow                  8.2.0
torchvision             0.9.1 @/home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20210604
iopath                  0.1.8
cv2                     4.4.0
----------------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```
I checked the common issues and nothing applies.

**Comment by jhwang7628** [comment]
I guess this sort of hints at the problem:
```
detectron2._C           not built correctly: /home/juiwang/opt/anaconda3/envs/badminton-cv/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```
but I am not sure which step am I doing incorrectly.

**Comment by ppwwyyxx** [comment]
This one from the common installation issues applies:

> Undefined C++ symbols (e.g. `GLIBCXX`) or C++ symbols not found.
Usually it's because the library is compiled with a newer C++ compiler but run with an old C++ runtime.
This often happens with old anaconda. Try conda update libgcc. Then rebuild detectron2.
The fundamental solution is to run the code with proper C++ runtime. One way is to use LD_PRELOAD=/path/to/libstdc++.so.

`conda update libgcc` is likely not enough since libgcc in anaconda is pretty old.
More explanation in the last section of https://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/

Closing as its unrelated to detectron2.
