### ISSUE TITLE
__init__() missing 1 required positional argument: 'dtypes'

### ISSUE THREAD

**Issue by OrjwanZaafarani** [facebookresearch/detectron2#3145]
I tried to train Faster RCNN (COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml) on a custom dataset. I faced the following error at the beginning of the training:

```
[06/13 16:37:53 d2.engine.train_loop]: Starting training from iteration 0
ERROR [06/13 16:37:54 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 226, in run_step
    data = next(self._data_loader_iter)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 179, in __iter__
    for d in self.dataset:
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/.local/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtypes'
[06/13 16:37:54 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[06/13 16:37:54 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 4469M

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-83-1e412945cb08> in <module>
      3 trainer = QMULTrainer(cfg)
      4 trainer.resume_or_load(resume=False)
----> 5 trainer.train()

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in train(self)
    429             OrderedDict of results, if evaluation is enabled. Otherwise None.
    430         """
--> 431         super().train(self.start_iter, self.max_iter)
    432         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    433             assert hasattr(

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    136                 for self.iter in range(start_iter, max_iter):
    137                     self.before_step()
--> 138                     self.run_step()
    139                     self.after_step()
    140                 # self.iter == max_iter can be used by `after_train` to

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in run_step(self)
    439     def run_step(self):
    440         self._trainer.iter = self.iter
--> 441         self._trainer.run_step()
    442 
    443     @classmethod

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in run_step(self)
    224         If you want to do something with the data, you can wrap the dataloader.
    225         """
--> 226         data = next(self._data_loader_iter)
    227         data_time = time.perf_counter() - start
    228 

/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py in __iter__(self)
    177 
    178     def __iter__(self):
--> 179         for d in self.dataset:
    180             w, h = d["width"], d["height"]
    181             bucket_id = 0 if w > h else 1

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    515             if self._sampler_iter is None:
    516                 self._reset()
--> 517             data = self._next_data()
    518             self._num_yielded += 1
    519             if self._dataset_kind == _DatasetKind.Iterable and \

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1197             else:
   1198                 del self._task_info[idx]
-> 1199                 return self._process_data(data)
   1200 
   1201     def _try_put_index(self):

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1223         self._try_put_index()
   1224         if isinstance(data, ExceptionWrapper):
-> 1225             data.reraise()
   1226         return data
   1227 

~/.local/lib/python3.6/site-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             raise self.exc_type(message=msg)
--> 429         raise self.exc_type(msg)
    430 
    431 

TypeError: __init__() missing 1 required positional argument: 'dtypes'

```
The following is the docker file that I used:

```
FROM nvidia/cuda:10.1-cudnn7-devel

COPY ./ /workspace

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install gcc mono-mcs python3-pip python3-dev ffmpeg libsm6 libxext6 && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade setuptools 
RUN pip3 install --upgrade pip
RUN pip install --user torch==1.8 torchvision==0.9 -f https://download.pytorch.org/whl/cu101/torch_stable.html
RUN pip3 install pyyaml==5.1 jupyter opencv-python numpy matplotlib detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html

WORKDIR /workspace

EXPOSE 8888

CMD jupyter notebook --no-browser --ip=0.0.0.0 --port 8888 --allow-root --NotebookApp.token='detectron2' --NotebookApp.allow_origin='*'

```

How can I fix this?

**Comment by OrjwanZaafarani** [comment]
Also, I tried building the repo's docker file and training. However, the same problem keeps occurring.

**Comment by ShadiZaki** [comment]
What was the fix?

**Comment by YixingHuang** [comment]
Choosing a smaller parameter for the **num_workers** helps me.
