### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by sunjeet95** [facebookresearch/detectron2#3153]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
```
2. What exact command you run: python apply_net.py show configs/cse/densepose_rcnn_R_50_FPN_s1x.yaml  https://dl.fbaipublicfiles.com/densepose/cse/densepose_rcnn_R_50_FPN_s1x/251155172/model_final_c4ea5f.pkl image.jpg dp_cse_texture,bbox  --texture_atlases_map '{"smpl_27554": "smpl_uvSnapshot_colors.jpg"}' -v

3. __Full logs__ or other relevant observations:
```
[06/15 01:31:19 apply_net]: Loading config from configs/cse/densepose_rcnn_R_50_FPN_s1x.yaml
[06/15 01:31:19 apply_net]: Loading model from https://dl.fbaipublicfiles.com/densepose/cse/densepose_rcnn_R_50_FPN_s1x/251155172/model_final_c4ea5f.pkl
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
  proposal_generator.anchor_generator.cell_anchors.{0, 1, 2, 3, 4}
[06/15 01:31:22 apply_net]: Loading data from image.jpg
Traceback (most recent call last):
  File "apply_net.py", line 354, in <module>
    main()
  File "apply_net.py", line 350, in main
    args.func(args)
  File "apply_net.py", line 101, in execute
    context = cls.create_context(args, cfg)
  File "apply_net.py", line 311, in create_context
    texture_atlases_dict = get_texture_atlases(args.texture_atlases_map)
  File "/home/sunjeet/detectron2/projects/DensePose/densepose/vis/densepose_outputs_vertex.py", line 139, in get_texture_atlases
    return {mesh_name: get_texture_atlas(path) for mesh_name, path in paths.items()}
  File "/home/sunjeet/detectron2/projects/DensePose/densepose/vis/densepose_outputs_vertex.py", line 139, in <dictcomp>
    return {mesh_name: get_texture_atlas(path) for mesh_name, path in paths.items()}
  File "/home/sunjeet/detectron2/projects/DensePose/densepose/vis/densepose_results_textures.py", line 21, in get_texture_atlas
    bgr_image = read_image(path)
  File "/home/sunjeet/.local/lib/python3.6/site-packages/detectron2/data/detection_utils.py", line 180, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/home/sunjeet/anaconda3/envs/torch/lib/python3.6/site-packages/iopath/common/file_io.py", line 930, in open
    path, mode, buffering=buffering, **kwargs
  File "/home/sunjeet/anaconda3/envs/torch/lib/python3.6/site-packages/iopath/common/file_io.py", line 597, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: 'smpl_uvSnapshot_colors.jpg'
```

## Expected behavior:

If there are no obvious crash in "full logs" provided above,
please tell us the expected behavior.

If you expect a model to converge / work better, we do not help with such issues, unless
a model fails to reproduce the results in detectron2 model zoo, or proves existence of bugs.

## Environment:

Paste the output of the following command:
```
----------------------  ---------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) [GCC 9.3.0]
numpy                   1.19.2
detectron2              0.4.1 @/home/sunjeet/.local/lib/python3.6/site-packages/detectron2
Compiler                GCC 5.4
CUDA compiler           CUDA 10.2
detectron2 arch flags   5.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1 @/home/sunjeet/anaconda3/envs/torch/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 860M (arch=5.0)
CUDA_HOME               /usr/local/cuda-10.2
Pillow                  8.2.0
torchvision             0.9.1+cu102 @/home/sunjeet/anaconda3/envs/torch/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20210609
iopath                  0.1.8
cv2                     4.5.2
----------------------  ---------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

```

If your issue looks like an installation issue / environment issue,
please first check common issues in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by vkhalidov** [comment]
Hi @sunjeet95, the error states that the file `smpl_uvSnapshot_colors.jpg` was not found. Did you verify that the file is available at the specified location?

**Comment by llpspark** [comment]
> Hi @sunjeet95, the error states that the file `smpl_uvSnapshot_colors.jpg` was not found. Did you verify that the file is available at the specified location?

hello, where can download this file? thanks.

**Comment by nxrcqupt01** [comment]
hello, where can download this file? thanks.

>

**Comment by ganlvtech** [comment]
* https://dl.fbaipublicfiles.com/densepose/web/coords.png
* https://dl.fbaipublicfiles.com/densepose/web/densepose_human_charts_wcoarse.png
* https://github.com/facebookresearch/DensePose/blob/main/DensePoseData/demo_data/texture_atlas_200.png
* https://github.com/facebookresearch/DensePose/blob/main/DensePoseData/demo_data/texture_from_SURREAL.png
* https://dl.fbaipublicfiles.com/densepose/web/apply_net/texture_from_SURREAL.jpg
* https://dl.fbaipublicfiles.com/densepose/web/apply_net/smpl_uvSnapshot_colors.jpg

![https://dl.fbaipublicfiles.com/densepose/web/densepose_human_charts_wcoarse.png](https://dl.fbaipublicfiles.com/densepose/web/densepose_human_charts_wcoarse.png)
![https://github.com/facebookresearch/DensePose/raw/main/DensePoseData/demo_data/texture_atlas_200.png](https://github.com/facebookresearch/DensePose/raw/main/DensePoseData/demo_data/texture_atlas_200.png)
![https://dl.fbaipublicfiles.com/densepose/web/apply_net/texture_from_SURREAL.jpg](https://dl.fbaipublicfiles.com/densepose/web/apply_net/texture_from_SURREAL.jpg)
![https://dl.fbaipublicfiles.com/densepose/web/apply_net/smpl_uvSnapshot_colors.jpg](https://dl.fbaipublicfiles.com/densepose/web/apply_net/smpl_uvSnapshot_colors.jpg)
