### ISSUE TITLE
Error when training DeepLabV3+

### ISSUE THREAD

**Issue by dinisov** [facebookresearch/detectron2#3197]
Hello, I get the following error when attempting to train a DeeplabV3 model for a simple foreground/background segmentation. 1024x1024 images are being fed to the model, annotations are as described in the documentation, i.e. single -channel images with 0's for one category and 1's for the other. The machine has 2 RTX 2080Ti GPUs.

```
File "/home/ndserv05/Documents/Python/detectron2/detectron2/layers/aspp.py", line 135, in forward
    "Input size: {} `pool_kernel_size`: {}".format(size, self.pool_kernel_size)
ValueError: `pool_kernel_size` must be divisible by the shape of inputs. Input size: torch.Size([32, 32]) `pool_kernel_size`: (32, 64)
```
## Instructions To Reproduce the Issue:

```
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random
import pycocotools
import skimage.draw
from PIL import Image, ImageDraw
from progress.bar import Bar
import datetime

from detectron2.engine.hooks import HookBase
from detectron2.evaluation import inference_context
from detectron2.utils.logger import log_every_n_seconds
import detectron2.utils.comm as comm
import torch
import time
import logging

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor, DefaultTrainer, launch, default_argument_parser, default_setup
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import DatasetMapper, MetadataCatalog, DatasetCatalog, build_detection_test_loader, build_detection_train_loader
import detectron2.data.transforms as T

# deeplab specific stuff
from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler

from detectron2.evaluation import COCOEvaluator, inference_on_dataset

from detectron2.structures import BoxMode

from tools.darwin import *

categories = ["Background", "Tower foreground"]


def build_sem_seg_train_aug(cfg):
    augs = [
        T.ResizeShortestEdge(
            cfg.INPUT.MIN_SIZE_TRAIN, cfg.INPUT.MAX_SIZE_TRAIN, cfg.INPUT.MIN_SIZE_TRAIN_SAMPLING
        )
    ]
    if cfg.INPUT.CROP.ENABLED:
        augs.append(
            T.RandomCrop_CategoryAreaConstraint(
                cfg.INPUT.CROP.TYPE,
                cfg.INPUT.CROP.SIZE,
                cfg.INPUT.CROP.SINGLE_CATEGORY_MAX_AREA,
                cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE,
            )
        )
    augs.append(T.RandomFlip())
    return augs


def setup(args):

    #set the number of GPUs
    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

    # REGISTER DATASETS
    dataset_directory = "/home/ndserv05/Documents/Data/Tower_foreground"

    for d in ["train", "val"]:
        # get_darwin_dataset(dataset_directory, d)
        DatasetCatalog.register("tower_foreground_" + d, lambda d=d: get_darwin_dataset(dataset_directory, d, categories))
        MetadataCatalog.get("tower_foreground_" + d).set(thing_classes=categories)

    # CONFIGURATION
    cfg = get_cfg()
    add_deeplab_config(cfg)
    cfg.merge_from_file("./projects/DeepLab/configs/Cityscapes-SemanticSegmentation/deeplab_v3_plus_R_103_os16_mg124_poly_90k_bs16.yaml")
    cfg.OUTPUT_DIR = "./output/" + "Tower_foreground" + "{:%Y%m%dT%H%M}".format(datetime.datetime.now())
    cfg.DATASETS.TRAIN = ("tower_foreground_train",)
    cfg.DATASETS.TEST = ()
    cfg.MODEL.WEIGHTS = "model_final_a8a355.pkl"  # downloaded from https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2
    cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = 2

    cfg.freeze()
    default_setup(cfg, args)

    return cfg

# TRAINER
class myTrainer(DefaultTrainer):

    @classmethod
    def build_train_loader(cls, cfg):
        if "SemanticSegmentor" in cfg.MODEL.META_ARCHITECTURE:
            mapper = DatasetMapper(cfg, is_train=True, augmentations=build_sem_seg_train_aug(cfg))
        else:
            mapper = None
        return build_detection_train_loader(cfg, mapper=mapper)

    @classmethod
    def build_lr_scheduler(cls, cfg, optimizer):
        """
        It now calls :func:`detectron2.solver.build_lr_scheduler`.
        Overwrite it if you'd like a different scheduler.
        """
        return build_lr_scheduler(cfg, optimizer)


def main(args):

    cfg = setup(args)

    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = myTrainer(cfg)
    trainer.resume_or_load(resume=False)
    
    return trainer.train()

if __name__ == '__main__':
    args = default_argument_parser().parse_args()
    launch(
        main,
        2,
        num_machines=1,
        machine_rank=args.machine_rank,
        dist_url=args.dist_url,
        args=(args,),
    )
```
## Expected behavior:

Training as usual.

## Environment:

```
detectron2              0.3 @/home/ndserv05/Documents/Python/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.0
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/home/ndserv05/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda-10.0
Pillow                  8.1.0
torchvision             0.8.2 @/home/ndserv05/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20210423
cv2                     4.5.1
----------------------  --------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by dinisov** [comment]
I realised that the size of the crop was the same as the image (at least on one of the edges) and that this may be problematic,  so I reduced it to:

`cfg.INPUT.CROP.SIZE = (256, 512)`

And now I get the following error:

```
  File "/home/ndserv05/Documents/Python/detectron2/projects/DeepLab/deeplab/loss.py", line 39, in forward
    pixel_losses, _ = torch.topk(pixel_losses, top_k_pixels)
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by dinisov** [comment]
So I updated CUDA to 11.4 and now I get:

```
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

My New environment is:

```
----------------------  ---------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
numpy                   1.19.5
detectron2              0.3 @/home/ndserv05/Documents/Python/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 11.4
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu102 @/home/ndserv05/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 NVIDIA GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda-11.4
Pillow                  8.1.0
torchvision             0.10.0+cu102 @/home/ndserv05/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3.post20210317
cv2                     4.5.1
----------------------  ---------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by dinisov** [comment]
So I downgraded CUDA to 11.1, torch to 1.8.1 torchvision to 0.9.1, and now my environment looks like this:

```
----------------------  --------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
numpy                   1.19.5
detectron2              0.3 @/home/ndserv05/Documents/Python/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 11.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu102 @/home/ndserv05/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda-11.1
Pillow                  8.1.0
torchvision             0.9.1+cu102 @/home/ndserv05/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.3.post20210317
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

And I am still getting:

```
[06/30 08:22:07 d2.engine.hooks]: Total training time: 0:00:10 (0:00:00 on hooks)
[06/30 08:22:07 d2.engine.hooks]: Total training time: 0:00:10 (0:00:00 on hooks)
[06/30 08:22:07 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 932M
[06/30 08:22:07 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 932M
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f82078cd2f2 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f82078ca67b in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f8207b251f9 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f82078b53a4 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e977a (0x7f820884477a in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e9821 (0x7f8208844821 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: /usr/bin/python3() [0x54edf6]
frame #7: /usr/bin/python3() [0x5731a0]
frame #8: /usr/bin/python3() [0x588bfc]
frame #9: /usr/bin/python3() [0x54eafb]
frame #10: /usr/bin/python3() [0x54eafb]
frame #11: /usr/bin/python3() [0x588fd8]
frame #12: /usr/bin/python3() [0x5add78]
frame #13: /usr/bin/python3() [0x5add8e]
frame #14: /usr/bin/python3() [0x5add8e]
frame #15: /usr/bin/python3() [0x5add8e]
frame #16: /usr/bin/python3() [0x5add8e]
frame #17: /usr/bin/python3() [0x5add8e]
frame #18: /usr/bin/python3() [0x5add8e]
frame #19: /usr/bin/python3() [0x5add8e]
frame #20: /usr/bin/python3() [0x5add8e]
frame #21: /usr/bin/python3() [0x5905a9]
frame #22: /usr/bin/python3() [0x590546]
frame #23: /usr/bin/python3() [0x629643]
frame #24: _PyEval_EvalFrameDefault + 0x4468 (0x50ff68 in /usr/bin/python3)
frame #25: /usr/bin/python3() [0x5096c8]
frame #26: /usr/bin/python3() [0x50a3fd]
frame #27: _PyEval_EvalFrameDefault + 0x444 (0x50bf44 in /usr/bin/python3)
frame #28: /usr/bin/python3() [0x5096c8]
frame #29: /usr/bin/python3() [0x50a3fd]
frame #30: _PyEval_EvalFrameDefault + 0x444 (0x50bf44 in /usr/bin/python3)
frame #31: /usr/bin/python3() [0x507cd4]
frame #32: /usr/bin/python3() [0x509a00]
frame #33: /usr/bin/python3() [0x50a3fd]
frame #34: _PyEval_EvalFrameDefault + 0x1215 (0x50cd15 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x507cd4]
frame #36: PyRun_StringFlags + 0xaf (0x6354af in /usr/bin/python3)
frame #37: PyRun_SimpleStringFlags + 0x3d (0x63891d in /usr/bin/python3)
frame #38: Py_Main + 0x353 (0x639433 in /usr/bin/python3)
frame #39: main + 0xe0 (0x4b0e40 in /usr/bin/python3)
frame #40: __libc_start_main + 0xe7 (0x7f820df9dbf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #41: _start + 0x2a (0x5b2f0a in /usr/bin/python3)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f2e8257d2f2 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f2e8257a67b in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f2e827d51f9 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f2e825653a4 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e977a (0x7f2e834f477a in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e9821 (0x7f2e834f4821 in /home/ndserv05/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: /usr/bin/python3() [0x54edf6]
frame #7: /usr/bin/python3() [0x5731a0]
frame #8: /usr/bin/python3() [0x588bfc]
frame #9: /usr/bin/python3() [0x54eafb]
frame #10: /usr/bin/python3() [0x54eafb]
frame #11: /usr/bin/python3() [0x588fd8]
frame #12: /usr/bin/python3() [0x5add78]
frame #13: /usr/bin/python3() [0x5add8e]
frame #14: /usr/bin/python3() [0x5add8e]
frame #15: /usr/bin/python3() [0x5add8e]
frame #16: /usr/bin/python3() [0x5add8e]
frame #17: /usr/bin/python3() [0x5add8e]
frame #18: /usr/bin/python3() [0x5add8e]
frame #19: /usr/bin/python3() [0x5add8e]
frame #20: /usr/bin/python3() [0x5add8e]
frame #21: /usr/bin/python3() [0x5905a9]
frame #22: /usr/bin/python3() [0x590546]
frame #23: /usr/bin/python3() [0x629643]
frame #24: _PyEval_EvalFrameDefault + 0x4468 (0x50ff68 in /usr/bin/python3)
frame #25: /usr/bin/python3() [0x5096c8]
frame #26: /usr/bin/python3() [0x50a3fd]
frame #27: _PyEval_EvalFrameDefault + 0x444 (0x50bf44 in /usr/bin/python3)
frame #28: /usr/bin/python3() [0x5096c8]
frame #29: /usr/bin/python3() [0x50a3fd]
frame #30: _PyEval_EvalFrameDefault + 0x444 (0x50bf44 in /usr/bin/python3)
frame #31: /usr/bin/python3() [0x507cd4]
frame #32: /usr/bin/python3() [0x509a00]
frame #33: /usr/bin/python3() [0x50a3fd]
frame #34: _PyEval_EvalFrameDefault + 0x1215 (0x50cd15 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x507cd4]
frame #36: PyRun_StringFlags + 0xaf (0x6354af in /usr/bin/python3)
frame #37: PyRun_SimpleStringFlags + 0x3d (0x63891d in /usr/bin/python3)
frame #38: Py_Main + 0x353 (0x639433 in /usr/bin/python3)
frame #39: main + 0xe0 (0x4b0e40 in /usr/bin/python3)
frame #40: __libc_start_main + 0xe7 (0x7f2e88c4dbf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #41: _start + 0x2a (0x5b2f0a in /usr/bin/python3)

Traceback (most recent call last):
  File "train_tower_foreground.py", line 226, in <module>
    args=(args,),
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/ndserv05/Documents/Python/detectron2/train_tower_foreground.py", line 216, in main
    return trainer.train()
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/engine/train_loop.py", line 232, in run_step
    loss_dict = self.model(data)
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ndserv05/Documents/Python/detectron2/detectron2/modeling/meta_arch/semantic_seg.py", line 82, in forward
    results, losses = self.sem_seg_head(features, targets)
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ndserv05/Documents/Python/detectron2/projects/DeepLab/deeplab/semantic_seg.py", line 231, in forward
    return None, self.losses(y, targets)
  File "/home/ndserv05/Documents/Python/detectron2/projects/DeepLab/deeplab/semantic_seg.py", line 259, in losses
    loss = self.loss(predictions, targets)
  File "/home/ndserv05/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ndserv05/Documents/Python/detectron2/projects/DeepLab/deeplab/loss.py", line 39, in forward
    pixel_losses, _ = torch.topk(pixel_losses, top_k_pixels)
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by dinisov** [comment]
So I reduced the crop size to:

`cfg.INPUT.CROP.SIZE = (64, 128)`

And now it works. Is this expected? DeepLab does not fit into 11GB of GPU memory with (256, 512) size images?!?

**Comment by dinisov** [comment]
It turns out all the errors above are due to lack of memory.
