### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by CarlBhy** [facebookresearch/detectron2#3200]
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "tools/train.py", line 246, in <module>
    res = Trainer.test(cfg, model)
  File "/home/sc/carl_test/detectron2-geo/detectron2/engine/defaults.py", line 606, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/sc/carl_test/detectron2-geo/detectron2/evaluation/evaluator.py", line 152, in inference_on_dataset
    outputs = model(inputs)
  File "/home/sc/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/meta_arch/rcnn.py", line 147, in forward
    return self.inference(batched_inputs)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/meta_arch/rcnn.py", line 210, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/sc/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/roi_heads.py", line 739, in forward
    pred_instances = self._forward_box(features, proposals)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/roi_heads.py", line 807, in _forward_box
    pred_instances, _ = self.box_predictor.inference(predictions, proposals, result_gcn)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/fast_rcnn.py", line 661, in inference
    self.test_topk_per_image,
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/fast_rcnn.py", line 84, in fast_rcnn_inference
    for scores_per_image, boxes_per_image, image_shape in zip(scores, boxes, image_shapes)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/fast_rcnn.py", line 84, in <listcomp>
    for scores_per_image, boxes_per_image, image_shape in zip(scores, boxes, image_shapes)
  File "/home/sc/carl_test/detectron2-geo/detectron2/modeling/roi_heads/fast_rcnn.py", line 179, in fast_rcnn_inference_single_image
    delete_sample = torch.tensor(drop_ids)
RuntimeError: CUDA error: device-side assert triggered

**Comment by CarlBhy** [comment]
When I modified the fast_rcnn_inference_single_image, an exception occurred. This problem has troubled me for a long time. I printed out the index, and the index did not cross the boundary.

**Comment by CarlBhy** [comment]
my environment:
python 3.7.10
torch 1.6.0
cuda 10.1

**Comment by dimzog** [comment]
Had the same issue. Check https://github.com/facebookresearch/detectron2/issues/3158#issuecomment-872858158
