### ISSUE TITLE
error due to metadata: thing_dataset_id_to_contiguous_id'

### ISSUE THREAD

**Issue by waldenmarshall** [facebookresearch/detectron2#3212]
## General Description:

I am trying to use a script given to me by a collaborator to train a panoptic segmentation dataset. I am able to register the dataset with `register_coco_panoptic()` but I am getting an error due to the dataset's metadata, or lack thereof.

1. Full runnable code:
```
import os
from torch.utils.tensorboard import SummaryWriter
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2 import model_zoo

#%%
# if your dataset is in COCO format, register dataset in coco format:
from detectron2.data.datasets import register_coco_instances
from detectron2.data.datasets import register_coco_panoptic
from detectron2.data.datasets import register_coco_panoptic_separated


base_dir='/home/walden/Desktop/appleData'
img_dir=base_dir+'/AppleA/FlowerImages'
GT_dir=base_dir+'/AppleA_GT'
panoptic_json=base_dir+'/appleA_imgsannscats.json'
register_coco_panoptic("AppleA_pan", {}, img_dir, GT_dir,panoptic_json)
#register_coco_panoptic_separated("AppleA", metadata, img_dir, GT_dir,panoptic_json, GT_dir, panoptic_json)

from detectron2.data import DatasetCatalog
DatasetCatalog.get('AppleA_pan')
#%%
# =============================================================================
# from detectron2.data import MetadataCatalog
# MetadataCatalog.get("AppleA_pan").thing_classes = ['flower']
# MetadataCatalog.get("AppleA_pan").stuff_classes = ['background']
# MetadataCatalog.get("AppleA_pan").thing_dataset_id_to_contiguous_id = {1:1}
# MetadataCatalog.get("AppleA_pan").stuff_dataset_id_to_contiguous_id = {0:0}
# MetadataCatalog.get("AppleA_pan").panoptic_json = panoptic_json
# 
# =============================================================================

#%%
'''
for n_iter in range(100):
    writer.add_scalar('Loss/train', np.random.random(), n_iter)
    writer.add_scalar('Loss/test', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/train', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/test', np.random.random(), n_iter)
'''
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("AppleA_pan",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")
if not os.path.exists(cfg.OUTPUT_DIR):
    os.makedirs(cfg.OUTPUT_DIR)

cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.005
cfg.SOLVER.MAX_ITER = 20000
cfg.SOLVER.STEPS = (5000, 10000, 15000, 20000)
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2
cfg.MODEL.BACKBONE.FREEZE_AT = 5
cfg.INPUT.MIN_SIZE_TRAIN = (640, 672, 704, 736, 768, 800,1080)
cfg.MODEL.ANCHOR_GENERATOR.ASPECT_RATIOS = [[0.5, 1.0, 2.0]] 
cfg.VIS_PERIOD = 1000
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```
2. What exact command you run:  
     Just the "Run" button in the IDE (Spyder)
3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):

  File "/home/walden/Desktop/appleData/train_clasp_det2.py", line 22, in <module>
    DatasetCatalog.get('AppleA_pan')

  File "/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()

  File "/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 88, in <lambda>
    lambda: load_coco_panoptic_json(panoptic_json, image_root, panoptic_root, metadata),

  File "/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 51, in load_coco_panoptic_json
    segments_info = [_convert_category_id(x, meta) for x in ann["segments_info"]]

  File "/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 51, in <listcomp>
    segments_info = [_convert_category_id(x, meta) for x in ann["segments_info"]]

  File "/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/data/datasets/coco_panoptic.py", line 27, in _convert_category_id
    if segment_info["category_id"] in meta["thing_dataset_id_to_contiguous_id"]:

KeyError: 'thing_dataset_id_to_contiguous_id'
```

## Expected behavior:

Successful training. Or at least not breaking due to the metadata

## Troubleshooting attempts:

First, I tried manually assigning the metadata values, as shown in the commented lines 25-30 (`MetadataCatalog.get("AppleA_pan").thing_dataset_id_to_contiguous_id = {1:1}`), etc. I also tried assigning these as empty dictionaries. When I did this, I did not include the lines `from detectron2.data import DatasetCatalog
DatasetCatalog.get('AppleA_pan')` The error I received also pertained to `thing_dataset_id_to_contiguous_id`, though in this case it came from one of the later lines: `trainer = DefaultTrainer(cfg)`

The other troubleshooting attempt I made was to neglect the commented lines(`MetadataCatalog.get("AppleA_pan").thing_dataset_id_to_contiguous_id = {1:1}`), etc and instead using `from detectron2.data import DatasetCatalog
DatasetCatalog.get('AppleA_pan')` as suggested in [Issue 189](https://github.com/facebookresearch/detectron2/issues/189)

## Environment:

```
----------------------  ------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
numpy                   1.20.1
detectron2              0.4 @/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   /home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1 @/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   NVIDIA Quadro K620 (arch=5.0)
CUDA_HOME               None - invalid!
Pillow                  8.2.0
torchvision             0.9.1 @/home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/torchvision
torchvision arch flags  /home/walden/anaconda3/envs/detectron2env/lib/python3.8/site-packages/torchvision/_C.so
fvcore                  0.1.3.post20210317
cv2                     4.5.2
----------------------  ------------------------------------------------------------------------------------------------------------------

**Comment by Mnsy-Syl** [comment]
Hey, I'm meeting with the same problem with you. Have you solved it? I've been caught in it for so long o(╥﹏╥)o

**Comment by hdnh2006** [comment]
Could you solve this issue? please provide some explanation if can.

**Comment by simsimee** [comment]
Is the problem solved? I'm stuck in this part, too. 
I want to solve it.............

**Comment by bansilol** [comment]
@waldenmarshall 
Hi!! Were you able to solve the issue y any chance ? I am facing exactly the same issue.
 Any inputs will be appreciated :)
