### ISSUE TITLE
[fixed] undefined symbol

### ISSUE THREAD

**Issue by 107061218** [facebookresearch/detectron2#3236]
# Undefined Symbol
## PLEASE HELP ME!!! THANKS A LOT!
Hello everyone, I put an image(00770ee8f5ad87ef.jpg ) into detectron2/demo and run this command
`python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input 00770ee8f5ad87ef.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl`
but it raises an error indicating `undefined symbol`, the whole error message is written as below: 
```
Traceback (most recent call last):  
  File "demo.py", line 14, in <module>
    from detectron2.data.detection_utils import read_image  
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/data/__init__.py", line 4, in <module>  
    from .build import (  
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /home/careplus/anaconda3/envs/det_2/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
```

Here is the details of my environment:
os: Ubuntu 18.04
python: 3.7.4
cuda: 10.2
pytorch: 1.8

Does anyone face the similar problem?
Thanks a lot for your help!

**Comment by 107061218** [comment]
Hi, what extra information should I provide? Thanks for your help!

**Comment by ppwwyyxx** [comment]
Please provide environment information following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?assignees=&labels=&template=unexpected-problems-bugs.md&title=Please+read+%26+provide+the+following).

**Comment by 107061218** [comment]
## PROBLEM SOLVED
I think I solved this problem. In the undefined symbol mentioned above, we can see "cuda" sub-string in it. So, what I did is uninstall my cuda driver and reinstall it and recompile related library. Finally, it can work properly now. 
Thank you for all your help. Thank my friend  [Bo-Wei Chen](https://github.com/BWbwchen) for help. Hope this information be useful for you if you encounter a problem similar to mine.
Thank you very much! Merci beaucoup! Danke!
