### ISSUE TITLE
[Fixed!]how to install TensorMask under Win10(win10 Pytorch1.9.0+CUDA11.1+CUDNN8.0.5)

### ISSUE THREAD

**Issue by Shuolongbj** [facebookresearch/detectron2#3248]
Hi Sir：

I meet some problems when i installed TensorMask in Detectron2 under Win10(Pytorch1.9.0+CUDA11.1+CUDNN8.0.5).

Can somebody help me...?

#1、the error msgs happend：
    D:\_DL\detectron2>pip install -e projects/TensorMask
         .......

    D:\_DL\detectron2\projects\TensorMask\tensormask\layers\csrc\SwapAlign2Nat/SwapAlign2Nat.h(43): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "d:\program files (x86)\python\python38\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
        subprocess.run(
      File "d:\program files (x86)\python\python38\lib\subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\_DL\detectron2\projects\TensorMask\setup.py", line 61, in <module>
        setup(
      File "d:\program files (x86)\python\python38\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "d:\program files (x86)\python\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\program files (x86)\python\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\program files (x86)\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\program files (x86)\python\python38\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "d:\program files (x86)\python\python38\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "d:\program files (x86)\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\program files (x86)\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\program files (x86)\python\python38\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "d:\program files (x86)\python\python38\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "d:\program files (x86)\python\python38\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "d:\program files (x86)\python\python38\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "d:\program files (x86)\python\python38\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "d:\program files (x86)\python\python38\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "d:\program files (x86)\python\python38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "d:\program files (x86)\python\python38\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "d:\program files (x86)\python\python38\lib\distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "d:\program files (x86)\python\python38\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "d:\program files (x86)\python\python38\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "d:\program files (x86)\python\python38\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "d:\program files (x86)\python\python38\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\program files (x86)\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\_DL\\detectron2\\projects\\TensorMask\\setup.py'"'"'; __file__='"'"'D:\\_DL\\detectron2\\projects\\TensorMask\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

#2
D:\_DL\detectron2>wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
----------------------  --------------------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
numpy                   1.19.2
detectron2              0.4.1 @D:\_DL\detectron2\detectron2
Compiler                MSVC 192930038
CUDA compiler           CUDA 11.0
detectron2 arch flags   D:\_DL\detectron2\detectron2\_C.cp38-win_amd64.pyd; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu111 @D:\Program Files (x86)\Python\Python38\lib\site-packages\torch
PyTorch debug build     False
GPU available           True
GPU 0                   Quadro T2000 with Max-Q Design (arch=7.5)
CUDA_HOME               D:\Program Files (x86)\NVIDIA GPU Computing Toolkit\CUDA\v11.0
Pillow                  8.2.0
torchvision             0.10.0+cu111 @D:\Program Files (x86)\Python\Python38\lib\site-packages\torchvision
torchvision arch flags  D:\Program Files (x86)\Python\Python38\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.5.post20210630
iopath                  0.1.8
cv2                     4.5.2
----------------------  --------------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

**Comment by Shuolongbj** [comment]
Finished to install TensorMask in Detectron2 in Win10(Pytorch1.9.0+CUDA11.1+CUDNN8.0.5)

(1) updated the fllowing files

1）.\detectron2\projects\TensorMask\tensormask\layers\csrc\SwapAlign2Nat\SwapAlign2Nat.h

if (X.type().is_cuda()) -->  if (X.is_cuda())
if (gY.type().is_cuda()) -->  if (gY.is_cuda())
2）.\detectron2\projects\TensorMask\tensormask\layers\csrc\SwapAlign2Nat\SwapAlign2Nat_cuda.cu

dim3 grid(std::min(at::cuda::ATenCeilDiv(Y.numel(), 512L), 4096L));  -->  dim3 grid(std::min(at::cuda::ATenCeilDiv((int)Y.numel(), 512), 4096));
dim3 grid(std::min(at::cuda::ATenCeilDiv(gY.numel(), 512L), 4096L)); -->  dim3 grid(std::min(at::cuda::ATenCeilDiv((int)gY.numel(), 512), 4096));

(2) make

cd /path/to/detectron2/projects/TensorMask
python setup.py build develop

copying build\lib.win-amd64-3.8\tensormask\_C.cp38-win_amd64.pyd -> tensormask
Creating d:\program files (x86)\python\python38\lib\site-packages\tensormask.egg-link (link to .)
Adding tensormask 0.1 to easy-install.pth file

Installed d:\_dl\detectron2\projects\tensormask
Processing dependencies for tensormask==0.1
Finished processing dependencies for tensormask==0.1

(3)
D:\_DL\detectron2\projects\TensorMask>wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
----------------------  --------------------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
numpy                   1.19.2
detectron2              0.4.1 @d:\_dl\detectron2\detectron2
Compiler                MSVC 192930038
CUDA compiler           CUDA 11.0
detectron2 arch flags   d:\_dl\detectron2\detectron2\_C.cp38-win_amd64.pyd; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu111 @D:\Program Files (x86)\Python\Python38\lib\site-packages\torch
PyTorch debug build     False
GPU available           True
GPU 0                   Quadro T2000 with Max-Q Design (arch=7.5)
CUDA_HOME               D:\Program Files (x86)\NVIDIA GPU Computing Toolkit\CUDA\v11.0
Pillow                  8.2.0
torchvision             0.10.0+cu111 @D:\Program Files (x86)\Python\Python38\lib\site-packages\torchvision
torchvision arch flags  D:\Program Files (x86)\Python\Python38\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.5.post20210630
iopath                  0.1.8
cv2                     4.5.2
----------------------  --------------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
