### ISSUE TITLE
RuntimeError on NCCL when Training with Multiple GPUs

### ISSUE THREAD

**Issue by Ribosome-rbx** [facebookresearch/detectron2#3257]
1. Full runnable code or full changes you made:
```
python tools/train_net.py --num-gpus 4 --config-file configs/LVISv1-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml
```
2. __Full logs__ or other relevant observations:
```
Command Line Args: Namespace(config_file='configs/LVISv1-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', dist_url='tcp://127.0.0.1:53449', eval_only=False, machine_rank=0, num_gpus=4, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "tools/train_net.py", line 169, in <module>
    args=(args,),
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/launch.py", line 80, in _distributed_worker
    comm.synchronize()
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/utils/comm.py", line 79, in synchronize
    dist.barrier()
  File "/home/zbao/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:761, internal error, NCCL version 2.7.8
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption
```

## Expected behavior:
train builtin model (R50-FPN) on Lvis v1 with 4 GPUs to reproduce the results in [ModuleZoo-lvis](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#lvis-instance-segmentation-baselines-with-mask-r-cnn) 

## Environment:

Paste the output of the following command:
```
2021-07-18 05:46:25 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/master/detectron2/utils/collect_env.py [7340/7340] -> "collect_env.py" [1]
---------------------  ---------------------------------------------------------------------------
sys.platform           linux
Python                 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
numpy                  1.20.3
detectron2             0.4 @/home/zbao/anaconda3/envs/d2/lib/python3.7/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          CUDA 10.2
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.8.0 @/home/zbao/anaconda3/envs/d2/lib/python3.7/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.3.1
torchvision            0.9.0 @/home/zbao/anaconda3/envs/d2/lib/python3.7/site-packages/torchvision
fvcore                 0.1.3.post20210317
cv2                    Not found
---------------------  ---------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```
When training or evaluating with num-gpus set to 1, the process goes on well. The error only occurs under multi-gpu settings.
Is there any way to fix this problem? Thank you a lot for your time and help!

**Comment by ppwwyyxx** [comment]
`torch.cuda.is_available()` returns False according to the environment info. So failure is expected and unrelated to detectron2.
