### ISSUE TITLE
register_coco_panoptic_separated fails because of metadata when I try to give and empty value

### ISSUE THREAD

**Issue by isagastiberri** [facebookresearch/detectron2#327]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
include:

## How To Reproduce the Issue
I'm trying to register Mapillary panoptic dataset and I finally decided as Mapillary data is in COCO format for panoptic that it would be best to create json annotations for instance segmentation for Mapillary. So, currently I have the whole dataset of Mapillary converted into COCO format. I try to use register_coco_panoptic_separated() in detectron2.data.datasets but when I run my code it gives me an error
1. what changes you made (`git diff`) or what code you wrote
The code I'm using is as follows:
``` 
if __name__ == '__main__':
    setup_logger()
    mp.set_start_method("spawn", force=True)

    root_dir = './datasets/mapillary-vistas-panoptic/'
    for d in ["training", "validation"]:
        data_name = 'mapillary-panoptic-'
        image_root = os.path.join(root_dir, "{}/images/".format(d))
        panoptic_root = os.path.join(root_dir,"{}/panoptic/".format(d))
        panoptic_json = os.path.join(panoptic_root, 'panoptic_2018.json')
        with open(panoptic_json) as panoptic_json_file:
            panoptic_dict = json.load(panoptic_json_file)
        sem_seg_root = os.path.join(root_dir,"{}/labels/".format(d))
        instances_json = os.path.join(root_dir,"coco/{}.json".format(d))
       
        register_coco_panoptic_separated(data_name + d, '', image_root, panoptic_root, panoptic_json, sem_seg_root, instances_json)
```
2. what exact command you run
I simply run this code with python tools/train_panoptic.py
3. what you observed (including the full logs):
```
Traceback (most recent call last):
  File "tools/train_panoptic.py", line 40, in <module>
    register_coco_panoptic_separated(data_name + d, '', image_root, panoptic_root, panoptic_json, sem_seg_root, instances_json)
  File "/workspace/detectron2/detectron2/data/datasets/register_coco.py", line 92, in register_coco_panoptic_separated
    **metadata
TypeError: set() argument after ** must be a mapping, not str
```

## Expected behavior

As in register_coco_instances() metadata is a dictionary and you can pass an empty dict I tried doing the same for panoptic but with a string instead, because in this case it's a string but I have this error. Do I need to pass some metadata? And in that case, what metadata does panoptic need? When I tried including some metadata created as in the code bellow I had the same error saying that metadata should be a mapping, not a MetaDataCatalog 
```
        things = []
        stuff = []
        for category in panoptic_dict['categories']:
            if category['isthing'] == 1:
                things.append(category['name'])
            else:
                stuff.append(category['name'])
        MetadataCatalog.get(data_name + d).set(thing_classes= things)
        MetadataCatalog.get(data_name + d).set(stuff_classes= stuff)
        mapillary_metadata = MetadataCatalog.get(root_dir + d)
´´´

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.
------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     Quadro M6000
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 8.0, V8.0.61
Pillow                    6.2.1
cv2                       3.4.2
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
It should be an empty dict, not string. This is a documentation error.

**Comment by isagastiberri** [comment]
Thanks! That solved that problem, but now the metadata saved with register_coco_panoptic is not properly saved. I register the dataset by using that function in a training script, but I prepared a inference code that loads MetadataCatalog, and the metadata that was created during training for mapillary is not there anymore. Is it possible to save the metadata so that it's available after exiting the code? Because right now I can only do training and inference in the same script and I'd like to have separated scripts for that.

in case I'm loading something incorrectly, here is my inference code:

```
from detectron2.utils.visualizer import Visualizer
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.data import MetadataCatalog
from detectron2.data.detection_utils import read_image
from detectron2.utils.visualizer import ColorMode

import os
import cv2 


cfg = get_cfg()
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = ("mapillary-panoptic-validation", )
predictor = DefaultPredictor(cfg)
# from detectron2.utils.visualizer import ColorMode
# dataset_dicts = get_balloon_dicts("balloon/val")
# for d in random.sample(dataset_dicts, 3):
root_dir = '/media/AjetoNetworking/tmp/isagastiberri/prueba/imgs'
mapillary_metadata = MetadataCatalog.get("mapillary-panoptic-validation_separated")
for root, _, files in os.walk(root_dir):
    for img_name in files:
        # im = cv2.imread(os.path.join(root_dir, img_name))
        im = read_image(os.path.join(root_dir, img_name), format="BGR")
        outputs = predictor(im)
        v = Visualizer(im[:, :, ::-1],
                    metadata=mapillary_metadata, 
                    scale=0.8, 
                    instance_mode=ColorMode.IMAGE
            )
        panoptic_seg, segments_info = outputs["panoptic_seg"]
        v = v.draw_panoptic_seg_predictions(
                panoptic_seg.to('cpu'), segments_info
            )
        cv2_imshow(v.get_image()[:, :, ::-1])
```
I debugged bot my training and inference code, and the metadata names created in training are no longer there during inference

**Comment by ppwwyyxx** [comment]
If you want separate scripts you can have your dataset code in a separate module which both your training and inference code import.

**Comment by isagastiberri** [comment]
Sorry, I don't understand what you mean. What I'd like to do is finetuning a network for panoptic and then being able to run an inference with different images that I'll be provided and with the metadata that was registered with register_coco_panoptic. I have metadata for training, as I'm using Mapillary, but for testing I just get raw images. Should I modify anything in register_coco_panoptic so that the metadata generated is accessible in the future? And what are the changes, or is there anything in the documentation about this issue?

I also have a second question, for now, I was running the code by training only for a few iterations and doing inference, without exiting, so that metadata wasn't lost and I run into another problem. It says there isn't stuff_classes in the metadata.

```
Traceback (most recent call last):
  File "tools/train_infere.py", line 6, in <module>
    infere()
  File "/workspace/detectron2/tools/inference.py", line 38, in infere
    panoptic_seg.to('cpu'), segments_info
  File "/workspace/detectron2/detectron2/utils/visualizer.py", line 435, in draw_panoptic_seg_predictions
    text = self.metadata.stuff_classes[category_idx]
  File "/workspace/detectron2/detectron2/data/catalog.py", line 116, in __getattr__
    key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'stuff_classes' does not exist in the metadata of 'mapillary-panoptic-training_separated'. Available keys are dict_keys(['name', 'panoptic_root', 'image_root', 'panoptic_json', 'sem_seg_root', 'json_file', 'evaluator_type', 'thing_classes', 'thing_dataset_id_to_contiguous_id']).
```

My training code is 
```
def train():
    setup_logger()
    root_dir = './datasets/mapillary-vistas-panoptic/'
    for d in ["training", "validation"]:
        data_name = 'mapillary-panoptic-'
        image_root = os.path.join(root_dir, "{}/images/".format(d))
        panoptic_root = os.path.join(root_dir,"{}/panoptic/".format(d))
        panoptic_json = os.path.join(panoptic_root, 'panoptic_2018.json')
        with open(panoptic_json) as panoptic_json_file:
            panoptic_dict = json.load(panoptic_json_file)
        sem_seg_root = os.path.join(root_dir,"{}/labels/".format(d))
        instances_json = os.path.join(root_dir,"coco/{}.json".format(d))
        register_coco_panoptic_separated(data_name + d, {}, image_root, panoptic_root, panoptic_json, sem_seg_root, instances_json)
    
mapillary_metadata_panoptic = MetadataCatalog.get("mapillary-panoptic-training_separated")
    mapillary_metadata_stuff = MetadataCatalog.get("mapillary-panoptic-training_stuffonly")
    mapillary_metadata = MetadataCatalog.get("mapillary-panoptic-validation_separated")
    mapillary_metadata = MetadataCatalog.get("mapillary-panoptic-validation_stuffonly")

    cfg = get_cfg()
    cfg.merge_from_file("./configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_1x.yaml")
    cfg.DATASETS.TRAIN = ("mapillary-panoptic-training_separated",)
    cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
    cfg.DATALOADER.NUM_WORKERS = 0
    cfg.MODEL.WEIGHTS = "models/model_final_panoptic.pkl"  # initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 1
    cfg.SOLVER.BASE_LR = 0.00025
    cfg.SOLVER.MAX_ITER = 100    # 300 iterations seems good enough, but you can certainly train longer
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 67  # 66 classes and background
    cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES = 67


    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg) 
    trainer.resume_or_load(resume=False)
    trainer.train()
```
And for inference :
```
def infere():
    cfg = get_cfg()
    cfg.merge_from_file("./configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_1x.yaml")
    cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
    cfg.DATASETS.TEST = ("mapillary-panoptic-validation_separated", )
    cfg.freeze()
    predictor = DefaultPredictor(cfg)
    root_dir = '/media/AjetoNetworking/tmp/isagastiberri/prueba/imgs'
    mapillary_metadata = MetadataCatalog.get("mapillary-panoptic-training_separated")
    for root, _, files in os.walk(root_dir):
        for img_name in files:
            # im = cv2.imread(os.path.join(root_dir, img_name))
            im = read_image(os.path.join(root_dir, img_name), format="BGR")
            outputs = predictor(im)
            v = Visualizer(im[:, :, ::-1],
                        metadata=mapillary_metadata, 
                        scale=0.8, 
                        instance_mode=ColorMode.IMAGE
                )
            panoptic_seg, segments_info = outputs["panoptic_seg"]
            v = v.draw_panoptic_seg_predictions(
                    panoptic_seg.to('cpu'), segments_info
                )
            cv2_imshow(v.get_image()[:, :, ::-1])

```

And thanks for the patience!

**Comment by isagastiberri** [comment]
Hi @ppwwyyxx I was reading through the documentation and saw that metadata is like a global variable, so it's only there during execution. So I think I understand what you meant, I'll just create the metadata and load it during inference too. But I still have the problem of **register_coco_panoptic** function not creating **stuff_classes** and **stuff_dataset_id_to_contiguous_id**. Shouldn't the function create these variables for both, things and stuff?

**Comment by ppwwyyxx** [comment]
Maybe it is possible to parse the names from the json file automatically, but now it requires you to specify the class names in the metadata you provided to `register_coco_panoptic_separated`. Their meaning are defined in https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets

**Comment by isagastiberri** [comment]
Thanks! I did that but now I have another error.
```
Exception has occurred: IndexError
list index out of range
  File "/workspace/detectron2/detectron2/utils/visualizer.py", line 435, in draw_panoptic_seg_predictions
    text = self.metadata.stuff_classes[category_idx]
  File "/workspace/detectron2/tools/inference.py", line 38, in infere
    panoptic_seg.to('cpu'), segments_info
  File "/workspace/detectron2/tools/train_infere.py", line 6, in <module>
    infere()
´´´

I'm directly loading the stuff classes as they appear in the json

**Comment by isagastiberri** [comment]
@ppwwyyxx okay, thanks! I have loaded the stuff-classes as they appear in the json and I now get this other error
 
```
Traceback (most recent call last):
  File "tools/train_infere.py", line 6, in <module>
    infere()
  File "/workspace/detectron2/tools/inference.py", line 38, in infere
    panoptic_seg.to('cpu'), segments_info
  File "/workspace/detectron2/detectron2/utils/visualizer.py", line 435, in draw_panoptic_seg_predictions
    text = self.metadata.stuff_classes[category_idx]
IndexError: list index out of range
```
I tried creating stuff_dataset_id_to_contiguous_id by making a dictionary where the key is the class id and the value is its position in the stuff_classes and another time with key and value swapped but with both I still got this same error

**Comment by ppwwyyxx** [comment]
That means the model is predicting more classes than what you provided in the metadata.

**Comment by isagastiberri** [comment]
Okay, I'll look into it. Thanks a lot for your help!

**Comment by zishanahmed08** [comment]
@isagastiberri Sorry for highjacking your thread. Is your implementation of mapillary vistas dataset wroking and is it available for others?
