### ISSUE TITLE
Train semantic segmentation using custom dataset

### ISSUE THREAD

**Issue by rihab13** [facebookresearch/detectron2#3277]
Hi,

I'm trying to train a semantic segmentation using Deeplabv3 , i annotated my dataset using VGG annotator , i registred the new dataset as below

```
 listname=  ["dataset_train", "dataset_val"]
    for d in listname:
      DatasetCatalog.register(  d, lambda d=d: get_class_dicts("/content/dataset/" + d,"/content/dataset/dataset_train/via_project_12Jul2021_22h25m_json.json"))
      MetadataCatalog.get(d).set(stuff_classes=['bg', 'sol', 'ciel','tronc','feuilles','soleil'], evaluator_type="sem_seg",) 
    print(MetadataCatalog.get("dataset_train"))

```

the get_class_dicts :  

```
def get_class_dicts(img_dir,json_file):
    with open(json_file) as f:
        imgs_anns = json.load(f)

    dataset_dicts = []
    for _, v in imgs_anns.items():
        record = {}
        
        filename = os.path.join(img_dir, v["filename"])
       
        height, width = cv2.imread(filename).shape[:2]
        
        record["file_name"] = filename
        record["height"] = height
        record["width"] = width
      
        annos = v["regions"]
        objs = []
        

        
        for  annot in annos:
            #print (anno["shape_attributes"])
            #assert not anno["shape_attributes"]
            
            anno = annot["shape_attributes"]
            print(anno)
            px = anno["all_points_x"]
            py = anno["all_points_y"]
            cl = annot["region_attributes"]["classe"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = list(itertools.chain.from_iterable(poly))

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": get_class_id(cl),
                "sem_seg_file_name" : filename,
                "iscrowd": 0
            }
            #print(cl+" :  " +str(get_class_id(cl)))
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts
```

please can anyone help me , thank you

 but i get this error ERROR [07/24 12:14:23 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/modeling/meta_arch/semantic_seg.py", line 108, in forward
    results, losses = self.sem_seg_head(features, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/projects/deeplab/semantic_seg.py", line 230, in forward
    return None, self.losses(y, targets)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/projects/deeplab/semantic_seg.py", line 258, in losses
    loss = self.loss(predictions, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/projects/deeplab/loss.py", line 30, in forward
    pixel_losses = self.criterion(logits, labels).contiguous().view(-1)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 1048, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2690, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2380, in nll_loss
    if input.size(0) != target.size(0):
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by ppwwyyxx** [comment]
Please follow the format documented in docs: https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#standard-dataset-dicts

According to the doc, "annotations" is not used for semantic segmentation at all, and "sem_seg_file_name" is not inside "annotations"
