### ISSUE TITLE
got error in exif__transpose

### ISSUE THREAD

**Issue by johnlanbor** [facebookresearch/detectron2#328]
It seems that error is because exif_transpose

`Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    args=(args,),
  File "/node01/jobs/mlt2017/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/node01/jobs/mlt2017/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/node01/jobs/mlt2017/tools/train.py", line 196, in main
    return trainer.train()
  File "/node01/jobs/mlt2017/detectron2/engine/defaults.py", line 354, in train
    super().train(self.start_iter, self.max_iter)
  File "/node01/jobs/mlt2017/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/node01/jobs/mlt2017/detectron2/engine/train_loop.py", line 206, in run_step
    data = next(self._data_loader_iter)
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/node01/jobs//mlt2017/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/node01/jobs//mlt2017/detectron2/data/dataset_mapper.py", line 74, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/node01/jobs/mlt2017/detectron2/data/detection_utils.py", line 53, in read_image
    image = ImageOps.exif_transpose(image)
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/PIL/ImageOps.py", line 545, in exif_transpose
    transposed_image.info["exif"] = exif.tobytes()
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/PIL/Image.py", line 3213, in tobytes
    return b"Exif\x00\x00" + head + ifd.tobytes(offset)
  File "/node01/jobs/io/env/detection_env/anaconda3_detectron/envs/torch1.3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 824, in tobytes
    data = self._write_dispatch[typ](self, *values)
TypeError: write_undefined() takes 2 positional arguments but 5 were given`

**Comment by ppwwyyxx** [comment]
This should be a bug in Pillow. Could you share the image file?
