### ISSUE TITLE
 Deployment script export_model.py does not recognize the datasets registered earlier while creating the config() object.

### ISSUE THREAD

**Issue by avadhutbhosarekar** [facebookresearch/detectron2#3301]
## Instructions To Reproduce the Issue:

The Training, Inference and Evaluation Cell Blocks are working as expected for a dataset in the coco format  but during deployment the **export_model.py script** (provided in detectron 2 ) does not recognize the datasets that I have registered in the earlier cell blocks and gives the following exception.  How do i register the datasets that I trained the models on so the deployment script recognizes them.
````
!python /content/detectron2/tools/deploy/export_model.py  --config-file /content/video_analytics/model_artifacts_trained/model_config_trained.yml \
    --output /content/video_analytics/deployment_files --export-method scripting --format torchscript \
    MODEL.WEIGHTS /content/video_analytics/model_artifacts_trained/model_final.pth \
    MODEL.DEVICE cuda 
````

````
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py", line 51, in get
            f = self[name]
          File "/usr/lib/python3.7/collections/__init__.py", line 1027, in __getitem__
            raise KeyError(key)
        KeyError: 'dataset_val'
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/content/detectron2/tools/deploy/export_model.py", line 219, in <module>
            sample_inputs = get_sample_inputs(args)
          File "/content/detectron2/tools/deploy/export_model.py", line 159, in get_sample_inputs
            data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
          File "/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py", line 192, in wrapped
            explicit_args = _get_args_from_config(from_config, *args, **kwargs)
          File "/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py", line 229, in _get_args_from_config
            ret = from_config_func(*args, **kwargs)
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 410, in _test_loader_from_config
            else None,
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 227, in get_detection_dataset_dicts
            dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 227, in <listcomp>
            dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
          File "/usr/local/lib/python3.7/dist-packages/detectron2/data/catalog.py", line 57, in get
            ) from e
        KeyError: "Dataset 'dataset_val' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"
````
I have provided the google colab notebook that reproduces this error: 
https://colab.research.google.com/drive/1NzcARQKYV4rFdly4nAo6sm2y9tZSb_h4?usp=sharing

**Comment by ppwwyyxx** [comment]
Code in cell and code in a script run by `!python` do not affect each other. This is working as expected and it's how python notebook works.
