### ISSUE TITLE
export_model.py deployment script throws out an exception 

### ISSUE THREAD

**Issue by avadhutbhosarekar** [facebookresearch/detectron2#3302]
I have trained a detectron2 [**"COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"**] model and while executing the deployment script **export_model.py**  (provided in detectron2 ) it throws an exception given below.
````
!python /content/detectron2/tools/deploy/export_model.py  --config-file /content/video_analytics/model_artifacts_trained/model_config_trained.yml \
    --output /content/video_analytics/deployment_files --export-method scripting --format torchscript --sample-image /content/video_analytics/datasets/fish_ds/test/IMG_2289_jpeg_jpg.rf.fe2a7a149e7b11f2313f5a7b30386e85.jpg \
    MODEL.WEIGHTS /content/video_analytics/model_artifacts_trained/model_final.pth \
    MODEL.DEVICE cuda 
````
````
Traceback (most recent call last):
  File "/content/detectron2/tools/deploy/export_model.py", line 225, in <module>
    exported_model = export_scripting(torch_model)
  File "/content/detectron2/tools/deploy/export_model.py", line 99, in export_scripting
    ts_model = scripting_with_instances(ScriptableAdapter(), fields)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/export/torchscript.py", line 57, in scripting_with_instances
    scripted_model = torch.jit.script(model)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 943, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 391, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 391, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 428, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 448, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 391, in _construct
    init_fn(script_module)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 428, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 452, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py", line 335, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Tried to access nonexistent attribute or method 'proposal_boxes' of type 'Tensor'.:
  File "/usr/local/lib/python3.7/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 470
        del targets
    
        proposal_boxes = [x.proposal_boxes for x in proposals]
                          ~~~~~~~~~~~~~~~~ <--- HERE
        box_features = self._shared_roi_transform(
            [features[f] for f in self.in_features], proposal_boxes
````
## Instructions To Reproduce the Issue:
I have attached the colab notebook  that reproduces this error.
https://colab.research.google.com/drive/1NzcARQKYV4rFdly4nAo6sm2y9tZSb_h4?usp=sharing 

Please let me know the step I can take to resolve the issue.

**Comment by ppwwyyxx** [comment]
We did not support C4 models, but only FPN models in the past. However the support is easy and will be added in #3318.
