### ISSUE TITLE
Transfer-Learning: Loading Weights from self-trained .pth file and Change Number of Classes 

### ISSUE THREAD

**Issue by YradenRavid** [facebookresearch/detectron2#332]
## ❓ Questions and Help

General questions about detectron2.

Hey!

I trained RetinaNet with detectron2, with NUM_CLASSES = 15
Now I want to resume to train on the last checkpoint, only with one class, NUM_CLASSES = 1

I configure the follow in tools/train_net.py:
cfg.MODEL.WEIGHTS = "output/yarden_test/model_0000009.pth"
cfg.MODEL.RETINANET.NUM_CLASSES = 1

The Architecture output is:
(cls_score): Conv2d(256, 9, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
(bbox_pred): Conv2d(256, 36, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

I get Those WARNINGS:
WARNING [11/17 15:05:17 fvcore.common.checkpoint]: 'head.cls_score.weight' has shape (117, 256, 3, 3) in the checkpoint but (9, 256, 3, 3) in the model! Skipped.
WARNING [11/17 15:05:17 fvcore.common.checkpoint]: 'head.cls_score.bias' has shape (117,) in the checkpoint but (9,) in the model! Skipped.
[11/17 15:05:17 fvcore.common.checkpoint]: Some model parameters are not in the checkpoint:
  head.cls_score.{weight, bias}

and the following error:
Traceback (most recent call last):
  File "tools/train_net.py", line 200, in <module>
    args=(args,),
  File "/home/ubuntu/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 188, in main
    return trainer.train()
  File "/home/ubuntu/detectron2/detectron2/engine/defaults.py", line 350, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/ubuntu/detectron2/detectron2/engine/train_loop.py", line 231, in run_step
    self.optimizer.step()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 51, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/optim/sgd.py", line 100, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The size of tensor a (117) must match the size of tensor b (9) at non-singleton dimension 0

What am I missing??

Thanks!

**Comment by ppwwyyxx** [comment]
The error is because the checkpoint you're loading contains the optimizer state that cannot be loaded, due to change in number of classes.
You can modify the checkpoint with `torch.load` and `torch.save`.
