### ISSUE TITLE
Custom Trainer throws error while training Point Rend Model

### ISSUE THREAD

**Issue by Jain-Archit** [facebookresearch/detectron2#3329]
Hi,
Wanted to ask whether point-rend is currently supported only for default trainer? I wrote a custom trainer for custom transformation of input data which trains perfectly fine in detectron2. However, when I try to train point-rend with the custom trainer (extended default trainer), it throws an error regarding input polygon mask (even though it was set to bitmask in cfg file). Point-rend model trains perfectly fine with the same code when using the default trainer. Does point-rend support custom trainers? if yes, what am I doing wrong?

**Code for Custom Trainer**

```
class customTrainer(DefaultTrainer):
    @classmethod
    def build_test_loader(cls, cfg, dataset_name):
        return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapper(cfg, False))

    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=custom_datasetMapper)

cfg = get_cfg()
```

**Code for Cfg File**

```
point_rend.add_pointrend_config(cfg)

cfg.INPUT.MAX_SIZE_TRAIN = 1440,
cfg.INPUT.MIN_SIZE_TRAIN = (800,),
cfg.INPUT.MASK_FORMAT= 'bitmask'
cfg.merge_from_file("detectron2_repo/projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml")
cfg.DATASETS.TRAIN = ("cpd_final",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = "detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_edd263.pkl"

cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(cpd_metadata.thing_classes)
cfg.MODEL.POINT_HEAD.NUM_CLASSES = len(cpd_metadata.thing_classes)
cfg.OUTPUT_DIR = './cpd'


cfg.SOLVER.MAX_ITER = 4000
cfg.SOLVER.STEPS = (2000,)
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.0025
cfg.SOLVER.WARMUP_ITERS = 500

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
```

**Code for Custom Training which throws error**

```
trainer = customTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Code for Training which works fine** 

```
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Error which is thrown when using custom trainer**

```
ERROR [07/23 09:18:31 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 163, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 735, in forward
    losses.update(self._forward_mask(features, proposals))
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 838, in _forward_mask
    return self.mask_head(features, instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/mask_head.py", line 233, in forward
    point_coords, point_labels = self._sample_train_points(coarse_mask, instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/mask_head.py", line 285, in _sample_train_points
    point_labels = sample_point_labels(instances, point_coords_wrt_image)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/point_features.py", line 251, in sample_point_labels
    assert isinstance(
AssertionError: Point head works with GT in 'bitmask' format. Set INPUT.MASK_FORMAT to 'bitmask'.
```

**Comment by Jain-Archit** [comment]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue:

  1. Create a custom trainer (other than the default trainer by extending the default trainer class. For Eg: adding custom augmentations).
  2. Set the config params for training of point-rend model and set cfg.INPUT.MASK_FORMAT= 'bitmask'
  3. Training the point-rend model with custom trainer created in step1 throws an error about input masks not being in 'bitmask' format. 

1. Full runnable code or full changes you made:
**Code for Custom Trainer**

```
class customTrainer(DefaultTrainer):
    @classmethod
    def build_test_loader(cls, cfg, dataset_name):
        return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapper(cfg, False))

    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=custom_datasetMapper)

cfg = get_cfg()
```

**Code for Cfg File**


```
point_rend.add_pointrend_config(cfg)

cfg.INPUT.MAX_SIZE_TRAIN = 1440,
cfg.INPUT.MIN_SIZE_TRAIN = (800,),
cfg.INPUT.MASK_FORMAT= 'bitmask'
cfg.merge_from_file("detectron2_repo/projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml")
cfg.DATASETS.TRAIN = ("cpd_final",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 4
cfg.MODEL.WEIGHTS = "detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_edd263.pkl"

cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(cpd_metadata.thing_classes)
cfg.MODEL.POINT_HEAD.NUM_CLASSES = len(cpd_metadata.thing_classes)
cfg.OUTPUT_DIR = './cpd'


cfg.SOLVER.MAX_ITER = 4000
cfg.SOLVER.STEPS = (2000,)
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.0025
cfg.SOLVER.WARMUP_ITERS = 500

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
```

**Code for Custom Training which throws error**

```
trainer = customTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

**Code for Training which works fine** 

```
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```
2. What exact command you run:
Error is thrown when trainer.train() is run.

3. __Full logs__ or other relevant observations:
**Error which is thrown when using custom trainer**

```
ERROR [07/23 09:18:31 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 163, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 735, in forward
    losses.update(self._forward_mask(features, proposals))
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 838, in _forward_mask
    return self.mask_head(features, instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/mask_head.py", line 233, in forward
    point_coords, point_labels = self._sample_train_points(coarse_mask, instances)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/mask_head.py", line 285, in _sample_train_points
    point_labels = sample_point_labels(instances, point_coords_wrt_image)
  File "/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/detectron2/projects/point_rend/point_features.py", line 251, in sample_point_labels
    assert isinstance(
AssertionError: Point head works with GT in 'bitmask' format. Set INPUT.MASK_FORMAT to 'bitmask'.
```


## Expected behavior:

Point-Rend model should be trained with custom-trainers( which are extended from detectron2's default trainers). 

## Environment:

Paste the output of the following command:
```
wget: /opt/tljh/user/lib/libuuid.so.1: no version information available (required by wget)
2021-08-10 09:59:19 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/master/detectron2/utils/collect_env.py [7468/7468] -> "collect_env.py" [1]
----------------------  ---------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numpy                   1.21.0
detectron2              0.5 @/home/jupyter-archit/.local/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 11.0
detectron2 arch flags   /home/jupyter-archit/.local/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1 @/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA Tesla T4 (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  8.3.0
torchvision             0.8.2 @/opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torchvision
torchvision arch flags  /opt/tljh/user/envs/pytorch/lib/python3.8/site-packages/torchvision/_C.so; cannot find cuobjdump
fvcore                  0.1.5.post20210624
iopath                  0.1.8
cv2                     4.5.2
----------------------  ---------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```
