### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Keiku** [facebookresearch/detectron2#3338]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

I'm trying Maskformer, but this seems to be a bug in detectron2. For the detectron2 build, I use the Dockerfile included in detectron2-0.4.zip.

2. What exact command you run:

After preparing the dataset in the Maskformer repository, I did the following:

```
python train_net.py \
  --config-file configs/ade20k-150/maskformer_R50_bs16_160k.yaml \
  --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0001
```

3. __Full logs__ or other relevant observations:

```
[08/09 07:54:59 d2.engine.train_loop]: Starting training from iteration 0
ERROR [08/09 07:54:59 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/detectron2_repo/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/detectron2_repo/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/detectron2_repo/detectron2/engine/train_loop.py", line 232, in run_step
    loss_dict = self.model(data)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Study-MaskFormer/mask_former/mask_former_model.py", line 180, in forward
    losses = self.criterion(outputs, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/criterion.py", line 162, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 163, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 123, in memory_efficient_forward
    cost_mask = batch_sigmoid_focal_loss(out_mask, tgt_mask)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 49, in batch_sigmoid_focal_loss
    focal_pos = ((1 - prob) ** gamma) * F.binary_cross_entropy_with_logits(
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/tensor.py", line 528, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered
[08/09 07:54:59 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[08/09 07:54:59 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 1008M
Traceback (most recent call last):
  File "train_net.py", line 264, in <module>
    launch(
  File "/detectron2_repo/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net.py", line 258, in main
    return trainer.train()
  File "/detectron2_repo/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/detectron2_repo/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/detectron2_repo/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/detectron2_repo/detectron2/engine/train_loop.py", line 232, in run_step
    loss_dict = self.model(data)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Study-MaskFormer/mask_former/mask_former_model.py", line 180, in forward
    losses = self.criterion(outputs, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/criterion.py", line 162, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 163, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 123, in memory_efficient_forward
    cost_mask = batch_sigmoid_focal_loss(out_mask, tgt_mask)
  File "/Study-MaskFormer/mask_former/modeling/matcher.py", line 49, in batch_sigmoid_focal_loss
    focal_pos = ((1 - prob) ** gamma) * F.binary_cross_entropy_with_logits(
  File "/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/tensor.py", line 528, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
docker@f4e418788992:/Study-MaskFormer$
```

4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

I follow the instructions in the Maskformer documentation. I downloaded ADEChallengeData2016 and prepared the annotation dataset.

## Expected behavior:

I do not know. I've never been successful.

## Environment:

I follow the instructions in the detectron2 and Maskformer documentation. I use the Dockerfile included in detectron2-0.4.zip.

**Comment by ppwwyyxx** [comment]
I don't think it's related to detectron2
