### ISSUE TITLE
 Caught IndexError in DataLoader worker process 0 and IndexError: index 7 is out of bounds for axis 0 with size 6

### ISSUE THREAD

**Issue by hemanth-mudusu** [facebookresearch/detectron2#3341]
I don't Think my dataset is wrong .Successfully registered coco format with detectron2 .but I got error while training the model.

from detectron2.data import MetadataCatalog

keypoint_names = ['ulx', 'uly', 'utlx', 'utly', 'utrx', 'utry', 'urx', 'ury', 'brx', 'bry','blx','bly']
keypoint_flip_map = [('ulx', 'uly'), ('utlx', 'utly'), ('utrx', 'utry'), ('urx', 'ury'), ('brx', 'bry'),('blx','bly')]

MetadataCatalog.get('tower_scape').keypoint_names = keypoint_names
MetadataCatalog.get('tower_scape').keypoint_flip_map = keypoint_flip_map

from detectron2.data import MetadataCatalog
MetadataCatalog.get("tower_scape").thing_classes = ["big_rectangle"]

from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("tower_scape",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.SOLVER.STEPS = []        # do not decay learning rate
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
#cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 6

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

## Expected behavior:

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
ERROR [08/09 04:48:04 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 497, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 267, in run_step
    data = next(self._data_loader_iter)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/common.py", line 179, in __iter__
    for d in self.dataset:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 172, in __call__
    for obj in dataset_dict.pop("annotations")
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 173, in <listcomp>
    if obj.get("iscrowd", 0) == 0
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 314, in transform_instance_annotations
    annotation["keypoints"], transforms, image_size, keypoint_hflip_indices
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 356, in transform_keypoint_annotations
    keypoints = keypoints[np.asarray(keypoint_hflip_indices, dtype=np.int32), :]
IndexError: index 7 is out of bounds for axis 0 with size 6

[08/09 04:48:04 d2.engine.hooks]: Total training time: 0:00:02 (0:00:00 on hooks)
[08/09 04:48:04 d2.utils.events]:  iter: 1  total_loss: 9.366  loss_cls: 0.1716  loss_box_reg: 0.0182  loss_keypoint: 8.629  loss_rpn_cls: 0.4768  loss_rpn_loc: 0.07013  data_time: 3.0182  lr: 2.5e-07  max_mem: 1622M
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-418aa2f95971> in <module>()
     18 trainer = DefaultTrainer(cfg)
     19 trainer.resume_or_load(resume=False)
---> 20 trainer.train()

8 frames
/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    423             # have message field
    424             raise self.exc_type(message=msg)
--> 425         raise self.exc_type(msg)
    426 
    427 

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 172, in __call__
    for obj in dataset_dict.pop("annotations")
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 173, in <listcomp>
    if obj.get("iscrowd", 0) == 0
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 314, in transform_instance_annotations
    annotation["keypoints"], transforms, image_size, keypoint_hflip_indices
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 356, in transform_keypoint_annotations
    keypoints = keypoints[np.asarray(keypoint_hflip_indices, dtype=np.int32), :]
IndexError: index 7 is out of bounds for axis 0 with size 6

**Comment by ppwwyyxx** [comment]
You provide 12 keypoints:

> keypoint_names = ['ulx', 'uly', 'utlx', 'utly', 'utrx', 'utry', 'urx', 'ury', 'brx', 'bry','blx','bly']

but says there are 6 keypoints:

> > #cfg.MODEL.ROI_KEYPOINT_HEAD.NUM_KEYPOINTS = 6

They should be the same.

**Comment by hemanth-mudusu** [comment]
Thanks it's Working Now
