### ISSUE TITLE
Resume flag starts training at iteration 1, and results in error when iteration ticks past previous MAX_ITER value

### ISSUE THREAD

**Issue by jjbuck** [facebookresearch/detectron2#3381]
## Instructions To Reproduce the Issue:

I have a model that I'm training with the default `train_net.py` training script that comes in the `tools` directory of Detectron2. After training it for 10,000 iterations, I then wanted to continue training this model for another 10,000 iterations. However, in my attempt to do so, I encountered an error...

1. Full runnable code or full changes you made:
(See question 2 below)

2. What exact command you run:

First, my initial training process (this runs just fine).
```
python ./ml/train_net.py \
    --num-gpus 1 \
    --config ./configs/faster_rcnn_R_50_FPN_1x.yaml \
    MODEL.WEIGHTS ./model_final_b275ba.pkl \
    DATASETS.TRAIN "('train',)" \
    DATASETS.TEST "('val',)" \
    SOLVER.MAX_ITER 10000 \
    TEST.EVAL_PERIOD 1000 \
    SOLVER.IMS_PER_BATCH 8 \
    MODEL.ROI_HEADS.NUM_CLASSES 1 \
    OUTPUT_DIR ./output/<my-output-directory>
```

Then, I try to run it again and resume training from where the first one left off.

```
python ./ml/train_net.py \
    --num-gpus 8 \
    --config ./configs/faster_rcnn_R_50_FPN_1x.yaml \
    --resume \
    DATASETS.TRAIN "('train',)" \
    DATASETS.TEST "('val',)" \
    SOLVER.MAX_ITER 20000 \
    TEST.EVAL_PERIOD 1000 \
    SOLVER.IMS_PER_BATCH 64 \
    MODEL.ROI_HEADS.NUM_CLASSES 1 \
    OUTPUT_DIR ./output/<my-output-directory>
```

3. __Full logs__ or other relevant observations:

The logs below are from my _second_ training job (the first ran successfully as mentioned above).
```
[08/18 18:13:52 d2.utils.events]:  eta: 5:54:22  iter: 19  total_loss: 0.1037  loss_cls: 0.02499  loss_box_reg: 0.06347  loss_rpn_cls: 0.001731  loss_rpn_loc: 0.01186  time: 0.7111  data_time: 0.
3843  lr: 0.02  max_mem: 7880M    
....
<steps 19-10,000 omitted for brevity>
[08/18 20:48:35 d2.utils.events]:  eta: 3:58:00  iter: 10002  total_loss: 0.09763  loss_cls: 0.02382  loss_box_reg: 0.0623  loss_rpn_cls: 0.001507  loss_rpn_loc: 0.01042  validation_loss: 0.1928  time: 0.7152  data_time: 0.0215  lr: 0.02  max_mem: 7880M
Traceback (most recent call last):
  File "./ml/train-fully-supervised.py", line 257, in <module>
    launch(
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 125, in _distributed_worker
    main_func(*args)
  File "/mnt/efs/fs1/ml/train-fully-supervised.py", line 251, in main
    return trainer.train()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 487, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 256, in after_step
    self.scheduler.step()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 152, in step
    values = self.get_lr()
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/solver/lr_scheduler.py", line 115, in get_lr
    multiplier = self._multiplier(self.last_epoch / self._max_iter)
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/fvcore/common/param_scheduler.py", line 423, in __call__
    return scheduler(scheduler_where)
  File "/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/fvcore/common/param_scheduler.py", line 236, in __call__
    raise RuntimeError(
RuntimeError: where in ParamScheduler must be in [0, 1]: got 1.0000333333333333
 
```

## Expected behavior:
My expectation is two-fold. First, that the second training job should start from iteration 10,001. Second, that even if the second training job starts from iteration 0, that it should not fail when it gets to iteration 10,001.

## Environment:

Paste the output of the following command:
```
----------------------  --------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) [GCC 9.3.0]
numpy                   1.21.2
detectron2              0.5 @/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.2
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu102 @/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-16GB (arch=7.0)
CUDA_HOME               /usr/local/cuda
Pillow                  8.3.1
torchvision             0.10.0+cu102 @/home/ubuntu/anaconda3/envs/detectron2/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20210812
iopath                  0.1.8
cv2                     4.5.3
----------------------  --------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

```

If your issue looks like an installation issue / environment issue,
please first check common issues in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
I can't reproduce this with the official `train_net.py`:
```
python3 tools/train_net.py --config-file configs/quick_schedules/mask_rcnn_R_50_FPN_instant_test.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.MAX_ITER 50 
python3 tools/train_net.py --config-file configs/quick_schedules/mask_rcnn_R_50_FPN_instant_test.yaml --resume SOLVER.IMS_PER_BATCH 2 SOLVER.MAX_ITER 100 
```

Running the above commands, the second training starts from iteration 50 and can correctly finishes. If you'd like help please provide a way to reproduce the issue.

**Comment by JJC6050** [comment]
Have you solved this problem now? How did you solve it?
Traceback (most recent call last):
File "tools/train_net.py", line 226, in
launch(
File "f:\cocoapi\detectron2-0.4\detectron2\engine\launch.py", line 62, in launch
main_func(*args)
File "tools/train_net.py", line 214, in main
trainer = Trainer(cfg)
File "f:\cocoapi\detectron2-0.4\detectron2\engine\defaults.py", line 323, in init
self.scheduler = self.build_lr_scheduler(cfg, optimizer)
File "f:\cocoapi\detectron2-0.4\detectron2\engine\defaults.py", line 474, in build_lr_scheduler
return build_lr_scheduler(cfg, optimizer)
File "f:\cocoapi\detectron2-0.4\detectron2\solver\build.py", line 246, in build_lr_scheduler
sched = WarmupParamScheduler(
File "f:\cocoapi\detectron2-0.4\detectron2\solver\lr_scheduler.py", line 37, in init
end_value = scheduler(warmup_length) # the value to reach when warmup ends
File "E:\Anaconda\envs\detectron2\lib\site-packages\fvcore\common\param_scheduler.py", line 236, in call
raise RuntimeError(
RuntimeError: where in ParamScheduler must be in [0, 1]: got 5.0

**Comment by cmj18** [comment]
How to solve it?
