### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by xiaofeng-c** [facebookresearch/detectron2#3420]
Thanks for you work,when i run the demo.py with the command of **" python demo/demo.py --input ./inference/10.jpg --output inference_result/"**,a problem occur as follow:
 0%|                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/demo.py", line 112, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/bobo/F/zwm/XiaoFeng/detectron2-master/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/bobo/cocoapi/PythonAPI/detectron2/detectron2/engine/defaults.py", line 316, in __call__
    predictions = self.model([inputs])[0]
  File "/home/bobo/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bobo/cocoapi/PythonAPI/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 146, in forward
    return self.inference(batched_inputs)
  File "/home/bobo/cocoapi/PythonAPI/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 206, in inference
    assert "proposals" in batched_inputs[0]
AssertionError
do you know how to solve it?

**Comment by ppwwyyxx** [comment]
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).
