### ISSUE TITLE
Unexpected Results

### ISSUE THREAD

**Issue by NickChang97** [facebookresearch/detectron2#3452]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue: ./train_net.py --num-gpus 4 --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. Full runnable code or full changes you made:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
I don't change anything about the code, I just want to start according to the  "https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html#inference-demo-with-pre-trained-models"
```
2. What exact command you run: ./train_net.py --num-gpus 4 --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml
3. __Full logs__ or other relevant observations:
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/data2/qing_chang/detectron2/tools/train_net.py", line 157, in main
    return trainer.train()
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 232, in run_step
    loss_dict = self.model(data)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 160, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 430, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 300, in label_and_sample_anchors
    match_quality_matrix = retry_if_cuda_oom(pairwise_iou)(gt_boxes_i, anchors)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/structures/boxes.py", line 360, in pairwise_iou
    inter = pairwise_intersection(boxes1, boxes2)
  File "/home/changqing/env_mmlab/lib/python3.6/site-packages/detectron2/structures/boxes.py", line 335, in pairwise_intersection
    width_height = torch.min(boxes1[:, None, 2:], boxes2[:, 2:]) - torch.max(
RuntimeError: CUDA error: device-side assert triggered

```

## Expected behavior:

If there are no obvious crash in "full logs" provided above,
please tell us the expected behavior.

If you expect a model to converge / work better, we do not help with such issues, unless
a model fails to reproduce the results in detectron2 model zoo, or proves existence of bugs.

## Environment:

Paste the output of the following command:
```
wget -nc -nv https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py.  I got 404 not Found with this command. The information "detectron2 Version: 0.4+cu111  & pytorch  1.8.1+cu111" in my envirionment.
```

If your issue looks like an installation issue / environment issue,
please first check common issues in https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by NickChang97** [comment]
The error is met when I use the machine with GPU 3090. When I changed to another machine with titan V, all things go well.

**Comment by NickChang97** [comment]
I changed the torch to 1.9.0 with GPU 3090. The code runs works fine
