### ISSUE TITLE
KeyError: 'image_id' on inferencing step

### ISSUE THREAD

**Issue by EtagiBI** [facebookresearch/detectron2#3521]
I'm trying to use Retinanet_R_50_FPN_3x for my object detection task. 
The training process starts fine, but then breaks pointing to a `KeyError: 'image_id'`.
I assume there could be a problem with my preprocessing function `get_board_dicts`.
I was surprised by the fact that Detectron2 rearranges the standard COCO structure into its own, so there could be some convertion isues.

## Instructions To Reproduce the Issue:
Here's my code:
```
import numpy as np
import os, json, cv2, random
import matplotlib.pyplot as plt

from detectron2.utils.logger import setup_logger
setup_logger()

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.structures import BoxMode
from detectron2.engine import DefaultTrainer
from detectron2.evaluation import COCOEvaluator


class CocoTrainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            os.makedirs("coco_eval", exist_ok=True)
            output_folder = "coco_eval"
        return COCOEvaluator(dataset_name, cfg, False, output_folder)


def get_board_dicts(path_to_images_dir, path_to_COCO_dir, COCO_file):
    json_file = path_to_COCO_dir + COCO_file #Fetch the json file
    with open(json_file) as f:
        dataset_dicts = json.load(f)
        annos = dataset_dicts["annotations"]
        for i in dataset_dicts["images"]:
            filename = i["file_name"]
            i["file_name"] = path_to_images_dir + filename
            j = list(filter(lambda anno: anno['image_id'] == i['id'], annos))
            for a in j:
                a["category_id"] = 0
                a["bbox_mode"] = BoxMode.XYWH_ABS
            i["annotations"] = j
    new_dicts = dataset_dicts["images"]
    return new_dicts

#Registering the Dataset
mapper = {"train": {"images_dir": "E:/Detectium/ready_images/templates/1_train/", "COCO_dir": "E:/Detectium/COCO/1_train/", "COCO_file": "1_train_COCO.json"},
         "valid": {"images_dir": "E:/Detectium/ready_images/templates/2_valid/", "COCO_dir": "E:/Detectium/COCO/2_valid/", "COCO_file": "2_valid_COCO.json"}}
for d in ["train", "valid"]:
    images_path = mapper[d]["images_dir"]
    COCO_path = mapper[d]["COCO_dir"]
    COCO_file = mapper[d]["COCO_file"]
    DatasetCatalog.register("boardetect_" + d, lambda d=d: get_board_dicts(images_path, COCO_path, COCO_file))
    MetadataCatalog.get("boardetect_" + d).set(thing_classes=["FLOWER"])
board_metadata = MetadataCatalog.get("boardetect_train")

if __name__ == '__main__':
    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/retinanet_R_50_FPN_3x.yaml")) #Get the basic model configuration from the model zoo
    #Passing the Train and Validation sets
    cfg.DATASETS.TRAIN = ("boardetect_train",)
    cfg.DATASETS.TEST = ("boardetect_valid",)

    # Number of data loading threads
    cfg.DATALOADER.NUM_WORKERS = 1
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/retinanet_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
    # Number of images per batch across all machines.
    cfg.SOLVER.IMS_PER_BATCH = 4
    cfg.SOLVER.BASE_LR = 0.00005 #0.0125  
    cfg.SOLVER.MAX_ITER = 1500  #No. of iterations
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1 # No. of classes
    cfg.TEST.EVAL_PERIOD = 500 # No. of iterations after which the Validation Set is evaluated.
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = CocoTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
```

Here's my log:
```
[09/24 18:17:24 d2.data.build]: Removed 0 images with no usable annotations. 840 images left.
[09/24 18:17:24 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
| FLOWER  | 864          |
|            |              |
[09/24 18:17:24 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[09/24 18:17:24 d2.data.build]: Using training sampler TrainingSampler
[09/24 18:17:24 d2.data.common]: Serializing 840 elements to byte tensors and concatenating them all ...
[09/24 18:17:24 d2.data.common]: Serialized dataset takes 0.25 MiB
WARNING [09/24 18:17:24 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
model_final_5bd44e.pkl: 152MB [00:48, 3.15MB/s]                           
The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
[09/24 18:18:13 d2.engine.train_loop]: Starting training from iteration 0
[09/24 18:18:38 d2.utils.events]:  eta: 0:29:42  iter: 19  total_loss: 1.703  loss_cls: 1.365  loss_box_reg: 0.3018  time: 1.2047  data_time: 0.1254  lr: 9.9905e-07  max_mem: 5091M
.................. MANY SIMILAR LINES .................. 
[09/24 18:23:36 d2.utils.events]:  eta: 0:11:21  iter: 479  total_loss: 0.1293  loss_cls: 0.03647  loss_box_reg: 0.08468  time: 0.6655  data_time: 0.0487  lr: 2.3976e-05  max_mem: 5092M
[09/24 18:23:49 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[09/24 18:23:49 d2.data.common]: Serializing 840 elements to byte tensors and concatenating them all ...
[09/24 18:23:49 d2.data.common]: Serialized dataset takes 0.25 MiB
WARNING [09/24 18:23:49 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[09/24 18:23:49 d2.evaluation.coco_evaluation]: Trying to convert 'boardetect_valid' to COCO format ...
WARNING [09/24 18:23:49 d2.data.datasets.coco]: Using previously cached COCO format annotations at 'coco_eval\boardetect_valid_coco_format.json'. You need to clear the cache file if your dataset has been modified.
[09/24 18:23:49 d2.evaluation.evaluator]: Start inference on 840 batches
ERROR [09/24 18:23:51 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "c:\users\e-soft\detectron2\detectron2\engine\train_loop.py", line 150, in train
    self.after_step()
  File "c:\users\e-soft\detectron2\detectron2\engine\train_loop.py", line 180, in after_step
    h.after_step()
  File "c:\users\e-soft\detectron2\detectron2\engine\hooks.py", line 550, in after_step
    self._do_eval()
  File "c:\users\e-soft\detectron2\detectron2\engine\hooks.py", line 523, in _do_eval
    results = self._func()
  File "c:\users\e-soft\detectron2\detectron2\engine\defaults.py", line 452, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "c:\users\e-soft\detectron2\detectron2\engine\defaults.py", line 607, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "c:\users\e-soft\detectron2\detectron2\evaluation\evaluator.py", line 164, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "c:\users\e-soft\detectron2\detectron2\evaluation\coco_evaluation.py", line 156, in process
    prediction = {"image_id": input["image_id"]}
KeyError: 'image_id'
[09/24 18:23:51 d2.engine.hooks]: Overall training speed: 497 iterations in 0:05:31 (0.6664 s / it)
[09/24 18:23:51 d2.engine.hooks]: Total training time: 0:05:34 (0:00:02 on hooks)
[09/24 18:23:51 d2.utils.events]:  eta: 0:11:08  iter: 499  total_loss: 0.1258  loss_cls: 0.03001  loss_box_reg: 0.08352  time: 0.6650  data_time: 0.0494  lr: 2.4975e-05  max_mem: 5092M
Traceback (most recent call last):
  File "E:/Detectium/Detectron2.py", line 91, in <module>
    trainer.train()
  File "c:\users\e-soft\detectron2\detectron2\engine\defaults.py", line 483, in train
    super().train(self.start_iter, self.max_iter)
  File "c:\users\e-soft\detectron2\detectron2\engine\train_loop.py", line 150, in train
    self.after_step()
  File "c:\users\e-soft\detectron2\detectron2\engine\train_loop.py", line 180, in after_step
    h.after_step()
  File "c:\users\e-soft\detectron2\detectron2\engine\hooks.py", line 550, in after_step
    self._do_eval()
  File "c:\users\e-soft\detectron2\detectron2\engine\hooks.py", line 523, in _do_eval
    results = self._func()
  File "c:\users\e-soft\detectron2\detectron2\engine\defaults.py", line 452, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "c:\users\e-soft\detectron2\detectron2\engine\defaults.py", line 607, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "c:\users\e-soft\detectron2\detectron2\evaluation\evaluator.py", line 164, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "c:\users\e-soft\detectron2\detectron2\evaluation\coco_evaluation.py", line 156, in process
    prediction = {"image_id": input["image_id"]}
KeyError: 'image_id'
```
I've traced the last call and added `print(input)` before the trouble line. Here's result:
```
{'file_name': 'E:/Detectium/ready_images/templates/2_valid/000000003889.jpg', 'height': 512, 'width': 512, 'id': 3889, 'image': tensor([[[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255]],

        [[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255]],

        [[255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         ...,
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255],
         [255, 255, 255,  ..., 255, 255, 255]]], dtype=torch.uint8)}
```
There's no key named "image_id", but as far as I understand "image_id" is the key for annotations dict, not images dict.
## Expected behavior:

The training process runs fine until completion. 

## Environment:

OS Platform: Windows 10 64-bit
Python version: 3.7
CUDA/cuDNN version: 10.1
GPU model and memory: GTX 1080 Ti

**Comment by EtagiBI** [comment]
The problem was caused by inappropriate input format. 
The correct input format's described here:
https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#standard-dataset-dicts
