### ISSUE TITLE
Sometime evaluation stuck for a long time, any idea?

### ISSUE THREAD

**Issue by lucasjinreal** [facebookresearch/detectron2#3562]
![image](https://user-images.githubusercontent.com/21303438/136642842-784d2341-9b59-4503-983b-45f93aa8187c.png)

It was stuck when evaluation on 8 GPUs 3090.

When I cut it, the traceback was:

```
^CTraceback (most recent call last):
  File "train_tl.py", line 93, in <module>
    args=(args,),
  File "/detectron2/detectron2/engine/launch.py", line 79, in launch
    daemon=False,
  File "/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 101, in join
    timeout=timeout,
  File "/anaconda3/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/naconda3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

```

Is that someting wrong with it?

But I dont' thave this problem on single GPU:

![image](https://user-images.githubusercontent.com/21303438/136645079-9cb050ea-4af5-4a86-95fc-ba18af825421.png)

Is it because of batchsize doesn't divided by 8 GPUs?

detectron2 version is latest master branch just built

**Comment by jinfagang** [comment]
I know why.
