### ISSUE TITLE
RuntimeError of sigmoid_focal_loss_jit when use torch1.10 and amp

### ISSUE THREAD

**Issue by xiaohu2015** [facebookresearch/detectron2#3629]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

2. What exact command you run:
```
python train_net.py --config-file=configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml SOLVER.AMP.ENABLED True
```
3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.9/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/apdcephfs/private_huye/projects/detection/tctdet/train_net.py", line 133, in main
    do_train(args, cfg)
  File "/apdcephfs/private_huye/projects/detection/tctdet/train_net.py", line 117, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/opt/conda/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/opt/conda/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/detectron2/modeling/meta_arch/dense_detector.py", line 101, in forward
    return self.forward_training(images, features, predictions, gt_instances)
  File "/opt/conda/lib/python3.9/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 158, in forward_training
    return self.losses(anchors, pred_logits, gt_labels, pred_anchor_deltas, gt_boxes)
  File "/opt/conda/lib/python3.9/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 189, in losses
    loss_cls = sigmoid_focal_loss_jit(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: default_program(60): error: more than one instance of overloaded function "pow" matches the argument list:
            function "pow(double, double)"
__nv_nvrtc_builtin_header.h(150131): here
            function "pow(float, float)"
__nv_nvrtc_builtin_header.h(150790): here
            function "pow(float, int)"
__nv_nvrtc_builtin_header.h(150797): here
            argument types are: (float, double)

default_program(62): error: more than one instance of overloaded function "pow" matches the argument list:
            function "pow(double, double)"
__nv_nvrtc_builtin_header.h(150131): here
            function "pow(float, float)"
__nv_nvrtc_builtin_header.h(150790): here
            function "pow(float, int)"
__nv_nvrtc_builtin_header.h(150797): here
            argument types are: (float, double)

2 errors detected in the compilation of "default_program".
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
PyTorch: 1.10.0+cu113
detectron2: 0.6
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/fvcore/commit/bfff2ef0e0bd75c7efab27fe584d869eb250e3ae should be able to workaround the issue.
