### ISSUE TITLE
How to use in cuda 8.0 or in conda environment

### ISSUE THREAD

**Issue by Wangweilai1** [facebookresearch/detectron2#373]
Ubuntu 16.04
GTX 1080Ti
CUDA-8.0
Python 3.7.3
gcc7.3
pytorch 1.3.1

when i run python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input ./1.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl

[11/22 20:18:29 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['./1.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
WARNING [11/22 20:18:29 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
File "demo/demo.py", line 73, in 
demo = VisualizationDemo(cfg)
File "/home/root1/Detection/detectron2/demo/predictor.py", line 35, in init
self.predictor = DefaultPredictor(cfg)
File "/home/root1/Detection/detectron2/detectron2/engine/defaults.py", line 149, in init
self.model = build_model(self.cfg)
File "/home/root1/Detection/detectron2/detectron2/modeling/meta_arch/build.py", line 18, in build_model
return META_ARCH_REGISTRY.get(meta_arch)(cfg)
File "/home/root1/Detection/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 37, in init
pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
File "/root/anaconda2/envs/detectron2/lib/python3.7/site-packages/torch/cuda/init.py", line 192, in _lazy_init
_check_driver()
File "/root/anaconda2/envs/detectron2/lib/python3.7/site-packages/torch/cuda/init.py", line 111, in _check_driver
of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError:
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

 for some reasons I can't up-to-date driver for cuda 10, but use conda build virtualenv, and cond install cudatoolkit=10.1, pytorch 1.3.1 is working,but detectron2 not work,what's can i do?

Bast wish

**Comment by ppwwyyxx** [comment]
> pytorch 1.3.1 is working

No it will not work with GPUs.

You should update your driver or install cuda 10.0 instead of 10.1
