### ISSUE TITLE
ImportError: cannot import name 'PY3' from 'torch._six' 

### ISSUE THREAD

**Issue by ColinAdreon** [facebookresearch/detectron2#3767]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
File ```detectron2/demo/demo.py```
2. What exact command you run:
When attempting to run the demo from the demo folder:
```
python demo.py --config file ../configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml --inputs ../tools/datasets/coco/620.jpg
```
3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/structures/__init__.py", line 3, in <module>
    from .image_list import ImageList
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/structures/image_list.py", line 8, in <module>
    from detectron2.layers.wrappers import shapes_to_tensor
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/yuganlab/Documents/colin/detectron2/detectron2/layers/deform_conv.py", line 9, in <module>
    from torchvision.ops import deform_conv2d
  File "/home/yuganlab/anaconda3/lib/python3.8/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/home/yuganlab/anaconda3/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "/home/yuganlab/anaconda3/lib/python3.8/site-packages/torchvision/datasets/lsun.py", line 19, in <module>
    from .utils import verify_str_arg, iterable_to_str
  File "/home/yuganlab/anaconda3/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 11, in <module>
    from torch._six import PY3
ImportError: cannot import name 'PY3' from 'torch._six' (/home/yuganlab/anaconda3/lib/python3.8/site-packages/torch/_six.py)
```
4. please simplify the steps as much as possible so they do not require additional resources to run

## Expected behavior:

A visual demo of the model evaluation on the input image

## Environment:
```conda list``` gives the following installed packages:

```
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             4.5                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   1.0.0                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
black                     21.4b2                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bzip2                     1.0.8                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2021.10.26           h06a4308_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cython                    0.29.25                  pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
freetype                  2.11.0               h70c0345_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
fvcore                    0.1.5.post20211023          pypi_0    pypi
giflib                    5.2.1                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gmp                       6.2.1                h2531618_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gnutls                    3.6.15               he1e5248_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.42.0                   pypi_0    pypi
hydra-core                1.1.1                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.8.2                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
iopath                    0.1.9                    pypi_0    pypi
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
lame                      3.100                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lcms2                     2.12                 h3be6417_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.35.1               h7274673_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.3.0               h5101ec6_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   9.3.0               h5101ec6_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libidn2                   2.3.2                h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libopus                   1.3.1                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.37               hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.3.0               hd4cf53a_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtasn1                  4.16.0               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.2.0                h85742a9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libunistring              0.9.10               h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuv                     1.40.0               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libvpx                    1.7.0                h439df22_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp                   1.2.0                h89dd481_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp-base              1.2.0                h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lz4-c                     1.9.3                h295c915_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.3.6                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py39h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.1            py39hd3c417c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py39h51133e4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nettle                    3.7.3                hbbd107a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.21.2           py39h20f2e39_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.21.2           py39h79a1101_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
omegaconf                 2.1.1                    pypi_0    pypi
openh264                  2.1.0                hd408876_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.1.1l               h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pathspec                  0.9.0                    pypi_0    pypi
pillow                    8.4.0            py39h5aabda8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       21.2.4           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
portalocker               2.3.2                    pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.3                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
python                    3.9.7                h12debd9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytorch-mutex             1.0                        cuda    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h27cfd23_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
regex                     2021.11.10               pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
setuptools                58.0.4           py39h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.16.0             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.36.0               hc218d9a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
toml                      0.10.2                   pypi_0    pypi
torchvision               0.11.1               py39_cu113    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
tqdm                      4.62.3             pyhd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
typing_extensions         3.10.0.2           pyh06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tzdata                    2021e                hda174b7_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.26.7                   pypi_0    pypi
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
x264                      1!157.20191217       h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zstd                      1.4.9                haebb681_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

**Comment by ppwwyyxx** [comment]
The error comes from `from torchvision import datasets` therefore unrelated to this project.
