### ISSUE TITLE
Iterating the data loader again leads to memory leak

### ISSUE THREAD

**Issue by liyz15** [facebookresearch/detectron2#3847]
I have not figured out why so I'm not sure if this is expected or a bug. But I spent days debugging this so I'm posting it in case anyone has a similar situation.

I'm trying to use the data loader inside another epoch-based loop so every epoch I reiterate the dataloader, and the cpu memory starts to explode at the second epoch.

Using the same iterator for all epochs everything is fine.

Here is a minimal snippet to reproduce on voc dataset
```
from detectron2.config import get_cfg
from detectron2.data.build import build_detection_train_loader
import os, psutil

def main():
    rcnn_cfg = get_cfg()

    rcnn_cfg.MODEL.META_ARCHITECTURE = "GeneralizedRCNN"
    rcnn_cfg.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
    rcnn_cfg.MODEL.ROI_HEADS.NUM_CLASSES = 20

    rcnn_cfg.SOLVER.IMS_PER_BATCH = 1
    rcnn_cfg.DATASETS.TRAIN = ('voc_2007_trainval', 'voc_2012_trainval')
    rcnn_cfg.DATASETS.TEST = ('voc_2007_test',)

    rcnn_cfg.INPUT.MAX_SIZE_TRAIN = 1333
    rcnn_cfg.INPUT.MIN_SIZE_TRAIN = (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
    rcnn_cfg.INPUT.MIN_SIZE_TEST = 800

    rcnn_cfg.DATALOADER.NUM_WORKERS = 0

    loader = build_detection_train_loader(rcnn_cfg)

    for epoch in range(100):
        loader_iter = iter(loader)
        for i in range(1000):
            data = next(loader_iter)
            if (i + 1) % 100 == 0:
                memory_usage = psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2
                print('{}/100 {}/1000 Memory Usage: {}'.format(epoch, i, memory_usage))
                

if __name__ == '__main__':
    main()
```

And the output

```
0/100 99/1000 Memory Usage: 235.74609375
0/100 199/1000 Memory Usage: 213.08203125
0/100 299/1000 Memory Usage: 192.0703125
0/100 399/1000 Memory Usage: 201.9921875
0/100 499/1000 Memory Usage: 212.4140625
0/100 599/1000 Memory Usage: 184.55859375
0/100 699/1000 Memory Usage: 265.8203125
0/100 799/1000 Memory Usage: 229.6640625
0/100 899/1000 Memory Usage: 195.96875
0/100 999/1000 Memory Usage: 184.48046875
1/100 99/1000 Memory Usage: 279.69921875
1/100 199/1000 Memory Usage: 314.33203125
1/100 299/1000 Memory Usage: 357.21875
1/100 399/1000 Memory Usage: 411.26953125
1/100 499/1000 Memory Usage: 423.75
1/100 599/1000 Memory Usage: 487.73828125
1/100 699/1000 Memory Usage: 547.7890625
1/100 799/1000 Memory Usage: 554.54296875
1/100 899/1000 Memory Usage: 625.46484375
1/100 999/1000 Memory Usage: 667.80078125
Traceback (most recent call last):
  File "main_debug.py", line 36, in <module>
  File "main_debug.py", line 29, in main
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/common.py", line 234, in __iter__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/common.py", line 201, in __iter__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/common.py", line 90, in __getitem__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/utils/serialize.py", line 26, in __call__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/dataset_mapper.py", line 164, in __call__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/transforms/augmentation.py", line 264, in __call__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/transforms/augmentation.py", line 170, in __call__
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/transforms/augmentation.py", line 335, in transform
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/detectron2/data/transforms/transform.py", line 123, in apply_image
  File "/mnt/cache/liyizhuo.vendor/.conda/envs/pytorch/lib/python3.7/site-packages/PIL/Image.py", line 703, in __array__
numpy.core._exceptions.MemoryError: Unable to allocate 2.10 MiB for an array with shape (736, 997, 3) and data type uint8
```

Environment:
```
>>> print(torch.__version__)
1.8.0
>>> print(torch.version.cuda)
10.2
>>> print(detectron2.__version__)
0.6
```

**Comment by ppwwyyxx** [comment]
Will be fixed by #3849. Re-iterate a training dataloader is in general not a good practice (for performance reasons) so in the project we have never done it before.
