### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by qslia** [facebookresearch/detectron2#3924]
[01/26 19:46:42 detectron2]: Arguments: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', webcam=False, video_input='/home/q/Videos/palace.mp4', input=None, output='./', confidence_threshold=0.5, opts=[])
[01/26 19:46:44 fvcore.common.checkpoint]: [Checkpointer] Loading from weights/model_final_f10217.pkl ...
[01/26 19:46:44 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
[ERROR:0@2.856] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2767) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@2.857] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2839) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@2.857] global /io/opencv/modules/videoio/src/cap.cpp (595) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /tmp/video_format_testtsdxarhf/test_file.mkv in function 'icvExtractPattern'

/home/q/Downloads/detectron2/demo/demo.py:154: UserWarning: x264 codec not available, switching to mp4v
  warnings.warn("x264 codec not available, switching to mp4v")
  0%|                                                                                                                 | 0/329 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/q/Downloads/detectron2/demo/demo.py", line 172, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/home/q/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/q/Downloads/detectron2/demo/predictor.py", line 129, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/q/Downloads/detectron2/demo/predictor.py", line 98, in process_predictions
    vis_frame = video_visualizer.draw_instance_predictions(frame, predictions)
  File "/home/q/anaconda3/lib/python3.9/site-packages/detectron2-0.6-py3.9-linux-x86_64.egg/detectron2/utils/video_visualizer.py", line 111, in draw_instance_predictions
    else [y[0] for y in filter(lambda x: x[1], zip(labels, visibilities))]
TypeError: 'NoneType' object is not iterable

I cant fix this bug, please help me

**Comment by qslia** [comment]
python demo/demo.py \
    --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml \
    --video-input /home/q/Videos/palace.mp4 \
    --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl    
    --output  ./



[01/26 19:59:12 detectron2]: Arguments: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', webcam=False, video_input='/home/q/Videos/palace.mp4', input=None, output=None, confidence_threshold=0.5, opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'])
[01/26 19:59:14 fvcore.common.checkpoint]: [Checkpointer] Loading from detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl ...
[01/26 19:59:14 fvcore.common.checkpoint]: Reading a file from 'Detectron2 Model Zoo'
[ERROR:0@2.873] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2767) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@2.873] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2839) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@2.873] global /io/opencv/modules/videoio/src/cap.cpp (595) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /tmp/video_format_testxkd8y7jb/test_file.mkv in function 'icvExtractPattern'


/home/q/Downloads/detectron2/demo/demo.py:154: UserWarning: x264 codec not available, switching to mp4v
  warnings.warn("x264 codec not available, switching to mp4v")
  0%|                                                                                                                 | 0/329 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/q/Downloads/detectron2/demo/demo.py", line 172, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/home/q/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/q/Downloads/detectron2/demo/predictor.py", line 129, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "/home/q/Downloads/detectron2/demo/predictor.py", line 98, in process_predictions
    vis_frame = video_visualizer.draw_instance_predictions(frame, predictions)
  File "/home/q/anaconda3/lib/python3.9/site-packages/detectron2-0.6-py3.9-linux-x86_64.egg/detectron2/utils/video_visualizer.py", line 111, in draw_instance_predictions
    else [y[0] for y in filter(lambda x: x[1], zip(labels, visibilities))]
TypeError: 'NoneType' object is not iterable
./run.sh: line 11: --output: command not found
