### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by futureflsl** [facebookresearch/detectron2#3943]
the same code for detectron2 -0.6 but result is different.when I train my pascal voc format dataset with GTX1060,It work well.But I place all to RTX3090 error occurred!
GTX1060 is torch=1.8.1+cu102
RTX3090 is torch=1.8.1+cu111
error with RTX3090
eta: 0:57:48  iter: 4  total_loss: 3.994  loss_cls: 3.154  loss_box_reg: 0.054  loss_rpn_cls: 0.7008  loss_rpn_loc: 0.06758  time: 0.1927  data_time: 0.0799  lr: 3.097e-05  max_mem: 2304M
Traceback (most recent call last):
  File "tools/train_net.py", line 156, in <module>
    launch(
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_net.py", line 150, in main
    return trainer.train()
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 157, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 472, in forward
    losses = self.losses(
  File "/home/howso/Anaconda/envs/detectron2/lib/python3.8/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 399, in losses
    num_pos_anchors = pos_mask.sum().item()
RuntimeError: CUDA error: device-side assert triggered

**Comment by futureflsl** [comment]
I updagrade torch==1.9.0,it work fine
