### ISSUE TITLE
TypeError: add(): argument 'alpha' must be Number, not NoneType #35

### ISSUE THREAD

**Issue by reubenwenisch** [facebookresearch/detectron2#3964]
Trying to run the model with a custom dataset. and have the following error
```
Traceback (most recent call last):
  File "train_net_custom.py", line 222, in <module>
    launch(
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net_custom.py", line 216, in main
    return trainer.train()
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 294, in run_step
    self.optimizer.step()
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/torch/optim/sgd.py", line 110, in step
    F.sgd(params_with_grad,
  File "/home/xxx/anaconda3/envs/detectron/lib/python3.8/site-packages/torch/optim/_functional.py", line 160, in sgd
    d_p = d_p.add(param, alpha=weight_decay)
TypeError: add(): argument 'alpha' must be Number, not NoneType
```
Detectron2 version: 0.6

**Comment by dedoogong** [comment]
I got the same error!

**Comment by reubenwenisch** [comment]
@dedoogong This error had come with using detectron2 latest version I moved it to previous version and the code started working. Hope this helps.

**Comment by awadsb1** [comment]
@reubenwenisch which version of Detectron2 did you move to?  Having the same issue

**Comment by Roywangj** [comment]
I have met the same problem, i find the setting "weight_decay" don't suppport numbers like 1e-4, when i replace 1e-4 to 0.0001, it  fixed.

**Comment by Yxt1212** [comment]
Same error too

**Comment by Roywangj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by frostinassiky** [comment]
> I have met the same problem, i find the setting "weight_decay" don't suppport numbers like 1e-4, when i replace 1e-4 to 0.0001, it fixed.

Great! The main reason is that the optimizer in this version does not handle `None` of weight_decay. I set it from `None` to `0` and my code is running smoothly.

**Comment by Roywangj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yuhao20** [comment]
> > I have met the same problem, i find the setting "weight_decay" don't suppport numbers like 1e-4, when i replace 1e-4 to 0.0001, it fixed.
> 
> Great! The main reason is that the optimizer in this version does not handle `None` of weight_decay. I set it from `None` to `0` and my code is running smoothly.

excuse me, could you tell me the place where we could change weight_decay? the .yaml?

**Comment by EGO-False-Sleep** [comment]
> I have met the same problem, i find the setting "weight_decay" don't suppport numbers like 1e-4, when i replace 1e-4 to 0.0001, it fixed.

您好，我最近也在学习这篇开源项目，遇到了这个问题，请问您是在何处修改的weight_decay,我找到了两个可能的位置，分别是defrcn/config/defaults.py 34行 值为5e-5以及detectron2\config\defaults.py 522行值为0.0001   ，分别对应着_CC以及_C,但是在defrcn/config/config.py的get_cfg函数中，实际返回值貌似为_CC，如果您有时间，请不吝赐教，这对我非常重要，谢谢，期待您的答复

**Comment by Roywangj** [comment]
你好 这是很久以前弄的了，我记得只是从 1e-4 改成 0.0001 就可以了，具体在哪里我已经不记得了，你可以都试一下，祝好

**Comment by EGO-False-Sleep** [comment]
> 你好 这是很久以前弄的了，我记得只是从 1e-4 改成 0.0001 就可以了，具体在哪里我已经不记得了，你可以都试一下，祝好

感谢您的回信，我研究了很久，最后找到了一个修改方案，但是后面又陆续出现了别的报错信息，我已经打算放弃这个项目了，关于小样本目标检测任务如果您有一些好的开源项目推荐，我将万分感谢
