### ISSUE TITLE
type object 'Tensor' has no attribute 'cat'

### ISSUE THREAD

**Issue by binyisu** [facebookresearch/detectron2#4048]
Traceback (most recent call last):
  File "/home/subinyi/Users/openworld_ldet-main/tools/trainer_ldet.py", line 231, in <module>
    args=(args,),
  File "/home/subinyi/anaconda3/envs/ldet/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/subinyi/Users/openworld_ldet-main/tools/trainer_ldet.py", line 218, in main
    do_train(cfg, model, resume=args.resume)
  File "/home/subinyi/Users/openworld_ldet-main/tools/trainer_ldet.py", line 147, in do_train
    loss_dict_normal = model(data)
  File "/home/subinyi/anaconda3/envs/ldet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/subinyi/Users/openworld_ldet-main/ldet/modeling/meta_arch/rcnn.py", line 163, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/subinyi/anaconda3/envs/ldet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/subinyi/Users/openworld_ldet-main/ldet/modeling/roi_heads/roi_heads.py", line 555, in forward
    losses = self._forward_box(features, proposals)
  File "/home/subinyi/Users/openworld_ldet-main/ldet/modeling/roi_heads/roi_heads.py", line 622, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/home/subinyi/Users/openworld_ldet-main/ldet/modeling/roi_heads/fast_rcnn.py", line 318, in losses
    proposal_boxes, gt_boxes, proposal_deltas, gt_classes
  File "/home/subinyi/Users/openworld_ldet-main/ldet/modeling/roi_heads/fast_rcnn.py", line 350, in box_reg_loss
    self.smooth_l1_beta,
  File "/home/subinyi/anaconda3/envs/ldet/lib/python3.7/site-packages/detectron2/modeling/box_regression.py", line 251, in _dense_box_regression_loss
    anchors = type(anchors[0]).cat(anchors).tensor  # (R, 4)
AttributeError: type object 'Tensor' has no attribute 'cat'

Process finished with exit code 1

**Comment by binyisu** [comment]
i have solved this problem, in detectron2 box_regession.py, i use: 
########
    if len(anchors)==1:
        anchors = anchors[0]
    else:
        anchors = type(anchors[0]).cat(anchors).tensor # (R, 4)
to replace:
anchors = type(anchors[0]).cat(anchors).tensor # (R, 4)
