### ISSUE TITLE
export default predictor using torchscript fails

### ISSUE THREAD

**Issue by zduey** [facebookresearch/detectron2#4175]
## Instructions To Reproduce the 🐛 Bug:

My understanding is that I should be able to create torchscript code from many of the detectron2 models. The following example demonstrates the error using the `DefaultPredictor`:

```python
# export.py

import torch

from detectron2 import model_zoo
from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.DEVICE = "cpu"
predictor = DefaultPredictor(cfg)

torch.jit.script(predictor.model)
```

Run `python export.py`, and the following error is encountered:

```
Traceback (most recent call last):
  File "export.py", line 14, in <module>
    torch.jit.script(predictor.model)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 513, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 587, in _construct
    init_fn(script_module)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 491, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 513, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 587, in _construct
    init_fn(script_module)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 491, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Module 'ResNet' has no attribute 'stages' (This attribute exists on the Python module, but we failed to convert Python type: 'list' to a TorchScript type. Could not infer type of list element: Cannot infer concrete type of torch.nn.Module. Its type was inferred; try adding a type annotation for the attribute.):
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/detectron2/modeling/backbone/resnet.py", line 449
        if "stem" in self._out_features:
            outputs["stem"] = x
        for name, stage in zip(self.stage_names, self.stages):
                                                 ~~~~~~~~~~~ <--- HERE
            x = stage(x)
            if name in self._out_features:
```
## Expected behavior:

I expected to be able to convert this detectron2 model using torchscript.

## Workarounds Attempted:

Based on the responses to [this issue](https://github.com/pytorch/pytorch/issues/50427), I tried to get around the problem by adding a type hint to the `stages` attribute. (diff below)

```
diff --git a/detectron2/modeling/backbone/resnet.py b/detectron2/modeling/backbone/resnet.py
index 5b8e842..dcbba2e 100644
--- a/detectron2/modeling/backbone/resnet.py
+++ b/detectron2/modeling/backbone/resnet.py
@@ -4,6 +4,7 @@ import fvcore.nn.weight_init as weight_init
 import torch
 import torch.nn.functional as F
 from torch import nn
+from typing import List

 from detectron2.layers import (
     CNNBlockBase,
@@ -386,7 +387,8 @@ class ResNet(Backbone):
         self._out_feature_strides = {"stem": current_stride}
         self._out_feature_channels = {"stem": self.stem.out_channels}

-        self.stage_names, self.stages = [], []
+        self.stage_names: List[str] = []
+        self.stages: List[CNNBlockBase] = []

         if out_features is not None:
             # Avoid keeping unused layers in this module. They consume extra memory
@@ -445,7 +447,8 @@ class ResNet(Backbone):
         x = self.stem(x)
         if "stem" in self._out_features:
             outputs["stem"] = x
-        for name, stage in zip(self.stage_names, self.stages):
+        stages: List[CNNBlockBase] = self.stages
+        for name, stage in zip(self.stage_names, stages):
             x = stage(x)
             if name in self._out_features:
                 outputs[name] = x
```

I encountered a different error that I was unable to solve:

```
Traceback (most recent call last):
  File "export.py", line 14, in <module>
    torch.jit.script(predictor.model)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 513, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 587, in _construct
    init_fn(script_module)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 491, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 513, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_script.py", line 587, in _construct
    init_fn(script_module)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 491, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
Unknown type name 'CNNBlockBase':
  File "/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/detectron2/modeling/backbone/resnet.py", line 450
        if "stem" in self._out_features:
            outputs["stem"] = x
        stages: List[CNNBlockBase] = self.stages
                     ~~~~~~~~~~~~ <--- HERE
        for name, stage in zip(self.stage_names, stages):
            x = stage(x)
```

## Environment:

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
---------------------  ------------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.8.11 (default, Aug 24 2021, 12:55:11) [GCC 9.3.0]
numpy                  1.22.3
detectron2             0.6 @/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          CUDA 11.3
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.10.1+cu111 @/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          No: torch.cuda.is_available() == False
Pillow                 9.1.0
torchvision            0.11.2+cu111 @/home/zduey/.pyenv/versions/detectron2-debugging/lib/python3.8/site-packages/torchvision
fvcore                 0.1.5.post20220414
iopath                 0.1.9
cv2                    Not found
---------------------  ------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by ppwwyyxx** [comment]
>  I should be able to create torchscript code from many of the detectron2 models

Yes, you can create torchscript from most detectron2 models, but your code is not the correct way to do it.
https://github.com/facebookresearch/detectron2/tree/main/tools/deploy is the official example that converts detectron2 models to torchscript.

**Comment by Z-star1** [comment]
when i use this https://github.com/facebookresearch/detectron2/tree/main/tools/deploy,i get a  problems, ""
detectron2-main/tools/deploy/build$ cmake ..
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found OpenCV: /usr (found suitable version "3.2.0", minimum required is "3.2.0") 
-- Configuring done
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "torchscript_mask_rcnn" links to target "Python3::Python" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by soulslicer** [comment]
I have the exact same problem. How did you fix it? @zduey
