### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ingaluxemburg** [facebookresearch/detectron2#4213]
1. Full runnable code or full changes you made:
```
# Some basic setup:
# Setup detectron2 logger
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
```

Trying to run this code from https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5, and have this report:
```
/usr/local/lib/python3.7/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-1-9283645e3740>](https://localhost:8080/#) in <module>()
     11 
     12 # import some common detectron2 utilities
---> 13 from detectron2 import model_zoo
     14 from detectron2.engine import DefaultPredictor
     15 from detectron2.config import get_cfg

9 frames
[/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/mobilenetv2.py](https://localhost:8080/#) in <module>()
      3 from torch import Tensor
      4 from torch import nn
----> 5 from torch.ao.quantization import QuantStub, DeQuantStub
      6 from torchvision.models.mobilenetv2 import InvertedResidual, MobileNetV2, model_urls
      7 

ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

## Expected behavior:

Imports without errors

## Environment:
I try to use google colab to correctly install detectron to use it then for LayoutLMv2
Paste the output of the following command:
```
2022-05-05 12:14:23 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/main/detectron2/utils/collect_env.py [8391/8391] -> "collect_env.py" [1]
/usr/local/lib/python3.7/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "collect_env.py", line 11, in <module>
    import torchvision
  File "/usr/local/lib/python3.7/dist-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/__init__.py", line 1, in <module>
    from .mobilenet import *
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import QuantizableMobileNetV2, mobilenet_v2, __all__ as mv2_all
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/usr/local/lib/python3.7/dist-packages/torch/ao/quantization/__init__.py)
```

**Comment by emadghalenoei** [comment]
have the same issue too

**Comment by darkhan-s** [comment]
@ingaluxemburg have you been able to resolve it? I was also testing the colab code and installed torch 1.10/CUDA 11.3 version of detectron2

**Comment by GuiQuQu** [comment]
I meet the same problem in colab,I think the package version is wrong,colab provide torch1.11/CUDA11.3，but I copy the install command in docs and the corresponding version is torch1.10/CUDA11.3
