### ISSUE TITLE
Cannot import name  from config.py: .py has to exist

### ISSUE THREAD

**Issue by khoinguyen19k8** [facebookresearch/detectron2#4214]
## Instructions To Reproduce the Issue and Full Logs:

This is my current project structure:
```
-----------home
      -------balloon_config
               -------__init__.py
               -------balloon.py # Content the same as detectron2/configs/common/data/coco.py besides different dataset name
               -------optim.py # Content the same as detectron2/common/optim.py
               -------train.py # Content the same as detectron2/common/train.py except dataset name
               -------mask_rcnn_fpn.py # Content the same as detectron2/common/models/mask_rcnn_fpn.py
               -------config.py # Content similar to detectron2/configs/new_baselines/mask_rcnn_R_50_FPN_100ep_LSJ.py except some changes (bellow)
               -------lazyconfig_train_net.py # Content the same as detectron2/tools/lazyconfig_train_net.py
```
Inside config.py the only thing that I changed are the import statements:

```
from .balloon import dataloader
from .mask_rcnn_fpn import model
from .optim import SGD as optimizer
from . import train
```

I then tried to train it by typing `python lazyconfig_train_net.py --config-file config.py --num-gpus 1 --num-machines 1`. 
I then got the following error:
```
Traceback (most recent call last):
  File "/home/akooi/projects/mask-rcnn/balloon_config/lazyconfig_train_net.py", line 124, in <module>
    launch(
  File "/home/akooi/Downloads/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/akooi/projects/mask-rcnn/balloon_config/lazyconfig_train_net.py", line 108, in main
    cfg = LazyConfig.load(args.config_file)
  File "/home/akooi/Downloads/detectron2/detectron2/config/lazy.py", line 210, in load
    exec(compile(content, filename, "exec"), module_namespace)
  File "config.py", line 10, in <module>
    from . import train # Can modify but not important and just keep it there
  File "/home/akooi/Downloads/detectron2/detectron2/config/lazy.py", line 139, in new_import
    cur_file = find_relative_file(globals["__file__"], name, level)
  File "/home/akooi/Downloads/detectron2/detectron2/config/lazy.py", line 126, in find_relative_file
    raise ImportError(
ImportError: Cannot import name  from config.py: .py has to exist.
```
Things should be working because config.py is in the same directory as lazyconfig_train_net.py. However, This file could not be found for some reasons.

## Your Environment
Fedora 35
Python 3.9.12
Detectron 0.6
Torch 1.10.1+cu111
Torchvision 0.11.2+cu111

**Comment by ppwwyyxx** [comment]
Importing a "directory" from a config file is not supported. This is expected according to this comment:
https://github.com/facebookresearch/detectron2/blob/b675879664a58546adaa99420e78abac09458dde/detectron2/config/lazy.py#L121-L123
