### ISSUE TITLE
CUDA out of memory even on strong hardware

### ISSUE THREAD

**Issue by khoinguyen19k8** [facebookresearch/detectron2#4226]
### Commands I run
I am trying to train mask-RCNN on my NVIDIA Quadro RTX 6000 by using the following configuration:
`python lazyconfig_train_net.py --config-file mask_rcnn_R_50_FPN_100ep_LSJ.py --num-gpus 1`

### Changes I made
I trained on the balloon dataset downloaded from the tutorial notebook. I also kept most configurations default. The only things I changed is from "SyncBN" to "GN" because of single GPU training and decrease batch size to 8. 

Here is the error that I encountered:

### Error
```
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.65 GiB total capacity; 15.88 GiB already allocated; 20.44 MiB free; 15.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Full logs
```
Traceback (most recent call last):
  File "/wecare/home/khoi/thesis/models/mask_rcnn/balloon_model/lazyconfig_train_net.py", line 126, in <module>
    launch(
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/wecare/home/khoi/thesis/models/mask_rcnn/balloon_model/lazyconfig_train_net.py", line 121, in main
    do_train(args, cfg)
  File "/wecare/home/khoi/thesis/models/mask_rcnn/balloon_model/lazyconfig_train_net.py", line 105, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 158, in forward
    features = self.backbone(images.tensor)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/modeling/backbone/fpn.py", line 126, in forward
    bottom_up_features = self.bottom_up(x)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/modeling/backbone/resnet.py", line 449, in forward
    x = stage(x)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/modeling/backbone/resnet.py", line 201, in forward
    out = self.conv3(out)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/detectron2/layers/wrappers.py", line 110, in forward
    x = self.norm(x)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 268, in forward
    return F.group_norm(
  File "/wecare/home/khoi/miniconda3/envs/maskrcnn/lib/python3.9/site-packages/torch/nn/functional.py", line 2360, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
```

## Expected behavior:

The batch size is not too big (8) and the balloon dataset is also very small. Even though my GPU is not the best, 24GB should be enough for such a small configuration.

## Environment:

Paste the output of the following command:
OS: Debian 10.2.1-6
python 3.9.7
pytorch 1.10.1+cu111
detectron2 0.6
GPU: Quadro RTX 6000
CUDA 11.2

**Comment by ppwwyyxx** [comment]
> Changes I made
I trained on the balloon dataset downloaded from the tutorial notebook. I also kept most configurations default. The only things I changed is from "SyncBN" to "GN" because of single GPU training and decrease batch size to 8.

Please post code (as the issue template suggests), don't describe them with words. 

> Full logs

Please post full logs as the issue template suggests.

**Comment by ppwwyyxx** [comment]
> I trained on the balloon dataset downloaded from the tutorial notebook. ... decrease batch size to 8.

FWIW, the ballon example uses a batch size of 2. 
8 is a very large batch size.
