### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by mrashidmaqbool** [facebookresearch/detectron2#4327]
I am running detectron2 in a docker file (clone from repository) and while running the demo.py I am getting the following error: 

Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from predictor import VisualizationDemo
  File "/home/appuser/detectron2_repo/demo/predictor.py", line 10, in <module>
    from detectron2.engine.defaults import DefaultPredictor
  File "/home/appuser/.local/lib/python3.6/site-packages/detectron2/engine/__init__.py", line 12, in <module>
    from .defaults import *
  File "/home/appuser/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 38, in <module>
    from detectron2.modeling import build_model
  File "/home/appuser/.local/lib/python3.6/site-packages/detectron2/modeling/__init__.py", line 5, in <module>
    from .backbone import (
  File "/home/appuser/.local/lib/python3.6/site-packages/detectron2/modeling/backbone/__init__.py", line 15, in <module>
    from .vit import ViT, SimpleFeaturePyramid, get_vit_lr_decay_rate
  File "/home/appuser/.local/lib/python3.6/site-packages/detectron2/modeling/backbone/vit.py", line 10, in <module>
    from fairscale.nn.checkpoint import checkpoint_wrapper
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 43, in <module>
    from fairscale.nn.misc import FlattenParamsWrapper
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/nn/misc/__init__.py", line 12, in <module>
    from .flatten_params_wrapper import FlattenParamsWrapper
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 34, in <module>
    from fairscale.experimental.nn.ssd_offload import SsdFlatParameter
  File "/home/appuser/.local/lib/python3.6/site-packages/fairscale/experimental/nn/ssd_offload.py", line 6
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Should I upgrade python to 3.7 as currently it is running in 3.6.9 to fix this issue or any other fix?

**Comment by AO-AO** [comment]
Same problem.
