### ISSUE TITLE
Testing new baselines model

### ISSUE THREAD

**Issue by Bill4869** [facebookresearch/detectron2#4337]
Hi, I am trying to test a new baseline on a single image. Below is the code I tried.
```
im = cv2.imread("./00153_colors.png")
cfg = model_zoo.get_config([new baseline path], trained=True)
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
```
However, I got the error in the `DefaultPredictor method`

```
Traceback (most recent call last):
  File "debug.py", line 42, in <module>
    predictor = DefaultPredictor(cfg)
  File "/home/bill/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 284, in __init__
    self.cfg = cfg.clone()  #can be modified by model
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 358, in __getattr__
    key=key, value=None, cause=e, type_override=ConfigAttributeError
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/base.py", line 237, in _format_and_raise
    type_override=type_override,
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 354, in __getattr__
    key=key, default_value=_DEFAULT_MARKER_, validate_key=False
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    key=key, throw_on_missing_key=True, validate_key=validate_key
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 78, in _get_child
    throw_on_missing_key=throw_on_missing_key,
  File "/home/bill/.local/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key clone
    full_key: clone
    object_type=dict
```
Can anyone tell me how to solve this problem? Or if there is another way to test the new baseline, I would really appreciate it.
I did look at the documentation but maybe due to my lack of understanding, I could not manage to make it work.

Thank you in advances.

**Comment by alrightkami** [comment]
Hey there, [as mentioned here](https://github.com/facebookresearch/detectron2/issues/3225#:~:text=DefaultPredictor%20would%20need%20a%20patch%20like%20%233755%20to%20work%20with%20new%20configs.), you'll need to write your own DefaultPredictor to work with new baselines

**Comment by bouachalazhar** [comment]
> Hey there, [as mentioned here](https://github.com/facebookresearch/detectron2/issues/3225#:~:text=DefaultPredictor%20would%20need%20a%20patch%20like%20%233755%20to%20work%20with%20new%20configs.), you'll need to write your own DefaultPredictor to work with new baselines

it's bad explication.

**Comment by daniellehot** [comment]
Hi. I wrote a basic Predictor class that can be used with the new baselines. I basically took the DefaultPredictor class and changed syntax from the old yaml files to match the new LazyConfig system. I am sure this can be improved further, but this was sufficient for my case. 

```python
from detectron2.config import LazyConfig, instantiate
from detectron2.data import MetadataCatalog
from detectron2.engine.defaults import create_ddp_model
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.utils.visualizer import Visualizer, ColorMode

import torch
import copy
import random
import cv2


class LazyConfigPredictor:
    def __init__(self, cfg, conf_threshold):
        self.cfg = copy.deepcopy(cfg)
        self.cfg.model.roi_heads.box_predictor.test_score_thresh = conf_threshold
        model = instantiate(self.cfg.model)
        model.to(self.cfg.train.device)
        self.model = create_ddp_model(model)
        self.model.eval()
        self.metadata = MetadataCatalog.get(self.cfg.dataloader.test.dataset.names[0]) 
        DetectionCheckpointer(self.model).load(self.cfg.train.init_checkpoint)
        self.input_format = self.cfg.dataloader.train.mapper.image_format
        assert self.input_format in ["RGB", "BGR"], self.input_format

    def __call__(self, original_image):
        with torch.no_grad():  # https://github.com/sphinx-doc/sphinx/issues/4258
            # Apply pre-processing to image.
            if self.input_format == "RGB":
                # whether the model expects BGR inputs or RGB
                original_image = original_image[:, :, ::-1]
            height, width = original_image.shape[:2]
            image = torch.as_tensor(original_image.astype("float32").transpose(2, 0, 1))
            inputs = {"image": image, "height": height, "width": width}
            predictions = self.model([inputs])[0]
            return predictions
        
if __name__=="__main__":
    # Model Configuration
    cfg = LazyConfig.load("PATH/TO/A/MODEL")
    cfg.train.init_checkpoint = ("PATH/TO/A/CHECKPOINT")
    # Predictor
    predictor = LazyConfigPredictor(cfg, conf_threshold=0.5)

    # Visualise predictions
    for d in random.sample(dataset_dict, 3):    
        im = cv2.imread(d["file_name"])
        outputs = predictor(im)  # format is documented at https://detectron2.readthedocs.io/tutorials/models.html#model-output-format
        #filtered_outputs = filter(outputs)
        v = Visualizer(im[:, :, ::-1],
                    metadata=dataset_metadata, 
                    scale=0.5, 
                    instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels. This option is only available for segmentation models
        )
        out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
        cv2.imshow("output", out.get_image()[:, :, ::-1])
        cv2.waitKey(0)
```
