### ISSUE TITLE
AssertionError: No valid data found in <dataset_name>.

### ISSUE THREAD

**Issue by LexTran** [facebookresearch/detectron2#4338]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
I was trying to run a demo with my own custom dataset

to do so, I defined a function to register my dataset as below:
```
def register_dataset():
    DatasetCatalog.register("my_train", lambda: load_coco_json(TRAIN_JSON, TRAIN_PATH))
    MetadataCatalog.get("my_train").set(thing_classes=CLASS_NAMES,
                                        evaluator_type='coco',
                                        json_file=TRAIN_JSON,
                                        image_root=TRAIN_PATH)
    DatasetCatalog.register("my_val", lambda: load_coco_json(VAL_JSON, VAL_PATH))
    MetadataCatalog.get("my_val").set(thing_classes=CLASS_NAMES,
                                        evaluator_type='coco',
                                        json_file=VAL_JSON,
                                        image_root=VAL_PATH)
```
2. What exact command you run:
I copied /tools/train_net.py into /tools/train.py, and run python trian.py --num-gpus 1 in command line

3. __Full logs__ or other relevant observations:
```
WARNING [06/16 13:21:14 d2.data.datasets.coco]: G:/CS/DL/CHY/data\train.json contains 43 annotations, but only 0 of them match to images in the file.
WARNING [06/16 13:21:14 d2.data.datasets.coco]: G:/CS/DL/CHY/data\train.json contains 43 annotations, but only 0 of them match to images in the file.
WARNING [06/16 13:21:14 d2.data.datasets.coco]: G:/CS/DL/CHY/data\train.json contains 43 annotations, but only 0 of them match to images in the file.
[06/16 13:21:14 d2.data.datasets.coco]: Loaded 11 images in COCO format from G:/CS/DL/CHY/data\train.json
[06/16 13:21:14 d2.data.datasets.coco]: Loaded 11 images in COCO format from G:/CS/DL/CHY/data\train.json
[06/16 13:21:14 d2.data.datasets.coco]: Loaded 11 images in COCO format from G:/CS/DL/CHY/data\train.json
[06/16 13:21:14 d2.data.build]: Removed 11 images with no usable annotations. 0 images left.
[06/16 13:21:14 d2.data.build]: Removed 11 images with no usable annotations. 0 images left.
[06/16 13:21:14 d2.data.build]: Removed 11 images with no usable annotations. 0 images left.
[06/16 13:21:14 d2.data.build]: Distribution of instances among all 5 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
| Right Arm  | 0            | Right Leg  | 0            |    Head    | 0            |
|  Left Arm  | 0            |  Left Leg  | 0            |            |              |
|   total    | 0            |            |              |            |              |
[06/16 13:21:14 d2.data.build]: Distribution of instances among all 5 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
| Right Arm  | 0            | Right Leg  | 0            |    Head    | 0            |
|  Left Arm  | 0            |  Left Leg  | 0            |            |              |
|   total    | 0            |            |              |            |              |
[06/16 13:21:14 d2.data.build]: Distribution of instances among all 5 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
| Right Arm  | 0            | Right Leg  | 0            |    Head    | 0            |
|  Left Arm  | 0            |  Left Leg  | 0            |            |              |
|   total    | 0            |            |              |            |              |
Traceback (most recent call last):

  File "G:\CS\DL\CHY\detectron2\tools\train.py", line 245, in <module>
    args=(args,),

  File "G:\CS\DL\CHY\detectron2\detectron2\engine\launch.py", line 82, in launch
    main_func(*args)

  File "G:\CS\DL\CHY\detectron2\tools\train.py", line 227, in main
    trainer = Trainer(cfg)

  File "G:\CS\DL\CHY\detectron2\detectron2\engine\defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)

  File "G:\CS\DL\CHY\detectron2\detectron2\engine\defaults.py", line 547, in build_train_loader
    return build_detection_train_loader(cfg)

  File "G:\CS\DL\CHY\detectron2\detectron2\config\config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)

  File "G:\CS\DL\CHY\detectron2\detectron2\config\config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)

  File "G:\CS\DL\CHY\detectron2\detectron2\data\build.py", line 350, in _train_loader_from_config
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,

  File "G:\CS\DL\CHY\detectron2\detectron2\data\build.py", line 278, in get_detection_dataset_dicts
    assert len(dataset_dicts), "No valid data found in {}.".format(",".join(names))

AssertionError: No valid data found in my_train.
```

By the way, I already checked https://github.com/facebookresearch/detectron2/issues/2907#issue-857664755
And I took a look at my .json file, my polygen is like :
{"segmentation": [[2278, 1461, 2278, 1776, 3283, 1776, 3283, 1461]], "area": 316575, "iscrowd": 0, "ignore": 0, "image_id": "00006.jpg", "bbox": [2278, 1461, 1005, 315], "category_id": 1, "id": 1}
I think it looks correct
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Environment:

```
sys.platform            win32
Python                  3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)]
numpy                   1.21.6
detectron2              0.6 @g:\cs\dl\chy\detectron2\detectron2
Compiler                MSVC 192930141
CUDA compiler           CUDA 11.6
detectron2 arch flags   g:\cs\dl\chy\detectron2\detectron2\_C.cp37-win_amd64.pyd; cannot find cuobjdump
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.2 @D:\Anaconda\envs\maskrcnn\lib\site-packages\torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce RTX 2060 SUPER (arch=7.5)
Driver version          511.65
CUDA_HOME               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
Pillow                  9.0.1
torchvision             0.9.2 @D:\Anaconda\envs\maskrcnn\lib\site-packages\torchvision
torchvision arch flags  D:\Anaconda\envs\maskrcnn\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.5.post20220512
iopath                  0.1.9
cv2                     Not found
----------------------  -----------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930040
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
```

**Comment by LexTran** [comment]
It turns out that my .json got sth. wrong, I use another way to generate it, and it works

**Comment by kevinma0522** [comment]
Hey how did you end up fixing the error? I Got the same exact thing in my code.

**Comment by LexTran** [comment]
> Hey how did you end up fixing the error? I Got the same exact thing in my code.

Hi! From how I fix it, I strongly suggest you check out your annotation file, in my case, I read the .json file line by line, and I found out that the 'image_id' in 'annotations' part is different from those in 'images' part, this is a .json that detectron2 can work with, you can check it out to see which part of your .json is wrong
[annotations.zip](https://github.com/facebookresearch/detectron2/files/8923614/annotations.zip)

**Comment by andywuod3245** [comment]
Hi ! I have the same problem , I'm running GNN model , when I change the dataset to mine ，and how did you create [annotations.zip]

**Comment by LexTran** [comment]
> Hi ! I have the same problem , I'm running GNN model , when I change the dataset to mine ，and how did you create [annotations.zip]
My origin labels are .xml files, I just search on Google how to transform .xml labels to COCO labels, nothing special, u can search how to change ur labels into COCO labels
