### ISSUE TITLE
Error while using a custom dataset mapper for 7-channel images

### ISSUE THREAD

**Issue by ddlabgit** [facebookresearch/detectron2#4347]
Hello

Im trying to train an instance segmentation model using 7-channel images.
As asked in [#2062](https://github.com/facebookresearch/detectron2/issues/2062) 
Of course I followed the Data loading tutorial and take care of the size of the MEAN and STD vectors
According to the tutorial I simply changed the library for the image reading, not PIL but TIFF, but I'm still not able to make it work

The error says:
>File "c:\users\uni bonn\detectron2\detectron2\data\common.py", line 235, in __iter__ 
> w, h = d["width"], d["height"]
> KeyError: 'width' 

I suspect the problem is that the mapping function, in the 'Instances' attribute is returning the wrong value of the Dict, probably only the annotations but not the width info that is in the same level of the file_name. 

This is the data format:
`{
	"test0": {
		"file_name": "0.tif",
		"height": 512,
		"width": 512,
		"image_id": "0",
		"annotations": [
			{
				"bbox": [
					134.0,
					43.0,
					9.0,
					9.0
				],
				"bbox_mode": "BoxMode.XYWH_ABS",
				"category_id": 0,
				"segmentation": [
					[
						[
							139,
							56
						],
						[...`

For now I'm not trying to do any augmentation. Just making the net able to receive the image as input for training, so I used the code as in teh tutorial.

The code and error goes at follows:

```
imgSize = 512

def custom_mapper(dataset_dict):
    dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below
    # can use other ways to read image
    image = tiff.imread(dataset_dict["file_name"])
    # See "Data Augmentation" tutorial for details usage
    auginput = T.AugInput(image)
    transform = T.Resize((800, 800))(auginput)
    image = torch.from_numpy(auginput.image.transpose(2, 0, 1))
    annos = [
        utils.transform_instance_annotations(annotation, [transform], image.shape[1:])
        for annotation in dataset_dict.pop("annotations")
    ]
    return {
       # create the format that the model expects
       "image": image,
       "instances": utils.annotations_to_instances(annos, image.shape[1:])
    }

class Trainer(DefaultTrainer):

    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=custom_mapper)

    
def setup():
    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
    cfg.DATASETS.TRAIN = ("circles_train",)
    cfg.DATASETS.TEST = ()
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.SOLVER.BASE_LR = 0.00025
    cfg.SOLVER.MAX_ITER = 400
    cfg.SOLVER.STEPS = []
    cfg.MODEL.WEIGHTS = ""
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
    cfg.INPUT.MIN_SIZE_TRAIN = imgSize
    cfg.INPUT.MAX_SIZE_TRAIN = imgSize
    cfg.INPUT.MASK_FORMAT = "polygon"
    cfg.MODEL.PIXEL_MEAN = [1, 1, 1, 1, 1, 1, 1]
    cfg.MODEL.PIXEL_STD = [1, 1, 1, 1, 1, 1, 1]
    return cfg

cfg = setup()
trainer = Trainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()
```

> [06/21 14:28:36 d2.data.build]: Removed 0 images with no usable annotations. 5000 images left.
> [06/21 14:28:36 d2.data.build]: Using training sampler TrainingSampler
> [06/21 14:28:36 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
> [06/21 14:28:36 d2.data.common]: Serialized dataset takes 25.49 MiB
> [06/21 14:28:36 d2.engine.train_loop]: Starting training from iteration 0
> ERROR [06/21 14:28:59 d2.engine.train_loop]: Exception during training:
> Traceback (most recent call last):
>   File "c:\users\uni bonn\detectron2\detectron2\engine\train_loop.py", line 149, in train
>     self.run_step()
>   File "c:\users\uni bonn\detectron2\detectron2\engine\defaults.py", line 494, in run_step
>     self._trainer.run_step()
>   File "c:\users\uni bonn\detectron2\detectron2\engine\train_loop.py", line 267, in run_step
>     data = next(self._data_loader_iter)
>   File "c:\users\uni bonn\detectron2\detectron2\data\common.py", line 235, in __iter__
>     w, h = d["width"], d["height"]
> KeyError: 'width'
> [06/21 14:28:59 d2.engine.hooks]: Total training time: 0:00:22 (0:00:00 on hooks)
> [06/21 14:28:59 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 1247M
> ...

> File c:\users\uni bonn\detectron2\detectron2\data\common.py:235, in AspectRatioGroupedDataset.__iter__(self)
>     233 def __iter__(self):
>     234     for d in self.dataset:
> --> 235         w, h = d["width"], d["height"]
>     236         bucket_id = 0 if w > h else 1
>     237         bucket = self._buckets[bucket_id]
> KeyError: 'width

Thanks for the help

**Comment by liviazampereti** [comment]
Hello [ddlabgit](https://github.com/ddlabgit), did you manage to resolve the problem? Because I'm having the same issue and don't know how to figure it out.

**Comment by erik856** [comment]
I am working with a 5 band images and I am having the same issue. Were you able to make the code work?
