### ISSUE TITLE
FCOS model doesn't support train or eval using benchmark.py

### ISSUE THREAD

**Issue by xuzhao9** [facebookresearch/detectron2#4369]
## Instructions To Reproduce the 🐛 Bug:
```
# on the latest main branch
$ python3 tools/benchmark.py --task train --config-file configs/COCO-Detection/fcos_R_50_FPN_1x.py
Traceback (most recent call last):
  File "tools/benchmark.py", line 198, in <module>
    launch(f, args.num_gpus, args.num_machines, args.machine_rank, args.dist_url, args=(args,))
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/benchmark.py", line 100, in benchmark_train
    model = build_model(cfg)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    meta_arch = cfg.MODEL.META_ARCHITECTURE
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key MODEL
    full_key: MODEL
    object_type=dict
```
```
$ python3 tools/benchmark.py --task eval --config-file configs/COCO-Detection/fcos_R_50_FPN_1x.py
Traceback (most recent call last):
  File "tools/benchmark.py", line 197, in <module>
    launch(f, args.num_gpus, args.num_machines, args.machine_rank, args.dist_url, args=(args,))
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/benchmark.py", line 144, in benchmark_eval
    model = instantiate(cfg.model)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 77, in instantiate
    return cls(**cfg)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/modeling/meta_arch/fcos.py", line 285, in __init__
    super().__init__(input_shape=input_shape, conv_dims=conv_dims, num_anchors=1, **kwargs)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/config/config.py", line 192, in wrapped
    init_func(self, *args, **kwargs)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/modeling/meta_arch/retinanet.py", line 356, in __init__
    norm_name = str(type(get_norm(norm, 1)))
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/layers/batch_norm.py", line 148, in get_norm
    return norm(out_channels)
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/detectron2/layers/batch_norm.py", line 141, in <lambda>
    "GN": lambda channels: nn.GroupNorm(32, channels),
  File "/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 252, in __init__
    raise ValueError('num_channels must be divisible by num_groups')
ValueError: num_channels must be divisible by num_groups
```

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:
Provide your environment information using the following command:
```
----------------------  ----------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
numpy                   1.21.2
detectron2              0.6 @/fsx/users/xzhao9/detectron2/detectron2
detectron2._C           not built correctly: No module named 'detectron2._C'
Compiler ($CXX)         c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA compiler           Build cuda_11.3.r11.3/compiler.29920130_0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.13.0.dev20220629+cu113 @/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA A100-SXM4-40GB (arch=8.0)
Driver version          510.47.03
CUDA_HOME               /usr/local/cuda-11.3
TORCH_CUDA_ARCH_LIST    6.0;6.1;6.2;7.0;7.2;8.0;8.6
Pillow                  8.4.0
torchvision             0.14.0.dev20220629+cu113 @/data/home/xzhao9/cluster/miniconda3/envs/py38/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20211023
iopath                  0.1.9
cv2                     4.4.0
----------------------  ----------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
```

**Comment by lbin** [comment]
Try this MR #4470
