### ISSUE TITLE
setup.py treats torch as a setup-time dependency

### ISSUE THREAD

**Issue by DenisKuplyakov** [facebookresearch/detectron2#4472]
## Instructions To Reproduce the 🐛 Bug:
1. create fresh virtualenv with python 3.8.5
2. run `pip install pip==22.2.2`
3. create requirements.txt file:

```
torch
torchvision
detectron2 @ git+https://github.com/facebookresearch/detectron2.git
```

4. run `pip install -r requirements.txt`
5. you will get an error

```
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-install-et917ffp/detectron2_f3545bf0ffe44ebcbd7f1785148fbfef
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-et917ffp/detectron2_f3545bf0ffe44ebcbd7f1785148fbfef
  Resolved https://github.com/facebookresearch/detectron2.git to commit 5aeb252b194b93dc2879b4ac34bc51a31b5aee13
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-et917ffp/detectron2_f3545bf0ffe44ebcbd7f1785148fbfef/setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Expected behavior:

Package should be installed successfully.

## Root of the problem:

setup.py checks minimal torch version [here](https://github.com/facebookresearch/detectron2/blob/main/setup.py#L14) by importing it. This requires torch to be not just runtime dependency, but also a setup-time dependency. Instead minimal torch version should be declared via `install_requires` (if its possible to avoid importing torch on installation) or torch should be declared as a setup-time dependency [this way](https://peps.python.org/pep-0518/#build-system-table). 

## Workaround:
Install everything, except detectron2, then install detectron2.

``` shell
pip3 install --no-cache-dir --no-deps -r <(grep -vE '^detectron2' requirements.txt) && \
pip3 install --no-cache-dir --no-deps -r <(grep -E '^(detectron2|--find-links)' requirements.txt)
```

**Comment by technicalpickles** [comment]
I found a manual way to run this:

- git clone https://github.com/facebookresearch/detectron2.git
- cd detectron2/docs
- edut requirements.txt to remove hard-coded pytorch and torchvision
- pip install pytorch torchvision
- pip install -r requirements.txt
- cd ..
- python setup.py build
- python setup.py install

I think I needed to manual build and install fvcore as well, but didn't keep track of the commands for that.

**Comment by bertsky** [comment]
> * cd detectron2/docs
> * edit requirements.txt to remove hard-coded pytorch and torchvision

Why `./docs`? AFAICS this is merely for building the documentation.

Manual installation **does work** as [instructed](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) – first get torch, then install the detectron2 pkg.

The real problem is with direct pip installation of detectron2 **as a dependency** in other projects.

Also, if you want **CUDA support** (for your specific version of CUDA), you may need to go one step further, because IIUC:
- Pytorch [uses its own, non-PyPI pkg indexes](https://pytorch.org/get-started/locally/#start-locally) for pip-only installation
- Detectron2 gets compiled and dynamically linked to that version of Pytorch, so replacing CUDA or Pytorch with different versions later-on will break Detectron2 at runtime
- Detecting the current CUDA version _programmatically_ is not so trivial (as there are multiple methods, depending on your OS/installation)
- Sometimes you get lucky and there is a prebuilt wheel for your platform; falling back from wheels to source installation on a git repo is not properly supported by pip, though; also, it seems that very recently FB stopped running their [wheel archive server](https://dl.fbaipublicfiles.com/detectron2/wheels/cu118/torch1.10/index.html)

So here's what I do (programmatically):

```sh
        if test -n "$CUDA_VERSION"; then :; \
        elif test -s /usr/local/cuda/version.txt; then \
                CUDA_VERSION=$(sed 's/^.* //;s/\([0-9]\+[.][0-9]\).*/\1/' /usr/local/cuda/version.txt); \
        elif command -v nvcc &>/dev/null; then \
                CUDA_VERSION=$(nvcc --version | sed -n '/^Cuda/{s/.* release //;s/,.*//;p;}'); \
        elif command -v nvidia-smi &>/dev/null; then \
                CUDA_VERSION=$(nvidia-smi | sed -n '/CUDA Version/{s/.*CUDA Version: //;s/ .*//;p;}'); \
        elif command -v pkg-config &>/dev/null; then \
                CUDA_VERSION=$(pkg-config --list-all | sed -n '/^cudart/{s/cudart-//;s/ .*//;p;q;}'); \
        fi && \
        if test -z "$CUDA_VERSION"; then \
                echo "Cannot find CUDA runtime library, assuming CPU-only"; CUDA_VERSION=CPU; \
        fi && echo "Detected CUDA version: $CUDA_VERSION" && \
        if test "$CUDA_VERSION" = CPU; then CUDA=cpu; \
        else IFS=. CUDA=($CUDA_VERSION) && CUDA=cu${CUDA[0]}${CUDA[1]}; \
        fi && \
        pip install -i "https://download.pytorch.org/whl/$CUDA" torch torchvision  && \
        pip install "git+https://github.com/facebookresearch/detectron2@v0.6#egg=detectron2==0.6"
```

**Comment by bertsky** [comment]
BTW, #4868 will make life easier in the current software environment, but the core issue (torch as an implicit setup-time dependency) is still not addressed.

**Comment by johnnynunez** [comment]
> Por cierto, #4868 hará la vida más fácil en el entorno de software actual, pero el problema central (la antorcha como una dependencia implícita del tiempo de configuración) aún no se aborda.

in case of requirements is: 
```
torch==2.0.1+cu118; sys_platform != 'darwin'
torch==2.0.1; sys_platform == 'darwin'
onnxruntime==1.15.0; sys_platform == 'darwin' and platform_machine != 'arm64'
onnxruntime-silicon==1.13.1; sys_platform == 'darwin' and platform_machine == 'arm64'
onnxruntime-gpu==1.15.0; sys_platform != 'darwin'
```
