### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\coco/annotations/instances_val2017.json'

### ISSUE THREAD

**Issue by sagarkalburgi** [facebookresearch/detectron2#4532]
## Instructions To Reproduce the Issue:

Code in question:

```
train_image_path = "path/to/train/images"
val_image_path = "path/to/val/images"
test_image_path = "path/to/test/images"
train_json = "path/to/train/images/train.json"
val_json = "path/to/val/images/val.json"
test_json = "path/to/test/images/val.json"

from detectron2.data.datasets import register_coco_instances
register_coco_instances("custom_train", {}, train_json, train_image_path)
register_coco_instances("custom_val", {}, val_json, val_image_path)
register_coco_instances("custom_test", {}, test_json, test_image_path)

windows_metadata = MetadataCatalog.get("custom_train")
dataset_dicts = DatasetCatalog.get("custom_train")

class CocoTrainer(DefaultTrainer):

  @classmethod
  def build_evaluator(cls, cfg, dataset_name, output_folder=None):

    if output_folder is None:
        os.makedirs("custom_val", exist_ok=True)
        output_folder = "custom_val"

    return COCOEvaluator(dataset_name, cfg, False, output_folder)

if __name__ == "__main__":

    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
    cfg.DATASETS.TRAIN = ("custom_train",)
    cfg.DATASETS.VAL = ("custom_val",)
    cfg.DATALOADER.NUM_WORKERS = 4
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml")  # Let training initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 4
    cfg.SOLVER.BASE_LR = 0.001
    cfg.SOLVER.WARMUP_ITERS = 250
    cfg.SOLVER.MAX_ITER = 10000
    cfg.SOLVER.STEPS = (4000, 6000, 8500)
    cfg.SOLVER.GAMMA = 0.05
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 16
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
    cfg.TEST.EVAL_PERIOD = 25
    # cfg.MODEL.BACKBONE.FREEZE_AT = 5

    cfg.OUTPUT_DIR = "path/to/output"
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

    trainer = CocoTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()
```

The following error pops up:
```
Traceback (most recent call last):
  File "d:\detectron2\detectron2\engine\train_loop.py", line 150, in train
    self.after_step()
  File "d:\detectron2\detectron2\engine\train_loop.py", line 180, in after_step
    h.after_step()
  File "d:\detectron2\detectron2\engine\hooks.py", line 555, in after_step
    self._do_eval()
  File "d:\detectron2\detectron2\engine\hooks.py", line 528, in _do_eval
    results = self._func()
  File "d:\detectron2\detectron2\engine\defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "d:\detectron2\detectron2\engine\defaults.py", line 602, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "d:\detectron2\detectron2\engine\defaults.py", line 558, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "d:\detectron2\detectron2\config\config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "d:\detectron2\detectron2\config\config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "d:\detectron2\detectron2\data\build.py", line 449, in _test_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "d:\detectron2\detectron2\data\build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "d:\detectron2\detectron2\data\build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "d:\detectron2\detectron2\data\catalog.py", line 58, in get
    return f()
  File "d:\detectron2\detectron2\data\datasets\coco.py", line 500, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "d:\detectron2\detectron2\data\datasets\coco.py", line 69, in load_coco_json
    coco_api = COCO(json_file)
  File "D:\Users\KalburgS\Anaconda3\envs\detectron_env\lib\site-packages\pycocotools\coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\coco/annotations/instances_val2017.json'
```

I tried `cfg.DATASETS.VAL = ()` as per #2012, but it didn't work either and I kept getting the same error. I had used the same code to train a model a couple of weeks ago, but now it seems to be popping this error.

## Environment:
```
(detectron_env) D:\detectron2>wget -nc -nv https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
2022-09-07 21:37:41 URL:https://raw.githubusercontent.com/facebookresearch/detectron2/main/detectron2/utils/collect_env.py [8391/8391] -> "collect_env.py" [1]
----------------------  ----------------------------------------------------------------------------------------------------------
sys.platform            win32
Python                  3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
numpy                   1.22.3
detectron2              0.6 @D:\detectron2\detectron2
detectron2._C           not built correctly: DLL load failed while importing _C: The specified procedure could not be found.
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu101 @D:\Users\KalburgS\Anaconda3\envs\detectron_env\lib\site-packages\torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   Quadro RTX 5000 (arch=7.5)
Driver version          512.15
CUDA_HOME               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
Pillow                  9.0.1
torchvision             0.9.1+cu101 @D:\Users\KalburgS\Anaconda3\envs\detectron_env\lib\site-packages\torchvision
torchvision arch flags  D:\Users\KalburgS\Anaconda3\envs\detectron_env\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                  0.1.5.post20220512
iopath                  0.1.9
cv2                     4.6.0
----------------------  ----------------------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
```

**Comment by RuiMingGao** [comment]
if you run the code in linux shell, you can try **export DETECTRON2_DATASETS=/path/to/your/dataset** in shell to fix this.
It will relocate the dataset location to your own location

**Comment by sagarkalburgi** [comment]
Thanks for the reply

> if you run the code in linux shell, you can try **export DETECTRON2_DATASETS=/path/to/your/dataset** in shell to fix this. It will relocate the dataset location to your own location

Thanks for the reply. But it ran successfully with any error the next day. Not sure what was the issue.
