### ISSUE TITLE
MacOS mps issue

### ISSUE THREAD

**Issue by darren-pei** [facebookresearch/detectron2#4575]
Hi

I'm running a model over the docbank dataset, just trying to replicate their results on my Mac.  I can run the model over the CPU without any issues, but when I switch to mps I get a torch exception.  At this stage I'm not sure if the issue is caused by torch or detectron2 (note that I'm using the nightly build of torch):

1. Full runnable code or full changes you made:
```
    from detectron2.config import get_cfg 
    from detectron2.engine import DefaultTrainer
    trainer = DefaultTrainer(cfg)
    trainer.train()

Config:
  _BASE_: "../models/Base-RCNN-FPN.yaml"
  MODEL:
    DEVICE: 'mps'
    WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
    MASK_ON: False
    PIXEL_STD: [57.375, 57.120, 58.395]
    RESNETS:
      STRIDE_IN_1X1: False  # this is a C2 model
      NUM_GROUPS: 32
      WIDTH_PER_GROUP: 8
      DEPTH: 101
    ROI_HEADS:
      NUM_CLASSES: 13
  SOLVER:
    STEPS: (24800, 27900)
    MAX_ITER: 31000
    IMS_PER_BATCH: 12
    BASE_LR: 0.015125
  DATASETS:
    TRAIN: ("docbank_train",)
    TEST: ("docbank_test",)
  DATALOADER:
    NUM_WORKERS: 1
  OUTPUT_DIR: "X101"

```
3. __Full logs__ or other relevant observations:
```
[09/28 08:55:44 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[09/28 08:55:44 d2.data.build]: Using training sampler TrainingSampler
[09/28 08:55:44 d2.data.common]: Serializing 399768 elements to byte tensors and concatenating them all ...
[09/28 08:55:47 d2.data.common]: Serialized dataset takes 255.14 MiB
[09/28 08:55:48 d2.engine.train_loop]: Starting training from iteration 0
WARNING:root:Pytorch pre-release version 1.13.0.dev20220927 - assuming intent to test it
WARNING:root:Pytorch pre-release version 1.13.0.dev20220927 - assuming intent to test it
1.13.0.dev20220927 False
/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torch/functional.py:500: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1664262542565/work/aten/src/ATen/native/TensorShape.cpp:3150.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
ERROR [09/28 08:56:13 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 274, in run_step
    loss_dict = self.model(data)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 471, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 339, in label_and_sample_anchors
    match_quality_matrix = retry_if_cuda_oom(pairwise_iou)(gt_boxes_i, anchors)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2/structures/boxes.py", line 353, in pairwise_iou
    iou = torch.where(
RuntimeError: All inputs of where should have same/compatible number of dims
```

## Expected behaviour:

The model runs (albeit very slowly) on the cpu.

## Environment:

Provide your environment information using the following command:
```
sys.platform           darwin
Python                 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]
numpy                  1.23.1
detectron2             0.6 @/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/detectron2
Compiler               clang 13.1.6
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.13.0.dev20220927 @/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torch
PyTorch debug build    False
GPU available          No: torch.cuda.is_available() == False
Pillow                 9.2.0
torchvision            0.14.0.dev20220927 @/Users/darrenthorpe/opt/anaconda3/envs/pytorch-p39/lib/python3.10/site-packages/torchvision
fvcore                 0.1.5.post20220512
iopath                 0.1.9
cv2                    Not found
---------------------  ---------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 13.1.6
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201811
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1664262542565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -DUSE_COREML_DELEGATE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=mkl, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 


```

**Comment by darren-pei** [comment]
Separate issue logged
