### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RUiSss** [facebookresearch/detectron2#459]
2. what exact command you run:
```
python demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml  --input 0.jpg 3.jpg --output /home/amax/iKang/dsr/Project/det2/output --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
```
3. what you observed (including the full logs):
```
[12/04 17:37:01 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml', input=['0.jpg', '3.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'], output='/home/amax/iKang/dsr/Project/det2/output', video_input=None, webcam=False)
WARNING [12/04 17:37:01 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
  0%|                                                                                                                           | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "demo/demo.py", line 85, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/amax/iKang/dsr/Project/det2/demo/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/amax/iKang/dsr/Project/det2/detectron2/engine/defaults.py", line 188, in __call__
    predictions = self.model([inputs])[0]
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/meta_arch/rcnn.py", line 66, in forward
    return self.inference(batched_inputs)
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/meta_arch/rcnn.py", line 119, in inference
    proposals, _ = self.proposal_generator(images, features, None)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/proposal_generator/rpn.py", line 179, in forward
    self.training,
  File "/home/amax/iKang/dsr/Project/det2/detectron2/modeling/proposal_generator/rpn_outputs.py", line 136, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
  File "/home/amax/iKang/dsr/Project/det2/detectron2/layers/nms.py", line 17, in batched_nms
    return box_ops.batched_nms(boxes, scores, idxs, iou_threshold)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 72, in batched_nms
    keep = nms(boxes_for_nms, scores, iou_threshold)
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 32, in nms
    _C = _lazy_import()
  File "/home/amax/anaconda3/envs/detpy369/lib/python3.6/site-packages/torchvision/extension.py", line 12, in _lazy_import
    from torchvision import _C as C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

```

**Comment by enric1994** [comment]
Which CUDA version do you have?  It should be 10.1
You can check it with: `nvcc --version`

**Comment by ppwwyyxx** [comment]
Closing as it's a torchvision installation issue and not related to detectron2.
