### ISSUE TITLE
Unable to train new baselines while filter_empty = false

### ISSUE THREAD

**Issue by alrightkami** [facebookresearch/detectron2#4616]
Hello there, I've noticed that as soon as I add the following line in my config.py, training crashes:
`dataloader.train.dataset.filter_empty = False`

The line I'm running:
`tools/lazyconfig_train_net.py --config-file configs/new_baselines/mask_rcnn_R_50_FPN_100ep.py`

Logs:
```
[32m[10/24 13:03:50 d2.engine.train_loop]: [0mStarting training from iteration 0
[4m[5m[31mERROR[0m [32m[10/24 13:03:50 d2.engine.train_loop]: [0mException during training:
Traceback (most recent call last):
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/engine/train_loop.py", line 409, in run_step
    data = next(self._data_loader_iter)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 234, in __iter__
    for d in self.dataset:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 438, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/dataset_mapper.py", line 189, in __call__
    self._transform_annotations(dataset_dict, transforms, image_shape)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/dataset_mapper.py", line 141, in _transform_annotations
    instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/structures/instances.py", line 66, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!

[32m[10/24 13:03:50 d2.engine.hooks]: [0mTotal training time: 0:00:00 (0:00:00 on hooks)
[32m[10/24 13:03:50 d2.utils.events]: [0m iter: 0    lr: N/A  max_mem: 181M
Traceback (most recent call last):
  File "tools/lazyconfig_train_net.py", line 159, in <module>
    launch(
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/lazyconfig_train_net.py", line 154, in main
    do_train(args, cfg)
  File "tools/lazyconfig_train_net.py", line 139, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/engine/train_loop.py", line 409, in run_step
    data = next(self._data_loader_iter)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 234, in __iter__
    for d in self.dataset:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 438, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/dataset_mapper.py", line 189, in __call__
    self._transform_annotations(dataset_dict, transforms, image_shape)
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/data/dataset_mapper.py", line 141, in _transform_annotations
    instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
  File "/home/jovyan/data/kamila/detrex/detectron2/detectron2/structures/instances.py", line 66, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_masks' in the given Instances!
```

**Comment by dcy0577** [comment]
Hi did you solve this problem? Do you know how to set up filtering_empty_annotation correctly in lazy config, like in old config cfg.DATALOADER.FILTER_EMPTY_ANNOTATIONS?

**Comment by alrightkami** [comment]
@dcy0577 Hi, no I still struggle with the issue

**Comment by alrightkami** [comment]
@dcy0577 FYI I fixed it in my PR if still relevant for you
