### ISSUE TITLE
OSError: [Errno 113] No route to host

### ISSUE THREAD

**Issue by dongfengxijian** [facebookresearch/detectron2#4625]
Thank you for sharing your excellent work. I trained a project using detectron2 as backbone. But when I trained a model in a machine with 8 GPUs, I met OSError: [Errno 113] No route to host as follow:
![image](https://user-images.githubusercontent.com/24863806/198558338-9ac4a810-7e0e-4e67-b45d-81d7de36a89b.png)
![image](https://user-images.githubusercontent.com/24863806/198558434-840e5caa-99f5-4362-bcb6-e60fa34360a5.png)
I found the error was in the detectron2/detectron2/engine/launch.py. 
I did not enable firewall, which might cause this error.
![image](https://user-images.githubusercontent.com/24863806/198559305-5d9e35c4-4f48-40cc-a392-23f5efc1586d.png)
Now I don't know how to solve it.

**Comment by dongfengxijian** [comment]
I train the multiple object detection project GTR [https://github.com/xingyizhou/GTR](url) which uses detectron2 as backbone. The full logs is as follow：
Traceback (most recent call last):
  File "train_net.py", line 267, in <module>
    launch(
  File "/data/phd/PycharmProjects/detectron2/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/phd/PycharmProjects/detectron2/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/data/phd/PycharmProjects/GTR/train_net.py", line 241, in main
    model = build_model(cfg)
  File "/data/phd/PycharmProjects/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/data/phd/PycharmProjects/detectron2/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/data/phd/PycharmProjects/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/data/phd/PycharmProjects/GTR/gtr/modeling/meta_arch/gtr_rcnn.py", line 35, in from_config
    ret = super().from_config(cfg)
  File "/data/phd/PycharmProjects/GTR/gtr/modeling/meta_arch/custom_rcnn.py", line 91, in from_config
    ret = super().from_config(cfg)
  File "/data/phd/PycharmProjects/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 73, in from_config
    backbone = build_backbone(cfg)
  File "/data/phd/PycharmProjects/detectron2/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/data/phd/PycharmProjects/GTR/third_party/CenterNet2/centernet/modeling/backbone/bifpn.py", line 411, in build_p37_dla_bifpn_backbone
    bottom_up = dla34(cfg)
  File "/data/phd/PycharmProjects/GTR/third_party/CenterNet2/centernet/modeling/backbone/dlafpn.py", line 395, in dla34
    model = DLA(cfg, [1, 1, 1, 2, 2, 1],
  File "/data/phd/PycharmProjects/GTR/third_party/CenterNet2/centernet/modeling/backbone/dlafpn.py", line 221, in __init__
    self.load_pretrained_model(
  File "/data/phd/PycharmProjects/GTR/third_party/CenterNet2/centernet/modeling/backbone/dlafpn.py", line 226, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/hub.py", line 524, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/data/phd/ProgramFiles/anaconda3/envs/gtr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

The environment is as follow:
(gtr) phd@amax:/data/phd/PycharmProjects/GTR$ conda list
# packages in environment at /data/phd/ProgramFiles/anaconda3/envs/gtr:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
absl-py                   1.3.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
black                     22.3.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
boto3                     1.24.96                  pypi_0    pypi
botocore                  1.27.96                  pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cudatoolkit               11.1.1              ha002fc5_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
detectron2                0.6                       dev_0    <develop>
fairscale                 0.4.12                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.8.0                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_0    conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.13.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
huggingface-hub           0.10.1                   pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.22.2                   pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
iopath                    0.1.9                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lap                       0.4.0                    pypi_0    pypi
ld_impl_linux-64          2.39                 hc81fddc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.2.0              h65d4601_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.2.0              h65d4601_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libsqlite                 3.39.4               h753d276_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              12.2.0              h46fd767_18    conda-forge
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   2.32.1            h7f98852_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
lvis                      0.5.3                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
motmetrics                1.2.5                    pypi_0    pypi
moviepy                   0.2.3.5                  pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
natsort                   8.2.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numba                     0.56.3                   pypi_0    pypi
numpy                     1.23.3           py38h14f4228_0    defaults
numpy-base                1.23.3           py38h31eccc5_0    defaults
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
omegaconf                 2.2.3                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
pathspec                  0.10.1                   pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.3               pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
platformdirs              2.5.2                    pypi_0    pypi
portalocker               2.6.0                    pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.5                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.13          ha86cf86_0_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytz                      2022.5                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
script-utils              0.0.1                    pypi_0    pypi
setuptools                65.5.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.4               h4ff8645_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tao                       0.1.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
timm                      0.6.11                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu111    pytorch
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xmltodict                 0.13.0                   pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yacs                      0.1.8                    pypi_0    pypi
youtube-dl                2021.12.17               pypi_0    pypi
zipp                      3.9.0                    pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by dongfengxijian** [comment]
The environment is as follow:

(gtr) phd@amax:/data/phd/PycharmProjects/GTR$ conda list
packages in environment at /data/phd/ProgramFiles/anaconda3/envs/gtr:
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
absl-py                   1.3.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
black                     22.3.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
boto3                     1.24.96                  pypi_0    pypi
botocore                  1.27.96                  pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.9.24                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cudatoolkit               11.1.1              ha002fc5_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
detectron2                0.6                       dev_0    <develop>
fairscale                 0.4.12                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.8.0                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_0    conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.13.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.50.0                   pypi_0    pypi
huggingface-hub           0.10.1                   pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.22.2                   pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
iopath                    0.1.9                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lap                       0.4.0                    pypi_0    pypi
ld_impl_linux-64          2.39                 hc81fddc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.2.0              h65d4601_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.2.0              h65d4601_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libsqlite                 3.39.4               h753d276_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              12.2.0              h46fd767_18    conda-forge
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   2.32.1            h7f98852_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
lvis                      0.5.3                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
motmetrics                1.2.5                    pypi_0    pypi
moviepy                   0.2.3.5                  pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
natsort                   8.2.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
numba                     0.56.3                   pypi_0    pypi
numpy                     1.23.3           py38h14f4228_0    defaults
numpy-base                1.23.3           py38h31eccc5_0    defaults
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
omegaconf                 2.2.3                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
pathspec                  0.10.1                   pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.3               pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
platformdirs              2.5.2                    pypi_0    pypi
portalocker               2.6.0                    pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.5                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.13          ha86cf86_0_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytz                      2022.5                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
script-utils              0.0.1                    pypi_0    pypi
setuptools                65.5.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.4               h4ff8645_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tao                       0.1.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
timm                      0.6.11                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu111    pytorch
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xmltodict                 0.13.0                   pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yacs                      0.1.8                    pypi_0    pypi
youtube-dl                2021.12.17               pypi_0    pypi
zipp                      3.9.0                    pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
