### ISSUE TITLE
Why does 'thing_classes' of custom COCO format dataset always wrong?

### ISSUE THREAD

**Issue by China-EvilDevil** [facebookresearch/detectron2#4655]
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

As a beginner in the field of drone imaging, I encountered some problems when using this model to train the drone data set VisDrone. I hope that experts and scholars can give me some advice.
According to the guidelines for registering custom datasets in detectron2, I registered the VisDrone dataset that has been converted into coco format, and then trained on this model. Then unexpectedly there were some problems that bothered me.

My code to register the VisDrone dataset is as follows:
detectron2/detectron2/data/datasets/builtin.py

```
##===============Register a custom dataset================##
from detectron2.data.datasets import register_coco_instances
register_coco_instances("Visdrone_2017_train", {},
json_file=r"/home/huangxiaokai/code/project/
SparseInst- main/datasets/VisDrone/annotations/instances_train2017.json",
image_root = r"/home/huangxiaokai/code/project/SparseInst-main/datasets/VisDrone/train2017")
register_coco_instances("Visdrone_2017_val", {},
r"/home/huangxiaokai/code/project/SparseInst-main/datasets/VisDrone/annotations/instances_val2017.json",
r"/home/huangxiaokai/code/project/SparseInst-main/datasets/VisDrone/val2017")

#set category
from detectron2.data import MetadataCatalog
MetadataCatalog.get("Visdrone_2017_train").thing_classes = ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck',
'tricycle', 'awning-tricycle', 'bus', 'motor']
MetadataCatalog.get("Visdrone_2017_val").thing_classes = ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck',
'tricycle', 'awning-tricycle', 'bus', 'motor']
##================ END =========================##
```
I also set NUM_CLASSES=10.

2. What exact command you run:
I just wanted to train the model on the VisDrone dataset, ran detectron2/tools/train_net.py

3. __Full logs__ or other relevant observations:
```
[11/12 09:15:46 d2.data.datasets.coco]: Loading /home/huangxiaokai/code/project/SparseInst-main/datasets/VisDrone/annotations/instances_train2017.json takes 1.33 seconds.
Traceback (most recent call last):
  File "/home/huangxiaokai/code/project/SparseInst-main/tools/train_net.py", line 182, in <module>
    launch(
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/home/huangxiaokai/code/project/SparseInst-main/tools/train_net.py", line 174, in main
    trainer = Trainer(cfg)
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/huangxiaokai/code/project/SparseInst-main/tools/train_net.py", line 144, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/build.py", line 344, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/datasets/coco.py", line 500, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/datasets/coco.py", line 80, in load_coco_json   
    meta.thing_classes = thing_classes
  File "/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2/data/catalog.py", line 148, in __setattr__
    assert oldval == val, (
AssertionError: Attribute 'thing_classes' in the metadata of 'Visdrone_2017_train' cannot be set to a different value!
['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor'] != ['pedestrain', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor']

```
What I don't understand is that in the error prompted, the content on the left and right sides of the equal sign is exactly the same, that is, the registered data set category is the same as the imported one, how can there be an unequal situation?

## Environment:

```
[11/12 09:15:42 detectron2]: Environment info:
----------------------  ----------------------------------------------------------------------------------
sys.platform            linux
Python                  3.9.12 (main, Apr  5 2022, 06:56:58) [GCC 7.5.0]
numpy                   1.23.4
detectron2              0.6 @/home/huangxiaokai/code/project/SparseInst-main/detectron2/detectron2
Compiler                GCC 9.5
CUDA compiler           CUDA 11.3
detectron2 arch flags   8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.13.0+cu117 @/home/huangxiaokai/anaconda3/lib/python3.9/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce RTX 3090 (arch=8.6)
Driver version          515.65.01
CUDA_HOME               /usr/local/cuda
Pillow                  9.0.1
torchvision             0.14.0+cu117 @/home/huangxiaokai/anaconda3/lib/python3.9/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220512
iopath                  0.1.7
cv2                     4.6.0
----------------------  ----------------------------------------------------------------------------------

```

I hope that experts and scholars can give answers and suggestions, thank you very much!

**Comment by ppwwyyxx** [comment]
> What I don't understand is that in the error prompted, the content on the left and right sides of the equal sign is exactly the same,

No, they are not the same. `pedestrian` is misspelled.
