### ISSUE TITLE
AssertionError: assert "proposals" in batched_inputs[0]  when using demo.py for detection 

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/detectron2#482]
## Instructions To Reproduce the Issue 

1. what changes you made (`git diff`) or what code you wrote
```
**NO**
```
2. what exact command you run:
```
python tools/demo.py \
      --config-file configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml \
      --input input2.jpg --output outputs \
      --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl
```
3. what you observed (including the full logs):
```
[12/08 20:55:27 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml', input=['input2.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl'], output='outputs', video_input=None, webcam=False)
WARNING [12/08 20:55:27 d2.config.compat]: Config 'configs/COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/csf/visualize/demo.py", line 83, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/data/csf/visualize/predictor.py", line 48, in run_on_image
    predictions = self.predictor(image)
  File "/data/csf/anaconda3/envs/pytorch13/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/data/csf/detectron2/detectron2/engine/defaults.py", line 188, in __call__
    predictions = self.model([inputs])[0]
  File "/data/csf/anaconda3/envs/pytorch13/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/csf/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 66, in forward
    return self.inference(batched_inputs)
  File "/data/csf/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 121, in inference
    assert "proposals" in batched_inputs[0]
AssertionError

Process finished with exit code 1
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior
get detection visualization

## Environment
```
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Oct 25 2019, 15:51:11) [GCC 7.3.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1                   GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.168
Pillow                    6.2.1
cv2                       4.1.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
Fast R-CNN needs object proposals provided by other independent algorithm, and therefore does not work on any arbitrary images.
