### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by GiovanniPasq** [facebookresearch/detectron2#484]
i trained mask rcnn with 1280x720 images, and when i try to call inference_on_dataset i have the following error (testset images have the same size 1280x720)

inference_on_dataset(trainer.model, val_loader, evaluator)

3 frames
/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
    383             # (https://bugs.python.org/issue2651), so we work around it.
    384             msg = KeyErrorMessage(msg)
--> 385         raise self.exc_type(msg)

SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/detectron2_repo/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/detectron2_repo/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/detectron2_repo/detectron2/data/dataset_mapper.py", line 75, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/content/detectron2_repo/detectron2/data/detection_utils.py", line 85, in check_image_size
    expected_wh,
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image ./drive/My Drive/dataset/Real_frame_object_detector_Bellomo/Test/Test8/40410.jpg, got (1280, 720), expect (924, 710)

**Comment by morestart** [comment]
Can you tell me how you solved the problem？
I have the  problem too..

**Comment by Jayshah25** [comment]
I am facing the same problem.
The issue vanishes sometimes when you re run the file but that's not a solution!

**Comment by morestart** [comment]
check your image size... use another annotation software. I use RectLabel to solve this problem

**Comment by Jayshah25** [comment]
Actually, there were issues with the size of some images.
