### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by Utkarsha666** [facebookresearch/detectron2#4923]
System config:
GPU:- GTX 1650
RAM:- 8GB
CUDA 11.2
Python = 3.9

I installed the torch with
`pip install --upgrade torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1
 -f https://download.pytorch.org/whl/torch_stable.html`

cloned a git repository and typed in my newly created conda environment.
`pip install --upgrade torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1
 -f https://download.pytorch.org/whl/torch_stable.html`

then as instructed 
`python -m pip install -e detectron2-computer-vision`

i got the following error:-

` C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
        ROIAlignRotated_cuda.cu
        D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py:370: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
          warnings.warn(f'Error checking compiler version for {compiler}: {error}')
        error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin\\nvcc.exe' failed with exit code 2
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [762 lines of output]
    running develop
    running egg_info
    writing detectron2.egg-info\PKG-INFO
    writing dependency_links to detectron2.egg-info\dependency_links.txt
    writing requirements to detectron2.egg-info\requires.txt
    writing top-level names to detectron2.egg-info\top_level.txt
    reading manifest file 'detectron2.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'detectron2.egg-info\SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DWITH_CUDA "-ID:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc" -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -ID:\anaconda3\envs\detectron2\include -ID:\anaconda3\envs\detectron2\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc "/TpD:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cpu.cpp" "/Fobuild\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cpu.obj" /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
    ROIAlignRotated_cpu.cpp
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(183): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
            with
            [
                T=at::Tensor
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(367): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
            with
            [
                T=at::Tensor
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
            with
            [
                T=at::Tensor
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to alias template instantiation 'c10::OptionalBase<T>' being compiled
            with
            [
                T=at::Tensor
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\ATen/core/TensorBody.h(734): note: see reference to class template instantiation 'c10::optional<at::Tensor>' being compiled
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(395): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
            with
            [
                T=at::Tensor
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(183): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
            with
            [
                T=at::Generator
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(367): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
            with
            [
                T=at::Generator
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
            with
            [
                T=at::Generator
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to alias template instantiation 'c10::OptionalBase<T>' being compiled
            with
            [
                T=at::Generator
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\ATen/core/TensorBody.h(800): note: see reference to class template instantiation 'c10::optional<at::Generator>' being compiled
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(395): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
            with
            [
                T=at::Generator
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(183): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(367): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\include\c10/util/Optional.h(427): note: see reference to alias template instantiation 'c10::OptionalBase<T>' being compiled
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]`

`.................................................................................................................................................................`
` C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
    ROIAlignRotated_cuda.cu
    D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py:370: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\bin\\nvcc.exe' failed with exit code 2
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.`

I have tried 2 times creating a new environment but still getting the same error.

I have installed visual studio compiler installed, Is it because of CUDA 11.2? I haven't tried updating my CUDA drivers because on my other environment I am using tensorflow-2.10.

**Comment by Utkarsha666** [comment]
> Had already the same issue, try to see this: https://blog.csdn.net/m0_56192771/article/details/123194532

PROBLEM
I am still facing getting a error, I have changed the file `detectron2\detectron2\layers\csrc\nms_rotated\nms_rotated_cuda.cu` 
as instructed in https://blog.csdn.net/m0_56192771/article/details/123194532

To reproduce the issue:-
`python setup.py build` or 
` python -m pip install -e detectron2-computer-vision`

EXPECTED BEHAVIOUR
successful installation of detectron2 on windows 11


LOGS:-
 ```
FAILED: D:/Computer Vision/detectron2-computer-vision/build/temp.win-amd64-cpython-38/Release/Computer Vision/detectron2-computer-vision/detectron2/layers/csrc/cuda_version.obj
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc --generate-dependencies-with-compile --dependency-output "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\cuda_version.obj".d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-ID:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc" -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -ID:\anaconda3\envs\detectron2\include -ID:\anaconda3\envs\detectron2\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c "D:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\cuda_version.cu" -o "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\cuda_version.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.

    cuda_version.cu

    [6/6] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc --generate-dependencies-with-compile --dependency-output "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.obj".d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-ID:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc" -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -ID:\anaconda3\envs\detectron2\include -ID:\anaconda3\envs\detectron2\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c "D:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.cu" -o "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
    FAILED: D:/Computer Vision/detectron2-computer-vision/build/temp.win-amd64-cpython-38/Release/Computer Vision/detectron2-computer-vision/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.obj
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc --generate-dependencies-with-compile --dependency-output "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.obj".d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-ID:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc" -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\detectron2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -ID:\anaconda3\envs\detectron2\include -ID:\anaconda3\envs\detectron2\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c "D:\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.cu" -o "D:\Computer Vision\detectron2-computer-vision\build\temp.win-amd64-cpython-38\Release\Computer Vision\detectron2-computer-vision\detectron2\layers\csrc\ROIAlignRotated\ROIAlignRotated_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.

    ROIAlignRotated_cuda.cu

    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
        subprocess.run(
      File "D:\anaconda3\envs\detectron2\lib\subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "D:\Computer Vision\detectron2-computer-vision\setup.py", line 147, in <module>
        setup(
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
        self._build_extensions_serial()
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
        self.build_extension(ext)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "D:\anaconda3\envs\detectron2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 549, in build_extension
        objects = self.compiler.compile(
      File "D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "D:\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.


```

**Comment by tkhe** [comment]
I think this may be because your VS version is too new, you can try to modify setup.py by adding `-allow-unsupported-compiler`.
```
extra_compile_args["nvcc"] = [
    "-O3",
    "-DCUDA_HAS_FP16=1",
    "-D__CUDA_NO_HALF_OPERATORS__",
    "-D__CUDA_NO_HALF_CONVERSIONS__",
    "-D__CUDA_NO_HALF2_OPERATORS__",
    "-allow-unsupported-compiler",
]
```
