### ISSUE TITLE
trying to compile detectron but getting error

### ISSUE THREAD

**Issue by Benndova** [facebookresearch/detectron2#4992]
If you do not know the root cause of the problem, please post according to this template:

## Instructions To Reproduce the Issue:
git clone detectron: https://github.com/facebookresearch/detectron2.git
Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

##What exact command you run:
Steps:
git clone detectron: https://github.com/facebookresearch/detectron2.git
cd detectron2
pip install -e .

 results: 
        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
[1/5] /usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o
/usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

3 errors detected in the compilation of "/tmp/tmpxft_00008e9d_00000000-6_ROIAlignRotated_cuda.cpp1.ii".
[2/5] /usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o
/usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

3 errors detected in the compilation of "/tmp/tmpxft_00008e9e_00000000-6_deform_conv_cuda_kernel.cpp1.ii".
[3/5] /usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o
/usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

3 errors detected in the compilation of "/tmp/tmpxft_00008ea1_00000000-6_box_iou_rotated_cuda.cpp1.ii".
[4/5] /usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o
/usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

3 errors detected in the compilation of "/tmp/tmpxft_00008ea3_00000000-6_nms_rotated_cuda.cpp1.ii".
[5/5] /usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o
/usr/bin/nvcc  -DWITH_CUDA -I/home/arl/facebookproj/detectron2/detectron2/layers/csrc -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/TH -I/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/THC -I/home/arl/anaconda3/envs/mask/include/python3.8 -c -c /home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o /home/arl/facebookproj/detectron2/build/temp.linux-x86_64-cpython-38/home/arl/facebookproj/detectron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

/usr/include/c++/8/utility(329): error: identifier "__integer_pack" is undefined
          detected during:
            instantiation of type "std::make_integer_sequence<std::size_t, 0UL>"
(340): here
            instantiation of type "std::make_index_sequence<0UL>"
/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(83): here
            instantiation of "std::array<c10::detail::infer_schema::ArgumentDef, <expression>> c10::detail::infer_schema::createReturns<std::tuple<ReturnTypes...>, void>::call() [with ReturnTypes=<>]"
/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(98): here

/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/infer_schema.h(82): error: no instance of function template "c10::detail::infer_schema::createArgumentVectorFromTypes" matches the argument list
            argument types are: (<error-type>)
          detected during instantiation of "std::array<c10::detail::infer_schema::ArgumentDef, <expression>> c10::detail::infer_schema::createReturns<std::tuple<ReturnTypes...>, void>::call() [with ReturnTypes=<>]"
(98): here

5 errors detected in the compilation of "/tmp/tmpxft_00008ea2_00000000-6_deform_conv_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/home/arl/facebookproj/detectron2/setup.py", line 151, in <module>
    setup(
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/command/develop.py", line 115, in install_for_development
    self.run_command('build_ext')
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/arl/anaconda3/envs/mask/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
[end of output]

## Environment:
----------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
numpy                   1.23.5
detectron2              0.6 @/home/arl/anaconda3/envs/trans/lib/python3.8/site-packages/detectron2
detectron2._C           not built correctly: /home/arl/anaconda3/envs/trans/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
Compiler ($CXX)         c++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0
CUDA compiler           Cuda compilation tools, release 10.1, V10.1.243
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0+cu102 @/home/arl/anaconda3/envs/trans/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA T550 Laptop GPU (arch=7.5)
Driver version          525.105.17
CUDA_HOME               /usr
Pillow                  9.5.0
torchvision             0.9.1+cu101 @/home/arl/anaconda3/envs/trans/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20221221
iopath                  0.1.9
cv2                     Not found
----------------------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

**Comment by Ambuj-Choudha** [comment]
I have the same issue!...were you able to fix this?!

**Comment by ErinZhang1998** [comment]
I just ran these lines, and then the` install -e .` worked for me
```
export CUDA_HOME="/usr/local/cuda-11.6"
export CUDA_PATH="$CUDA_HOME"
export PATH="$CUDA_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:$CUDA_HOME/lib:$CUDA_HOME/extras/CUPTI/lib64:$CUDA_HOME/efa/lib:$LD_LIBRARY_PATH"
```

**Comment by miquel-espinosa** [comment]
https://github.com/facebookresearch/detectron2/issues/5008#issuecomment-2079206586
