### ISSUE TITLE
I encountered this error when training my model

### ISSUE THREAD

**Issue by BMB4PRESIDENT** [facebookresearch/detectron2#5056]
## 📚 Documentation Issue

This issue category is for problems about existing documentation, not for asking how-to questions.

* Provide a link to an existing documentation/comment/tutorial:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
ImportError: numpy.core.multiarray failed to import
          File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
      File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
Traceback (most recent call last):
from .Sample import Samplefrom .Sample import Sample
  File "multiprocessing\spawn.py", line 115, in _main
from .Sample import Sample      File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>

from .Sample import Sample  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
Traceback (most recent call last):
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>

  File "multiprocessing\spawn.py", line 115, in _main
      File "<string>", line 1, in <module>
from .Sample import Sample  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main

    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
  File "multiprocessing\spawn.py", line 115, in _main
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
                        from core.cv2ex import *from core.cv2ex import *from core.cv2ex import *from core.cv2ex import *from core.cv2ex import *from .Sample import Sample

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
    from core.cv2ex import *
    from core.interact import interact as io
    from core.interact import interact as io
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
                    from core import imagelib     from core import imagelib from core import imagelib from core import imagelib from core import imagelib
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>

from core import imagelib

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
    from .interact import interact
    from .interact import interact
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
                    from .text import get_text_image, get_draw_text_linesfrom .morph import morph_by_points
from .text import get_text_image, get_draw_text_linesfrom .morph import morph_by_points
from .text import get_text_image, get_draw_text_lines  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>

from .text import get_text_image, get_draw_text_lines  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>
    import cv2
    import cv2
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
                    from PIL import Image, ImageDraw, ImageFontfrom scipy.spatial import Delaunayfrom scipy.spatial import Delaunayfrom PIL import Image, ImageDraw, ImageFont    from PIL import Image, ImageDraw, ImageFontfrom PIL import Image, ImageDraw, ImageFont

    from .cv2 import *
    from .cv2 import *

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\__init__.py", line 148, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\__init__.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
MemoryError
ImportError: numpy.core.multiarray failed to import
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\PIL\Image.py", line 114, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError        MemoryErrorMemoryError
from scipy._lib._ccallback import LowLevelCallablefrom scipy._lib._ccallback import LowLevelCallable

  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
  File "C:\Users\obaro\Downloads\Programs\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The paging file is too small for this operation to complete.
        from . import _ccallback_cfrom . import _ccallback_c

ImportErrorImportError: : DLL load failed: The paging file is too small for this operation to complete.DLL load failed: The paging file is too small for this operation to complete.
* How should the above documentation/comment/tutorial improve:

**Comment by BMB4PRESIDENT** [comment]
How can the avoce error be fixed?
