### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by Tickets14** [facebookresearch/detectron2#5117]
Error when building a detectron2 on docker 
Hello. Im experiencing a weird behavior where if im building a docker with detectron2 it always showing an error 
```
3.930   × python setup.py egg_info did not run successfully.
3.930   │ exit code: 1
3.930   ╰─> [6 lines of output]
3.930       Traceback (most recent call last):
3.930         File "<string>", line 2, in <module>
3.930         File "<pip-setuptools-caller>", line 34, in <module>
3.930         File "/tmp/pip-req-build-sz8hbgh3/setup.py", line 10, in <module>
3.930           import torch
3.930       ModuleNotFoundError: No module named 'torch'
3.930       [end of output]
```
Here is my Dokerfile

```
FROM public.ecr.aws/lambda/python:3.9


# Install Git
RUN yum install -y git

# Copy requirements.txt
COPY requirements.txt ./

# Install the specified packages
RUN pip3 install -r requirements.txt;


COPY sample.py ./
CMD [ "sampl.handler"]
```

Here is my requirements.txt
```
boto3==1.28.62
Pillow==10.0.1
numpy==1.24.3
torch==2.0.0
torchvision==0.15.1
opencv-python==4.6.0.66
git+https://github.com/facebookresearch/detectron2.git

```

**Comment by Tickets14** [comment]
I also tried this on my docker 

```
FROM public.ecr.aws/lambda/python:3.9


# Install Git
RUN yum install -y git

# Copy requirements.txt
COPY requirements.txt ./

# Install the specified packages
RUN pip3 install -r requirements.txt;
RUN git clone https://github.com/facebookresearch/detectron2.git
RUN pip3 install -e detectron2

COPY sample.py ./
CMD [ "sample.handler"]
```

Here is the error
```
21.34   Running setup.py install for antlr4-python3-runtime: started
21.49   Running setup.py install for antlr4-python3-runtime: finished with status 'done'
21.83   Attempting uninstall: iopath
21.83     Found existing installation: iopath 0.1.10
21.83     Uninstalling iopath-0.1.10:
21.94       Successfully uninstalled iopath-0.1.10
22.75   Attempting uninstall: fvcore
22.75     Found existing installation: fvcore 0.1.6
22.75     Uninstalling fvcore-0.1.6:
22.82       Successfully uninstalled fvcore-0.1.6
22.82   DEPRECATION: fvcore is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
22.82   Running setup.py install for fvcore: started
22.96   Running setup.py install for fvcore: finished with status 'done'
24.18   Running setup.py develop for detectron2
25.38     error: subprocess-exited-with-error
25.38     
25.38     × python setup.py develop did not run successfully.
25.38     │ exit code: 1
25.38     ╰─> [15 lines of output]
25.38         running develop
25.38         running egg_info
25.38         creating detectron2.egg-info
25.38         writing detectron2.egg-info/PKG-INFO
25.38         writing dependency_links to detectron2.egg-info/dependency_links.txt
25.38         writing requirements to detectron2.egg-info/requires.txt
25.38         writing top-level names to detectron2.egg-info/top_level.txt
25.38         writing manifest file 'detectron2.egg-info/SOURCES.txt'
25.38         /var/lang/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
25.38           warnings.warn(msg.format('we could not find ninja.'))
25.38         reading manifest file 'detectron2.egg-info/SOURCES.txt'
25.38         adding license file 'LICENSE'
25.38         writing manifest file 'detectron2.egg-info/SOURCES.txt'
25.38         running build_ext
25.38         error: [Errno 2] No such file or directory: 'which'
25.38         [end of output]
25.38     
25.38     note: This error originates from a subprocess, and is likely not a problem with pip.
25.38 error: subprocess-exited-with-error
25.38 
25.38 × python setup.py develop did not run successfully.
25.38 │ exit code: 1
25.38 ╰─> [15 lines of output]
25.38     running develop
25.38     running egg_info
25.38     creating detectron2.egg-info
25.38     writing detectron2.egg-info/PKG-INFO
25.38     writing dependency_links to detectron2.egg-info/dependency_links.txt
25.38     writing requirements to detectron2.egg-info/requires.txt
25.38     writing top-level names to detectron2.egg-info/top_level.txt
25.38     writing manifest file 'detectron2.egg-info/SOURCES.txt'
25.38     /var/lang/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
25.38       warnings.warn(msg.format('we could not find ninja.'))
25.38     reading manifest file 'detectron2.egg-info/SOURCES.txt'
25.38     adding license file 'LICENSE'
25.38     writing manifest file 'detectron2.egg-info/SOURCES.txt'
25.38     running build_ext
25.38     error: [Errno 2] No such file or directory: 'which'
25.38     [end of output]
25.38 
25.38 note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by Prayag22** [comment]
FROM public.ecr.aws/lambda/python:3.9
# Install packages
RUN pip install torch==2.0.0

# Install Git
RUN yum install -y git

# Copy requirements.txt
COPY requirements.txt ./

# Install the specified packages
RUN pip3 install -r requirements.txt;
RUN git clone https://github.com/facebookresearch/detectron2.git
RUN pip3 install -e detectron2

COPY sample.py ./
CMD [ "sample.handler"]can you try

**Comment by brownaaron45** [comment]
I wanted to post a solution that I found for this problem. It is not a problem with detection but rather a problem with your torch library. Since you are using lambda which is CPU only you need to specifically select CPU wheel files for pytorch.

https://pytorch.org/get-started/locally/#start-locally

```Dockerfile
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu \
    && python -c "import torch; print(torch.__version__)"
```
