### ISSUE TITLE
Trace is useless

### ISSUE THREAD

**Issue by XZRRRRRR** [facebookresearch/detectron2#5198]
### Discussed in https://github.com/facebookresearch/detectron2/discussions/5197

<div type='discussions-op-text'>

<sup>Originally posted by **XZRRRRRR** January 18, 2024</sup>
Recently, when I deployed a Detectron2 model in C++, I tried using the export_tracing function in tools/deploy/export_model.py, and it works fine but the extracted model is only available for case inputs, not for other image inputs (but it is correctly available when it should); When I try to use the export_scripting function, I get an error for modeling/backbone/swin_transformer.py:
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::view(Tensor(a) self, SymInt[] size) -> Tensor(a):
  Expected a value of type 'int' for argument '<varargs>' but instead found type 'NoneType'.

The original call is:
  File "/home/xiangzhaorui/python_projects/SwinTextSpotter/detectron2/modeling/backbone/swin_transformer.py", line 205
        shortcut = x
        x = self.norm1(x)
        x = x.view(B, H, W, C)
            ~~~~~~ <--- HERE
    
        # pad feature maps to multiples of window size

Is anyone can help me there? Please!!!!!!!!!</div>

**Comment by XZRRRRRR** [comment]
Instructions To Reproduce the Issue and Full Logs：
(swts) (base) xiangzhaorui@tesla-a40-2:~/python_projects/SwinTextSpotter$ python cpp.py
/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the `__init__` method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "
/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
test
/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py:266: UserWarning: 'batch_first' was found in ScriptModule constants, but was not actually set in __init__. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Traceback (most recent call last):
  File "/home/xiangzhaorui/python_projects/SwinTextSpotter/cpp.py", line 88, in <module>
    export_scripting(torch_model)
  File "/home/xiangzhaorui/python_projects/SwinTextSpotter/cpp.py", line 51, in export_scripting
    ts_model = scripting_with_instances(ScriptableAdapter(), fields)
  File "/home/xiangzhaorui/python_projects/SwinTextSpotter/detectron2/export/torchscript.py", line 58, in scripting_with_instances
    scripted_model = torch.jit.script(model)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 1284, in script
    return torch.jit._recursive.create_script_module(
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_script.py", line 614, in _construct
    init_fn(script_module)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/xiangzhaorui/miniconda3/envs/swts/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::view(Tensor(a) self, SymInt[] size) -> Tensor(a):
  Expected a value of type 'int' for argument '<varargs>' but instead found type 'NoneType'.

The original call is:
  File "/home/xiangzhaorui/python_projects/SwinTextSpotter/detectron2/modeling/backbone/swin_transformer.py", line 205
        shortcut = x
        x = self.norm1(x)
        x = x.view(B, H, W, C)
            ~~~~~~ <--- HERE
    
        # pad feature maps to multiples of window size
my code:
import argparse
import torch
from detectron2.modeling import GeneralizedRCNN,RetinaNet,build_model
from projects.SWINTS.swints import add_SWINTS_config
from detectron2.config import get_cfg
from detectron2.data.detection_utils import read_image
from detectron2.checkpoint.detection_checkpoint import DetectionCheckpointer
from detectron2.data import build_detection_test_loader
from detectron2.structures import Boxes
from typing import Dict, List, Tuple
from torch import Tensor
from detectron2.export import dump_torchscript_IR, scripting_with_instances
from detectron2.utils.testing import reload_script_model
import torch.nn as nn


def export_scripting(torch_model):
    # fields = {
    #     "proposal_boxes": Boxes,
    #     "objectness_logits": Tensor,
    #     "pred_boxes": Boxes,
    #     "scores": Tensor,
    #     "pred_classes": Tensor,
    #     "pred_masks": Tensor,
    #     "pred_keypoints": torch.Tensor,
    #     "pred_keypoint_heatmaps": torch.Tensor,
    # }
    fields = {"pred_boxes": Boxes, "scores": torch.Tensor,"pred_masks": torch.Tensor,"pred_rec":torch.Tensor}

    class ScriptableAdapterBase(nn.Module):
        # Use this adapter to workaround https://github.com/pytorch/pytorch/issues/46944
        # by not retuning instances but dicts. Otherwise the exported model is not deployable
        def __init__(self):
            super().__init__()
            self.model = torch_model
            self.eval()

    if isinstance(torch_model, GeneralizedRCNN):

        class ScriptableAdapter(ScriptableAdapterBase):
            def forward(self, inputs: Tuple[Dict[str, torch.Tensor]]) -> List[Dict[str, Tensor]]:
                instances = self.model.inference(inputs, do_postprocess=False)
                return [i.get_fields() for i in instances]

    else:
        class ScriptableAdapter(ScriptableAdapterBase):
            def forward(self, inputs: Tuple[Dict[str, torch.Tensor]]) -> List[Dict[str, Tensor]]:
                instances = self.model(inputs)
                return [i.get_fields() for i in instances]

    ts_model = scripting_with_instances(ScriptableAdapter(), fields)
    # with PathManager.open(os.path.join(args.output, "model.ts"), "wb") as f:
    #     torch.jit.save(ts_model, f)
    # dump_torchscript_IR(ts_model, args.output)
    # # TODO inference in Python now missing postprocessing glue code
    return None


def setup_cfg(args):
    cfg = get_cfg()
    # cuda context is initialized before creating dataloader, so we don't fork anymore
    add_SWINTS_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.MODEL.RETINANET.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = args.confidence_threshold
    cfg.MODEL.WEIGHTS = '/home/xiangzhaorui/python_projects/SwinTextSpotter/output/model_final.pth'
    cfg.MODEL.DEVICE = 'cuda:0'
    cfg.freeze()
    return cfg

parser = argparse.ArgumentParser(description="Export a model for deployment.")
parser.add_argument("--config-file", default="", metavar="FILE", help="path to config file")
parser.add_argument('--confidence-threshold', type=float, help='Confidence threshold')
args_string = "--config-file /home/xiangzhaorui/python_projects/SwinTextSpotter/projects/SWINTS/configs/myconfig.yaml --confidence-threshold 0.4"
args_list = args_string.split()
args = parser.parse_args(args_list)
cfg = setup_cfg(args)
torch_model = build_model(cfg)
DetectionCheckpointer(torch_model).resume_or_load(cfg.MODEL.WEIGHTS)
torch_model.eval()

# img_path = '/home/xiangzhaorui/python_projects/SwinTextSpotter/datasets/totaltext/totaltext_test_images/4.png'
# img = read_image(img_path, format="BGR")
# img = img.copy()  # 复制数组
# img = torch.from_numpy(img.transpose(2, 0, 1)).float()
# inputs = [{"image": img}]
export_scripting(torch_model)

# script_model = scripting_with_instances(torch_model, fields)
#script_model = reload_script_model(script_model)
# with torch.no_grad():
#     instance = torch_model.inference(inputs, do_postprocess=False)[0]
    
My env:
Ubuntu 18.04 with conda env:
absl-py                   2.0.0                    pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_10    conda-forge
black                     24.1a1                   pypi_0    pypi
blas                      1.0                         mkl    defaults
brotli-python             1.0.9           py310h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.12.12           h06a4308_0    defaults
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17      py310h06a4308_0    defaults
cffi                      1.16.0          py310h5eee18b_0    defaults
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7           py310h06a4308_0    defaults
cloudpickle               3.0.0                    pypi_0    pypi
cmake                     3.26.4               hcfe8598_0    conda-forge
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.2.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0                    pypi_0    pypi
cryptography              41.0.7          py310hdda0065_0    defaults
cuda                      11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-cccl                 11.7.58              hc415cf5_0    nvidia/label/cuda-11.7.0
cuda-command-line-tools   11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-compiler             11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.60              h6a7c232_0    nvidia/label/cuda-11.7.0
cuda-cuobjdump            11.7.50              h28cc80a_0    nvidia/label/cuda-11.7.0
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             11.7.50              hb365495_0    nvidia/label/cuda-11.7.0
cuda-demo-suite           11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-documentation        11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-driver-dev           11.7.60                       0    nvidia/label/cuda-11.7.0
cuda-gdb                  11.7.50              h4a0ac72_0    nvidia/label/cuda-11.7.0
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-memcheck             11.7.50              hc446b2b_0    nvidia/label/cuda-11.7.0
cuda-nsight               11.7.50                       0    nvidia/label/cuda-11.7.0
cuda-nsight-compute       11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-nvcc                 11.7.64                       0    nvidia/label/cuda-11.7.0
cuda-nvdisasm             11.7.50              h5bd0695_0    nvidia/label/cuda-11.7.0
cuda-nvml-dev             11.7.50              h3af1343_0    nvidia/label/cuda-11.7.0
cuda-nvprof               11.7.50              h7a2404d_0    nvidia/label/cuda-11.7.0
cuda-nvprune              11.7.50              h7add7b4_0    nvidia/label/cuda-11.7.0
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.50              heada363_0    nvidia/label/cuda-11.7.0
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 11.7.50              hd2289d5_0    nvidia/label/cuda-11.7.0
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        11.7.50              hb424887_0    nvidia/label/cuda-11.7.0
cuda-toolkit              11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-tools                11.7.0                        0    nvidia/label/cuda-11.7.0
cuda-version              11.7                 h67201e3_2    conda-forge
cuda-visual-tools         11.7.0                        0    nvidia/label/cuda-11.7.0
cudatoolkit               11.7.1              h4bc3d14_12    conda-forge
cudatoolkit-dev           11.7.0               h1de0b5d_6    conda-forge
cudnn                     8.9.2.26               cuda11_0    defaults
cusparselt                0.5.0.1              hd5ab71f_1    conda-forge
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.8.0           py310hc6cd4ac_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
detectron2                0.4                      pypi_0    pypi
dpcpp-cpp-rt              2024.0.2            intel_49895    intel
dpcpp_cpp_rt              2024.0.2            intel_49895    intel
editdistance              0.6.2                    pypi_0    pypi
efficientnet-pytorch      0.7.1                    pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h6a678d5_0    defaults
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py310h06a4308_0    defaults
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.47.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    defaults
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gcc_impl_linux-64         10.3.0              hf2f2afa_16    conda-forge
gcc_linux-64              10.3.0              hc39de41_10    conda-forge
gds-tools                 1.3.0.44                      0    nvidia/label/cuda-11.7.0
giflib                    5.2.1                h5eee18b_3    defaults
gmp                       6.2.1                h295c915_3    defaults
gmpy2                     2.1.2           py310heeb90bb_0    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google                    3.0.0                    pypi_0    pypi
google-auth               2.26.1                   pypi_0    pypi
google-auth-oauthlib      1.2.0                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
gxx_impl_linux-64         10.3.0              hf2f2afa_16    conda-forge
gxx_linux-64              10.3.0              h2593f52_10    conda-forge
huggingface-hub           0.20.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
icc_rt                    2024.0.2            intel_49895    intel
idna                      3.6                      pypi_0    pypi
imageio                   2.33.1                   pypi_0    pypi
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
intel-cmplr-lib-rt        2024.0.2            intel_49895    intel
intel-cmplr-lic-rt        2024.0.2            intel_49895    intel
intel-opencl-rt           2024.0.2            intel_49895    intel
intel-openmp              2024.0.2            intel_49895    intel
intelpython               2024.0.0                      0    intel
iopath                    0.1.7                    pypi_0    pypi
ipykernel                 6.28.0             pyhd33586a_0    conda-forge
ipython                   8.20.0             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2           py310h06a4308_0    defaults
jpeg                      9e                   h5eee18b_1    defaults
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.1           py310hff52083_0    conda-forge
kernel-headers_linux-64   3.10.0              h57e8cba_10    defaults
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1    defaults
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h295c915_0    defaults
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.1.25           h0c8ac2b_0    nvidia/label/cuda-11.7.0
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufft-dev              10.7.2.50            h59a5ac8_0    nvidia/label/cuda-11.7.0
libcufile                 1.8.1.2                       0    nvidia
libcufile-dev             1.3.0.44                      0    nvidia/label/cuda-11.7.0
libcurand                 10.3.4.107                    0    nvidia
libcurand-dev             10.2.10.50           hd49a9cd_0    nvidia/label/cuda-11.7.0
libcurl                   8.5.0                h251f7ec_0    defaults
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.3.5.50            hc6eba6f_0    nvidia/label/cuda-11.7.0
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.3.50            hc644b96_0    nvidia/label/cuda-11.7.0
libcxx                    16.0.6               h00ab1b0_0    conda-forge
libcxxabi                 16.0.6               ha770c72_0    conda-forge
libdeflate                1.17                 h5eee18b_1    defaults
libedit                   3.1.20230828         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-devel_linux-64     10.3.0              he6cfe16_16    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.16                 h7f8727e_2    defaults
libidn2                   2.3.4                h5eee18b_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.3.21            hb6476a9_0    nvidia/label/cuda-11.7.0
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.7.2.34            h2e48410_0    nvidia/label/cuda-11.7.0
libpng                    1.6.39               h5eee18b_0    defaults
libprotobuf               3.20.3               he621ea3_0    defaults
libsanitizer              10.3.0              h26c7422_16    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-devel_linux-64  10.3.0              he6cfe16_16    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtasn1                  4.19.0               h5eee18b_0    defaults
libtiff                   4.5.1                h6a678d5_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libuv                     1.39.0               h516909a_0    conda-forge
libwebp                   1.2.4                h11a3e52_1    defaults
libwebp-base              1.2.4                h5eee18b_1    defaults
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                h6a678d5_0    defaults
markdown                  3.5.1                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2024.0.0            intel_49656    intel
mkl-include               2024.0.0            intel_49656    intel
mkl-service               2.4.0           py310h3539a15_41    intel
mkl-static                2024.0.0            intel_49656    intel
mkl_fft                   1.3.6           py310h1d81ff8_61    intel
mkl_random                1.2.2           py310h5a378b4_81    intel
mkl_umath                 0.1.1           py310h2b1685c_91    intel
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.3.0           py310h06a4308_0    defaults
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nccl                      2.19.4.1             h0800d71_0    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  3.1             py310h06a4308_0    defaults
nsight-compute            2022.2.0.13                   0    nvidia/label/cuda-11.7.0
numpy                     1.24.3          py310ha320b8e_5    intel
numpy-base                1.24.3          py310hbac2b65_5    intel
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0    defaults
omegaconf                 2.3.0                    pypi_0    pypi
onednn                    3.3              omp_hc847620_3    conda-forge
onnx                      1.15.0                   pypi_0    pypi
onnx-caffe2               1.0.0           pyhd8ed1ab_1004    conda-forge
onnxruntime-gpu           1.16.3                   pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.12.1                   pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       23.3.1          py310h06a4308_0    defaults
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
polygon3                  3.0.9.1                  pypi_0    pypi
portalocker               2.8.2                    pypi_0    pypi
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.7           py310h2372a71_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydot                     2.0.0                    pypi_0    pypi
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0          py310h06a4308_0    defaults
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.13              h955ad1f_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1           py310h5eee18b_0    defaults
pyzmq                     25.1.2          py310h795f18f_0    conda-forge
rapidfuzz                 2.15.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.31.0          py310h06a4308_0    defaults
requests-oauthlib         1.3.1                    pypi_0    pypi
rhash                     1.4.3                hdbd6064_0    defaults
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.2.2          py310h06a4308_0    defaults
shapely                   2.0.2                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.12            py310h06a4308_0    defaults
sysroot_linux-64          2.17                h57e8cba_10    defaults
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0    defaults
tbb4py                    2021.8.0        py310hdb19cb5_0    defaults
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
timm                      0.9.12                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
tomli                     2.0.1                    pypi_0    pypi
torchaudio                2.0.2               py310_cu117    pytorch
torchtriton               2.0.0                     py310    pytorch
torchvision               0.15.2              py310_cu117    pytorch
tornado                   6.3.3           py310h2372a71_1    conda-forge
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                    pypi_0    pypi
typing_extensions         4.7.1           py310h06a4308_0    defaults
tzdata                    2023d                h04d1e81_0    defaults
urllib3                   2.1.0                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2          py310h06a4308_0    defaults
xz                        5.4.5                h5eee18b_0    defaults
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0    defaults
yarl                      1.9.4                    pypi_0    pypi
zeromq                    4.3.5                h59595ed_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0    defaults
