### ISSUE TITLE
'DefaultPredictor' object is not subscriptable

### ISSUE THREAD

**Issue by hoangpm-2081** [facebookresearch/detectron2#521]
I clone detectron2 repo and train with my own dataset, after 3500 epoch, i get modek weight. First time, i test on jupyter but nothing happened. Then second time i write code on IDE and the problem appear below:
```
cfg = get_cfg()
cfg.merge_from_file("configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth") cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
predictor = DefaultPredictor(cfg)
p1 = predictor["instances"].pred_classes
p2 = predictor["instances"].pred_boxes
print(p1)
```
```
<Config 'configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
'roi_heads.box_predictor.cls_score.weight' has shape (2, 1024) in the checkpoint but (81, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (2,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (4, 1024) in the checkpoint but (320, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (4,) in the checkpoint but (320,) in the model! Skipped.
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    test_detectron2()
  File "train.py", line 130, in test_detectron2
    p1 = predictor["instances"].pred_classes
TypeError: 'DefaultPredictor' object is not subscriptable
>
```
Anyone help  me !!!

**Comment by ppwwyyxx** [comment]
See https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=Vk4gID50K03a on how to use a predictor.
