### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aligoglos** [facebookresearch/detectron2#528]
I've compiled detectron2 successfully but when I tried to run `demo.py` I got error:

```
python demo.py --output --config-file ../configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml --input Inputs/test.jpg --opts MODEL.WEIGHTS ../WEIGHTS/faster_rcnn_X_101_32x8d_FPN_3x.pkl                                                                     Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from detectron2.config import get_cfg
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\detectron2-0.1-py3.5-win-amd64.egg\detectron2\config\__init__.py", line 2, in <module>
    from .compat import downgrade_config, upgrade_config
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\detectron2-0.1-py3.5-win-amd64.egg\detectron2\config\compat.py", line 151
    RENAME: List[Tuple[str, str]] = []  # list of tuples of (old name, new name)
          ^
SyntaxError: invalid syntax
```

python version : 3.5.4

**Comment by ppwwyyxx** [comment]
As [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) said python >= 3.6 is required.
