### ISSUE TITLE
How to convert densepose model to onnx?

### ISSUE THREAD

**Issue by Asadashino-o** [facebookresearch/detectron2#5286]
I run export_model.py as below:

python detectron2/tools/deploy/export_model.py --config-file detectron2/projects/DensePose/configs/densepose_rcnn_R_50_FPN_s1x.yaml --output densepose.onnx --format onnx --sample-image example.jpg --export-method tracing MODEL.DEVICE cuda MODEL.WEIGHTS model_final_162be9.pkl

Maybe there is some errors:
Traceback (most recent call last):
  File "/data/hdd1/xietingyu/vid2densepose/detectron2/tools/deploy/export_model.py", line 261, in <module>
    main()  # pragma: no cover
  File "/data/hdd1/xietingyu/vid2densepose/detectron2/tools/deploy/export_model.py", line 225, in main
    cfg = setup_cfg(args)
  File "/data/hdd1/xietingyu/vid2densepose/detectron2/tools/deploy/export_model.py", line 34, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/data/hdd1/xietingyu/miniconda3/envs/det/lib/python3.9/site-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/data/hdd1/xietingyu/miniconda3/envs/det/lib/python3.9/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/data/hdd1/xietingyu/miniconda3/envs/det/lib/python3.9/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/data/hdd1/xietingyu/miniconda3/envs/det/lib/python3.9/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/data/hdd1/xietingyu/miniconda3/envs/det/lib/python3.9/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.DENSEPOSE_ON'

It seems detectron2 give no way to convert densepose?
What should I do? Thank you!

**Comment by Programmer-RD-AI** [comment]
Hi,
Please refer to issues #258 and #5111 which show case the same issue...
Thank you
