### ISSUE TITLE
error raised during installation

### ISSUE THREAD

**Issue by LSKhappychild** [facebookresearch/detectron2#5332]
## Instructions To Reproduce the Issue:

```
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```
```
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
          subprocess.run(
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

## Environment:

Paste the output of the following command:
```
PyTorch version: 2.3.1+cu121
OS: Ubuntu 20.04.6 LTS (x86_64)
CUDA runtime version: 12.1.105
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.28.1
Libc version: glibc-2.31
```

**Comment by jackkolb** [comment]
I'm getting this error too.

**Comment by stevemanavalan** [comment]
i am facing this problem as well during installation. The installation used to work earlier

**Comment by LSKhappychild** [comment]
In the full log, which I didn't saved tho, there exists an separate error log showing why the ninja build failed. I'm closing this, since I just found I didn't prepared one required library. To whom it may concern, may take a look at any error log shown.
