### ISSUE TITLE
cannot import name '_C' from 'detectron2' 

### ISSUE THREAD

**Issue by wbyiml** [facebookresearch/detectron2#538]
#75  When I run the balloon demo,
the code "from detectron2.structures import BoxMode" comes to an error.

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from detectron2.structures import BoxMode
  File "/home/nls1/tmp/detectron2/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/nls1/tmp/detectron2/detectron2/structures/boxes.py", line 8, in <module>
    from detectron2.layers import cat
  File "/home/nls1/tmp/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/nls1/tmp/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: cannot import name '_C' from 'detectron2' 

Please help.

**Comment by ppwwyyxx** [comment]
You need to install detectron2 following https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md or the colab.
