### ISSUE TITLE
_C.cpython-37m-darwin.so rename _C.so also failed

### ISSUE THREAD

**Issue by butters001** [facebookresearch/detectron2#59]
```
python3 demo/demo.py --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml   --input input1.jpg input2.jpg   --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/data/build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/structures/boxes.py", line 7, in <module>
    from detectron2.layers import cat
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: dlopen(/Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/_C.cpython-37m-darwin.so, 2): Symbol not found: __ZN3c1019NonVariableTypeMode10is_enabledEv
  Referenced from: /Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/_C.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/jxc/PycharmProjects/detectron2/detectron2/detectron2/_C.cpython-37m-darwin.so

```

**Comment by ppwwyyxx** [comment]
The issue is mentioned in https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#common-installation-issues. Please check if the solution there helps.
