### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Ghul-huan** [facebookresearch/detectron2#608]
when training , a bug occurs: 

Process SpawnProcess-1:
Traceback (most recent call last):
  File "/data/welab/models/Detection/anaconda/envs/facebook_detector2/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/welab/models/Detection/detectron2_repo/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/data/welab/models/WeAI/ComputerVision/certdetect/train/train_net.py", line 186, in main
    return trainer.train()
  File "/data/welab/models/Detection/detectron2_repo/detectron2/engine/defaults.py", line 371, in train
    super().train(self.start_iter, self.max_iter)
  File "/data/welab/models/Detection/detectron2_repo/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/data/welab/models/Detection/detectron2_repo/detectron2/engine/train_loop.py", line 218, in run_step
    self._write_metrics(metrics_dict)
  File "/data/welab/models/Detection/detectron2_repo/detectron2/engine/train_loop.py", line 253, in _write_metrics
    all_metrics_dict = comm.gather(metrics_dict)
  File "/data/welab/models/Detection/detectron2_repo/detectron2/utils/comm.py", line 200, in gather
    size_list, tensor = _pad_to_largest_tensor(tensor, group)
  File "/data/welab/models/Detection/detectron2_repo/detectron2/utils/comm.py", line 126, in _pad_to_largest_tensor
    dist.all_gather(size_list, local_size, group=group)
  File "/data/welab/models/Detection/anaconda/envs/facebook_detector2/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1160, in all_gather
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1573049301898/work/third_party/gloo/gloo/transport/tcp/pair.cc:572] Conne                                                ction closed by peer

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by sunnyheart008205** [comment]
@Ghul-huan  hi, have you solved the problem provided? I have this problem too.

**Comment by xudong19** [comment]
@Ghul-huan @ppwwyyxx @sunnyheart008205 Any update about this problem? I met similar problem. 

When I use comm.gather() function in my customized evaluator, the program will be stuck there forever and then break due to too long waiting-time.
