### ISSUE TITLE
Training Mask-RCNN on Mapillary Vistas - CUDA out of memory

### ISSUE THREAD

**Issue by jsaric** [facebookresearch/detectron2#659]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
I converted Mapillary Vistas dataset to COCO format with script from:
https://github.com/mapillary/seamseg
Registered the dataset according to instructions and ran a training script.

2. what exact command you run:
```python tools/train_net.py --num-gpus 2 --config-file configs/mapillary/mask_rcnn_R_50_FPN_all.yaml```

3. what you observed (including the full logs):
```
Traceback (most recent call last):                                                                                                                                                                                                    [0/1924]
  File "tools/train_net.py", line 178, in <module>
    launch(
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/launch.py", line 45, in launch
    mp.spawn(
  File "/usr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/jsaric/lib/my-detectron2/tools/train_net.py", line 162, in main
    return trainer.train()
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/train_loop.py", line 133, in train
    self.after_step()
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/train_loop.py", line 151, in after_step
    h.after_step()
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/hooks.py", line 323, in after_step
    results = self._func()
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/defaults.py", line 324, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/jsaric/lib/my-detectron2/detectron2/engine/defaults.py", line 484, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/jsaric/lib/my-detectron2/detectron2/evaluation/evaluator.py", line 121, in inference_on_dataset
    outputs = model(inputs)
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jsaric/lib/my-detectron2/detectron2/modeling/meta_arch/rcnn.py", line 109, in forward
    return self.inference(batched_inputs)
  File "/home/jsaric/lib/my-detectron2/detectron2/modeling/meta_arch/rcnn.py", line 183, in inference
    r = detector_postprocess(results_per_image, height, width)
  File "/home/jsaric/lib/my-detectron2/detectron2/modeling/postprocessing.py", line 41, in detector_postprocess
    results.pred_masks = paste_masks_in_image(
  File "/home/jsaric/lib/my-detectron2/detectron2/layers/mask_ops.py", line 117, in paste_masks_in_image
    masks_chunk, spatial_inds = _do_paste_mask(
  File "/home/jsaric/lib/my-detectron2/detectron2/layers/mask_ops.py", line 57, in _do_paste_mask
    grid = torch.stack([gx, gy], dim=3)
RuntimeError: CUDA out of memory. Tried to allocate 2.02 GiB (GPU 0; 10.76 GiB total capacity; 4.19 GiB already allocated; 1.62 GiB free; 4.09 GiB cached)
```
## Expected behavior:
I expected successful training without bugs.

## Environment:
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.8.0 (default, Oct 23 2019, 18:51:26) [GCC 9.2.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 9.2
Detectron2 CUDA Compiler  10.2
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1                   GeForce RTX 2080 Ti
CUDA_HOME                 /opt/cuda
NVCC                      Cuda compilation tools, release 10.2, V10.2.89
Pillow                    6.2.2
cv2                       4.2.0
------------------------  --------------------------------------------------

Error happens completely at random. I tried to run the experiment a couple of times, each time it happened at different iteration of the training. This time it happened at the iteration 80979. 

I also tried to run it on different machine (2X GTX 1080 Ti), error also occured. 

I also tried reducing the batch size, but it did not help. 

I attached my yaml config file:
[config.txt](https://github.com/facebookresearch/detectron2/files/4039984/config.txt)

**Comment by ppwwyyxx** [comment]
Depending on the nature of your dataset and/or the size of images you use (which is pretty large) or batch size it can certainly take much more memory than a standard model. This seems reasonable to me.
