### ISSUE TITLE
[Bug] Unexpected crash during crop transform

### ISSUE THREAD

**Issue by ZekunZh** [facebookresearch/detectron2#687]
I encountered an unexpected crash in the middle of training that might suggest a bug in crop transformation and any ideas/suggestions are appreciated. @ppwwyyxx 
```
Original Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/dataset_mapper.py", line 89, in __call__
    np.random.choice(dataset_dict["annotations"]),
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/detection_utils.py", line 396, in gen_crop_transform_with_instance
    x0 = np.random.randint(min_yx[1], max_yx[1] + 1)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high
```

## Instructions To Reproduce the Issue:

1. what changes I made (`git diff`) 
The following modifications are based on commit [5e2a6f6](https://github.com/facebookresearch/detectron2/commit/5e2a6f62ef752c8b8c700d2e58405e4bede3ddbe).
I used a new config file:
```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  LOAD_PROPOSALS: False
  RESNETS:
    DEPTH: 50
    NORM: GN
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 4
INPUT:
  CROP:
    ENABLED: True
    SIZE: [0.8, 1]
    TYPE: relative_range
  AUGMT:
    ENABLED: True
    TRANSLATE: (0.15, 0.15)
    ROTATE: 10
    HFLIP: True
```
And I also made some modifications to be able to run other types of augmentations like translation and augmentation. The whole diff is [diff.txt](https://github.com/facebookresearch/detectron2/files/4053168/diff.txt)
 

2. what exact command I run:
```
python train_net.py --num-gpus 4 --config-file our_custom_config_file_shown_above.yaml
```

3. what I observed (including the full logs):
Training crashed after 24010 iterations with following error:
```
The experiment failed. Finalizing run...
Starting the daemon thread to refresh tokens in background for process with pid = 434
Traceback (most recent call last):
  File "azureml/azureml_train.py", line 52, in <module>
    args=(args,),
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/tools/train_net.py", line 152, in run_detectron
    return trainer.train()
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/engine/train_loop.py", line 206, in run_step
    data = next(self._data_loader_iter)
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/common.py", line 109, in __iter__
    for d in self.dataset:
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/dataset_mapper.py", line 89, in __call__
    np.random.choice(dataset_dict["annotations"]),
  File "/mnt/batch/tasks/shared/LS_root/jobs/batchai-service/azureml/od-d2-r50-fpn-1x-glm-fullspec_1578679609_7527d50f/mounts/workspaceblobstore/azureml/od-d2-R50-FPN-1x-glm-fullspec_1578679609_7527d50f/detectron2/data/detection_utils.py", line 396, in gen_crop_transform_with_instance
    x0 = np.random.randint(min_yx[1], max_yx[1] + 1)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high
```
The full log file is [log-4gpu-d2-glm-fullspec.txt](https://github.com/facebookresearch/detectron2/files/4053681/log-4gpu-d2-glm-fullspec.txt)

4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

I believe that the bug is reproducible with COCO dataset, but haven't tested yet.

## Possible bug in `gen_crop_transform_with_instance`

When I looked into the code of function `gen_crop_transform_with_instance` in `detectron2/data/detection_utils.py`, the code didn't seem to be coherent with its description in the following line:

```
max_yx = np.minimum(max_yx, np.ceil(center_yx).astype(np.int32)) # We want to include the center of box, however max_yx could be smaller than the center, and even smaller than min_yx. In this case, the bug shown above will happen.
```

## Environment:
```
------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                     1.15.0
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     Tesla K80
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    5.2.0
cv2                       4.1.0
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
This can happen if your bounding box's center is outside the image or if your crop size is larger than the image. Both cases conflict with the definition of the function https://detectron2.readthedocs.io/modules/data.html#detectron2.data.detection_utils.gen_crop_transform_with_instance

**Comment by ZekunZh** [comment]
Thanks for your response ! But it seems strange to me using `minimum` in the line 
```
max_yx = np.minimum(max_yx, np.ceil(center_yx).astype(np.int32))
```
If `max_yx` is smaller than `center_yx`, then the center will not be included, as shown in the following graph:
![Screenshot from 2020-01-14 11-03-46](https://user-images.githubusercontent.com/16140400/72334424-92edd380-36bd-11ea-9e35-84f1a4876f27.png)

So I think we should change it to `np.maximum`.

**Comment by ppwwyyxx** [comment]
`max_yx` is the "maximum possible __top-left corner__ of the box to be cropped". The box to be cropped can have size crop_size starting from `max_yx` to `max_yx + crop_size`, so I think it should still include the box center.

**Comment by ZekunZh** [comment]
Yes you're right. I think it's the problem of my dataset. Thanks !
