### ISSUE TITLE
Evaluate balloon dataset

### ISSUE THREAD

**Issue by AumXIV** [facebookresearch/detectron2#708]
## ❓ How to Evaluate 

My code is look like this.

```
import detectron2
from` detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import cv2
import random

import os
import numpy as np
import json
from detectron2.structures import BoxMode
import itertools

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.data import DatasetCatalog, MetadataCatalog


def get_balloon_dicts(img_dir):
    json_file = os.path.join(img_dir, "via_region_data.json")
    with open(json_file) as f:
        imgs_anns = json.load(f)

    dataset_dicts = []
    for idx, v in enumerate(imgs_anns.values()):
        record = {}

        filename = os.path.join(img_dir, v["filename"])
        height, width = cv2.imread(filename).shape[:2]

        record["file_name"] = filename
        record["image_id"] = idx
        record["height"] = height
        record["width"] = width

        annos = v["regions"]
        objs = []
        for _, anno in annos.items():
            assert not anno["region_attributes"]
            anno = anno["shape_attributes"]
            px = anno["all_points_x"]
            py = anno["all_points_y"]
            poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
            poly = list(itertools.chain.from_iterable(poly))

            obj = {
                "bbox": [np.min(px), np.min(py), np.max(px), np.max(py)],
                "bbox_mode": BoxMode.XYXY_ABS,
                "segmentation": [poly],
                "category_id": 0,
                "iscrowd": 0
            }
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    print(dataset_dicts)
    return dataset_dicts

for d in ["train", "val"]:
    DatasetCatalog.register("balloon_" + d, lambda d=d: get_balloon_dicts("datasets/balloon/" + d))
    MetadataCatalog.get("balloon_" + d).set(thing_classes=["balloon"])
balloon_metadata = MetadataCatalog.get("balloon_train")

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("balloon_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7   # set the testing threshold for this model
cfg.DATASETS.TEST = ("balloon_val", )
predictor = DefaultPredictor(cfg)

from detectron2.utils.visualizer import ColorMode
dataset_dicts = get_balloon_dicts("datasets/balloon/val")
for d in random.sample(dataset_dicts, 3):
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=balloon_metadata,
                   scale=0.8,
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    # cv2.imshow(d["file_name"], v.get_image()[:, :, ::-1])
    # cv2.waitKey(2500)

from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
evaluator = COCOEvaluator("balloon_val", cfg, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg, "balloon_val")
trainer = DefaultTrainer(cfg)
inference_on_dataset(trainer.model, val_loader, evaluator)
```

And after I run I got this.

`
`
`
`
`
`

**Comment by AumXIV** [comment]
```
[01/16 15:30:14 d2.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[01/16 15:30:14 d2.data.build]: Using training sampler TrainingSampler
[01/16 15:30:14 d2.evaluation.evaluator]: Start inference on 13 images
[01/16 15:30:16 d2.evaluation.evaluator]: Total inference time: 0:00:00 (0.000000 s / img per device, on 1 devices)
[01/16 15:30:16 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.084000 s / img per device, on 1 devices)
[01/16 15:30:16 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[01/16 15:30:16 d2.evaluation.coco_evaluation]: Saving results to ./output/coco_instances_results.json
[01/16 15:30:16 d2.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test_balloon.py", line 112, in <module>
    inference_on_dataset(trainer.model, val_loader, evaluator)
  File "/home/ee303/detectron2/detectron2/evaluation/evaluator.py", line 155, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/ee303/detectron2/detectron2/evaluation/coco_evaluation.py", line 131, in evaluate
    self._eval_predictions(set(self._tasks))
  File "/home/ee303/detectron2/detectron2/evaluation/coco_evaluation.py", line 174, in _eval_predictions
    if len(self._coco_results) > 0
  File "/home/ee303/detectron2/detectron2/evaluation/coco_evaluation.py", line 476, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "/home/ee303/anaconda3/envs/rcnn_env/lib/python3.7/site-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:
NameError: name 'unicode' is not defined

```

And my pycocotools  is  2.0.0

**Comment by AumXIV** [comment]
And warning

> WARNING [01/16 16:04:31 d2.evaluation.coco_evaluation]: json_file was not found in MetaDataCatalog for 'balloon_val'
[01/16 16:04:31 d2.data.datasets.coco]: Reading cached annotations in COCO format from:./output/balloon_val_coco_format.json ...

**Comment by ppwwyyxx** [comment]
Please follow the example in colab tutorial.

**Comment by AumXIV** [comment]
I copy the first code from colab tutorial, but cut out the training part. I want to separate train and test(including evaluate) to 2 files.

**Comment by northeastsquare** [comment]
I change the according line to, evalutation not 0 or None now:
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
trainer.resume_or_load(resume=True)

**Comment by AumXIV** [comment]
> I change the according line to, evalutation not 0 or None now:
> cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
> trainer.resume_or_load(resume=True)

It's work! Thanks.

**Comment by drapado** [comment]
@AumXIV 

> It's work! Thanks.

I tried the last solution but it does not work for me, could you share the whole code with the solution?
Thanks!
