### ISSUE TITLE
Can't train multi-gpu from command line: Process group URL: None and MASTER_ADDR expected, but not set

### ISSUE THREAD

**Issue by rbavery** [facebookresearch/detectron2#753]
I can run the following script in the notebook  with a single gpu without using `launch`. But when I try to use multiple gpus on a single machine with the following command I get these errors (full logs included below):
`Process group URL: None`
`ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set`

1. what changes you made (`git diff`) or what code you wrote
in detectron2 I've only changed the file for reading images so that tif images can be read
```
(cropmask) ryan@cropmask-mgpu-18-v2:~/detectron2$ git diff
diff --git a/detectron2/data/detection_utils.py b/detectron2/data/detection_utils.py
index ee6e5f9..5d7cce9 100644
--- a/detectron2/data/detection_utils.py
+++ b/detectron2/data/detection_utils.py
@@ -25,7 +25,7 @@ from detectron2.structures import (
 
 from . import transforms as T
 from .catalog import MetadataCatalog
-
+from imageio import imread
 
 class SizeMismatchError(ValueError):
     """
@@ -45,29 +45,32 @@ def read_image(file_name, format=None):
     Returns:
         image (np.ndarray): an HWC image
     """
-    with PathManager.open(file_name, "rb") as f:
-        image = Image.open(f)
-
-        # capture and ignore this bug: https://github.com/python-pillow/Pillow/issues/3973
-        try:
-            image = ImageOps.exif_transpose(image)
-        except Exception:
-            pass
-
-        if format is not None:
-            # PIL only supports RGB, so convert to RGB and flip channels over below
-            conversion_format = format
+    if file_name.endswith(".tif"):
+        return imread(file_name)
+    else:
+        with PathManager.open(file_name, "rb") as f:
+            image = Image.open(f)
+
+            # capture and ignore this bug: https://github.com/python-pillow/Pillow/issues/3973
+            try:
+                image = ImageOps.exif_transpose(image)
+            except Exception:
+                pass
+
+            if format is not None:
+                # PIL only supports RGB, so convert to RGB and flip channels over below
+                conversion_format = format
+                if format == "BGR":
+                    conversion_format = "RGB"
+                image = image.convert(conversion_format)
+            image = np.asarray(image)
             if format == "BGR":
-                conversion_format = "RGB"
-            image = image.convert(conversion_format)
-        image = np.asarray(image)
-        if format == "BGR":
-            # flip channels if needed
-            image = image[:, :, ::-1]
-        # PIL squeezes out the channel dimension for "L", so make it HWC
-        if format == "L":
-            image = np.expand_dims(image, -1)
-        return image
+                # flip channels if needed
+                image = image[:, :, ::-1]
+            # PIL squeezes out the channel dimension for "L", so make it HWC
+            if format == "L":
+                image = np.expand_dims(image, -1)
+            return image
```

2. The file I'm running is based on the `train_net.py` script that supports multiple gpus on the same machine using the `launch function`. It imports my `cfg` object which is in another file so I don't supply it as a command line argument.
train_model.py
```python
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# import some common libraries
from pathlib import Path
import os

import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()
# import some common detectron2 utilities
from detectron2.engine import DefaultPredictor, launch, default_argument_parser
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
from detectron2.data.datasets import register_coco_instances, load_coco_json

from cropmask.misc import parse_yaml, make_dirs
from cropmask.coco_convert import split_save_train_validation_test_df, save_coco_annotation, create_coco_dataset
from cropmask.detectron2_cropmask_cfg import cfg
from cropmask import detectron2_reclass # fair amount of stuff goes on in here to make detectron work for this project.

def setup_register_load_inputs(cfg):
    param_path = "/home/ryan/work/CropMask_RCNN/test_inspection_config.yaml"
    params = parse_yaml(param_path)
    tiles_path = Path(os.path.join(params['dirs']['root'], params['dirs']['dataset'], "tiles"))

    train, validation, test = split_save_train_validation_test_df(tiles_path, save_empty_tiles=False)
    coco_path = Path(params['dirs']['root']) / params['dirs']['dataset'] / "coco"

    train_coco_instances_path = str(coco_path / "instances_train.json")
    val_coco_instances_path = str(coco_path / "instances_val.json")
    test_coco_instances_path = str(coco_path / "instances_test.json")
    if (coco_path / "instances_train.json").exists() is False:
        train_coco_dict = create_coco_dataset(train)
        val_coco_dict = create_coco_dataset(validation)
        test_coco_dict = create_coco_dataset(test)
        save_coco_annotation(train_coco_instances_path, train_coco_dict)
        save_coco_annotation(val_coco_instances_path, val_coco_dict)
        save_coco_annotation(test_coco_instances_path, test_coco_dict)
    # register each val and test set if there are more than one.
    register_coco_instances(cfg.DATASETS.TRAIN[0], {}, train_coco_instances_path, str(next(tiles_path.glob("*image*"))))
    register_coco_instances(cfg.DATASETS.VALIDATION[0], {}, val_coco_instances_path, str(next(tiles_path.glob("*image*"))))
    register_coco_instances(cfg.DATASETS.TEST[0], {}, test_coco_instances_path, str(next(tiles_path.glob("*image*"))))

    train_json = load_coco_json(train_coco_instances_path,  str(next(tiles_path.glob("*image*"))))
    val_json = load_coco_json(val_coco_instances_path,  str(next(tiles_path.glob("*image*"))))
    test_json = load_coco_json(test_coco_instances_path,  str(next(tiles_path.glob("*image*"))))
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=False)

def main(cfg):
    setup_register_load_inputs(cfg)
    trainer = detectron2_reclass.Trainer(cfg)
    trainer.resume_or_load(resume=False)
    return trainer.train()

if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    launch(
        main,
        args.num_gpus,
        args=(args,),
    )
```

my cfg file

```
from detectron2.config import get_cfg
from detectron2 import model_zoo

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.VALIDATION = ("validation_nirrg",) # added after subclassing Default Trainer above in order to plot validtion loss curves during training. need to do 3 way split and register validation
cfg.DATASETS.TRAIN = ("train_nirrg",)
cfg.DATASETS.TEST = ("test_nirrg",)

# https://github.com/facebookresearch/detectron2/blob/dfc678a0aa6aaaae4e925877fe9f653edf627c86/detectron2/config/defaults.py
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 16
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 4000 
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512   # this is the default
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class 
cfg.TEST.EVAL_PERIOD = 0 # the period in terms of steps to evaluate the model on the test set by computing AP statistics, but should be edited to run on val set.
cfg.SOLVER.CHECKPOINT_PERIOD = 800
cfg.VALIDATION_PERIOD = 20
cfg.OUTPUT_DIR = "/home/ryan/work/cropmask_experiments/test1"
cfg.CUDNN_BENCHMARK = False # might cause speed gains since all images are same size if set to True (default is False)
cfg.INPUT.FORMAT = "RGB"
# Default values are the mean pixel value from ImageNet: [103.53, 116.28, 123.675]
cfg.MODEL.PIXEL_MEAN = [103.530, 116.280, 123.675]
# When using pre-trained models in Detectron1 or any MSRA models,
# std has been absorbed into its conv1 weights, so the std needs to be set 1.
# Otherwise, you can use [57.375, 57.120, 58.395] (ImageNet std)
cfg.MODEL.PIXEL_STD = [1.0, 1.0, 1.0]
```

3. what you observed (including the full logs):
```
(cropmask) ryan@cropmask-mgpu-18-v2:~/detectron2$ python ~/work/CropMask_RCNN/cropmask/train_model.py --num-gpus 4 dist_url="auto"
Command Line Args: Namespace(config_file='', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=4, num_machines=1, opts=['dist_url=auto'], resume=False)
ERROR [01/24 21:11:46 d2.engine.launch]: Process group URL: None
ERROR [01/24 21:11:46 d2.engine.launch]: Process group URL: None
ERROR [01/24 21:11:46 d2.engine.launch]: Process group URL: None
ERROR [01/24 21:11:46 d2.engine.launch]: Process group URL: None
Traceback (most recent call last):
  File "/home/ryan/work/CropMask_RCNN/cropmask/train_model.py", line 62, in <module>
    args=(args,),
  File "/home/ryan/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ryan/detectron2/detectron2/engine/launch.py", line 67, in _distributed_worker
    raise e
  File "/home/ryan/detectron2/detectron2/engine/launch.py", line 62, in _distributed_worker
    backend="NCCL", init_method=dist_url, world_size=world_size, rank=global_rank
  File "/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 130, in _env_rendezvous_handler
    raise _env_error("MASTER_ADDR")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set

```

## Expected behavior:

Maybe the dist_url is not actually being set even though I supply the `dist_url="auto"` command line argument? I'd expect this to be automatically set, I assume `ERROR [01/24 21:11:46 d2.engine.launch]: Process group URL: None` means that it isn't. I'm not sure how the `MASTER_ADDR` issue is related, from the [docs](https://pytorch.org/docs/stable/distributed.html) it looks like this shouldn't matter if machine rank is 0 and I left that default in place in the call to `launch`.

(2) It indicates a detectron2 bug.

## Environment:

```
(cropmask) ryan@cropmask-mgpu-18-v2:~/detectron2$ python -m detectron2.utils.collect_env
------------------------  ----------------------------------------------------------------------------------
sys.platform              linux
Python                    3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) [GCC 7.3.0]
numpy                     1.17.5
detectron2                0.1 @/home/ryan/detectron2/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_60
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3               Tesla P100-PCIE-16GB
CUDA_HOME                 /usr/local/cuda-10.1
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.1.0
torchvision               0.4.2 @/home/ryan/miniconda3/envs/cropmask/lib/python3.6/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  ----------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
Following our train_net.py, you need `launch(..., dist_url="auto")` or "dist_url=args.dist_url". Otherwise it's None.
