### ISSUE TITLE
Caught OSError in DataLoader worker process 3.

### ISSUE THREAD

**Issue by SherlockHolmes221** [facebookresearch/detectron2#764]
[01/29 11:07:32 d2.evaluation.evaluator]: Inference done 1884/5000. 0.0967 s / img. ETA=0:08:13
datasets/coco/val2017/000000217614.jpg
datasets/coco/val2017/000000217400.jpg
Traceback (most recent call last):
  File "tools/train_net.py", line 162, in <module>
datasets/coco/val2017/000000217285.jpg
    args=(args,),
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/engine/launch.py", line 52, in launch
datasets/coco/val2017/000000217753.jpg
    main_func(*args)
  File "tools/train_net.py", line 133, in main
    res = Trainer.test(cfg, model)
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/engine/defaults.py", line 487, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/evaluation/evaluator.py", line 115, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/data/dataset_mapper.py", line 75, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.img_format)
  File "/content/drive/Colab Notebooks/faster_rcnn/detectron2/detectron2/data/detection_utils.py", line 63, in read_image
    image = image.convert(conversion_format)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 930, in convert
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (72 bytes not processed)

**Comment by SherlockHolmes221** [comment]
solved by adding DATALOADER.NUM_WORKERS 1

**Comment by ppwwyyxx** [comment]
As the log says, PIL fails to read your image.
