### ISSUE TITLE
Conv2d wrapper fails with empty tensor when groups>1

### ISSUE THREAD

**Issue by rakhimovv** [facebookresearch/detectron2#772]
## Instructions To Reproduce the Issue:

1. 
```
import torch
from detectron2.layers import Conv2d
x = torch.zeros(size=(0, 20, 100, 100))
model = Conv2d(20, 20, 3, 1, 1)
print(model(x))
```
produces `tensor([], size=(0, 20, 100, 100), grad_fn=<MkldnnConvolutionBackward>)`

2.
```
import torch
from detectron2.layers import Conv2d
x = torch.zeros(size=(0, 20, 100, 100))
model = Conv2d(20, 20, 3, 1, 1, groups=20)
print(model(x))
```
produces
```
Traceback (most recent call last):
  File "/home/rakhimov/test.py", line 6, in <module>
    print(model(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rakhimov/detectron2/detectron2/layers/wrappers.py", line 67, in forward
    x = super().forward(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: std::exception
```

## Environment:

```
------------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) [GCC 7.3.0]
numpy                     1.17.3
detectron2                0.1 @/home/rakhimov/detectron2/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1 @/opt/conda/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0,1,2,3               GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.1
torchvision               0.4.2 @/opt/conda/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.1
------------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

**Comment by ppwwyyxx** [comment]
Too bad. Looks like convolution with empty input are still not fully supported in pytorch. I'll add back our hacks

**Comment by ppwwyyxx** [comment]
It looks like this is fixed in pytorch 2 days ago in https://github.com/pytorch/pytorch/pull/32709.
We'll keep our workaround in `wrappers.py` until we stop supporting pytorch 1.4
