### ISSUE TITLE
How to inference on images by using PointRend？

### ISSUE THREAD

**Issue by sunnyheart008205** [facebookresearch/detectron2#807]
## ❓How to inference on images by using PointRend？

Questions like:
When I use this command “python demo/demo_for_pointrend.py --config-file projects/PointRe
nd/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml --input datasets/testset/mytest.png --opts MODEL.WEIGHTS ./projects/PointRend/weights/model_final_3c3198_3x_coco.pkl”, the problems following appears.

[02/05 07:49:42 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml', input=['datasets/testset/mytest.png'], opts=['MODEL.WEIGHTS', './projects/PointRend/weights/model_final_3c3198_3x_coco.pkl'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo/demo_for_pointrend.py", line 75, in <module>
    cfg = setup_cfg(args)
  File "demo/demo_for_pointrend.py", line 26, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/data/s00378650/InstanceSegmentation/detectron2/detectron2-master/detectron2/config/config.py", line 45, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/opt/conda/lib/python3.6/site-packages/fvcore/common/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/opt/conda/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/opt/conda/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_MASK_HEAD.FC_DIM'

Q: How to inference PointRend model by using demo.py?

**Comment by ppwwyyxx** [comment]
You need to call https://github.com/facebookresearch/detectron2/blob/ee0cbd8c67622ff2753493ce0dcfeb3e3dd9945e/projects/PointRend/train_net.py#L69 to enable it.

**Comment by ppwwyyxx** [comment]
See also https://colab.research.google.com/drive/1isGPL5h5_cKoPPhVL9XhMokRtHDvmMVL

**Comment by BigBigOranges** [comment]
May I ask if you have solved this problem?If it is solved, can you share the method?
