### ISSUE TITLE
T.RandomCrop giving ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by ysefwakil** [facebookresearch/detectron2#826]
While trying to add my own Data Augmentation, all of the other methods work for augmentation except for Random Crop. Any idea how to fix this, thanks!

Code:

`def mapper(dataset_dict):
    # Implement a mapper, similar to the default DatasetMapper, but with your own customizations
    dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below
    image = Image.open(dataset_dict["file_name"])
    image =image.convert('RGB')
    image = np.array(image)

    image, transforms = T.apply_transform_gens([T.Resize((2056, 600)), 
    image, transforms = T.apply_transform_gens([T.RandomCrop("relative_range", (0.4, 0.4))],image)
    dataset_dict["image"] = torch.as_tensor(image.transpose(2, 0, 1).astype("float32"))
    annos = [
        utils.transform_instance_annotations(obj, transforms, image.shape[:2])
        for obj in dataset_dict.pop("annotations")
        if obj.get("iscrowd", 0) == 0
    ]
    instances = utils.annotations_to_instances(annos, image.shape[:2])
    dataset_dict["instances"] = utils.filter_empty_instances(instances)
    return dataset_dict`

> Traceback (most recent call last):
  File "training.py", line 207, in <module>
    newTrainer.train()
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/engine/train_loop.py", line 206, in run_step
    data = next(self._data_loader_iter)
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/common.py", line 109, in __iter__
    for d in self.dataset:
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "training.py", line 173, in mapper
    for obj in dataset_dict.pop("annotations")
  File "training.py", line 174, in <listcomp>
    if obj.get("iscrowd", 0) == 0
  File "/home/appuser/detectron2_repo/DOCKER/detectron2/data/detection_utils.py", line 176, in transform_instance_annotations
    p.reshape(-1) for p in transforms.apply_polygons(polygons)
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/transforms/transform.py", line 225, in <lambda>
    return lambda x: self._apply(x, name)
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/transforms/transform.py", line 216, in _apply
    x = getattr(t, meth)(x)
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/transforms/transform.py", line 577, in apply_polygons
    polygon = geometry.Polygon(polygon).buffer(0.0)
  File "/home/appuser/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 243, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/home/appuser/.local/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 251, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by ppwwyyxx** [comment]
The log says that your polygon has < 3 coordinates.

**Comment by ysefwakil** [comment]
Found the fault, thank you
