### ISSUE TITLE
IndexError when training masked R-CNN with RLE

### ISSUE THREAD

**Issue by minhduc0711** [facebookresearch/detectron2#854]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
I use the training code from Getting Started notebook.
My segmentation is a `dict` with `size` and `counts` keys.
I also set
```
cfg.INPUT.MASK_FORMAT = 'bitmask'
```
2. what exact command you run:
3. what you observed (including the full logs):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 214, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 129, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 566, in forward
    losses = self._forward_box(features_list, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 639, in _forward_box
    return outputs.losses()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 266, in losses
    "loss_cls": self.softmax_cross_entropy_loss(),
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 199, in softmax_cross_entropy_loss
    return F.cross_entropy(self.pred_class_logits, self.gt_classes, reduction="mean")
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 2159121 is out of bounds.
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Environment:
Google Colab.

**Comment by ppwwyyxx** [comment]
What it says is that your annotation is in wrong format.

Please check https://detectron2.readthedocs.io/tutorials/datasets.html again, especially this:

> category_id (int): an integer in the range [0, num_categories) representing the category label. The value num_categories is reserved to represent the “background” category, if applicable.

**Comment by minhduc0711** [comment]
You're right, thanks. 
I forgot to set `dataset_name` in `load_coco_json()` so the ID mapping didn't run.
