### ISSUE TITLE
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#885]
Dataset used : COCO person dataset 2014
Datasets are registered successfully. Training started and stopped at iteration 179 with the following error

`[02/17 11:59:23 d2.utils.events]: eta: 0:48:04  iter: 39  total_loss: 1.372  loss_cls: 0.366  loss_box_reg: 0.388  loss_rpn_cls: 0.403  loss_rpn_loc: 0.214  time: 0.5316  data_time: 0.0027  lr: 0.000799  max_mem: 4739M
[02/17 11:59:34 d2.utils.events]: eta: 0:47:39  iter: 59  total_loss: 1.372  loss_cls: 0.306  loss_box_reg: 0.466  loss_rpn_cls: 0.399  loss_rpn_loc: 0.176  time: 0.5294  data_time: 0.0026  lr: 0.001199  max_mem: 4739M
[02/17 11:59:44 d2.utils.events]: eta: 0:47:41  iter: 79  total_loss: 1.442  loss_cls: 0.357  loss_box_reg: 0.496  loss_rpn_cls: 0.380  loss_rpn_loc: 0.182  time: 0.5325  data_time: 0.0026  lr: 0.001598  max_mem: 4739M
[02/17 11:59:55 d2.utils.events]: eta: 0:47:29  iter: 99  total_loss: 1.061  loss_cls: 0.228  loss_box_reg: 0.162  loss_rpn_cls: 0.436  loss_rpn_loc: 0.174  time: 0.5326  data_time: 0.0028  lr: 0.001998  max_mem: 4739M
[02/17 12:00:06 d2.utils.events]: eta: 0:47:21  iter: 119  total_loss: 1.153  loss_cls: 0.298  loss_box_reg: 0.255  loss_rpn_cls: 0.395  loss_rpn_loc: 0.201  time: 0.5323  data_time: 0.0028  lr: 0.002398  max_mem: 4739M
[02/17 12:00:16 d2.utils.events]: eta: 0:47:09  iter: 139  total_loss: 1.553  loss_cls: 0.361  loss_box_reg: 0.297  loss_rpn_cls: 0.437  loss_rpn_loc: 0.256  time: 0.5315  data_time: 0.0027  lr: 0.002797  max_mem: 4739M
[02/17 12:00:26 d2.utils.events]: eta: 0:46:55  iter: 159  total_loss: 14.243  loss_cls: 7.475  loss_box_reg: 2.270  loss_rpn_cls: 0.535  loss_rpn_loc: 0.551  time: 0.5286  data_time: 0.0027  lr: 0.003197  max_mem: 4739M
[02/17 12:00:36 d2.utils.events]: eta: 0:46:30  iter: 179  total_loss: 85.440  loss_cls: 53.145  loss_box_reg: 16.274  loss_rpn_cls: 1.296  loss_rpn_loc: 2.467  time: 0.5224  data_time: 0.0027  lr: 0.003596  max_mem: 4739M
[02/17 12:00:37 d2.engine.hooks]: Overall training speed: 181 iterations in 0:01:34 (0.5206 s / it)
[02/17 12:00:37 d2.engine.hooks]: Total training time: 0:01:34 (0:00:00 on hooks)
Traceback (most recent call last):
  File "train_tridentnet.py", line 79, in <module>
    trainer.train() #start training
  File "/home/detectron2/detectron2/engine/defaults.py", line 369, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/detectron2/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/home/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 131, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/remote/samjith/MPC_Model/detectron2/TridentNet/tridentnet/trident_rcnn.py", line 66, in forward
    pred_instances, losses = super().forward(images, features, proposals, all_targets)
  File "/home/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 409, in forward
    losses = outputs.losses()
  File "/home/detect/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py", line 266, in losses
    "loss_cls": self.softmax_cross_entropy_loss(),
  File "/home/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py", line 198, in softmax_cross_entropy_loss
    self._log_accuracy()
  File "/home/detectron2/detectron2/modeling/roi_heads/fast_rcnn.py", line 173, in _log_accuracy
    pred_classes = self.pred_class_logits.argmax(dim=1)
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity
`

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by chongruo** [comment]
same here

**Comment by ppwwyyxx** [comment]
Closing as the requested information is not provided.
