### ISSUE TITLE
Processes from `launch` terminate with signal SIGSEGV

### ISSUE THREAD

**Issue by corysaildrone** [facebookresearch/detectron2#908]
When I launch processes using `detectron2.engine` `launch`, it looks like at least one process always ends in a segmentation fault. Sometimes the other processes finish, but sometimes they are brought down by the `SpawnContext` before completing 

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
This is minimal_example.py
```
import os

from detectron2.engine import launch


def main():
    print('test')


if __name__ == '__main__':
    launch(
        main,
        2,
        num_machines=1,
        machine_rank=0,
        dist_url=f'tcp://127.0.0.1:{2 ** 15 + 2 ** 14 + hash(os.getuid()) % 2 ** 14}',
    )
```
2. what exact command you run:
```
$ python minimal_example.py 
```
3. what you observed (including the full logs):
```
test
test
Traceback (most recent call last):
  File "tools/minimal_example.py", line 16, in <module>
    dist_url=f'tcp://127.0.0.1:{2 ** 15 + 2 ** 14 + hash(os.getuid()) % 2 ** 14}',
  File "/home/cory/anaconda3/envs/mlvision2/lib/python3.7/site-packages/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/cory/anaconda3/envs/mlvision2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/cory/anaconda3/envs/mlvision2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 1 terminated with signal SIGSEGV
```

If I comment out the `synchronize` call here https://github.com/facebookresearch/detectron2/blob/e1282a5625d79a8b108e7390b47850959c272bd4/detectron2/engine/launch.py#L70 it succeeds with no error

## Environment:
```$ python -m detectron2.utils.collect_env
------------------------  ------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1,2,3               TITAN Xp
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.326
Pillow                    6.2.1
cv2                       4.2.0
------------------------  ------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
We cannot reproduce this issue. In fact, as you can see in source code, your code is the same as 3 pytorch calls:
1. https://github.com/facebookresearch/detectron2/blob/e1282a5625d79a8b108e7390b47850959c272bd4/detectron2/engine/launch.py#L45-L50
2. https://github.com/facebookresearch/detectron2/blob/e1282a5625d79a8b108e7390b47850959c272bd4/detectron2/engine/launch.py#L61-L63
3. https://github.com/facebookresearch/detectron2/blob/e1282a5625d79a8b108e7390b47850959c272bd4/detectron2/engine/launch.py#L70

So it makes more sense to simplify the code to not use detectron2 and report this issue to pytorch.
