### ISSUE TITLE
ImportError: dlopen

### ISSUE THREAD

**Issue by FiReTiTi** [facebookresearch/detectron2#918]
Hi,
I wanted to get acquainted with Detectron so I decided to start with the balloons project. I started the code to format the data, but I got an error that I cannot figure out:

```
Traceback (most recent call last):
  File "balloon.py", line 4, in <module>
    from detectron2.structures import BoxMode
  File "/Users/firetiti/Downloads/detectron2-master/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/Users/firetiti/Downloads/detectron2-master/detectron2/structures/boxes.py", line 8, in <module>
    from detectron2.layers import cat
  File "/Users/firetiti/Downloads/detectron2-master/detectron2/layers/__init__.py", line 5, in <module>
    from .nms import batched_nms, batched_nms_rotated, nms, nms_rotated
  File "/Users/firetiti/Downloads/detectron2-master/detectron2/layers/nms.py", line 5, in <module>
    from torchvision.ops import boxes as box_ops
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so, 2): Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so
```

I installed it by using the following options: `MACOSX_DEPLOYMENT_TARGET=10.15.3 CC=clang CXX=clang++ pip install -e .`
I didn't get any error reported. I tried to reinstall, bu nothing changed.

## Environment:
Run `python -m detectron2.utils.collect_env` in the environment where you observerd the issue, and paste the output.
If detectron2 hasn't been successfully installed, use `python detectron2/utils/collect_env.py`.

I tried these instructions, but same error.

**Comment by ppwwyyxx** [comment]
The error comes from `    from torchvision import _C` and is therefore unrelated to detectron2.
Most likely the version of your torchvision does not match pytorch.
