### ISSUE TITLE
error happens when changing the cfg.OUTPUT_DIR

### ISSUE THREAD

**Issue by yustaub** [facebookresearch/detectron2#931]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
<DatasetCatalog.register("wurenji_train",lambda :train_dataset_dicts)
    MetadataCatalog.get("wurenji_train").set(thing_class=["wurenji"])
    wurenji_train_metadata=MetadataCatalog.get("wurenji_train")
    #for validation
    DatasetCatalog.register("wurenji_val", lambda: val_dataset_dicts)
    MetadataCatalog.get("wurenji_val").set(thing_class=["wurenji"])
    wurenji_val_metadata = MetadataCatalog.get("wurenji_val")
    # dataset_dicts = get_dict
    # for d in random.sample(dataset_dicts, 3):
    #     img = cv2.imread(d["file_name"])
    #     visualizer = Visualizer(img[:, :, ::-1], metadata=wurenji2_metadata, scale=0.5)
    #     vis = visualizer.draw_dataset_dict(d)
    #     cv2.imwrite("wurenji.jpg",vis.get_image()[:, :, ::-1])

    cfg = get_cfg()
    cfg.merge_from_file(model_zoo.get_config_file("PascalVOC-Detection/faster_rcnn_R_50_C4.yaml"))
    cfg.DATASETS.TRAIN = ("wurenji_train",)
    cfg.DATASETS.TEST = ("wurenji_val",)
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
        "PascalVOC-Detection/faster_rcnn_R_50_C4.yaml")  # Let training initialize from model zoo
    cfg.SOLVER.IMS_PER_BATCH = 2
    #cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
    #300 iters
    cfg.SOLVER.BASE_LR = 0.00025
    cfg.SOLVER.MAX_ITER = 100  # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
    #18000 iters
    # cfg.SOLVER.BASE_LR = 0.02
    # cfg.SOLVER.MAX_ITER = 18000  # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
    # cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256  # faster, and good enough for this toy dataset (default: 512)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # only has one class (ballon)
    cfg.OUTPUT_DIR="./output/faster_rcnn_R_50_C4/"
    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
    trainer = DefaultTrainer(cfg)
    trainer.resume_or_load(resume=False)
    trainer.train()

    import pdb;pdb.set_trace()
    #####################for validation #########################
    cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.7  # set the testing threshold for this model
    cfg.DATASETS.TEST = ("wurenji_val",)
    predictor = DefaultPredictor(cfg)

    from detectron2.evaluation import COCOEvaluator, inference_on_dataset
    from detectron2.data import build_detection_test_loader

    evaluator = COCOEvaluator("wurenji_val", cfg, False, output_dir="./output/faster_rcnn_R_50_C4/")
    val_loader = build_detection_test_loader(cfg, "wurenji_val")
    inference_on_dataset(trainer.model, val_loader, evaluator)>
```
2. what exact command you run: python test.py
3. what you observed (including the full logs):
```
<[02/24 19:44:35 d2.utils.events]: eta: 0:00:22  iter: 279  total_loss: 0.262  loss_cls: 0.032  loss_box_reg: 0.229  loss_rpn_cls: 0.001  loss_rpn_loc: 0.002  time: 1.0611  data_time: 0.0070  lr: 0.000250  max_mem: 1897M
WARNING [02/24 19:44:59 d2.engine.defaults]: No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.
[02/24 19:44:59 d2.utils.events]: eta: 0:00:01  iter: 299  total_loss: 0.307  loss_cls: 0.035  loss_box_reg: 0.257  loss_rpn_cls: 0.001  loss_rpn_loc: 0.002  time: 1.0639  data_time: 0.0084  lr: 0.000250  max_mem: 1897M
[02/24 19:44:59 d2.engine.hooks]: Overall training speed: 297 iterations in 0:05:17 (1.0675 s / it)
[02/24 19:44:59 d2.engine.hooks]: Total training time: 0:05:19 (0:00:02 on hooks)
WARNING [02/24 19:45:00 d2.evaluation.coco_evaluation]: json_file was not found in MetaDataCatalog for 'wurenji_val'
[02/24 19:45:00 d2.data.datasets.coco]: Converting dataset annotations in 'wurenji_val' to COCO format ...)
Traceback (most recent call last):
  File "video_test_t8v2.py", line 245, in <module>
    evaluator = COCOEvaluator("wurenji_val", cfg, False, output_dir="./output/faster_rcnn_R_50_C4/")
  File "/home/yuwentao/ml_test/detectron2/detectron2/evaluation/coco_evaluation.py", line 68, in __init__
    convert_to_coco_json(dataset_name, cache_path)
  File "/home/yuwentao/ml_test/detectron2/detectron2/data/datasets/coco.py", line 407, in convert_to_coco_json
    coco_dict = convert_to_coco_dict(dataset_name)
  File "/home/yuwentao/ml_test/detectron2/detectron2/data/datasets/coco.py", line 294, in convert_to_coco_dict
    for id, name in enumerate(MetadataCatalog.get(dataset_name).thing_classes)
  File "/home/yuwentao/ml_test/detectron2/detectron2/data/catalog.py", line 119, in __getattr__
    key, self.name, str(self.__dict__.keys())
AttributeError: Attribute 'thing_classes' does not exist in the metadata of 'wurenji_val'. Available keys are dict_keys(['name', 'thing_class', 'json_file']).
>
```
I just want to change the output dir and the error happens,how to change the output dir correctly?

**Comment by ppwwyyxx** [comment]
```
AttributeError: Attribute 'thing_classes' does not exist in the metadata of 'wurenji_val'. Available keys are dict_keys(['name', 'thing_class', 'json_file']).
```

as the error says you use wrong metadata name.
