### ISSUE TITLE
load_coco_json fails with "KeyError: 'categories' ", bug in pycocotools dependency?

### ISSUE THREAD

**Issue by breznak** [facebookresearch/detectron2#946]
- problem: I'm trying to load a custom COCO-style dataset, following the tutorial:
https://detectron2.readthedocs.io/tutorials/datasets.html 
- I think the issue might be in the dependency `pycocotools` and its API. I've installed according to the instructions: `pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'` 
and verify: 
```
$ pip list |grep coco
pycocotools (2.0)
```

Thank you for any help, 

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote:
I'm getting an error when loading my custom COCO-style dataset (the format is 99% good, as I use the same dataset for another (COCO) project and it works there. 

```
# load a custom COCO dataset
from detectron2.data.datasets import register_coco_instances
detectron2.data.datasets.load_coco_json("/home/mmm/dataset_kuka_env_pybullet_12/train/annotations.json", "/home/mmm/dataset_kuka_env_pybullet_12/train", "kuka_train")
```
2. what exact command you run:
3. what you observed (including the full logs):
```
ubuntu:~/detectron2$ python train_detectron_coco.py
[02/25 19:11:31 d2.data.datasets.coco]: Loading /home/mmm/dataset_kuka_env_pybullet_12/train/annotations.json takes 1.19 seconds.
Traceback (most recent call last):
File "train_detectron_coco.py", line 44, in <module>
detectron2.data.datasets.load_coco_json("/home/mmm/dataset_kuka_env_pybullet_12/train/annotations.json", "/home/mmm/dataset_kuka_env_pybullet_12/train", "kuka_train")
File "/home_shared/mmm/detectron2/detectron2/data/datasets/coco.py", line 66, in load_coco_json
cat_ids = sorted(coco_api.getCatIds())
File "/home_shared/mmm/detectron2/pyenv/lib/python3.7/site-packages/pycocotools/coco.py", line 170, in getCatIds
cats = self.dataset['categories']
KeyError: 'categories'
```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(2) It indicates a detectron2 bug.

## Environment:

Run `python -m detectron2.utils.collect_env` in the environment where you observerd the issue, and paste the output.
```
$ python -m detectron2.utils.collect_env
------------------------  --------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]
numpy                     1.18.1
detectron2                0.1 @/home_shared/mmm/detectron2/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.1
detectron2 arch flags     sm_61
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home_shared/mmm/detectron2/pyenv/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     GeForce GTX 1080 Ti
CUDA_HOME                 /usr/local/cuda-10.1/
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    7.0.0
torchvision               0.5.0 @/home_shared/mmm/detectron2/pyenv/lib/python3.7/site-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.2.0
------------------------  --------------------------------------------------------------------------------
PyTorch built with:
- GCC 7.3
- Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- NNPACK is enabled
- CUDA Runtime 10.1
- NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
- CuDNN 7.6.3
- Magma 2.5.1
- Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2-fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1,PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```
If detectron2 hasn't been successfully installed, use `python detectron2/utils/collect_env.py`.

**Comment by ppwwyyxx** [comment]
It seems your json file does not have the key "categories" - so it's not a proper COCO format json file.

You can download a COCO json file to look at its format.

**Comment by breznak** [comment]
> You can download a COCO json file to look at its format. 

You're right. I've found the `datasets/README` which is informative and I'm testing with the mini-COCO
