### ISSUE TITLE
There were no tensor arguments to this function 

### ISSUE THREAD

**Issue by Samjith888** [facebookresearch/detectron2#952]
Changes made :

```
cfg = get_cfg()
cfg.merge_from_file(project_root+"/configs/COCO-Detection/rpn_R_50_FPN_1x.yaml") 
cfg.MODEL.WEIGHTS = project_root+'/tools/output/model_0079999.pth'
cfg.DATASETS.TRAIN = ("train", )
cfg.DATASETS.TEST = ("val", )
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.SOLVER.MAX_ITER =82200
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE =  128

#load the checkpoints and model
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=True)
trainer.train() #start training
```

Error:
Here i have trained a model using RPN , while evaluating the model , i got the following error 

Error log:
```

[02/26 13:55:22 d2.evaluation.evaluator]: Inference done 7992/10958. 0.0385 s / img. ETA=0:02:16
[02/26 13:55:27 d2.evaluation.evaluator]: Inference done 8099/10958. 0.0385 s / img. ETA=0:02:11
[02/26 13:55:32 d2.evaluation.evaluator]: Inference done 8211/10958. 0.0385 s / img. ETA=0:02:06
[02/26 13:55:37 d2.evaluation.evaluator]: Inference done 8333/10958. 0.0385 s / img. ETA=0:02:00
[02/26 13:55:42 d2.evaluation.evaluator]: Inference done 8443/10958. 0.0385 s / img. ETA=0:01:55
[02/26 13:55:48 d2.evaluation.evaluator]: Inference done 8555/10958. 0.0385 s / img. ETA=0:01:50
[02/26 13:55:53 d2.evaluation.evaluator]: Inference done 8669/10958. 0.0385 s / img. ETA=0:01:45
[02/26 13:55:58 d2.evaluation.evaluator]: Inference done 8773/10958. 0.0385 s / img. ETA=0:01:40
[02/26 13:56:03 d2.evaluation.evaluator]: Inference done 8876/10958. 0.0385 s / img. ETA=0:01:35
[02/26 13:56:08 d2.evaluation.evaluator]: Inference done 8978/10958. 0.0385 s / img. ETA=0:01:31
[02/26 13:56:13 d2.evaluation.evaluator]: Inference done 9096/10958. 0.0385 s / img. ETA=0:01:25
[02/26 13:56:18 d2.evaluation.evaluator]: Inference done 9204/10958. 0.0385 s / img. ETA=0:01:20
[02/26 13:56:23 d2.evaluation.evaluator]: Inference done 9315/10958. 0.0385 s / img. ETA=0:01:15
[02/26 13:56:28 d2.evaluation.evaluator]: Inference done 9430/10958. 0.0385 s / img. ETA=0:01:10
[02/26 13:56:33 d2.evaluation.evaluator]: Inference done 9544/10958. 0.0385 s / img. ETA=0:01:05
[02/26 13:56:38 d2.evaluation.evaluator]: Inference done 9659/10958. 0.0385 s / img. ETA=0:00:59
[02/26 13:56:43 d2.evaluation.evaluator]: Inference done 9774/10958. 0.0385 s / img. ETA=0:00:54
[02/26 13:56:48 d2.evaluation.evaluator]: Inference done 9890/10958. 0.0385 s / img. ETA=0:00:49
[02/26 13:56:53 d2.evaluation.evaluator]: Inference done 10002/10958. 0.0385 s / img. ETA=0:00:43
[02/26 13:56:58 d2.evaluation.evaluator]: Inference done 10113/10958. 0.0385 s / img. ETA=0:00:38
[02/26 13:57:03 d2.evaluation.evaluator]: Inference done 10215/10958. 0.0385 s / img. ETA=0:00:34
[02/26 13:57:08 d2.evaluation.evaluator]: Inference done 10322/10958. 0.0385 s / img. ETA=0:00:29
[02/26 13:57:13 d2.evaluation.evaluator]: Inference done 10429/10958. 0.0385 s / img. ETA=0:00:24
[02/26 13:57:18 d2.evaluation.evaluator]: Inference done 10549/10958. 0.0385 s / img. ETA=0:00:18
[02/26 13:57:23 d2.evaluation.evaluator]: Inference done 10660/10958. 0.0385 s / img. ETA=0:00:13
[02/26 13:57:28 d2.evaluation.evaluator]: Inference done 10772/10958. 0.0385 s / img. ETA=0:00:08
[02/26 13:57:33 d2.evaluation.evaluator]: Inference done 10882/10958. 0.0385 s / img. ETA=0:00:03
[02/26 13:57:37 d2.evaluation.evaluator]: Total inference time: 0:08:22.440849 (0.045872 s / img per device, on 1 devices)
[02/26 13:57:37 d2.evaluation.evaluator]: Total inference pure compute time: 0:07:02 (0.038550 s / img per device, on 1 devices)
[02/26 13:57:38 d2.evaluation.coco_evaluation]: Evaluating bbox proposals ...
Traceback (most recent call last):
  File "rpn_train.py", line 113, in <module>
    inference_on_dataset(trainer.model, val_loader, evaluator)
  File "/home/samjith/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 159, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/samjith/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 136, in evaluate
    self._eval_box_proposals()
  File "/home/samjith/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 223, in _eval_box_proposals
    stats = _evaluate_box_proposals(
  File "/home/samjith/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/evaluation/coco_evaluation.py", line 452, in _evaluate_box_proposals
    gt_overlaps = torch.cat(gt_overlaps, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]
```
 
This issue only happened with rpn model. (even it is trained successfully )

**Comment by ppwwyyxx** [comment]
This happens when the model makes no predictions for any images. Will be handled properly in future commits.

**Comment by Samjith888** [comment]
> This happens when the model makes no predictions for any images. Will be handled properly in future commits.

Is this a bug in RPN ?

**Comment by ppwwyyxx** [comment]
This is an oversight in evaluation because we've not met situation where the RPN makes no predictions.
