### ISSUE TITLE
Segmentation Fault on Dataloader

### ISSUE THREAD

**Issue by dreaquil** [facebookresearch/detectron2#954]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote

config_test.py:
```
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.data.datasets import register_coco_instances
from detectron2.data import build_detection_train_loader

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.merge_from_file('configs/roi-config.yaml')

register_coco_instances("RoIDataset", {}, "./annotations/roi-dataset.json", "./datasets/RoIDataset")

train_loader = build_detection_train_loader(cfg, mapper=None)

print(next(iter(train_loader)))

```
configs/roi-config.yaml:
```
DATASETS:
  TRAIN: ("RoIDataset",)
  TEST: ("RoIDataset",)
DATALOADER:
  NUM_WORKERS: 4
```

2. what exact command you run:
Run the config_test.py
3. what you observed (including the full logs):
```
(.venv) andre@D4:~/projects/roi-detectron$ /home/andre/projects/roi-detectron/.venv/bin/python3.7 /home/andre/projects/roi-detectron/config_test.py
Config 'configs/roi-config.yaml' has no VERSION. Assuming it to be compatible with latest v2.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f39e40c6710>
Traceback (most recent call last):
  File "/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 961, in __del__
    self._shutdown_workers()
  File "/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _shutdown_workers
    w.join()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 29873) is killed by signal: Segmentation fault. 
Segmentation fault (core dumped)
```

## Expected behavior:

I expect to get a tensor object of my dataset. This works fine on my local machine. However, when I try to run this on an Azure VM, I get the above error log. I have identified where the issue is: 

- If NUM_WORKERS is set to 0, the script works. 
- If the script is run in debug it works.
- If NUM_WORKERS is set to >0, the script segfaults.

## Environment:
```
------------------------  -------------------------------------------------------------------------------------------------------------------------
sys.platform              linux
Python                    3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]
numpy                     1.18.1
detectron2                0.1.1 @/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  not available
detectron2 arch flags     /home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0 @/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla K80
CUDA_HOME                 None
Pillow                    7.0.0
torchvision               0.5.0 @/home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torchvision
torchvision arch flags    /home/andre/projects/roi-detectron/.venv/lib/python3.7/site-packages/torchvision/_C.so
------------------------  -------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by ppwwyyxx** [comment]
As you know this is an environment issue - unless you can provide an environment to reproduce the issue such as a dockerfile or colab notebook, it's unlikely someone will be able to guess what's wrong.

**Comment by dreaquil** [comment]
Thanks for taking a look regardless. For anyone experiencing this issue:

In my case, it seemed that some of the dependencies required that were installed from pip did not bind well to some other low level libraries when pip install was executed on the Virtual machine. I don't have enough low level linux knowledge to point out exactly what was the issue but if you replace these dependencies using sudo apt-get install package (in my case it was numpy and opencv-python) and make sure your environment is using that, it solved the segmentation errors.
