### ISSUE TITLE
Installation on WSL ubuntu18.04

### ISSUE THREAD

**Issue by giesrjing** [facebookresearch/detectron2#98]
I have done according to the [Colab Notebook ](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=b-i4hmGYk1dL), but when I install detectron2,  it return nothing.
import detectron2 is OK. but can not import other packages.
for example: No module named 'detectron2.utils'

`Cloning into 'detectron2_repo'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 861 (delta 51), reused 60 (delta 26), pack-reused 748
Receiving objects: 100% (861/861), 1.57 MiB | 861.00 KiB/s, done.
Resolving deltas: 100% (392/392), done.
Checking out files: 100% (339/339), done.
root@GISer:/mnt/c/Users/gell# pip install -e detectron2_repo
Obtaining file:///mnt/c/Users/gell/detectron2_repo
Requirement already satisfied: termcolor>=1.1 in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (1.1.0)
Requirement already satisfied: Pillow in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (6.2.0)
Requirement already satisfied: yacs>=0.1.6 in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (0.1.6)Requirement already satisfied: tabulate in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (0.8.5)
Requirement already satisfied: cloudpickle in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (1.2.2)Requirement already satisfied: matplotlib in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (3.1.1)
Requirement already satisfied: tqdm>4.29.0 in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (4.36.1)
Requirement already satisfied: shapely in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (1.6.4.post2)
Requirement already satisfied: tensorboard in /root/anaconda3/lib/python3.7/site-packages (from detectron2==0.1) (2.0.0)Requirement already satisfied: PyYAML in /root/anaconda3/lib/python3.7/site-packages (from yacs>=0.1.6->detectron2==0.1) (5.1.2)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1) (2.4.2)
Requirement already satisfied: python-dateutil>=2.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1) (2.8.0)
Requirement already satisfied: numpy>=1.11 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.1) (1.17.2)
Requirement already satisfied: setuptools>=41.0.0 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (41.4.0)
Requirement already satisfied: absl-py>=0.4 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (0.8.1)
Requirement already satisfied: markdown>=2.6.8 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (0.16.0)
Requirement already satisfied: six>=1.10.0 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (1.12.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (0.33.6)
Requirement already satisfied: protobuf>=3.6.0 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (3.10.0)
Requirement already satisfied: grpcio>=1.6.3 in /root/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.1) (1.24.1)
Installing collected packages: detectron2
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/gell/detectron2_repo/setup.py'"'"'; __file__='"'"'/mnt/c/Users/gell/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/c/Users/gell/detectron2_repo/
    Complete output (49 lines):
    No CUDA runtime is found, using CUDA_HOME='/usr'
    running develop
    running egg_info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/gell/detectron2_repo/setup.py", line 85, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/root/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/root/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/root/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/root/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/root/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 238, in build_extensions
        self._check_abi()
      File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 380, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 168, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 144, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/root/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/root/anaconda3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/gell/detectron2_repo/setup.py'"'"'; __file__='"'"'/mnt/c/Users/gell/detectron2_repo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
root@GISer:/mnt/c/Users/gell#`

**Comment by ppwwyyxx** [comment]
Your error says
>  line 487, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['which', 'g++']

pytorch cannot find gcc/g++, which [detectron2 requires](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md).
