### ISSUE TITLE
How to evaluate a model's performance after training?

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#997]
I found these from GETTING_STARTED.md,
```
python tools/train_net.py \
	--config-file configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml \
	--eval-only MODEL.WEIGHTS /path/to/checkpoint_file
```
But I don't know what to write down into the "/path/to/checkpoint_file" part.

And which weight file does this code use what if I do not use "MODEL.WEIGHTS /path/to/checkpoint_file" part, like

```
python tools/train_net.py \
	--config-file configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml \
	--eval-only 
```

**Comment by ppwwyyxx** [comment]
> But I don't know what to write down into the "/path/to/checkpoint_file" part.

use the model file that's trained

> And which weight file does this code use what if I do not use "MODEL.WEIGHTS

the one specified by the config. Or empty, by default.

**Comment by emjay73** [comment]
Based on this,
https://pytorch.org/tutorials/beginner/saving_loading_models.html
I tried to find checkpoint file ends with 'tar' format but it seems like you are talking about 'pth', correct?
If not, could you please tell me where is the default path for checkpoint?

**Comment by ppwwyyxx** [comment]
Yes, the extension for checkpoints is pth.

**Comment by emjay73** [comment]
Well, I tried,
```
python tools/train_net.py --config-file configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml --eval-only MODEL.WEIGTHS output/model_0144999.pth
```
and error came out.


```
Command Line Args: Namespace(config_file='configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml', dist_url='tcp://127.0.0.1:50152', eval_only=True, machine_rank=0, num_gpus=1, num_machines=1, opts=['MODEL.WEIGTHS', 'output/model_0144999.pth'], resume=False)
Traceback (most recent call last):
  File "tools/train_net.py", line 162, in <module>
    args=(args,),
  File "/home/emjay/Documents/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 126, in main
    cfg = setup(args)
  File "tools/train_net.py", line 119, in setup
    cfg.merge_from_list(args.opts)
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/fvcore/common/config.py", line 132, in merge_from_list
    return super().merge_from_list(cfg_list)
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/yacs/config.py", line 243, in merge_from_list
    _assert_with_logging(subkey in d, "Non-existent key: {}".format(full_key))
  File "/home/emjay/Install/anaconda3/envs/torch/lib/python3.7/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Non-existent key: MODEL.WEIGTHS

```
*Should I open new issue for this?)

**Comment by ppwwyyxx** [comment]
you had a typo

**Comment by emjay73** [comment]
GOSH, It's embarrassing. I'm really sorry about that. It works now. thanks!!!
